### ISSUE TITLE
Crash accessing parameters of dynamic MethodInfo

### ISSUE THREAD

**Issue by joncham** [mono/mono#10201]
## Steps to Reproduce

1. Run test case below
2. 
3. 

```
using System;
using System.Diagnostics;
using System.Reflection;
using System.Reflection.Emit;

class Program
{
    static void Main(string[] args)
    {
        var targetObject = new Printer();

        var emitTool = new ILEmitTool<Printer>();
        emitTool.CallPublicInstanceMethod(targetObject, "PrintStackTrace");
    }
}

public class Printer
{
    public void PrintStackTrace()
    {
        var stackTrace = new StackTrace();
        foreach (var frame in stackTrace.GetFrames())
            Console.WriteLine(frame.GetMethod());
    }
}

public class ILEmitTool<TTargetClass>
{
    private delegate void DynamicMethodDelegate(TTargetClass target);

    public void CallPublicInstanceMethod(TTargetClass targetObject, string methodName)
    {
        var ttype = typeof(TTargetClass);

        var dynamicMethodParams = new Type[] { ttype };

        var dynamicMethodOwner = typeof(ILEmitTool<TTargetClass>);

        var typeDynamicMethodDelegate = typeof(DynamicMethodDelegate);

        var methodInfo = ttype.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public);
            
        var dynamicMethod = new DynamicMethod(methodInfo.Name, null, dynamicMethodParams, dynamicMethodOwner);

        var il = dynamicMethod.GetILGenerator();
        il.Emit(OpCodes.Ldarg_0);
        il.Emit(OpCodes.Callvirt, methodInfo);
        il.Emit(OpCodes.Ret);

        var completedDynamicMethod = (DynamicMethodDelegate)dynamicMethod.CreateDelegate(typeDynamicMethodDelegate);

        completedDynamicMethod(targetObject);
    }

}
```

### Current Behavior

```
* Assertion at class-accessors.c:128, condition `mono_class_has_static_metadata (klass)' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Reflection.MonoMethodInfo.get_parameter_info (intptr,System.Reflection.MemberInfo) [0x0000b] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Reflection.MonoMethodInfo.GetParametersInfo (intptr,System.Reflection.MemberInfo) [0x00000] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Reflection.MonoMethod.GetParameters () [0x00000] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Reflection.MethodBase.GetParametersNoCopy () [0x00000] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Reflection.RuntimeMethodInfo.FormatNameAndSig (bool) [0x0003a] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Reflection.RuntimeMethodInfo.ToString () [0x0000b] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.IO.TextWriter.WriteLine (object) [0x00028] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.IO.TextWriter/SyncTextWriter.WriteLine (object) [0x00000] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at (wrapper synchronized) System.IO.TextWriter/SyncTextWriter.WriteLine (object) [0x0000a] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at System.Console.WriteLine (object) [0x00000] in <5173b30cdbff43c6af8f4d412fcda477>:0
  at Printer.PrintStackTrace () [0x0001d] in <419a7ceea17b4e9580c646ca1e90144f>:0
  at (wrapper dynamic-method) ILEmitTool`1<Printer>.PrintStackTrace (Printer) [0x00000] in <419a7ceea17b4e9580c646ca1e90144f>:0
  at ILEmitTool`1<TTargetClass_REF>.CallPublicInstanceMethod (TTargetClass_REF,string) [0x0008a] in <419a7ceea17b4e9580c646ca1e90144f>:0
  at Program.Main (string[]) [0x0000d] in <419a7ceea17b4e9580c646ca1e90144f>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x0001e] in <419a7ceea17b4e9580c646ca1e90144f>:0
```

### Expected Behavior

No crash

## On which platforms did you notice this

[ X] macOS
[ ] Linux
[ X] Windows

**Version Used**:

```
Mono JIT compiler version 5.19.0.45 (pull-request-10012/5bad4e77d4b Fri Aug 10 10:48:49 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by lambdageek** [comment]
Also fails with `2018-06` and `2018-02`.

**Comment by Wohlstand** [comment]
Copy of my post from [another issue](https://github.com/mono/mono/issues/7095#issuecomment-470465597)

--------------


This STILL crash on 5.18 and even on 5.20!
[pascalabcnet-dev.zip](https://github.com/mono/mono/files/2940636/pascalabcnet-dev.zip)

Run:
```bash
mono pabcnetc.exe lab1-02_draw.pas
```

And result:
```
$ mono pabcnetc.exe lab1-02_draw.pas
Loading core...
Подключен парсер PascalABC.NET Language Parser v1.2
Подключен парсер Documentation Comments Tag Parser v0.9
PascalABCCompiler.Core v3.4.2.1991
Copyright (c) 2005-2018 by Ivan Bondarev, Stanislav Mihalkovich
OK 39,277ms
Connected parsers: PascalABC.NET (*.pas); 
Connected conversions: Optimizer; 
Compiling assembly lab1-02_draw.pas...
* Assertion at class-accessors.c:41, condition `mono_class_is_ginst (klass)' not met


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
/proc/self/maps:
4067b000-4068b000 rwxp 00000000 00:00 0 
41f87000-42047000 rwxp 00000000 00:00 0 
55f9ee8f7000-55f9eed43000 r-xp 00000000 08:13 4850616                    /usr/bin/mono-sgen
55f9eef42000-55f9eef49000 r--p 0044b000 08:13 4850616                    /usr/bin/mono-sgen
55f9eef49000-55f9eef4e000 rw-p 00452000 08:13 4850616                    /usr/bin/mono-sgen
55f9eef4e000-55f9eef65000 rw-p 00000000 00:00 0 
55f9f0c9f000-55f9f1b16000 rw-p 00000000 00:00 0                          [heap]
7f4b870bc000-7f4b8713c000 rw-p 00000000 00:00 0 
7f4b87140000-7f4b871c0000 rw-p 00000000 00:00 0 
7f4b871c4000-7f4b87244000 rw-p 00000000 00:00 0 
7f4b87248000-7f4b872c8000 rw-p 00000000 00:00 0 
7f4b872cc000-7f4b8734c000 rw-p 00000000 00:00 0 
7f4b87350000-7f4b873d0000 rw-p 00000000 00:00 0 
7f4b873d4000-7f4b87454000 rw-p 00000000 00:00 0 
7f4b87458000-7f4b874d8000 rw-p 00000000 00:00 0 
7f4b874dc000-7f4b8755c000 rw-p 00000000 00:00 0 
7f4b87560000-7f4b875e0000 rw-p 00000000 00:00 0 
7f4b875e4000-7f4b87664000 rw-p 00000000 00:00 0 
7f4b87668000-7f4b876e8000 rw-p 00000000 00:00 0 
7f4b876ec000-7f4b8776c000 rw-p 00000000 00:00 0 
7f4b8776e000-7f4b87873000 rw-p 00000000 00:00 0 
7f4b87978000-7f4b879f8000 rw-p 00000000 00:00 0 
7f4b879fc000-7f4b87a7c000 rw-p 00000000 00:00 0 
7f4b87a7e000-7f4b87ed5000 rw-p 00000000 00:00 0 
7f4b8832c000-7f4b883ac000 rw-p 00000000 00:00 0 

=================================================================
	Basic Fault Adddress Reporting
=================================================================
Memory around native instruction pointer (0x7f4b9a956e97):0x7f4b9a956e87  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f4b9a956e97  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
0x7f4b9a956ea7  00 44 89 c0 75 1f 48 81 c4 18 01 00 00 c3 0f 1f  .D..u.H.........
0x7f4b9a956eb7  00 48 8b 15 a9 bf 3a 00 f7 d8 41 b8 ff ff ff ff  .H....:...A.....

=================================================================
	Native stacktrace:
=================================================================
        0x55f9eea219a8 - mono : (null)
        0x55f9ee9b7284 - mono : (null)
        0x7f4b9af33890 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
        0x7f4b9a956e97 - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
        0x7f4b9a958801 - /lib/x86_64-linux-gnu/libc.so.6 : abort
        0x55f9eec0da77 - mono : (null)
        0x55f9eebf3f93 - mono : (null)
        0x55f9eec0d9f8 - mono : (null)
        0x55f9eec0def3 - mono : monoeg_assertion_message
        0x55f9eeab63cd - mono : (null)
        0x55f9eeab0e99 - mono : (null)
        0x55f9eead0843 - mono : (null)
        0x41f894ff - Unknown

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7f4b90343700 from 0x7f4b9badd780
Entering thread summarizer pause from 0x7f4b9badd780
Finished thread summarizer pause from 0x7f4b9badd780.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
        External Debugger Dump:
=================================================================
[New LWP 20252]
[New LWP 20253]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f4b9af3323a in __waitpid (pid=20264, stat_loc=0x7ffee9f10b14, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: Нет такого файла или каталога.
  Id   Target Id         Frame 
* 1    Thread 0x7f4b9badd780 (LWP 20251) "mono" 0x00007f4b9af3323a in __waitpid (pid=20264, stat_loc=0x7ffee9f10b14, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f4b927ff700 (LWP 20252) "SGen worker" 0x00007f4b9af2e9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55f9eef62bc8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7f4b90343700 (LWP 20253) "Finalizer" 0x00007f4b9af316d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55f9eef53d80) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7f4b90343700 (LWP 20253)):
#0  0x00007f4b9af316d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55f9eef53d80) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55f9eef53d80, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f4b9af317c8 in __new_sem_wait_slow (sem=0x55f9eef53d80, abstime=0x0) at sem_waitcommon.c:181
#3  0x000055f9eeb88758 in ?? ()
#4  0x000055f9eeb3e58b in ?? ()
#5  0x00007f4b9af286db in start_thread (arg=0x7f4b90343700) at pthread_create.c:463
#6  0x00007f4b9aa3988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f4b927ff700 (LWP 20252)):
#0  0x00007f4b9af2e9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55f9eef62bc8) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55f9eef62be0, cond=0x55f9eef62ba0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55f9eef62ba0, mutex=0x55f9eef62be0) at pthread_cond_wait.c:655
#3  0x000055f9eebe98fa in ?? ()
#4  0x00007f4b9af286db in start_thread (arg=0x7f4b927ff700) at pthread_create.c:463
#5  0x00007f4b9aa3988f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f4b9badd780 (LWP 20251)):
#0  0x00007f4b9af3323a in __waitpid (pid=20264, stat_loc=0x7ffee9f10b14, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x000055f9eea21bf8 in ?? ()
#2  0x000055f9ee9b7284 in ?? ()
#3  <signal handler called>
#4  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#5  0x00007f4b9a958801 in __GI_abort () at abort.c:79
#6  0x000055f9eec0da77 in monoeg_assert_abort ()
#7  0x000055f9eebf3f93 in ?? ()
#8  0x000055f9eec0d9f8 in ?? ()
#9  0x000055f9eec0def3 in monoeg_assertion_message ()
#10 0x000055f9eeab63cd in ?? ()
#11 0x000055f9eeab0e99 in ?? ()
#12 0x000055f9eead0843 in ?? ()
#13 0x0000000041f894ff in ?? ()
#14 0x0000000000000014 in ?? ()
#15 0x0000000000000003 in ?? ()
#16 0x00007f4b871010c0 in ?? ()
#17 0x0000000000000014 in ?? ()
#18 0x00007f4b871010c0 in ?? ()
#19 0x000055f9f0cdb380 in ?? ()
#20 0x00007ffee9f12530 in ?? ()
#21 0x00007ffee9f123d0 in ?? ()
#22 0x0000000000000000 in ?? ()

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.RuntimeType:GetConstructors_native <0x000de>
          at System.RuntimeType:GetConstructors_internal <0x00054>
          at System.RuntimeType:GetConstructorCandidates <0x0019e>
          at System.RuntimeType:GetConstructors <0x00044>
          at System.Type:GetConstructors <0x00019>
          at PascalABCCompiler.TreeRealization.compiled_type_node:init_constructors <0x00037>
          at PascalABCCompiler.TreeRealization.compiled_type_node:get_type_node <0x000d5>
          at PascalABCCompiler.TreeRealization.compiled_function_node:.ctor <0x0022d>
          at PascalABCCompiler.TreeRealization.compiled_function_node:get_compiled_method <0x00069>
          at PascalABCCompiler.NetHelper.NetHelper:FindName <0x002ad>
          at PascalABCCompiler.TreeRealization.compiled_type_node:compiled_find <0x0001d>
          at PascalABCCompiler.TreeRealization.compiled_type_node:find <0x00079>
          at PascalABCCompiler.TreeRealization.compiled_type_node:find_in_type <0x00048>
          at PascalABCCompiler.TreeRealization.generic_instance_type_node:find_in_type <0x00037>
          at PascalABCCompiler.TreeRealization.common_type_node:find_in_type <0x00996>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit_method_call <0x01628>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x00011>
          at PascalABCCompiler.SyntaxTree.method_call:visit <0x00025>
          at PascalABCCompiler.TreeConverter.returner:visit <0x00024>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:convert_strong <0x0004d>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x001d3>
          at PascalABCCompiler.SyntaxTree.procedure_call:visit <0x00025>
          at PascalABCCompiler.TreeConverter.returner:visit <0x0001f>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:convert_strong <0x000eb>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x0021c>
          at PascalABCCompiler.SyntaxTree.statement_list:visit <0x00025>
          at PascalABCCompiler.TreeConverter.returner:visit <0x0001f>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:convert_strong <0x000eb>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit_program_code <0x0002c>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x0143a>
          at PascalABCCompiler.SyntaxTree.block:visit <0x00025>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:hard_node_test_and_visit <0x00077>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x014a8>
          at PascalABCCompiler.SyntaxTree.procedure_definition:visit <0x00025>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x00364>
          at PascalABCCompiler.SyntaxTree.declarations:visit <0x00025>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:weak_node_test_and_visit <0x00039>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit <0x00273>
          at PascalABCCompiler.SyntaxTree.implementation_node:visit <0x00025>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:hard_node_test_and_visit <0x00077>
          at PascalABCCompiler.TreeConverter.syntax_tree_visitor:visit_implementation <0x002d4>
          at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter:CompileImplementation <0x00434>
          at PascalABCCompiler.Compiler:CompileUnit <0x030a4>
          at PascalABCCompiler.Compiler:CompileUnit <0x01cff>
          at PascalABCCompiler.Compiler:Compile <0x00416>
          at PascalABCCompiler.Compiler:Compile <0x0007a>
          at PascalABCCompiler.Compiler:Compile <0x00024>
          at PascalABCCompiler.Compiler:Compile <0x0008a>
          at PascalABCCompiler.ConsoleCompiler:CompileAssembly <0x00301>
          at PascalABCCompiler.ConsoleCompiler:Main <0x002ec>
          at <Module>:runtime_invoke_int_object <0x000f4>
=================================================================
Аварийный останов (стек памяти сброшен на диск)
```

**Comment by CoffeeFlux** [comment]
Fixed with 016a5253bb57c376c9b444387edf22d3facc6ed8

**Comment by Wohlstand** [comment]
Going to test this once I'll get the working build on my end...

**Comment by CoffeeFlux** [comment]
You should be able to install a nightly to test (https://www.mono-project.com/download/nightly/), or any builds from 2019-08 (Mono version 6.6). If it's not fixed, I'll reopen.

I don't think this will fix #7095, but feel free to test that as well and let me know. Otherwise, I'll look at it next sprint.

**Comment by Wohlstand** [comment]
This still is crashy... 
```
Mono JIT compiler version 6.7.0.771 (tarball Thu Sep 26 14:15:18 UTC 2019)
```
[pascalabcnet.zip](https://github.com/mono/mono/files/3678715/pascalabcnet.zip)
run:
```
./pabcnetc lab1-03.pas
```
Looks like I should wait for tomorrow and pull the update and re-test...

**Comment by CoffeeFlux** [comment]
That looks like a different issue, which we're tracking at #7095. The bug in the first post here should be fixed.

**Comment by Wohlstand** [comment]
Ok, going to just track that issue. Thanks for the note!
