### ISSUE TITLE
Mono crashed on OSX 10.12.6

### ISSUE THREAD

**Issue by zulhfreelancer** [mono/mono#10524]
I'm trying to use Fiddler on Mac. But Mono was crashing.

## Steps to Reproduce

1. Download  Mono 5.14.0 (Stable channel) for Mac from [here](https://www.mono-project.com/download/stable/)
2. Run `/Library/Frameworks/Mono.framework/Versions/5.14.0/bin/mozroots --import --sync` in Terminal
3. Download Fiddler for Mac [here](https://www.telerik.com/download/fiddler/fiddler-osx-beta)
4. Extract the Fiddler artifacts from step 3
5. `cd` into the folder (step 4) and run `mono Fiddler.exe`

### Current Behavior

Mono was crashing with the following logs:

```
$ mono Fiddler.exe

WARNING: The Carbon driver has not been ported to 64bits, and very few parts of Windows.Forms will work properly, or at all
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.XplatUICarbon.CGDisplayBounds (intptr) [0x00002] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.XplatUICarbon.get_WorkingArea () [0x00005] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.XplatUICarbon.get_VirtualScreen () [0x00000] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.XplatUI.get_VirtualScreen () [0x00000] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Screen..cctor () [0x00034] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0001e] in <016f22b59bd64951b06e38b9f5a0506c>:0
  at <unknown> <0xffffffff>
  at System.Windows.Forms.Form.get_CreateParams () [0x00157] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Control.CreateHandle () [0x0002a] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Form.CreateHandle () [0x00000] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Control.CreateControl () [0x00039] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Control.SetVisibleCore (bool) [0x00057] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Form.SetVisibleCore (bool) [0x00065] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Control.set_Visible (bool) [0x00009] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at System.Windows.Forms.Control.Show () [0x00000] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control.Show () [0x00031] in <c3b66a59cfdf4121a767dcf115e9a2ab>:0
  at Fiddler.frmViewer. (string[]) [0x00081] in <09623c708fdb40a483cea147bbea7a7f>:0
  at Fiddler.frmViewer. (string[]) [0x00016] in <09623c708fdb40a483cea147bbea7a7f>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x0004e] in <09623c708fdb40a483cea147bbea7a7f>:0

Native stacktrace:

	0   mono                                0x000000010bfb5e98 mono_handle_native_crash + 264
	1   mono                                0x000000010c020446 altstack_handle_and_restore + 70
	2   SkyLight                            0x00007fff9057881c SLDisplayBounds + 50
	3   ???                                 0x0000000113a82c3e 0x0 + 4624755774
	4   ???                                 0x000000010c5a3526 0x0 + 4502205734
	5   mono                                0x000000010bf07f17 mono_jit_runtime_invoke + 1383
	6   mono                                0x000000010c0f7bd4 do_runtime_invoke + 84
	7   mono                                0x000000010c0f3b85 mono_runtime_class_init_full + 997
	8   mono                                0x000000010bf00855 mono_jit_compile_method_inner + 1205
	9   mono                                0x000000010bf03d69 mono_jit_compile_method_with_opt + 2537
	10  mono                                0x000000010bfb8c44 common_call_trampoline + 1364
	11  mono                                0x000000010bfb86a3 mono_magic_trampoline + 67
	12  ???                                 0x000000010c3a8393 0x0 + 4500128659
	13  ???                                 0x000000010fe83f8b 0x0 + 4561846155
	14  ???                                 0x000000010ebe725f 0x0 + 4542329439
	15  ???                                 0x000000010ebe6f37 0x0 + 4542328631
	16  ???                                 0x000000010c5a3053 0x0 + 4502204499
	17  mono                                0x000000010bf07f17 mono_jit_runtime_invoke + 1383
	18  mono                                0x000000010c0f7bd4 do_runtime_invoke + 84
	19  mono                                0x000000010c0fb3a9 do_exec_main_checked + 137
	20  mono                                0x000000010bf76d69 mono_jit_exec + 297
	21  mono                                0x000000010bf79d7d mono_main + 11213
	22  mono                                0x000000010bef7298 main + 264
	23  mono                                0x000000010bef7184 start + 52

Debug info from gdb:

(lldb) command source -s 0 '/tmp/mono-gdb-commands.Nmd1g3'
Executing commands in '/tmp/mono-gdb-commands.Nmd1g3'.
(lldb) process attach --pid 73309
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/mono/4.5/mscorlib.dll.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
warning: (x86_64) /Library/Frameworks/Mono.framework/Versions/5.14.0/lib/libglib-2.0.0.dylib empty dSYM file detected, dSYM was created with an executable with no debug info.
Process 73309 stopped
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007fff9434b3ee libsystem_kernel.dylib`__wait4 + 10
libsystem_kernel.dylib`__wait4:
->  0x7fff9434b3ee <+10>: jae    0x7fff9434b3f8            ; <+20>
    0x7fff9434b3f0 <+12>: movq   %rax, %rdi
    0x7fff9434b3f3 <+15>: jmp    0x7fff94343cd4            ; cerror
    0x7fff9434b3f8 <+20>: retq
Target 0: (mono) stopped.

Executable module set to "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono".
Architecture set to: x86_64h-apple-macosx.
(lldb) thread list
Process 73309 stopped
* thread #1: tid = 0x4bd233, 0x00007fff9434b3ee libsystem_kernel.dylib`__wait4 + 10, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  thread #2: tid = 0x4bd237, 0x00007fff9434abf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'SGen worker'
  thread #3: tid = 0x4bd238, 0x00007fff94343386 libsystem_kernel.dylib`semaphore_wait_trap + 10, name = 'Finalizer'
  thread #4: tid = 0x4bd239, 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #5: tid = 0x4bd23a, 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #6: tid = 0x4bd23b, 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
  thread #7: tid = 0x4bd261, 0x00007fff9434abf2 libsystem_kernel.dylib`__psynch_cvwait + 10, name = 'Timer-Scheduler'
(lldb) thread backtrace all
* thread #1, name = 'tid_307', queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00007fff9434b3ee libsystem_kernel.dylib`__wait4 + 10
    frame #1: 0x000000010bfb6078 mono`mono_handle_native_crash(signal=<unavailable>, ctx=<unavailable>, info=<unavailable>) at mini-exceptions.c:3048 [opt]
    frame #2: 0x000000010c020446 mono`altstack_handle_and_restore(ctx=0x00007fff53d08f60, obj=0x0000000000000000, stack_ovf=0) at exceptions-amd64.c:855 [opt]
    frame #3: 0x00007fff9057881c SkyLight`SLDisplayBounds + 50
    frame #4: 0x0000000113a82c3e
    frame #5: 0x000000010c5a3526
    frame #6: 0x000000010bf07f17 mono`mono_jit_runtime_invoke(method=0x00007fb66b002410, obj=<unavailable>, params=0x0000000000000000, exc=0x00007fff53d09600, error=<unavailable>) at mini-runtime.c:3074 [opt]
    frame #7: 0x000000010c0f7bd4 mono`do_runtime_invoke(method=0x00007fb669844698, obj=0x0000000000000000, params=0x0000000000000000, exc=0x00007fff53d09600, error=0x00007fff53d097c0) at object.c:2942 [opt]
    frame #8: 0x000000010c0f3b85 mono`mono_runtime_class_init_full [inlined] mono_runtime_try_invoke(method=<unavailable>, obj=<unavailable>, params=<unavailable>, error=0x00007fff53d097c0) at object.c:3049 [opt]
    frame #9: 0x000000010c0f3b40 mono`mono_runtime_class_init_full(vtable=0x00007fb66a16a6f0, error=0x00007fff53d097c0) at object.c:519 [opt]
    frame #10: 0x000000010bf00855 mono`mono_jit_compile_method_inner(method=0x00007fb669844520, target_domain=0x00007fb669606190, opt=<unavailable>, error=0x00007fff53d097c0) at mini.c:4181 [opt]
    frame #11: 0x000000010bf03d69 mono`mono_jit_compile_method_with_opt(method=0x00007fb669844520, opt=<unavailable>, jit_only=<unavailable>, error=0x00007fff53d097c0) at mini-runtime.c:2394 [opt]
    frame #12: 0x000000010bfb8c44 mono`common_call_trampoline(regs=0x00007fff53d09878, code=<unavailable>, m=0x00007fb669844520, vt=0x0000000000000000, vtable_slot=<unavailable>, error=0x00007fff53d097c0) at mini-trampolines.c:755 [opt]
    frame #13: 0x000000010bfb86a3 mono`mono_magic_trampoline(regs=0x00007fff53d09878, code="H\x8b�H��\xa8H\x8b�8, arg=0x00007fb669844520, tramp=<unavailable>) at mini-trampolines.c:888 [opt]
    frame #14: 0x000000010c3a8393
    frame #15: 0x000000010fe83f8b
    frame #16: 0x000000010ebe725f
    frame #17: 0x000000010ebe6f37
    frame #18: 0x000000010c5a3053
    frame #19: 0x000000010bf07f17 mono`mono_jit_runtime_invoke(method=0x00007fb669607908, obj=<unavailable>, params=0x00007fff53d0a0d8, exc=0x0000000000000000, error=<unavailable>) at mini-runtime.c:3074 [opt]
    frame #20: 0x000000010c0f7bd4 mono`do_runtime_invoke(method=0x00007fb669607908, obj=0x0000000000000000, params=0x00007fff53d0a0d8, exc=0x0000000000000000, error=0x00007fff53d0a118) at object.c:2942 [opt]
    frame #21: 0x000000010c0fb3a9 mono`do_exec_main_checked [inlined] mono_runtime_invoke_checked(method=<unavailable>, obj=<unavailable>, error=0x00007fff53d0a118) at object.c:3095 [opt]
    frame #22: 0x000000010c0fb368 mono`do_exec_main_checked(method=0x00007fb669607908, args=<unavailable>, error=0x00007fff53d0a118) at object.c:4848 [opt]
    frame #23: 0x000000010bf76d69 mono`mono_jit_exec(domain=<unavailable>, assembly=<unavailable>, argc=1, argv=0x00007fff53d0a4a0) at driver.g.c:1211 [opt]
    frame #24: 0x000000010bf79d7d mono`mono_main [inlined] main_thread_handler at driver.g.c:1288 [opt]
    frame #25: 0x000000010bf79d49 mono`mono_main(argc=<unavailable>, argv=<unavailable>) at driver.g.c:2430 [opt]
    frame #26: 0x000000010bef7298 mono`main [inlined] mono_main_with_options(argc=<unavailable>, argv=<unavailable>) at main.c:50 [opt]
    frame #27: 0x000000010bef7284 mono`main(argc=2, argv=<unavailable>) at main.c:398 [opt]
    frame #28: 0x000000010bef7184 mono`start + 52
  thread #2, name = 'SGen worker'
    frame #0: 0x00007fff9434abf2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff944367fa libsystem_pthread.dylib`_pthread_cond_wait + 712
    frame #2: 0x000000010c1c052e mono`thread_func [inlined] mono_os_cond_wait(mutex=<unavailable>) at mono-os-mutex.h:173 [opt]
    frame #3: 0x000000010c1c051b mono`thread_func at sgen-thread-pool.c:165 [opt]
    frame #4: 0x000000010c1c050d mono`thread_func(data=0x0000000000000000) at sgen-thread-pool.c:196 [opt]
    frame #5: 0x00007fff9443593b libsystem_pthread.dylib`_pthread_body + 180
    frame #6: 0x00007fff94435887 libsystem_pthread.dylib`_pthread_start + 286
    frame #7: 0x00007fff9443508d libsystem_pthread.dylib`thread_start + 13
  thread #3, name = 'Finalizer'
    frame #0: 0x00007fff94343386 libsystem_kernel.dylib`semaphore_wait_trap + 10
    frame #1: 0x000000010c16e22c mono`finalizer_thread [inlined] mono_os_sem_wait(flags=MONO_SEM_FLAGS_ALERTABLE) at mono-os-semaphore.h:90 [opt]
    frame #2: 0x000000010c16e221 mono`finalizer_thread at mono-coop-semaphore.h:43 [opt]
    frame #3: 0x000000010c16e215 mono`finalizer_thread(unused=<unavailable>) at gc.c:903 [opt]
    frame #4: 0x000000010c11bbc3 mono`start_wrapper [inlined] start_wrapper_internal at threads.c:1098 [opt]
    frame #5: 0x000000010c11bb33 mono`start_wrapper(data=0x00007fb669702690) at threads.c:1158 [opt]
    frame #6: 0x00007fff9443593b libsystem_pthread.dylib`_pthread_body + 180
    frame #7: 0x00007fff94435887 libsystem_pthread.dylib`_pthread_start + 286
    frame #8: 0x00007fff9443508d libsystem_pthread.dylib`thread_start + 13
  thread #4
    frame #0: 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff94435621 libsystem_pthread.dylib`_pthread_wqthread + 1426
    frame #2: 0x00007fff9443507d libsystem_pthread.dylib`start_wqthread + 13
  thread #5
    frame #0: 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff9443548e libsystem_pthread.dylib`_pthread_wqthread + 1023
    frame #2: 0x00007fff9443507d libsystem_pthread.dylib`start_wqthread + 13
  thread #6
    frame #0: 0x00007fff9434b44e libsystem_kernel.dylib`__workq_kernreturn + 10
    frame #1: 0x00007fff94435621 libsystem_pthread.dylib`_pthread_wqthread + 1426
    frame #2: 0x00007fff9443507d libsystem_pthread.dylib`start_wqthread + 13
  thread #7, name = 'Timer-Scheduler'
    frame #0: 0x00007fff9434abf2 libsystem_kernel.dylib`__psynch_cvwait + 10
    frame #1: 0x00007fff94436833 libsystem_pthread.dylib`_pthread_cond_wait + 769
    frame #2: 0x000000010c1cdc04 mono`mono_os_cond_timedwait(cond=0x00007fb66a8184e0, mutex=0x00007fb66a8184a0, timeout_ms=497) at mono-os-mutex.c:44 [opt]
    frame #3: 0x000000010c139b67 mono`mono_w32handle_timedwait_signal_handle at mono-coop-mutex.h:102 [opt]
    frame #4: 0x000000010c139b49 mono`mono_w32handle_timedwait_signal_handle [inlined] mono_w32handle_timedwait_signal_naked(poll=0, alerted=<unavailable>) at w32handle.c:646 [opt]
    frame #5: 0x000000010c139b49 mono`mono_w32handle_timedwait_signal_handle(handle_data=<unavailable>, timeout=<unavailable>, poll=0, alerted=<unavailable>) at w32handle.c:761 [opt]
    frame #6: 0x000000010c139a41 mono`mono_w32handle_wait_one(handle=<unavailable>, timeout=<unavailable>, alertable=<unavailable>) at w32handle.c:879 [opt]
    frame #7: 0x000000010c139cb2 mono`mono_w32handle_wait_multiple(handles=0x00007000067399a0, nhandles=1, waitall=0, timeout=<unavailable>, alertable=1) at w32handle.c:917 [opt]
    frame #8: 0x000000010c116598 mono`ves_icall_System_Threading_WaitHandle_Wait_internal(handles=<unavailable>, numhandles=<unavailable>, waitall='\0', timeout=-1, error=0x00007000067398b0) at threads.c:2054 [opt]
    frame #9: 0x0000000113a74c9d
    frame #10: 0x000000010e240120 mscorlib.dll.dylib`System_Threading_WaitHandle_InternalWaitOne_System_Runtime_InteropServices_SafeHandle_long_bool_bool + 64
    frame #11: 0x000000010e2400cc mscorlib.dll.dylib`System_Threading_WaitHandle_WaitOne_long_bool + 44
    frame #12: 0x000000010e23ff2c mscorlib.dll.dylib`System_Threading_WaitHandle_WaitOne_int_bool + 60
    frame #13: 0x000000010e24005c mscorlib.dll.dylib`System_Threading_WaitHandle_WaitOne_int + 28
    frame #14: 0x000000010e2455a6 mscorlib.dll.dylib`System_Threading_Timer_Scheduler_SchedulerThread + 262
    frame #15: 0x000000010e238c57 mscorlib.dll.dylib`System_Threading_ThreadHelper_ThreadStart_Context_object + 151
    frame #16: 0x000000010e236781 mscorlib.dll.dylib`System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool + 33
    frame #17: 0x000000010e236712 mscorlib.dll.dylib`System_Threading_ExecutionContext_Run_System_Threading_ExecutionContext_System_Threading_ContextCallback_object + 82
    frame #18: 0x000000010e238d9f mscorlib.dll.dylib`System_Threading_ThreadHelper_ThreadStart + 47
    frame #19: 0x000000010c5ae129
    frame #20: 0x000000010bf07f17 mono`mono_jit_runtime_invoke(method=0x000000010c854028, obj=<unavailable>, params=0x0000700006739ea8, exc=0x000000010c8542c8, error=<unavailable>) at mini-runtime.c:3074 [opt]
    frame #21: 0x000000010c0f7bd4 mono`do_runtime_invoke(method=0x00007fb66b151c60, obj=0x000000010c854180, params=0x0000700006739ea8, exc=0x0000000000000000, error=0x0000700006739e40) at object.c:2942 [opt]
    frame #22: 0x000000010c11bbee mono`start_wrapper at threads.c:1106 [opt]
    frame #23: 0x000000010c11bb33 mono`start_wrapper(data=0x00007fb66976d030) at threads.c:1158 [opt]
    frame #24: 0x00007fff9443593b libsystem_pthread.dylib`_pthread_body + 180
    frame #25: 0x00007fff94435887 libsystem_pthread.dylib`_pthread_start + 286
    frame #26: 0x00007fff9443508d libsystem_pthread.dylib`thread_start + 13
(lldb) detach

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

Process 73309 detached
(lldb) quit
[1]    73309 abort      mono Fiddler.exe
```

### Expected Behavior

Mono runs without any problem so that Fiddler can be used.

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**: 5.14.0

## My environment

OSX: 10.12.6
Processor: 2.3 GHz Intel Core i5
Memory: 16 GB 2133 MHz LPDDR3

**Comment by filipnavara** [comment]
More info: https://github.com/mono/mono/issues/6701

**Comment by akoeplinger** [comment]
Closing since the work of making WinForms work in 64bit Mono is tracked by #6701.

**Comment by ajariwala** [comment]
I had same issue - here is what I did - you can run it with 32bit mode. 
mono --arch=32 fiddler.exe
