### ISSUE TITLE
Getting Mono.Cecil.ResolutionException during build

### ISSUE THREAD

**Issue by danroth27** [mono/mono#10653]
_From @kunalspathak on September 16, 2018 4:25_

Please let me know if this issue should be open in mono repository,

I followed [directions](https://blazor.net/docs/get-started.html) to start Blazor. It build and worked fine. Then I tried writing some code using [Prose SDKs](https://www.nuget.org/packages/Microsoft.ProgramSynthesis/) and when I built, I get following errors. Is there something that is not supported yet?
```cmd
         Fatal error in IL Linker
         Mono.Cecil.ResolutionException: Failed to resolve System.Runtime.Loader.AssemblyLoadContext
            at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
            at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
            at Mono.Linker.Steps.MarkStep.MarkField(FieldReference reference)
            at Mono.Linker.Steps.MarkStep.InitializeFields(TypeDefinition type)
            at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
            at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
            at Mono.Linker.Steps.MarkStep.Initialize()
            at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
            at Mono.Linker.Pipeline.Process(LinkContext context)
            at Mono.Linker.Driver.Run(ILogger customLogger)
            at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
```

The code I had in `cshtml` file is 

```csharp
        Session s = new Session();
        IEnumerable<Example> examples = new[]
        {
            new Example(new InputRow("Greta Hermansson"), "Hermansson, G.")
        };
        s.Constraints.Add(examples);
        Microsoft.ProgramSynthesis.Transformation.Text.Program program = s.Learn();
        code = program.ToString();
```

_Copied from original issue: aspnet/Blazor#1431_

**Comment by danroth27** [comment]
Looks like a potential issue with the IL linker. Moving to mono.

**Comment by marek-safar** [comment]
@kunalspathak could you share also your Example class definition

**Comment by kunalspathak** [comment]
Sure. I am using [Prose SDKs](https://microsoft.github.io/prose/) and the docs for `Example` class and other classes are [here](https://prose-docs.azurewebsites.net/html/T_Microsoft_ProgramSynthesis_Transformation_Text_Example.htm).

**Comment by marek-safar** [comment]
Self contained code

```c#
using System;
using System.Collections.Generic;
using Microsoft.ProgramSynthesis;
using Microsoft.ProgramSynthesis.Transformation.Text;
using Microsoft.ProgramSynthesis.Transformation.Text.Semantics;
using Microsoft.ProgramSynthesis.Wrangling.Constraints;
using System.Reflection;
using System.Runtime.InteropServices;

namespace Application {
	class Example : Microsoft.ProgramSynthesis.Wrangling.Constraints.Constraint<IRow, object> {
		public Example (IRow ir, string s)
		{
		}

		public override int GetHashCode ()
		{
			throw new NotImplementedException ();
		}

		public override bool Equals (Constraint<IRow, object> other)
		{
			throw new NotImplementedException ();
		}

		public override bool Valid (Program<IRow, object> program)
		{
			throw new NotImplementedException ();
		}

		public override bool ConflictsWith (Constraint<IRow, object> other)
		{
			throw new NotImplementedException ();
		}
	}

	class MainClass {
		public static void Main (string [] args)
		{
			Session s = new Session ();
			IEnumerable<Example> examples = new [] {
				new Example(new InputRow("Greta Hermansson"), "Hermansson, G.")
			};

			s.Constraints.Add (examples);
			Microsoft.ProgramSynthesis.Transformation.Text.Program program = s.Learn ();
			var code = program.ToString ();
		}
	}
}
```

**Comment by kumpera** [comment]
Looks like we have a reduced test case that shows the issue.

**Comment by kunalspathak** [comment]
any update on this?

I am facing similar issue when I run 
```
"C:\Program Files (x86)\Mono\bin\mono.exe" F:\tools\wasm-sdk\packager.exe --copy=always --out=bin\Debug\netstandard2.0\eweb_extension --asset=sample.html --asset=manifest.json --asset=hello_extensions.png --asset=sample-init.js --asset=contentScript.js --asset=mono.js bin\Debug\netstandard2.0\EWeb.dll


1>Unhandled Exception:
1>Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.ProgramSynthesis.Extraction.Web, Version=6.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
1>
1>  at Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00105] in <14ff9be60fb24519843c33e0ecbcfe5f>:0
1>
1>  at Driver.Import (System.String ra, Driver+AssemblyKind kind) [0x0015b] in <d8768d8a2f894dd0aa21c1a732124906>:0
1>
1>  at Driver.Run (System.String[] args) [0x00869] in <d8768d8a2f894dd0aa21c1a732124906>:0
1>
1>  at Driver.Main (System.String[] args) [0x00006] in <d8768d8a2f894dd0aa21c1a732124906>:0
1>[ERROR] FATAL UNHANDLED EXCEPTION: Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.ProgramSynthesis.Extraction.Web, Version=6.20.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
1>
1>  at Mono.Cecil.BaseAssemblyResolver.Resolve (Mono.Cecil.AssemblyNameReference name, Mono.Cecil.ReaderParameters parameters) [0x00105] in <14ff9be60fb24519843c33e0ecbcfe5f>:0
1>
1>  at Driver.Import (System.String ra, Driver+AssemblyKind kind) [0x0015b] in <d8768d8a2f894dd0aa21c1a732124906>:0
1>
1>  at Driver.Run (System.String[] args) [0x00869] in <d8768d8a2f894dd0aa21c1a732124906>:0
1>
1>  at Driver.Main (System.String[] args) [0x00006] in <d8768d8a2f894dd0aa21c1a732124906>:0
```

**Comment by kunalspathak** [comment]
Ignore my above comment. Adding `--search-path` solved it. I was referring to the nuget package and I am not sure how `mono` resolves the `dlls` to be loaded for a nuget package. I had to  create a dummy project, added nuget packages, consumed it and then did `dotnet publish` which published all the required `dlls` in a folder. Then I passed that folder in `--search-path`.
