### ISSUE TITLE
[WASM] call to emscripten_sleep function in c and linkage to C#

### ISSUE THREAD

**Issue by roozbehid** [mono/mono#11750]
I have a function which calls emscripten_sleep which is async and I do put that function in EMTERPRETIFY_WHITELIST while I am compiling it to driver.c but I do get following errors 

`

    Uncaught (in promise) abort("Assertion failed: The call to mono_wasm_invoke_method is running asynchronously. If this was intended, add the async option to the ccall/cwrap call.") at Error

    at jsStackTrace (http://localhost:8000/mono.js:890:12)
    at stackTrace (http://localhost:8000/mono.js:904:11)
    at abort (http://localhost:8000/mono.js:19284:43)
    at assert (http://localhost:8000/mono.js:508:3)
    at ccall (http://localhost:8000/mono.js:565:3)
    at Object.invoke_method (http://localhost:8000/mono.js:582:10)
    at Object.call_method (http://localhost:8000/mono.js:14507:18)
    at Object.call_static_method (http://localhost:8000/mono.js:14553:15)
    at Object.init (http://localhost:8000/:21:13)
    at http://localhost:8000/runtime.js:11:9
`

So I am wondering if there is a way to call a function which uses emscripten_sleep ?

**Comment by kjpou1** [comment]
Could you maybe provide a sample project for us to look at?

**Comment by roozbehid** [comment]
Well I omitted that part because it is a bit complicated (or the way I know is complicated)

But here is the sample.

driver_inc.c

    void func() {
    printf("Hello\n");
    emscripten_sleep(1000);
    printf("World\n");
    }

then you do the following patch to driver.c (from mono/sdks/wasm)


     --- a/sdks/wasm/driver.c
     +++ b/sdks/wasm/driver.c
     @@ -141,6 +141,8 @@ mono_wasm_setenv (const char *name, const char *value)
             monoeg_g_setenv (strdup (name), strdup (value), 1);
      }
     
     +#include "driver_inc.c"
     +
      EMSCRIPTEN_KEEPALIVE void
      mono_wasm_load_runtime (const char *managed_path, int enable_debugging)
      {
     @@ -191,6 +193,8 @@ mono_wasm_load_runtime (const char *managed_path, int enable_debugging)
             // Blazor specific custom routines - see dotnet_support.js for backing code
             mono_add_internal_call ("WebAssembly.JSInterop.InternalCalls::InvokeJSMarshalled", mono_wasm_invoke_js_marshalled);
             mono_add_internal_call ("WebAssembly.JSInterop.InternalCalls::InvokeJSUnmarshalled", mono_wasm_invoke_js_unmarshalled);
     +
     +    mono_add_internal_call ("cs.Program::func", func);
     
      }

Then you compile using the instructions in [mono/sdks/wasm/READNE.MD](https://github.com/mono/mono/blob/master/sdks/wasm/README.md)

Your cs file would be 

    using System;
    using System.Runtime.CompilerServices;
    using System.Runtime.InteropServices;
    
    namespace cs
    {
        class Program
        {
            [MethodImpl(MethodImplOptions.InternalCall)]
            public static extern void func();
    
            static void Main(string[] args)
            {
                func();
            }
        }
    }

It wont work normally because you are calling a async method (emscripten_sleep) so you have to use [emterpreter](https://github.com/kripken/emscripten/wiki/Emterpreter) version of that function.

Which leads to add following to your compile instructions (the one you used from README.MD)
`-s EMTERPRETIFY=1 -s EMTERPRETIFY_ASYNC=1 -s "EMTERPRETIFY_WHITELIST=['func']"`

But then the problem seems to be any function calling this method should also be included which leads to what I posted in the first post. But it still wont work because mono calls synchronos versions of ccall/cwrap.

I also found this merge into Emscripten which enables [asynchronous ccal/cwrap](https://github.com/kripken/emscripten/issues/3596) but still I couldnt fully make it work.
