### ISSUE TITLE
Periodic crash in Ubuntu

### ISSUE THREAD

**Issue by wspear** [mono/mono#12731]
I have already reported this bug to the keepass folks and they said it was an issue for Mono. Since reproducing the problem on other systems may be difficult I am happy to do additional testing if necessary.

## Steps to Reproduce

0. This may not be relevant, but my system has 2 monitors running on Nvidia drivers. One of the monitors is rotated 90 degrees by the driver. I have not seen this error on other systems and do not know what else makes this one unique.
1. Install the latest (or any recent) keepass2 (https://keepass.info/download.html)
2. Load and use keepass2.
3. Keep keepass2 open in the background while using other applications
4. Upon returning to the keepass2 window, sometimes but unpredictably the error will occur. 

### Current Behavior

The application crashes or sometimes (with keepass2's new error handling features) freezes and must be killed.

### Expected Behavior

Use the application and change between applications without fatal errors.

## On which platforms did you notice this

[ ] macOS
[X] Linux (Ubuntu 18.04.1 LTS. Also observed on prior LTS release)
[ ] Windows

**Version Used**:

5.18.0.240 (From Ubuntu Mono PPA) (Also observed on the version provided by default Ubuntu repos)

## Stacktrace

```
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.Windows.Forms.X11Keyboard.XSetICFocus (intptr) [0x00002] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.X11Keyboard.FocusIn (intptr) [0x0004e] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.XplatUIX11.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) [0x0149e] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.XplatUI.GetMessage (object,System.Windows.Forms.MSG&,intptr,int,int) [0x00000] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) [0x0034e] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) [0x00011] in <895eff5fc3c3440985711e3d9bfab833>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) [0x00006] in <895eff5fc3c3440985711e3d9bfab833>:0
  at KeePass.Program.MainPriv (string[]) [0x004f4] in <fbae7671f2e746cc8d58dca1009b7b47>:0
  at KeePass.Program.Main (string[]) [0x00000] in <fbae7671f2e746cc8d58dca1009b7b47>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x0004e] in <fbae7671f2e746cc8d58dca1009b7b47>:0
/proc/self/maps:
40012000-40165000 rwxp 00000000 00:00 0 
410f2000-412ee000 rwxp 00000000 00:00 0 
412fc000-4130c000 rwxp 00000000 00:00 0 
55c4f0ef3000-55c4f133e000 r-xp 00000000 08:01 8913082                    /usr/bin/mono-sgen
55c4f153d000-55c4f1544000 r--p 0044a000 08:01 8913082                    /usr/bin/mono-sgen
55c4f1544000-55c4f1549000 rw-p 00451000 08:01 8913082                    /usr/bin/mono-sgen
55c4f1549000-55c4f15da000 rw-p 00000000 00:00 0 
55c4f26d5000-55c4f3a7f000 rw-p 00000000 00:00 0                          [heap]
7fa02c000000-7fa02c067000 rw-p 00000000 00:00 0 
7fa02c067000-7fa030000000 ---p 00000000 00:00 0 
7fa030000000-7fa030021000 rw-p 00000000 00:00 0 
7fa030021000-7fa034000000 ---p 00000000 00:00 0 
7fa034000000-7fa034021000 rw-p 00000000 00:00 0 
7fa034021000-7fa038000000 ---p 00000000 00:00 0 
7fa038000000-7fa038066000 rw-p 00000000 00:00 0 
7fa038066000-7fa03c000000 ---p 00000000 00:00 0 
7fa03c000000-7fa03c021000 rw-p 00000000 00:00 0 
7fa03c021000-7fa040000000 ---p 00000000 00:00 0 
7fa040000000-7fa040021000 rw-p 00000000 00:00 0 
7fa040021000-7fa044000000 ---p 00000000 00:00 0 
7fa044000000-7fa044021000 rw-p 00000000 00:00 0 
7fa044021000-7fa048000000 ---p 00000000 00:00 0 
7fa048000000-7fa04813a000 rw-p 00000000 00:00 0 
7fa04813a000-7fa04c000000 ---p 00000000 00:00 0 
7fa04d7b4000-7fa04d834000 rw-p 00000000 00:00 0
```

**Comment by t00** [comment]
The issue is regularly happening after a sleep / resume cycle when KeePass is running. It happens with the latest arch linux build 2.54.

```
Oct 01 17:06:17 archlinux systemd-coredump[51975]: [🡕] Process 4694 (mono) of user 1000 dumped core.
                                                   
                                                   Module KeePass.exe.so without build-id.
                                                   Module mscorlib.dll.so without build-id.
                                                   Stack trace of thread 4694:
                                                   #0  0x00007f07c5c5183c n/a (libc.so.6 + 0x8e83c)
                                                   #1  0x00007f07c5c01668 raise (libc.so.6 + 0x3e668)
                                                   #2  0x00007f07c5be94b8 abort (libc.so.6 + 0x264b8)
                                                   #3  0x00005560181e211c n/a (mono-sgen + 0x2b11c)
                                                   #4  0x00005560182758e5 n/a (mono-sgen + 0xbe8e5)
                                                   #5  0x000055601b1c2fa0 n/a (n/a + 0x0)
                                                   #6  0x00000000413a49c5 n/a (n/a + 0x0)
                                                   ELF object binary architecture: AMD x86-64
Oct 01 17:06:17 archlinux systemd[1]: Started Process Core Dump (PID 51974/UID 0).
Oct 01 17:06:17 archlinux keepass.desktop[4694]: =================================================================
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at <Module>:runtime_invoke_void_object <0x00091>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at KeePass.Program:Main <0x00028>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at KeePass.Program:MainPriv <0x0113f>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.Application:Run <0x0004f>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.Application:Run <0x0007f>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.Application:RunLoop <0x00aab>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.XplatUI:GetMessage <0x00064>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.XplatUIX11:GetMessage <0x03beb>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.X11Keyboard:FocusIn <0x000f7>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at System.Windows.Forms.X11Keyboard:XSetICFocus <0x00092>
Oct 01 17:06:17 archlinux keepass.desktop[4694]:           at <unknown> <0xffffffff>
Oct 01 17:06:17 archlinux keepass.desktop[4694]: =================================================================
Oct 01 17:06:17 archlinux keepass.desktop[4694]:         Managed Stacktrace:
Oct 01 17:06:17 archlinux keepass.desktop[4694]: =================================================================
Oct 01 17:06:17 archlinux keepass.desktop[4694]: 0x55601b1c2fc0  e0 2f e2 1a 60 55 00 00 60 44 bf 1a 60 55 00 00  ./..`U..`D..`U..
Oct 01 17:06:17 archlinux keepass.desktop[4694]: 0x55601b1c2fb0  40 bf d9 c5 07 7f 00 00 10 48 91 1a 60 55 00 00  @........H..`U..
Oct 01 17:06:17 archlinux keepass.desktop[4694]: 0x55601b1c2fa0  00 00 00 00 00 00 00 00 d1 04 00 00 00 00 00 00  ................
Oct 01 17:06:17 archlinux keepass.desktop[4694]: Memory around native instruction pointer (0x55601b1c2fa0):0x55601b1c2f90  08 0a 89 f8 09 0a 88 f8 06 07 84 fb 02 02 6a c3  ..............j.
Oct 01 17:06:17 archlinux keepass.desktop[4694]: =================================================================
Oct 01 17:06:17 archlinux keepass.desktop[4694]:         Basic Fault Address Reporting
Oct 01 17:06:17 archlinux keepass.desktop[4694]: =================================================================
Oct 01 17:06:17 archlinux keepass.desktop[51923]: [Inferior 1 (process 4694) detached]
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #8  0x0000000000000000 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #7  0x00007f07ba81df30 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #6  0x000000004139cda3 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #5  0x0000000000000001 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #4  0x000055601b1c2fa0 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #3  0x00005560182758e5 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #2  0x0000556018230437 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #1  0x00005560182871a6 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #0  0x00007f07c5cbd1c7 in wait4 () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: Thread 1 (Thread 0x7f07c5bc2040 (LWP 4694) "mono"):
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #4  0x00007f07c5cd37cc in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #3  0x00007f07c5c4f9eb in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #2  0x00005560184e7855 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #1  0x00007f07c5c4ed40 in pthread_cond_wait () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #0  0x00007f07c5c4c4ae in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: Thread 2 (Thread 0x7f07c4fff6c0 (LWP 4697) "SGen worker"):
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #5  0x00007f07c5cd37cc in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #4  0x00007f07c5c4f9eb in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #3  0x000055601843fb11 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #2  0x000055601848b6a6 in  ()
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #1  0x00007f07c5c57980 in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #0  0x00007f07c5c4c4ae in  () at /usr/lib/libc.so.6
Oct 01 17:06:17 archlinux keepass.desktop[51923]: Thread 3 (Thread 0x7f07c577b6c0 (LWP 4698) "Finalizer"):
Oct 01 17:06:17 archlinux keepass.desktop[51923]: #33 0x00007f07c1e307db in KeePass_Util_IpcBroadcast_TcpThreadProcPriv () at /usr/share/keepass/KeePass.exe.so

```
