### ISSUE TITLE
[WASM] Mixed Mode: function signature mismatch

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#13463]
Using the sample here: https://github.com/jeromelaban/Wasm.Samples/tree/master/MixedMode.Tests

The built website is using mixed mode compilation, with some assemblies explicitly excluded. I could not get down to a smaller repro.

## Steps to Reproduce
1. Using linux (and the setup [outlined here](https://github.com/nventive/Uno/blob/bd4717975745abcfcc6a49dabd48a5fa00db5e20/doc/blog/201903-using-wsl-to-build-aot.md#setting-the-build-environment-under-wsl)), build the application using
`msbuild /r /p:Configuration=Release`
2. Run the application in FF or Chrome in the `bin\Release\netstandard2.0\dist` using the `server.py`

### Current Behavior

```
uno-bootstrap.js:147 RuntimeError: function signature mismatch
    at _Uno_Foundation_Uno_Extensions_NotifyCollectionChangedEventArgsExtensions_ToNotifyCollectionChangedEventArgs_Windows_Foundation_Collections_IVectorChangedEventArgs (wasm-function[7855]:320)
    at _aot_wrapper_gsharedvt_out_sig_u4_u4 (wasm-function[8333]:18)
    at _jit_call_cb (wasm-function[16434]:143)
    at dynCall_vi (wasm-function[17338]:5)
    at Module.dynCall_vi (http://localhost:8000/mono.js:13810:38)
    at invoke_vi (http://localhost:8000/mono.js:10324:5)
    at _mono_llvm_cpp_catch_exception (wasm-function[10866]:20)
    at _do_jit_call (wasm-function[16420]:957)
    at _interp_exec_method_full (wasm-function[16410]:25137)
    at _interp_exec_method_full (wasm-function[16410]:22575)
```

### Expected Behavior
`OnItemsSourceSingleCollectionChanged` is displayed in the debugging console.

## On which platforms did you notice this
**Version Used**: 8fed6666b080d3d5634fd9068cd42f273f819eeb

**Comment by vargaz** [comment]
Have some difficulty building this ? Could you attach the obj and bin directories for the app ?
