### ISSUE TITLE
Interpreter Crash on Reference Source System.Web.Extensions 

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14079]
During the jenkins build for https://github.com/mono/mono/pull/12619, there was an interesting interpreter crash that I wasn't able to reproduce.  

## Steps to Reproduce

1. Pull branch from https://github.com/mono/mono/pull/12619
2. Run interpreter test for System.Web.Extensions (make -w -C mcs/class/System.Web.Extensions run-test V=1)

### Current Behavior

A crash is reported for MonoTests.System.Web.UI.WebControls.ListViewTest.Bug_535701_2

https://gist.github.com/steveisok/6cc918de0b0243bf59c5418be489a25f

https://jenkins.mono-project.com/job/test-mono-pull-request-interpreter/16479/parsed_console/log.html

### Expected Behavior

It shouldn't crash

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Comment by lewurm** [comment]
The relevant bits from the crash
```
Thread 1 (Thread 0x7fd4eac65740 (LWP 21816)):
#0  0x00007fd4ea132b5a in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000055ed6fad6700 in dump_native_stacktrace (mctx=mctx@entry=0x7ffd8c6ebf00, signal=0x55ed6fd4e578 "SIGABRT") at mini-posix.c:1111
#2  0x000055ed6fad6801 in mono_dump_native_crash_info (signal=signal@entry=0x55ed6fd4e578 "SIGABRT", mctx=mctx@entry=0x7ffd8c6ebf00, info=info@entry=0x7ffd8c6ec1f0) at mini-posix.c:1153
#3  0x000055ed6fa838d9 in mono_handle_native_crash (signal=signal@entry=0x55ed6fd4e578 "SIGABRT", mctx=mctx@entry=0x7ffd8c6ebf00, info=info@entry=0x7ffd8c6ec1f0) at mini-exceptions.c:3324
#4  0x000055ed6fad5b8f in sigabrt_signal_handler (_dummy=6, _info=0x7ffd8c6ec1f0, context=0x7ffd8c6ec0c0) at mini-posix.c:234
#5  <signal handler called>
#6  0x00007fd4e9b9efff in raise () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x00007fd4e9ba042a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#8  0x00007fd4e9bdcc00 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00007fd4e9be2fc6 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#10 0x00007fd4e9be380e in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#11 0x000055ed6fb7b76f in generate (error=<optimized out>, generic_context=<optimized out>, rtm=0x7ffd8c6ecbf0, header=<optimized out>, method=<optimized out>) at interp/transform.c:5776
#12 mono_interp_transform_method (imethod=0x7ffd8c6ecbf0, context=context@entry=0x55ed70ff03f0, error=error@entry=0x7ffd8c6ece10) at interp/transform.c:5896
#13 0x000055ed6fb5116e in do_transform_method (frame=0x7ffd8c6ed470, context=0x55ed70ff03f0) at interp/interp.c:2289
#14 0x000055ed6fb6457c in interp_exec_method_full (frame=0x7ffd8c6ed470, context=0x55ed70ff03f0, clause_args=0x0) at interp/interp.c:2870
#15 0x000055ed6fb57438 in interp_exec_method_full (frame=0x7ffd8c6ed7c0, context=0x55ed70ff03f0, clause_args=0x0) at interp/interp.c:3109
#16 0x000055ed6fb57438 in interp_exec_method_full (frame=0x7ffd8c6edb00, context=0x55ed70ff03f0, clause_args=0x0) at interp/interp.c:3109
#17 0x000055ed6fb5295c in interp_exec_method_full (frame=0x7ffd8c6ede60, context=0x55ed70ff03f0, clause_args=0x0) at interp/interp.c:3296
#18 0x000055ed6fb5295c in interp_exec_method_full (frame=0x7ffd8c6ee190, context=0x55ed70ff03f0, clause_args=0x0) at interp/interp.c:3296
```

/cc @BrzVlad

**Comment by marek-safar** [comment]
@BrzVlad any update on this crash?

**Comment by BrzVlad** [comment]
didn't look into it yet
