### ISSUE TITLE
[netcore] Test runner crashes on master

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14689]
## Steps to Reproduce

1. Pull from master 
2. Build for netcore (--with-core=only)
3. cd netcore && make xtest-System.Collections.Tests (or any test package for that matter)

### Current Behavior

Crashes with:

```
touch corefx/.stamp-dl-corefx-tests-4.6.0-preview6.19271.5
echo -n "***************** System.Collections.Tests *********************"
-n ***************** System.Collections.Tests *********************
cp corefx/restore/corefx-restore.deps.json corefx/tests/extracted/System.Collections.Tests/xunit.console.deps.json
cp corefx/restore/corefx-restore.deps.json corefx/tests/extracted/System.Collections.Tests/Microsoft.DotNet.RemoteExecutorHost.deps.json
cp corefx/restore/corefx-restore.runtimeconfig.dev.json corefx/tests/extracted/System.Collections.Tests/xunit.console.runtimeconfig.dev.json
cp corefx/restore/corefx-restore.runtimeconfig.dev.json corefx/tests/extracted/System.Collections.Tests/Microsoft.DotNet.RemoteExecutorHost.runtimeconfig.dev.json
cp corefx/restore/corefx-restore.dll corefx/tests/extracted/System.Collections.Tests/corefx-restore.dll
sed -i -e 's/9.9.9/3.0.0-preview6-27720-09/g' corefx/tests/extracted/System.Collections.Tests/*.runtimeconfig.json
cd corefx/tests/extracted/System.Collections.Tests && \
	COMPlus_DebugWriteToStdErr=1 /Users/steve/dev/mono-quicktest/netcore/./dotnet --fx-version "3.0.0-preview6-27720-09" xunit.console.dll System.Collections.Tests.dll \
		-html ../../TestResult-System.Collections.Tests.html -nunit ../../TestResult-System.Collections.Tests-netcore-xunit.xml \
		-notrait category=nonosxtests @../../../../CoreFX.issues.rsp \
		 || true

Unhandled Exception:
System.InvalidProgramException: Invalid IL code in System.IO.PathInternal:RemoveRelativeSegments (string,int): IL_0009: localloc  


   at System.IO.Path.GetFullPath(String path) in /Users/steve/dev/mono-quicktest/netcore/System.Private.CoreLib/shared/System/IO/Path.Unix.cs:line 37
   at System.IO.File.Exists(String path) in /_/src/System.IO.FileSystem/src/System/IO/File.cs:line 125
   at Xunit.AssemblyHelper..ctor(String assemblyFileName, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.AssemblyHelper.SubscribeResolveForAssembly(Type typeInAssembly, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.ConsoleClient.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidProgramException: Invalid IL code in System.IO.PathInternal:RemoveRelativeSegments (string,int): IL_0009: localloc  


   at System.IO.Path.GetFullPath(String path) in /Users/steve/dev/mono-quicktest/netcore/System.Private.CoreLib/shared/System/IO/Path.Unix.cs:line 37
   at System.IO.File.Exists(String path) in /_/src/System.IO.FileSystem/src/System/IO/File.cs:line 125
   at Xunit.AssemblyHelper..ctor(String assemblyFileName, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.AssemblyHelper.SubscribeResolveForAssembly(Type typeInAssembly, IMessageSink internalDiagnosticsMessageSink)
   at Xunit.ConsoleClient.Program.Main(String[] args)
```

### Expected Behavior

Test runner should run

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Comment by EgorBo** [comment]
No idea 🙁
As a workaround - remove this check https://github.com/mono/mono/blob/master/mono/mini/method-to-ir.c#L10777-L10778
but what went wrong and when?

**Comment by filipnavara** [comment]
I see there was a Roslyn bump recently. We have seen a similar error with miscompiled code from recent Roslyn so it may be worth investigating.

**Comment by EgorBo** [comment]
Yeah it started to fail after
https://github.com/mono/mono/commit/538ecf31efb5d51ac6255077869b64edd0f8fd9a
+
https://github.com/mono/mono/commit/0f4dd6bc49ed750e90d202e52052ef2d0f82487e

**Comment by filipnavara** [comment]
I believe the issue is the same as this one: https://github.com/dotnet/roslyn/issues/35764 ... a newer Roslyn may help?

**Comment by EgorBo** [comment]
Hm.. trying `3.2.0-beta3-19279-03`
