### ISSUE TITLE
SIGSEGV when calling GetType with IronPython

### ISSUE THREAD

**Issue by slozier** [mono/mono#14712]
## Steps to Reproduce

1. mono /usr/share/ironpython2.7/ipy.exe -S -c "import clr; print((1).GetType().Name)"

### Current Behavior

Got a SIGSEGV while executing native code.

### Expected Behavior

Expected an ouput of `Int32`

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:02:17 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(600)
        Suspend:       hybrid
        GC:            sgen (concurrent by default)

## Stacktrace

```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
/proc/self/maps:
7fec0000-80000000 rwxp 00000000 00:00 0
7fbda3ec0000-7fbda3f40000 rw-p 00000000 00:00 0
7fbda3f4a000-7fbda4000000 r--p 00000000 00:00 1075989            /usr/share/ironpython2.7/IronPython.Modules.dll
7fbda4000000-7fbda4021000 rw-p 00000000 00:00 0
7fbda4021000-7fbda8000000 ---p 00000000 00:00 0
7fbda8020000-7fbda8030000 rwxp 00000000 00:00 0
7fbda8030000-7fbda8031000 rw-p 00000000 00:00 0
7fbda8040000-7fbda8041000 rw-p 00000000 00:00 0
7fbda8045000-7fbda8200000 r--p 00000000 00:00 1075986            /usr/share/ironpython2.7/IronPython.dll
7fbda8200000-7fbda8301000 rw-p 00000000 00:00 0
7fbda8302000-7fbda8320000 r--p 00000000 00:00 143047             /usr/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll
7fbda8320000-7fbda8321000 rw-p 00000000 00:00 0
7fbda8323000-7fbda8370000 r--p 00000000 00:00 142843             /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7fbda8370000-7fbda8678000 r--p 00000000 00:00 142856             /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
7fbda8678000-7fbda88eb000 r--p 00000000 00:00 142914             /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
7fbda88eb000-7fbda89f0000 r--p 00000000 00:00 143034             /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
7fbda89f0000-7fbda89f1000 ---p 00000000 00:00 0
7fbda89f1000-7fbda89f2000 rw-p 00000000 00:00 0
7fbda89f2000-7fbda89fa000 ---p 00000000 00:00 0
7fbda89fa000-7fbda8bf1000 rw-p 00000000 00:00 0
7fbda8bfd000-7fbda917b000 r-xp 00000000 00:00 142894             /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fbda917b000-7fbda937b000 ---p 0057e000 00:00 142894             /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fbda937b000-7fbda937c000 r--p 0057e000 00:00 142894             /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fbda937c000-7fbda937d000 rw-p 0057f000 00:00 142894             /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so
7fbda937d000-7fbda93a6000 rw-p 00000000 00:00 0

=================================================================
        Native stacktrace:
=================================================================
        0x7fbdacd2b6c8 - mono : (null)
        0x7fbdaccc0944 - mono : (null)
        0x7fbdacd250b0 - mono : (null)
        0x7fbdace681e8 - mono : (null)

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7fbda8bf0700 from 0x7fbdacac0780
Entering thread summarizer pause from 0x7fbdacac0780
Finished thread summarizer pause from 0x7fbdacac0780.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
        External Debugger Dump:
=================================================================
mono_gdb_render_native_backtraces not supported on this platform, unable to find gdb or lldb
Aborted (core dumped)

```

**Comment by lewurm** [comment]
@slozier Thanks for your report!  Could you install `gdb` on your machine? This will give the crash reporter the opportunity to print better information.

**Comment by slozier** [comment]
@lewurm Here's the dump with gdb installed. Also it looks like I was incorrect in the title, it's not crashing when calling `GetType`, but when trying to do something (e.g. access a property, call a function) with the resulting type.
```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
/proc/self/maps:
7fec0000-80000000 rwxp 00000000 00:00 0
7fdb64000000-7fdb64021000 rw-p 00000000 00:00 0
7fdb64021000-7fdb68000000 ---p 00000000 00:00 0
7fdb69c8f000-7fdb69d45000 r--p 00000000 00:00 1075989            /usr/share/ironpython2.7/IronPython.Modules.dll
7fdb69d45000-7fdb69f00000 r--p 00000000 00:00 1075986            /usr/share/ironpython2.7/IronPython.dll
7fdb69f00000-7fdb6a000000 rw-p 00000000 00:00 0
7fdb6a000000-7fdb6a010000 rwxp 00000000 00:00 0
7fdb6a010000-7fdb6a011000 rw-p 00000000 00:00 0
7fdb6a020000-7fdb6a0a1000 rw-p 00000000 00:00 0
7fdb6a0b0000-7fdb6a0b1000 rw-p 00000000 00:00 0
7fdb6a0b2000-7fdb6a0d0000 r--p 00000000 00:00 143047             /usr/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll
7fdb6a0d0000-7fdb6a0d1000 rw-p 00000000 00:00 0
7fdb6a0e0000-7fdb6a0e1000 rw-p 00000000 00:00 0
7fdb6a0e3000-7fdb6a130000 r--p 00000000 00:00 142843             /usr/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
7fdb6a130000-7fdb6a131000 rw-p 00000000 00:00 0
7fdb6a140000-7fdb6a141000 rw-p 00000000 00:00 0
7fdb6a145000-7fdb6a44d000 r--p 00000000 00:00 142856             /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
7fdb6a44d000-7fdb6a6c0000 r--p 00000000 00:00 142914             /usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
7fdb6a6c0000-7fdb6a6de000 r--p 00000000 00:00 142901             /usr/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
7fdb6a6de000-7fdb6a7e3000 r--p 00000000 00:00 143034             /usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll
7fdb6a7e3000-7fdb6a806000 r--p 00000000 00:00 1075990            /usr/share/ironpython2.7/Microsoft.Scripting.dll
7fdb6a806000-7fdb6a8e0000 r--p 00000000 00:00 1075988            /usr/share/ironpython2.7/Microsoft.Dynamic.dll
7fdb6a8e0000-7fdb6a8e1000 ---p 00000000 00:00 0
7fdb6a8e1000-7fdb6a8e2000 rw-p 00000000 00:00 0
7fdb6a8e2000-7fdb6a8ea000 ---p 00000000 00:00 0

=================================================================
        Native stacktrace:
=================================================================
        0x7fdb6eb2b6c8 - mono : (null)
        0x7fdb6eac0944 - mono : (null)
        0x7fdb6eb250b0 - mono : (null)
        0x7fdb6ec681e8 - mono : (null)

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7fdb6aae0700 from 0x7fdb6e870780
Entering thread summarizer pause from 0x7fdb6e870780
Finished thread summarizer pause from 0x7fdb6e870780.

Waiting for dumping threads to resume

Debug info from gdb:


=================================================================
        External Debugger Dump:
=================================================================
[New LWP 250]
[New LWP 251]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fdb6dc3223a in __waitpid (pid=253, stat_loc=0x7fffc2314864, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame
* 1    Thread 0x7fdb6e870780 (LWP 249) "mono" 0x00007fdb6dc3223a in __waitpid (pid=253, stat_loc=0x7fffc2314864, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7fdb6cff0700 (LWP 250) "SGen worker" 0x00007fdb6dc2d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fdb6f071508) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7fdb6aae0700 (LWP 251) "Finalizer" 0x00007fdb6dc306d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fdb6f0626a0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7fdb6aae0700 (LWP 251)):
#0  0x00007fdb6dc306d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x7fdb6f0626a0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x7fdb6f0626a0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007fdb6dc307c8 in __new_sem_wait_slow (sem=0x7fdb6f0626a0, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007fdb6ec962e8 in ?? ()
#4  0x00007fdb6ec4bc5b in ?? ()
#5  0x00007fdb6dc276db in start_thread (arg=0x7fdb6aae0700) at pthread_create.c:463
#6  0x00007fdb6d72188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7fdb6cff0700 (LWP 250)):
#0  0x00007fdb6dc2d9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x7fdb6f071508) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x7fdb6f071520, cond=0x7fdb6f0714e0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x7fdb6f0714e0, mutex=0x7fdb6f071520) at pthread_cond_wait.c:655
#3  0x00007fdb6ecf72ca in ?? ()
#4  0x00007fdb6dc276db in start_thread (arg=0x7fdb6cff0700) at pthread_create.c:463
#5  0x00007fdb6d72188f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fdb6e870780 (LWP 249)):
#0  0x00007fdb6dc3223a in __waitpid (pid=253, stat_loc=0x7fffc2314864, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007fdb6eb2b918 in ?? ()
#2  0x00007fdb6eac0944 in ?? ()
#3  0x00007fdb6eb250b0 in ?? ()
#4  0x00007fdb6ec681e8 in ?? ()
#5  0x0000000000000000 in ?? ()
Aborted (core dumped)
```

**Comment by lewurm** [comment]
@alexanderkyte this looks like a crash in the crash dumper

**Comment by slozier** [comment]
@lewurm I'm running this in WSL, would this be causing the "crash in the crash dumper"? I'll see if I can spin up a real VM.

**Comment by alexanderkyte** [comment]
@lewurm I see the expected output for the crash dumper, not a hang or anything. If it manages to successfully return from calling out to lldb, that is the end of the "critical section" for the crash dumper.

At first glance it looks like it correctly dumped another native fault, and that the root cause of the fault broke the internal stack walker.

The aborted(core dumped) is just what happens when the signal handler returns at the end of the crash reporter. The signal that we temporarily suspended to dump the runtime gets to terminate us after the signal handler returns.

**Comment by slozier** [comment]
Doesn't appear to be an issue with Mono 6.4.0. I was using the latest bits at the time but presumably the issue would also have occurred with 2.7.9. The issue popped up in CI when Azure changed the Mono version from 5.18 to 5.20 in its ubuntu-16.04 VM.

**Comment by lewurm** [comment]
Okay, let's close it for now. If it re-appears feel free to open this issue again.

**Comment by slozier** [comment]
@lewurm This issue is back with Mono 6.8.0.96. I'm not seeing an option to re-open the issue?

**Comment by slozier** [comment]
Here's the stack trace:
```
$ mono /usr/share/ironpython2.7/ipy.exe -S -c "import clr; print((1).GetType().Name)"

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x55815e267265 - mono : (null)
        0x55815e2675fc - mono : (null)
        0x55815e212a21 - mono : (null)
        0x55815e260bfb - mono : (null)
        0x55815e41f658 - mono : (null)

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7f5daa285700 from 0x7f5dae4d4780
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x7f5dae4d4780
Finished thread summarizer pause from 0x7f5dae4d4780.

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 9901]
[New LWP 9902]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f5dadca523a in __waitpid (pid=9904, stat_loc=0x7ffc69e8b124, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id         Frame
* 1    Thread 0x7f5dae4d4780 (LWP 9900) "mono" 0x00007f5dadca523a in __waitpid (pid=9904, stat_loc=0x7ffc69e8b124, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f5dac7ff700 (LWP 9901) "SGen worker" 0x00007f5dadca09f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55815e842008) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7f5daa285700 (LWP 9902) "Finalizer" 0x00007f5dadca36d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55815e833280) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7f5daa285700 (LWP 9902)):
#0  0x00007f5dadca36d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x55815e833280) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x55815e833280, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f5dadca37c8 in __new_sem_wait_slow (sem=0x55815e833280, abstime=0x0) at sem_waitcommon.c:181
#3  0x000055815e44e5b8 in ?? ()
#4  0x000055815e401750 in ?? ()
#5  0x00007f5dadc9a6db in start_thread (arg=0x7f5daa285700) at pthread_create.c:463
#6  0x00007f5dad08488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f5dac7ff700 (LWP 9901)):
#0  0x00007f5dadca09f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55815e842008) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x55815e842020, cond=0x55815e841fe0) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x55815e841fe0, mutex=0x55815e842020) at pthread_cond_wait.c:655
#3  0x000055815e4a753a in ?? ()
#4  0x00007f5dadc9a6db in start_thread (arg=0x7f5dac7ff700) at pthread_create.c:463
#5  0x00007f5dad08488f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f5dae4d4780 (LWP 9900)):
#0  0x00007f5dadca523a in __waitpid (pid=9904, stat_loc=0x7ffc69e8b124, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x000055815e267575 in ?? ()
#2  0x000055815e2675fc in ?? ()
#3  0x000055815e212a21 in ?? ()
#4  0x000055815e260bfb in ?? ()
#5  0x000055815e41f658 in ?? ()
#6  0x0000000000000000 in ?? ()

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x55815e41f658):0x55815e41f648  00 00 00 00 41 55 41 54 55 53 0f 84 58 01 00 00  ....AUATUS..X...
0x55815e41f658  48 8b 42 18 49 89 fd 49 89 f4 49 89 d6 4c 89 c3  H.B.I..I..I..L..
0x55815e41f668  80 38 2e 0f 85 af 00 00 00 48 8d 3d 38 ee 0b 00  .8.......H.=8...
0x55815e41f678  b9 06 00 00 00 48 89 c6 f3 a6 0f 97 c2 80 da 00  .....H..........

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.RuntimeType:GetInterfaceMapData <0x000e0>
          at System.RuntimeType:GetInterfaceMap <0x000d6>
          at IronPython.Runtime.Types.PythonType:AddSystemInterfaces <0x005de>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0049f>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x0008b>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000eb>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x00123>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0027f>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x0008b>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000eb>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x00123>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0027f>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x0008b>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000eb>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x00123>
          at IronPython.Runtime.Types.DynamicHelpers:GetPythonTypeFromType <0x00043>
          at ResolveBinder:GetContributingTypes <0x000b3>
          at StandardResolver:ResolveMember <0x000bd>
          at IronPython.Runtime.Types.PythonTypeInfo:GetMemberGroup <0x00098>
          at IronPython.Runtime.Types.PythonTypeInfo:GetMemberAll <0x0008b>
          at IronPython.Runtime.Binding.PythonBinder:GetMember <0x0008f>
          at IronPython.Runtime.Binding.PythonGetMemberBinder:MakeGetMemberTarget <0x000d5>
          at IronPython.Runtime.Binding.PythonGetMemberBinder:BindDelegate <0x0120f>
          at System.Runtime.CompilerServices.CallSiteBinder:BindCore <0x0006e>
          at System.Dynamic.UpdateDelegates:UpdateAndExecute2 <0x00623>
          at GetMemberInstruction:Run <0x000f0>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x0014a>
          at Microsoft.Scripting.Interpreter.LightLambda:Run1 <0x000f3>
          at IronPython.Compiler.RuntimeScriptCode:InvokeTarget <0x00169>
          at IronPython.Compiler.RuntimeScriptCode:Run <0x00033>
          at IronPython.Hosting.PythonCommandLine:RunCommandWorker <0x001d6>
          at IronPython.Hosting.PythonCommandLine:RunCommand <0x00093>
          at Microsoft.Scripting.Hosting.Shell.CommandLine:Run <0x00054>
          at IronPython.Hosting.PythonCommandLine:Run <0x0042f>
          at Microsoft.Scripting.Hosting.Shell.CommandLine:Run <0x0010e>
          at Microsoft.Scripting.Hosting.Shell.ConsoleHost:RunCommandLine <0x0017f>
          at Microsoft.Scripting.Hosting.Shell.ConsoleHost:ExecuteInternal <0x000bf>
          at PythonConsoleHost:ExecuteInternal <0x0007f>
          at Microsoft.Scripting.Hosting.Shell.ConsoleHost:Execute <0x00158>
          at Microsoft.Scripting.Hosting.Shell.ConsoleHost:Run <0x006c7>
          at PythonConsoleHost:Main <0x00092>
          at <Module>:runtime_invoke_int_object <0x00091>
=================================================================
Aborted
```

**Comment by slozier** [comment]
I was able to reproduce the crash with the following C# code:
```C#
var type = typeof(System.Type);
foreach(var interf in type.GetInterfaces()) {
    type.GetInterfaceMap(interf);
}
```

**Comment by lambdageek** [comment]
Thanks for the concise repro @slozier !
Some gdb output (mono 6.8.0.96 on Linux amd64):
```
Thread 1 "mono" received signal SIGSEGV, Segmentation fault.
method_object_construct (domain=domain@entry=0x555555c4cd20, 
    refclass=refclass@entry="System.Type", method=method@entry=0x0, 
    user_data=user_data@entry=0x0, error=error@entry=0x7fffffffd760)
    at reflection.c:625
625	reflection.c: No such file or directory.
(gdb) bt
#0  method_object_construct (domain=domain@entry=0x555555c4cd20, 
    refclass=refclass@entry="System.Type", method=method@entry=0x0, 
    user_data=user_data@entry=0x0, error=error@entry=0x7fffffffd760)
    at reflection.c:625
#1  0x00005555557dda03 in check_or_construct_handle (
    construct=0x5555557dd790 <method_object_construct>, error=0x7fffffffd760, 
    user_data=0x0, item=0x0, klass="System.Type", domain=0x555555c4cd20)
    at ../../mono/metadata/reflection-cache.h:123
#2  mono_method_get_object_handle (domain=domain@entry=0x555555c4cd20, 
    method=0x0, refclass=refclass@entry="System.Type", 
    error=error@entry=0x7fffffffd760) at reflection.c:664
#3  0x000055555572e1ac in set_interface_map_data_method_object (
    error=0x7fffffffd760, i=9, methods=..., targets=..., klass="System.Type", 
    ioffset=32, iclass="System.Runtime.InteropServices._Type", 
    method=<optimized out>, domain=0x555555c4cd20) at icall.c:2900
#4  ves_icall_RuntimeType_GetInterfaceMapData (ref_type=..., 
    ref_type@entry=..., ref_iface=..., ref_iface@entry=..., targets=..., 
    targets@entry=..., methods=methods@entry=..., 
    error=error@entry=0x7fffffffd760) at icall.c:2943
#5  0x000055555574b6a9 in ves_icall_RuntimeType_GetInterfaceMapData_raw (
    a0=0x7fffffffd7f8, a1=0x7fffffffd800, a2=0x7fffffffd7e8, 
    a3=0x7fffffffd7f0, error=0x7fffffffd760)
    at ../../mono/metadata/icall-def.h:880
```

**Comment by ahstram** [comment]
Would just like to report that I experienced this issue with mono 6.8.0.105, 6.10.0.104 and 6.12.0.86.

I did not experience the issue with mono 3.2.8, but needed to update mono due to an unrelated TERM issue that was fixed in https://github.com/mono/mono/pull/6960.

Here is what my output looked like:

```=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x64eab8):0x64eaa8  00 41 55 41 54 55 53 48 85 f6 0f 84 48 01 00 00  .AUATUSH....H...
0x64eab8  48 8b 42 18 49 89 fe 49 89 f4 49 89 d5 4c 89 c3  H.B.I..I..I..L..
0x64eac8  80 38 2e 0f 85 af 00 00 00 b9 06 00 00 00 48 8d  .8............H.
0x64ead8  3d 35 e6 0b 00 48 89 c6 f3 a6 0f 97 c2 80 da 00  =5...H..........

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.RuntimeType:GetInterfaceMapData <0x000a4>
          at System.RuntimeType:GetInterfaceMap <0x0011f>
          at IronPython.Runtime.Types.PythonType:AddSystemInterfaces <0x0035f>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0045b>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x00087>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000df>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x000f3>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0024b>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x00087>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000df>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x000f3>
          at IronPython.Runtime.Types.PythonType:AddSystemBases <0x0024b>
          at IronPython.Runtime.Types.PythonType:InitializeSystemType <0x00087>
          at IronPython.Runtime.Types.PythonType:.ctor <0x000df>
          at IronPython.Runtime.Types.PythonType:GetPythonType <0x000f3>
          at IronPython.Runtime.Types.DynamicHelpers:GetPythonTypeFromType <0x0003f>
          at IronPython.Runtime.Types.DynamicHelpers:GetPythonType <0x000b7>
          at IronPython.Runtime.Binding.MetaPythonObject:GetPythonType <0x0008f>
          at IronPython.Runtime.Binding.BindingHelpers:TryGetStaticFunction <0x0005b>
          at IronPython.Runtime.Binding.SlotOrFunction:TryGetBinder <0x000cb>
          at IronPython.Runtime.Binding.SlotOrFunction:TryGetBinder <0x0005b>
          at IronPython.Runtime.Binding.SlotOrFunction:GetSlotOrFunction <0x00067>
          at IronPython.Runtime.Binding.PythonProtocol:MakeComparisonOperation <0x001df>
          at IronPython.Runtime.Binding.PythonProtocol:MakeBinaryOperation <0x00057>
          at IronPython.Runtime.Binding.PythonProtocol:Operation <0x0040f>
          at IronPython.Runtime.Binding.PythonBinaryOperationBinder:FallbackBinaryOperation <0x00043>
          at System.Dynamic.BinaryOperationBinder:FallbackBinaryOperation <0x00040>
          at System.Dynamic.DynamicMetaObject:BindBinaryOperation <0x00057>
          at System.Dynamic.BinaryOperationBinder:Bind <0x000b9>
          at System.Dynamic.DynamicMetaObjectBinder:Bind <0x001ff>
          at System.Runtime.CompilerServices.CallSiteBinder:BindCore <0x000a5>
          at System.Dynamic.UpdateDelegates:UpdateAndExecute2 <0x005ff>
          at Microsoft.Scripting.Interpreter.DynamicInstruction`3:Run <0x00117>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x000ed>
          at Microsoft.Scripting.Interpreter.LightLambda:Run2 <0x0010f>
          at IronPython.Compiler.PythonCallTargets:OriginalCallTarget1 <0x00075>
          at IronPython.Runtime.FunctionCaller`1:Call1 <0x000b3>
          at System.Dynamic.UpdateDelegates:UpdateAndExecute3 <0x0033f>
          at Microsoft.Scripting.Interpreter.DynamicInstruction`4:Run <0x00174>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x000ed>
          at Microsoft.Scripting.Interpreter.LightLambda:Run1 <0x000eb>
          at IronPython.Compiler.PythonCallTargets:OriginalCallTarget0 <0x00068>
          at Microsoft.Scripting.Interpreter.FuncCallInstruction`3:Run <0x000fa>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x000ed>
          at Microsoft.Scripting.Interpreter.LightLambda:Run3 <0x00137>
          at System.Dynamic.UpdateDelegates:UpdateAndExecute2 <0x00666>
          at Microsoft.Scripting.Interpreter.DynamicInstruction`3:Run <0x00117>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x000ed>
          at Microsoft.Scripting.Interpreter.LightLambda:Run1 <0x000eb>
          at IronPython.Compiler.PythonCallTargets:OriginalCallTarget0 <0x00068>
          at IronPython.Runtime.FunctionCaller:Call0 <0x000a8>
          at System.Dynamic.UpdateDelegates:UpdateAndExecute2 <0x00327>
          at Microsoft.Scripting.Interpreter.DynamicInstruction`3:Run <0x00117>
          at Microsoft.Scripting.Interpreter.Interpreter:Run <0x000ed>
          at Microsoft.Scripting.Interpreter.LightLambda:Run2 <0x0010f>
          at IronPython.Compiler.PythonScriptCode:RunWorker <0x00089>
          at IronPython.Compiler.PythonScriptCode:Run <0x00067>
          at IronPython.Compiler.RuntimeScriptCode:InvokeTarget <0x002b1>
          at IronPython.Compiler.RuntimeScriptCode:Run <0x0002f>
          at Microsoft.Scripting.SourceUnit:Execute <0x00088>
          at Microsoft.Scripting.SourceUnit:Execute <0x00037>
          at Microsoft.Scripting.Hosting.ScriptSource:Execute <0x0006b>
          at Microsoft.Scripting.Hosting.ScriptSource:Execute <0x0007b>
          at Chronos.Scripting.Script:Execute <0x0008f>
          at Chronos.Scripting.StartupScripts:RunScript <0x00103>
          at Chronos.Scripting.StartupScripts:RunPreBuildScript <0x0009b>
          at Chronos.Parser.Files.Pipeline:Init <0x00edb>
          at Chronos.Program:Process <0x00205>
          at Chronos.Program:Process <0x0019b>
          at Chronos.Program:Main <0x000d7>
          at <Module>:runtime_invoke_int_object <0x00085>
=================================================================
```

Thanks @slozier for suggesting mono 6.4.0. This is an acceptable workaround for me.
