### ISSUE TITLE
[interp] fix test failures of xtest-System.Runtime.Tests

### ISSUE THREAD

**Issue by lewurm** [mono/mono#14847]
See https://github.com/mono/mono/pull/14547

**Comment by lewurm** [comment]
If I understand correctly not everything is fixed by #15677, thus reopen.

**Comment by imhameed** [comment]
Ah, it looks like there were some changes made between 537fc4b60d0783dc260b4b26b64d1fd03db52cc8 (the parent of https://github.com/imhameed/mono/commit/ad092eb22d398b0e70aa4310356bc3a86da04308) and 561b400baa6322dcb3fb6d2b92bd48513fab79f7 that caused a new batch of failures. For posterity, here's what's failing as of 561b400baa6322dcb3fb6d2b92bd48513fab79f7: https://gist.github.com/imhameed/fae02b496acaf5176bc9d50cd7e6a45e

I'll take a look at these in a moment.

**Comment by lewurm** [comment]
```
Unhandled Exception:
System.ExecutionEngineException: Collectible AssemblyLoadContexts are not yet supported by MonoVM
   at System.Runtime.Loader.AssemblyLoadContext.InitializeAssemblyLoadContext(IntPtr thisHandlePtr, Boolean representsTPALoadContext, Boolean isCollectible)
   at System.Runtime.Loader.AssemblyLoadContext..ctor(Boolean representsTPALoadContext, Boolean isCollectible, String name)
   at System.Runtime.Loader.AssemblyLoadContext..ctor(Boolean isCollectible)
   at System.Reflection.Tests.TestAssemblyLoadContext..ctor()
   at System.Reflection.Tests.IsCollectibleTests.<>c.<MemberInfo_IsCollectibleTrue_WhenUsingAssemblyLoadContext>b__10_0(String marshalledName)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args)
```
@lambdageek any advice? ^

**Comment by imhameed** [comment]
Just reran this. There's one outstanding failure now:
```
    System.Runtime.CompilerServices.Tests.RuntimeFeatureTests.DynamicCode_Jit [FAIL]
    Assert.True() Failure
    Expected: True
    Actual:   False
      Stack Trace:
      /_/src/System.Runtime/tests/System/Runtime/CompilerServices/RuntimeFeatureTests.cs(35,0): at System.Runtime.CompilerServices.Tests.RuntimeFeatureTests.DynamicCode_Jit()
      /home/imran/ms/mono/mono/src/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by imhameed** [comment]
It looks like this test is already marked to not be run on CI via `CoreFX.issues_interpreter.rsp`, and the formerly failing `IsCollectibleTests` have also already been added to `CoreFX.issues.rsp`. I'm going to close this issue now.
