### ISSUE TITLE
[netcore]Make Microsoft.VisualBasic.Tests.ErrObjectTests.Clear pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14854]
The test currently fails with:

```
   Microsoft.VisualBasic.Tests.ErrObjectTests.Clear [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   2
      Stack Trace:
           at Microsoft.VisualBasic.Tests.ErrObjectTests.Clear()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    Microsoft.VisualBasic.Core.Tests
```

Try to determine why it's failing and make it pass.

**Comment by MaximLipnin** [comment]
Actually, this assert fails:
```
Assert.Equal(0, errObj.LastDllError);
```

**Comment by MaximLipnin** [comment]
Stephen [commented](https://github.com/dotnet/corefx/issues/37341#issuecomment-488434007) on the similar issue:

> It looks like this ends up using a shared ErrObject, and with tests running concurrently, there are race conditions. We should either a) mark the test project as requiring sequential test execution, b) use RemoteInvoke.Execute to run the code in a separate process, and/or c) change the test to not use a shared object (though I imagine that's part of what the test is testing).

The fix in there was to run Microsoft.VisualBasic.Core.Tests sequentially. Since we consume the tests from netcore feed netcore-mono should already use that fix.

**Comment by MaximLipnin** [comment]
```
ReadOnly Property LastDllError() As Integer
    Get
        Return Marshal.GetLastWin32Error()
    End Get
End Property
```
Is it supposed to work on non-Windows platforms?

**Comment by filipnavara** [comment]
> Is it supposed to work on non-Windows platforms?

Yes, it is. There's `Marshal.SetLastWin32Error` and `errno` in P/Invoke. I believe I implemented the first one few months ago but there was probably some other issue breaking this test.

**Comment by MaximLipnin** [comment]
Just for record - the test passes with the default build on the latest master of 'dotnet/runtime'.
