### ISSUE TITLE
[netcore]Make Microsoft.VisualBasic.ApplicationServices.Tests.AssemblyInfoTests.LoadedAssemblies pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14855]
The current test fails with:

```
   Microsoft.VisualBasic.ApplicationServices.Tests.AssemblyInfoTests.LoadedAssemblies [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at Microsoft.VisualBasic.ApplicationServices.AssemblyInfo.get_LoadedAssemblies()
           at Microsoft.VisualBasic.ApplicationServices.Tests.AssemblyInfoTests.LoadedAssemblies()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
  Finished:    Microsoft.VisualBasic.Core.Tests
```

Determine why this is failing and try to make it pass.

**Comment by filipnavara** [comment]
Missing implementation in `AssemblyLoadContext`:

https://github.com/mono/mono/blob/a5a26a2f92d00ab174d794f077007faaab5d3843/mcs/class/System.Private.CoreLib/System.Runtime.Loader/AssemblyLoadContext.cs#L39-L42
