### ISSUE TITLE
[netcore]Make System.Collections.Specialized.Tests.NameValueCollectionCtorTests.Ctor_NegativeCapacity_ThrowsArgumentOutOfRangeException Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14858]
The current test fails with:

```
System.Collections.Specialized.Tests.NameValueCollectionCtorTests.Ctor_NegativeCapacity_ThrowsArgumentOutOfRangeException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.OutOfMemoryException)
      Actual:   typeof(System.ArgumentException): Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
      Parameter name: capacity
      ---- System.ArgumentException : Hashtable's capacity overflowed and went negative. Check load factor, capacity and the current size of the table.
      Parameter name: capacity
      Stack Trace:
           at System.Collections.Hashtable..ctor(Int32 capacity, Single loadFactor)
           at System.Collections.Hashtable..ctor(Int32 capacity, Single loadFactor, IEqualityComparer equalityComparer)
           at System.Collections.Hashtable..ctor(Int32 capacity, IEqualityComparer equalityComparer)
           at System.Collections.Specialized.NameObjectCollectionBase.Reset(Int32 capacity)
           at System.Collections.Specialized.NameObjectCollectionBase..ctor(Int32 capacity)
           at System.Collections.Specialized.NameValueCollection..ctor(Int32 capacity)
           at System.Collections.Specialized.Tests.NameValueCollectionCtorTests.<>c.<Ctor_NegativeCapacity_ThrowsArgumentOutOfRangeException>b__4_3()
        ----- Inner Stack Trace -----
           at System.Collections.Hashtable..ctor(Int32 capacity, Single loadFactor)
           at System.Collections.Hashtable..ctor(Int32 capacity, Single loadFactor, IEqualityComparer equalityComparer)
           at System.Collections.Hashtable..ctor(Int32 capacity, IEqualityComparer equalityComparer)
           at System.Collections.Specialized.NameObjectCollectionBase.Reset(Int32 capacity)
           at System.Collections.Specialized.NameObjectCollectionBase..ctor(Int32 capacity)
           at System.Collections.Specialized.NameValueCollection..ctor(Int32 capacity)
           at System.Collections.Specialized.Tests.NameValueCollectionCtorTests.<>c.<Ctor_NegativeCapacity_ThrowsArgumentOutOfRangeException>b__4_3()
  Finished:    System.Collections.Specialized.Tests
```
Determine why the test fails and pass it.

**Comment by EgorBo** [comment]
@steveisok there should be a lot of similar issues because mono supports large arrays unlike coreclr.
This one should be fixed but other should be ignored in CoreFX (using sort of IsLargeArraySupported)
