### ISSUE TITLE
[netcore] Stack Traces Seem Too Short

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14868]
## Steps to Reproduce

1. Build monovm (cd netcore && ./build.sh) 
2. In netcore/CoreFX.issues.rsp, change from -nomethod to -method for Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_*
3. Type make xtest-System.Collections.Tests

### Current Behavior
Notice the stack traces in the failures seem a little light.  @filipnavara thinks we may be missing around 3 calls from the bottom of the stack.  Case in point:

``` Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ValueTypeKey(comparerType: null) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.<DictionaryConcurrentAccessDetection>d__0`2[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
           at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ValueTypeKey(Type comparerType)
```

### Expected Behavior
The full stack trace should be available

## On which platforms did you notice this

[X] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Master

**Comment by lewurm** [comment]
Could be that inlining swallows frames.  Could you verify by running without inlining? It's `-O=-inline`.

**Comment by filipnavara** [comment]
> Could be that inlining swallows frames. Could you verify by running without inlining? It's `-O=-inline`.

That's not it. It is consistent and playing with the `skipFrames` constants in `StackTrace`/`StackFrame` classes makes it go away.

**Comment by steveisok** [comment]
Yeah, that out to double check and it makes no difference.

**Comment by filipnavara** [comment]
Actually, at least in one instance disabling the inlining helped. With `MONO_ENV_OPTIONS="-O=-inline" make xtest-Microsoft.VisualBasic.Core.Tests` I am now getting the full trace here:

```
    Microsoft.VisualBasic.ApplicationServices.Tests.AssemblyInfoTests.LoadedAssemblies [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at System.Runtime.Loader.AssemblyLoadContext.GetLoadedAssemblies()
           at System.AppDomain.GetAssemblies()
           at Microsoft.VisualBasic.ApplicationServices.AssemblyInfo.get_LoadedAssemblies()
           at Microsoft.VisualBasic.ApplicationServices.Tests.AssemblyInfoTests.LoadedAssemblies()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

I would like some independent verification, preferably on different test.

**Comment by steveisok** [comment]
I ran it against one of the collections tests and it didn’t make a difference.  I’ll try your example and others to see if I can spot anything.

**Comment by steveisok** [comment]
I tried a few more and disabling inline does help.  

This test by default shows:

```
System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
           at System.Reflection.Assembly.Load(Byte[] rawAssembly)
           at System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

But with inlining off, it'll show:

```
System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes [FAIL]
      System.NotImplementedException : The method or operation is not implemented.
      Stack Trace:
           at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(Byte[] arrAssembly, Byte[] arrSymbols)
           at System.Reflection.Assembly.Load(Byte[] rawAssembly, Byte[] rawSymbolStore)
           at System.Reflection.Assembly.Load(Byte[] rawAssembly)
           at System.Reflection.Tests.AssemblyTests.AssemblyLoadFromBytes()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by lewurm** [comment]
running `make xtest-System.Collections.Tests`:
```
=== TEST EXECUTION SUMMARY ===
   System.Collections.Tests  Total: 4, Errors: 0, Failed: 4, Skipped: 0, Time: 0.413s
```
running `MONO_ENV_OPTIONS="-O=-inline" make xtest-System.Collections.Tests`:
```
=== TEST EXECUTION SUMMARY ===
   System.Collections.Tests  Total: 4, Errors: 0, Failed: 0, Skipped: 0, Time: 0.221s
```
not sure why you guys see something else. Note that I'm not using the `netcore/build.sh` script; do you mind trying `MONO_ENV_OPTIONS="-O=-inline,-aot"`?   It disables inlining _and_ using AOT'd code. If the latter was generated with inlining enabled, then you would still get truncated stack traces...
