### ISSUE TITLE
[netcore] Make System.Linq.Expressions.Tests.BindTests.ConstantField Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14918]
The test currently fails with:

```
System.Linq.Expressions.Tests.BindTests.ConstantField(useInterpreter: False) [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.NotSupportedException)
      Actual:   typeof(System.MissingFieldException): Field not found: .PropertyAndFields.ConstantString Due to: Using static instructions with literal field
      ---- System.MissingFieldException : Field not found: .PropertyAndFields.ConstantString Due to: Using static instructions with literal field
      Stack Trace:
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
           at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
           at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
           at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
           at System.Linq.Expressions.Expression`1[[System.Func`1[[System.Linq.Expressions.Tests.BindTests.PropertyAndFields, System.Linq.Expressions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Compile(Boolean preferInterpretation)
           at System.Linq.Expressions.Tests.BindTests.<>c__DisplayClass15_0.<ConstantField>b__0()
        ----- Inner Stack Trace -----
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure, Boolean allowClosed)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method, Boolean throwOnBindFailure)
           at System.Delegate.CreateDelegate(Type type, Object firstArgument, MethodInfo method)
           at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
           at System.Linq.Expressions.Compiler.LambdaCompiler.CreateDelegate()
           at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
           at System.Linq.Expressions.Expression`1[[System.Func`1[[System.Linq.Expressions.Tests.BindTests.PropertyAndFields, System.Linq.Expressions.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Compile(Boolean preferInterpretation)
           at System.Linq.Expressions.Tests.BindTests.<>c__DisplayClass15_0.<ConstantField>b__0()
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
According to the stack trace it fails in [`Delegate.CreateDelegate_internal`](https://github.com/mono/mono/blob/master/netcore/System.Private.CoreLib/src/System/Delegate.cs#L141)  method.

If found only one place where `"Using static instructions with literal field"` message gets set: https://github.com/mono/mono/blob/master/mono/mini/method-to-ir.c#L9222

**Comment by MaximLipnin** [comment]
Repro:
```
using System;
using System.Reflection;
using System.Linq.Expressions;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            MemberInfo member = typeof(PropertyAndFields).GetMember(nameof(PropertyAndFields.ConstantString))[0];
            Expression<Func<PropertyAndFields>> attemptAssignToConstant = Expression.Lambda<Func<PropertyAndFields>>(
                Expression.MemberInit(
                    Expression.New(typeof(PropertyAndFields)),
                    Expression.Bind(member, Expression.Constant(""))
                    )
                );
            var useInterpreter = false;
            attemptAssignToConstant.Compile(useInterpreter);
        }

        private class PropertyAndFields
        {
#pragma warning disable 649 // Assigned through expressions.
            public const string ConstantString = "Constant";
#pragma warning restore 649
        }
    }
}
```

**Comment by MaximLipnin** [comment]
This is from usual netcore run where `NotSupportedException` is thrown:
```
  at System.Reflection.MdFieldInfo.get_FieldHandle()
   at System.Reflection.Emit.DynamicILGenerator.GetTokenFor(RuntimeFieldInfo runtimeField, RuntimeType rtType)
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, FieldInfo field)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberAssignment(MemberAssignment binding, Type objectType)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitBinding(MemberBinding binding, Type objectType)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(ReadOnlyCollection`1 bindings, Boolean keepOnStack, Type objectType)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitMemberInit(MemberInitExpression init)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitExpression(Expression node, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody()
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at HelloWorld.Program.Main(String[] args)
```

**Comment by lambdageek** [comment]
Looks like one for @SamMonoRT and company

**Comment by naricc** [comment]
I don't think we use this test in dotnet/runtime and I don't think we are going to fix it in mono/mono?
