### ISSUE TITLE
[netcore] Make System.Linq.Expressions.Tests.BindTests.GlobalField Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14917]
The test currently fails with:

```
    System.Linq.Expressions.Tests.BindTests.GlobalField [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.AssertExtensions.Throws[ArgumentException](String paramName, Func`1 testCode)
           at System.Linq.Expressions.Tests.BindTests.GlobalField()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
```
using System;
using System.Reflection;
using System.Reflection.Emit;
using System.Linq.Expressions;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            ModuleBuilder module = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Name"), AssemblyBuilderAccess.RunAndCollect).DefineDynamicModule("Module");
            FieldBuilder fieldBuilder = module.DefineInitializedData("GlobalField", new byte[4], FieldAttributes.Public);
            module.CreateGlobalFunctions();
            FieldInfo globalField = module.GetField(fieldBuilder.Name);
            //Console.WriteLine($"globalField.DeclaringType is null = {globalField.DeclaringType == null}");
            // ArgumentException expected
            Expression.Bind(globalField, Expression.Default(globalField.FieldType)); 
        }
    }
}
```
Seems that `globalField.DeclaringType` should be `null` but it's `Module`.

**Comment by MaximLipnin** [comment]
https://github.com/dotnet/corefx/pull/15318

**Comment by MaximLipnin** [comment]
Does it make sense to fix it here?
```
--- a/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeFieldInfo.cs
+++ b/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeFieldInfo.cs
@@ -168,7 +168,8 @@ namespace System.Reflection
                }
                public override Type DeclaringType {
                        get {
-                               return GetParentType (true);
+                               Type parentType = GetParentType (true);
+                               return parentType.Name == "<Module>" ? null : parentType;
                        }
                }
                public override string Name {
```
