### ISSUE TITLE
[netcore] Make System.Linq.Expressions.Tests.ExceptionHandlingExpressions.ExceptionThrownInFilter Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#14924]
The test currently fails with:

```
System.Linq.Expressions.Tests.ExceptionHandlingExpressions.ExceptionThrownInFilter(useInterpreter: False) [FAIL]
      System.InvalidOperationException : Operation is not valid due to the current state of the object.
      Stack Trace:
           at System.Linq.Expressions.Tests.ExceptionHandlingExpressions.ExceptionThrownInFilter(Boolean useInterpreter)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
Extracted from the test:
```
using System;
using System.Linq.Expressions;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            var useInterpreter = false;
            TryExpression tryExp = Expression.TryCatch(
                Expression.Throw(Expression.Constant(new TestException()), typeof(int)),
                Expression.Catch(
                    typeof(TestException),
                    Expression.Constant(2),
                    Expression.LessThan(
                        Expression.Constant(3),
                        Expression.Throw(Expression.Constant(new InvalidOperationException()), typeof(int))
                        )
                    ),
                Expression.Catch(typeof(TestException), Expression.Constant(9))
                );
            Func<int> func = Expression.Lambda<Func<int>>(tryExp).Compile(useInterpreter);
            Console.WriteLine(9 == func());
        }

        protected class TestException : Exception
        {
            public TestException()
                : base("This is a test exception")
            {
            }
        }
    }
}
```

**Comment by MaximLipnin** [comment]
The similar sample w/o expressions:

```
using System;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            var z = 0;
            try {
                throw new TestException();
            }
            catch(TestException) when (3 < Throw())
            {
                z = 2;
            }
            catch(TestException) 
            {
                z = 9;
            }

            Console.WriteLine(z == 9);
        }

        static int Throw () {
            throw new InvalidOperationException();
        }

        protected class TestException : Exception
        {
            public TestException()
                : base("This is a test exception")
            {
            }
        }
    }
}
```
From the [test](https://github.com/dotnet/corefx/blob/master/src/System.Linq.Expressions/tests/ExceptionHandling/ExceptionHandlingExpressions.cs#L936 ):

> An exception in a filter should be eaten and the filter fail.
