### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15028]
The test currently fails with:

```
System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: 
      Actual:   enumType
                ↑ (pos 0)
      Stack Trace:
           at System.AssertExtensions.Throws[ArgumentException](String paramName, Func`1 testCode)
           at System.Reflection.Tests.TypeInfoTests.IsEnumDefined_Invalid()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by svick** [comment]
A very closely related issue: https://github.com/dotnet/runtime/issues/27491.
