### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyNameTests.FullName Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15073]
The test currently fails with: 

```
System.Reflection.Tests.AssemblyNameTests.FullName(name: "name", expectedName: "name") [FAIL]
      Expected
      name, publickeytoken=null == name
      or
      name, publickeytoken=null == name, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.FullName(name: "NAME", expectedName: "NAME") [FAIL]
      Expected
      name, publickeytoken=null == name
      or
      name, publickeytoken=null == name, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.FullName(name: "name with spaces", expectedName: "name with spaces") [FAIL]
      Expected
      name with spaces, publickeytoken=null == name with spaces
      or
      name with spaces, publickeytoken=null == name with spaces, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.FullName(name: "𐀀", expectedName: "𐀀") [FAIL]
      Expected
      𐀀, publickeytoken=null == 𐀀
      or
      𐀀, publickeytoken=null == 𐀀, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.FullName(name: "привет", expectedName: "привет") [FAIL]
      Expected
      привет, publickeytoken=null == привет
      or
      привет, publickeytoken=null == привет, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.AssemblyNameTests.FullName(name: "🐻🐻🐻🐻🐻", expectedName: "🐻🐻🐻🐻🐻") [FAIL]
      Expected
      🐻🐻🐻🐻🐻, publickeytoken=null == 🐻🐻🐻🐻🐻
      or
      🐻🐻🐻🐻🐻, publickeytoken=null == 🐻🐻🐻🐻🐻, culture=neutral, publickeytoken=null
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.AssemblyNameTests.FullName(String name, String expectedName)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by CoffeeFlux** [comment]
For some reason, we're failing to list the culture. Shouldn't require ALCs, seems like a simple formatting issue. Worth noting that this only happens with NETCORE because otherwise it just returns the simple `name`, which matches `expectedName` exactly.

**Comment by CoffeeFlux** [comment]
The test is a little weird since it offers two possible behaviors, but it seems .NET Core 3 just returns the name itself rather than defaulting on the culture and publickeytoken, so I'll just imitate that behavior. I think I can fix `System.Reflection.Tests.AssemblyNameTests.SetPublicKeyToken_GetPublicKeyToken` along with this.

**Comment by marek-safar** [comment]
@CoffeeFlux please improve the test in corefx repo
