### ISSUE TITLE
[netcore] Make System.Reflection.Tests.GetTypeTests.GetType Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15077]
The test throws a NRE:

```
System.Reflection.Tests.GetTypeTests.GetType(typeName: "SYSTEM.REFLECTION.TESTS.MYNAMESPACE1.MYNAMESPACE3."..., expectedResult: typeof(System.Reflection.Tests.MyNamespace1.MynAmespace3.Goo<int>)) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.Reflection.Tests.GetTypeTests.GetType(String typeName, Type expectedResult)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make it pass.

**Comment by CoffeeFlux** [comment]
Relevant issue: https://github.com/mono/mono/issues/11269

**Comment by CoffeeFlux** [comment]
I'm actually unable to reproduce this locally, similar to what was mentioned in the issue. Needs further investigation.

**Comment by filipnavara** [comment]
I can reproduce it. File line for reference:
```
    System.Reflection.Tests.GetTypeTests.GetType(typeName: "SYSTEM.REFLECTION.TESTS.MYNAMESPACE1.MYNAMESPACE3."..., expectedResult: typeof(System.Reflection.Tests.MyNamespace1.MynAmespace3.Goo<int>)) [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /_/src/System.Reflection/tests/GetTypeTests.cs(217,0): at System.Reflection.Tests.GetTypeTests.GetType(String typeName, Type expectedResult)
        /Users/filipnavara/Documents/GitHub/mono/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeMethodInfo.cs(343,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by CoffeeFlux** [comment]
I'll try again later today then, maybe I had a weird config last time.

**Comment by CoffeeFlux** [comment]
Able to repro now, not sure what I did wrong last time.

**Comment by CoffeeFlux** [comment]
This bug is kind of funny - the reason for the failure is that with a lowercase 'p', the PublicKeyToken isn't set correctly, and what seems to be another bug related to its lookup is avoided. See: https://github.com/mono/mono/blob/8fe4109eadc3213a7cdc23ffe02fc25f17531e2a/mono/metadata/reflection.c#L1552
Working on fixing the root issue.
