### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyNetCoreAppTests.AssemblyGetForwardedTypesLoadFailure Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15078]
The test currently fails with:

```
System.Reflection.Tests.AssemblyNetCoreAppTests.AssemblyGetForwardedTypesLoadFailure [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Reflection.ReflectionTypeLoadException)
      Actual:   typeof(System.TypeLoadException): Could not load type '' from assembly ''.
      ---- System.TypeLoadException : Could not load type '' from assembly ''.
      Stack Trace:
           at System.Reflection.Tests.AssemblyNetCoreAppTests.<>c__DisplayClass1_0.<AssemblyGetForwardedTypesLoadFailure>b__0()
        ----- Inner Stack Trace -----
           at System.Reflection.Tests.AssemblyNetCoreAppTests.<>c__DisplayClass1_0.<AssemblyGetForwardedTypesLoadFailure>b__0()
```

Determine why and make it pass.

**Comment by CoffeeFlux** [comment]
See https://github.com/mono/mono/blob/377030eaab594540d7e043f8657a30bbe92e6c33/mono/metadata/icall.c#L6061-L6063
