### ISSUE TITLE
[netcore] Make System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15081]
The test currently fails with:

```
System.Resources.Tests.ResourceManagerTests.GetString_ExpectEvents [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 2
        Actual:   0
           at System.Resources.Tests.ResourceManagerTests.Remote_ExpectEvents()
           at System.Resources.Tests.ResourceManagerTests.<>c.<GetString_ExpectEvents>b__10_0()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          System.Resources.ResourceManager.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Resources.Tests.ResourceManagerTests+<>c Void <GetString_ExpectEvents>b__10_0()
```

The thought is that netcore is missing assembly resolve events on AppDomain and AssemblyLoadContext.  Determine if that's the case and make the test pass.

**Comment by CoffeeFlux** [comment]
This appears to be an issue with satellite resolution - the test wires up two functions on the events and checks whether they were fired by incrementing a counter. The problem is that for some reason, the aname being passed to `netcore_load_reference` does not include a non-neutral culture - somewhere along the way, the 'af-ZA' is being dropped.
