### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeInfoTests.IsAssignableFrom Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15080]
The test currently fails with:

```
System.Reflection.Tests.TypeInfoTests.IsAssignableFrom(type: typeof(System.Reflection.Tests.TI_NonGenericInterface1[]), c: typeof(System.Reflection.Tests.TypeInfoTests+NonGenericStructWithNonGenericInterface[]), expected: False) [FAIL]
      Assert.Equal() Failure
      Expected: False
      Actual:   True
      Stack Trace:
           at System.Reflection.Tests.TypeInfoTests.IsAssignableFrom(Type type, Type c, Boolean expected)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by CoffeeFlux** [comment]
Appears to be the result of https://github.com/mono/mono/issues/10848
