### ISSUE TITLE
[netcore] Make System.Runtime.InteropServices.Tests.OffsetOfTests.OffsetOf_Decimal_ReturnsExpected Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15092]
The test currently fails with:

```
System.Runtime.InteropServices.Tests.OffsetOfTests.OffsetOf_Decimal_ReturnsExpected [FAIL]
      Assert.Equal() Failure
      Expected: 96
      Actual:   88
      Stack Trace:
           at System.Runtime.InteropServices.Tests.OffsetOfTests.OffsetOf_Decimal_ReturnsExpected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Figure out why the offsets are different and make it pass.[

**Comment by EgorBo** [comment]
Repro:
```csharp
using System;
using System.Runtime.InteropServices;

class Program
{
    static void Main(string[] args)
    {
        Console.WriteLine(Marshal.SizeOf<WithDecimal>());   // prints: 24 (on Mono: 20)
        Console.WriteLine(Marshal.SizeOf<WithMyDecimal>()); // prints: 20 (on Mono: 20)
    }
}

[StructLayout(LayoutKind.Sequential)]
public struct WithDecimal
{
    public decimal d; // 16 byte = 4 int * 4
    public byte b;    // 1 byte
}

[StructLayout(LayoutKind.Sequential)]
public struct WithMyDecimal
{
    public MyDecimal d; // 16 byte = 4 int * 4
    public byte b;      // 1 byte
}

[StructLayout(LayoutKind.Sequential)]
public struct MyDecimal
{
    public int a;
    public int b;
    public int c;
    public int d;
}
```
When there is a decimal field in a struct, the alignment on x64 should be 8 bytes.
