### ISSUE TITLE
[netcore] Make System.Numerics.Tests.ComplexTests.Sin_Advanced Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15106]
The test currently fails with:

```
System.Numerics.Tests.ComplexTests.Sin_Advanced(real: 1.7976931348623157E+308, imaginary: 0, expectedReal: 0.004961954789184061, expectedImaginary: 0) [FAIL]
      Failure at line 1380. Expected real: 0.004961954789184061. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Sin_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Numerics.Tests.ComplexTests.Sin_Advanced(real: -1.7976931348623157E+308, imaginary: 0, expectedReal: -0.004961954789184061, expectedImaginary: 0) [FAIL]
      Failure at line 1380. Expected real: -0.004961954789184061. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Sin_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Numerics.Tests.ComplexTests.Sin_Advanced(real: 1.7976931348623157E+308, imaginary: 1.7976931348623157E+308, expectedReal: ∞, expectedImaginary: -∞) [FAIL]
      Failure at line 1380. Expected imaginary: -∞. Actual imaginary: ∞
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Sin_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by EgorBo** [comment]
I suspect all `System.Numerics.Tests.ComplexTests.` need fixes for Math/MathF internal calls (see HAVE_COMPATIBLE_xxx) - corner cases
