### ISSUE TITLE
[netcore] Make System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValBoolArray_Success Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15102]
The test currently fails with:

```
System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValBoolArray_Success [FAIL]
      Assert.Equal() Failure
      Expected: 255
      Actual:   1
      Stack Trace:
           at System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValBoolArray_Success()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by EgorBo** [comment]
hmm.. is this struct blittable or not?
```public struct StructWithBoolArray
{
    [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
    public bool[] array;
}```
?
if it could go to the "blittable" path in emit_struct_to_ptr_ilgen...
