### ISSUE TITLE
[netcore] Make System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValDateArray_Success Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15103]
The test currently fails with: 

```
System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValDateArray_Success [FAIL]
      System.Runtime.InteropServices.MarshalDirectiveException : Type System.DateTime which is passed to unmanaged code must have a StructLayout attribute.
      Stack Trace:
           at System.Runtime.InteropServices.Marshal.StructureToPtr[StructWithDateArray](StructWithDateArray structure, IntPtr ptr, Boolean fDeleteOld)
           at System.Runtime.InteropServices.Tests.StructureToPtrTests.StructureToPtr_ByValDateArray_Success()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by EgorBo** [comment]
Actually duplicates https://github.com/mono/mono/issues/15102 - the code doesn't properly handle ByValArray + Size for non-blittable structs
