### ISSUE TITLE
[netcore] Make System.Numerics.Tests.ComplexTests.Cosh_Advanced Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15109]
The test currently fails with:

```
System.Numerics.Tests.ComplexTests.Cosh_Advanced(real: 0, imaginary: 1.7976931348623157E+308, expectedReal: -0.9999876894265599, expectedImaginary: 0) [FAIL]
      Failure at line 670. Expected real: -0.9999876894265599. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Cosh_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Numerics.Tests.ComplexTests.Cosh_Advanced(real: 0, imaginary: -1.7976931348623157E+308, expectedReal: -0.9999876894265599, expectedImaginary: 0) [FAIL]
      Failure at line 670. Expected real: -0.9999876894265599. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Cosh_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Numerics.Tests.ComplexTests.Cosh_Advanced(real: -1.7976931348623157E+308, imaginary: -1.7976931348623157E+308, expectedReal: -∞, expectedImaginary: ∞) [FAIL]
      Failure at line 670. Expected real: -∞. Actual real: ∞
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
           at System.Numerics.Tests.ComplexTests.Cosh_Advanced(Double real, Double imaginary, Double expectedReal, Double expectedImaginary)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
The example extracted from the test:
```
using System;
using System.Numerics;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            var c = new Complex(double.MaxValue, double.MinValue);
            Console.WriteLine($"c.Real = {c.Real}");
            Console.WriteLine($"cos = {Math.Cos(c.Real)}");
            Console.WriteLine($"cos of double.MaxValue = {Math.Cos(double.MaxValue)}");
            Console.WriteLine($"sin = {Math.Sin(c.Real)}");
            Console.WriteLine($"sin of double.MaxValue = {Math.Sin(double.MaxValue)}");
        }
    }
}
```
The netcore-mono's output:
```
c.Real = 1.7976931348623157E+308
cos = 1.7976931348623157E+308
cos of double.MaxValue = -0.9999876894265599
sin = 1.7976931348623157E+308
sin of double.MaxValue = 0.004961954789184061
```
The regular netcore's output:
```
c.Real = 1.79769313486232E+308
cos = -0.99998768942656
cos of double.MaxValue = -0.99998768942656
sin = 0.00496195478918406
sin of double.MaxValue = 0.00496195478918406
```

**Comment by MaximLipnin** [comment]
The simpler repro - just assigning `double.MaxValue` to a variable and calculating `cos` of it produces incorrect result:
```
using System;
using System.Numerics;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            double d = double.MaxValue;
            Console.WriteLine($"d = {d}");
            Console.WriteLine($"double.MaxValue= {double.MaxValue}");
            Console.WriteLine($"cos = {Math.Cos(d)}");
            Console.WriteLine($"cos of double.MaxValue = {Math.Cos(double.MaxValue)}");
        }
    }
}
```
The output is:
```
d = 1.7976931348623157E+308
double.MaxValue= 1.7976931348623157E+308
cos = 1.7976931348623157E+308
cos of double.MaxValue = -0.9999876894265599
```

**Comment by MaximLipnin** [comment]
For values more or equal to `long.MaxValue` (or less or equal to `long.MinValue`) `Math.Cos` returns the same value as it takes in.
```
using System;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            double d = long.MaxValue; // 9 223 372 036 854 775 807
            Console.WriteLine(Math.Cos(d)); // returns the same value as it takes in
            
            d = 9223372036854774807; // it's in range of long
            Console.WriteLine(Math.Cos(d)); // returns calculated cosine
        }
    }
}
```
The output:
```
9.223372036854776E+18
-0.1586063985336008
```

**Comment by MaximLipnin** [comment]
Since `Math.Cos(double.MaxValue`) invokes https://github.com/mono/mono/blob/master/mono/mini/intrinsics.c#L1556 the value is calculated.

The code
```
double d = double.MaxValue;
Math.Cos(d);
```
invokes https://github.com/mono/mono/blob/master/mono/mini/intrinsics.c#L1699 but I have no idea where the result gets calculated then and why it's not correct for arguments that are more than or equal to `long.MaxValue` (see previous comment)

**Comment by vargaz** [comment]
Its emitted by mono_arch_emit_inst_for_method () in mini-amd64.c, and implemented by:
		case OP_COS:
			EMIT_SSE2_FPFUNC (code, fcos, ins->dreg, ins->sreg1);
			break;

**Comment by MaximLipnin** [comment]
@vargaz thank you

From https://www.felixcloutier.com/x86/fcos:
>The source operand must be given in radians and must be within the range −2^63 to +2^63.

> If the source operand is outside the acceptable range, the C2 flag in the FPU status word is set, and the value in register ST(0) remains unchanged. The instruction does not raise an exception when the source operand is out of range. It is up to the program to check the C2 flag for out-of-range conditions. Source values outside the range − 2^63 to +2^63 can be reduced to the range of the instruction by subtracting an appropriate integer multiple of 2π.

**Comment by MaximLipnin** [comment]
Some interesting comments: [1](https://github.com/mono/mono/pull/9281), [2](https://github.com/dotnet/coreclr/issues/12737#issuecomment-314801620)

**Comment by MaximLipnin** [comment]
IIUC the following options could be here:
1. check if the value of `fcos` argument is out of the range `− 2^63; +2^63` and reduce it to the range of the instruction
2. somehow avoid using FPU `fcos` intrinsic in favor of C' `cos`  implementation.

**Comment by vargaz** [comment]
Another option is checking what code the C cos implementation contains.

**Comment by MaximLipnin** [comment]
@vargaz Some code in mono/mini/intrinsics.c that already uses C' `cos` (like below)
```
case OP_COS:
    result = cos (source);
    break;
```
refers to something in XCode toolchain `math.h` file on macOS. 
```
// cos

#if !(defined(_AIX) || defined(__sun__))
inline _LIBCPP_INLINE_VISIBILITY float       cos(float __lcpp_x) _NOEXCEPT       {return ::cosf(__lcpp_x);}
inline _LIBCPP_INLINE_VISIBILITY long double cos(long double __lcpp_x) _NOEXCEPT {return ::cosl(__lcpp_x);}
#endif

template <class _A1>
inline _LIBCPP_INLINE_VISIBILITY
typename std::enable_if<std::is_integral<_A1>::value, double>::type
cos(_A1 __lcpp_x) _NOEXCEPT {return ::cos((double)__lcpp_x);}
```

How can it be useful here?

What is a good option to proceed?

**Comment by MaximLipnin** [comment]
I need someone with runtime superpowers to help here.
