### ISSUE TITLE
[netcore] Make System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15115]
The test currently fails with:

```
System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateAgainstBlobs [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.PopulateException[Exception](Exception exception, Boolean setHResult)
           at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects()+MoveNext()
           at System.Collections.Generic.LargeArrayBuilder`1[[System.Object[], System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].AddRange(IEnumerable`1 items)
           at System.Collections.Generic.EnumerableHelpers.ToArray[Object[]](IEnumerable`1 source)
           at System.Linq.Enumerable.ToArray[Object[]](IEnumerable`1 source)
           at System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializableObjects_MemberData()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by filipnavara** [comment]
Technically the tests depend on setting the internals of the Exception object through reflection (https://raw.githubusercontent.com/dotnet/corefx/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Runtime.Serialization.Formatters/tests/BinaryFormatterTestData.cs):

```csharp
        private static T PopulateException<T>(T exception, bool setHResult = true)
            where T : Exception
        {
            exception.HelpLink = "http://msdn.microsoft.com";
            exception.Source = "Exception_Class_Samples";

            exception.Data.Add("secret", true);
            exception.Data.Add(1, "one");

            typeof(Exception)
                .GetField("_stackTraceString", BindingFlags.Instance | BindingFlags.NonPublic)
                .SetValue(exception, "StackTrace string...");
            if (setHResult)
            {
                typeof(Exception)
                    .GetField("_HResult", BindingFlags.Instance | BindingFlags.NonPublic)
                    .SetValue(exception, 1000);
            }
            typeof(Exception)
                .GetField("_remoteStackTraceString", BindingFlags.Instance | BindingFlags.NonPublic)
                .SetValue(exception, "Remote StackTrace string...");

            return exception;
        }
```

This is fragile and breaks because Mono uses different internal object layout and field names. Not sure whether we should fix this on Mono side. Opinions?

**Comment by marek-safar** [comment]
This should be fixed in the test to be more robust. For example GetField("_HResult") is not needed if there is already public HResult property setter.

Similarly, there are SerializationStackTraceString and SerializationRemoteStackTraceString which could be extended to support shared private setting.

**Comment by CoffeeFlux** [comment]
It appears that `System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.ValidateBasicObjectsRoundtrip` and `System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.RoundtripManyObjectsInOneStream` are passing in master, at least. Unsure of when that changed or if we should re-enable them.

**Comment by akoeplinger** [comment]
These work now in dotnet/runtime.
