### ISSUE TITLE
[netcore] Make System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15157]
The test fails and the process hangs with:

```
Unhandled Exception:
System.Threading.WaitHandleCannotBeOpenedException: No handle of the given name exists.
   at System.Threading.Mutex.OpenExisting(String name)
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(String m, String f)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.Threading.WaitHandleCannotBeOpenedException: No handle of the given name exists.
   at System.Threading.Mutex.OpenExisting(String name)
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(String m, String f)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args)
    System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(prefix: "08a81f11b9494fff83ce839b0f2e38bc") [FAIL]
      System.AggregateException : One or more errors occurred. (Remote process failed with an unhandled exception.)
      ---- Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
           at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__1()
           at System.Threading.Tests.ThreadTestHelpers.<>c__DisplayClass4_0.<CreateGuardedThread>b__2()
           at System.Threading.Tests.ThreadTestHelpers.RunTestInBackgroundThread(Action test)
           at System.Threading.Tests.MutexTests.CrossProcess_NamedMutex_ProtectedFileAccessAtomic(String prefix)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        ----- Inner Stack Trace -----
        
        Child exception:
          System.Threading.WaitHandleCannotBeOpenedException: No handle of the given name exists.
           at System.Threading.Mutex.OpenExisting(String name)
           at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(String m, String f)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          System.Threading.Tests, Version=4.1.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Threading.Tests.MutexTests+<>c Int32 <CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(System.String, System.String)
        
        Child arguments:
          08a81f11b9494fff83ce839b0f2e38bc793f9dfa31d14048be50968946ac94f8, /var/folders/mv/2lx3zn1n1zlb8vvhvk5pvdsh0000gn/T/MutexTests_u0cptqvl.fbl/CrossProcess_NamedMutex_ProtectedFileAccessAtomic_227_81061c30
        

Unhandled Exception:
System.Threading.WaitHandleCannotBeOpenedException: No handle of the given name exists.
   at System.Threading.Mutex.OpenExisting(String name)
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(String m, String f)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: System.Threading.WaitHandleCannotBeOpenedException: No handle of the given name exists.
   at System.Threading.Mutex.OpenExisting(String name)
   at System.Threading.Tests.MutexTests.<>c.<CrossProcess_NamedMutex_ProtectedFileAccessAtomic>b__14_1(String m, String f)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args)
```

Find out why the process hangs / test fails and make it pass.

**Comment by MaximLipnin** [comment]
Related CoreFX issue: https://github.com/dotnet/corefx/issues/34666

**Comment by MaximLipnin** [comment]
During doing the work https://github.com/dotnet/runtime/pull/2087, it found out that the mentioned test is already annotated with more general CoreFX active issue. So I'm closing the current issue.
