### ISSUE TITLE
[netcore] Make System.Threading.Tests.SemaphoreTests.OpenExisting_NotSupported_Unix Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15160]
The test currently fails with:

```
System.Threading.Tests.SemaphoreTests.OpenExisting_NotSupported_Unix [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.PlatformNotSupportedException)
      Actual:   typeof(System.ArgumentNullException): Value cannot be null.
      Parameter name: name
      ---- System.ArgumentNullException : Value cannot be null.
      Parameter name: name
      Stack Trace:
           at System.Threading.Semaphore.OpenExistingWorker(String name, Semaphore& result)
           at System.Threading.Semaphore.OpenExisting(String name)
           at System.Threading.Tests.SemaphoreTests.<>c.<OpenExisting_NotSupported_Unix>b__10_0()
        ----- Inner Stack Trace -----
           at System.Threading.Semaphore.OpenExistingWorker(String name, Semaphore& result)
           at System.Threading.Semaphore.OpenExisting(String name)
           at System.Threading.Tests.SemaphoreTests.<>c.<OpenExisting_NotSupported_Unix>b__10_0()
```

Determine why and make the test pass.

**Comment by mickeyjf** [comment]
This, and #15158 sound related to the issue I mistakenly posted in MonoDevelop rather than here: 

https://github.com/mono/monodevelop/issues/7914

Not clear to me if these things simply are not, and will likely never be implemented, or if I'm just missing something. Also don't know if there is a simple way to transfer my comments to here where they are more likely to get an authoritative response.
