### ISSUE TITLE
[netcore] Make System.Composition.Hosting.Tests.ContainerConfigurationTests.WithAssembly_Assembly_ThrowsCompositionFailedExceptionOnCreation Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15173]
Fails the same as #15170

This is a tracking issue.

**Comment by CoffeeFlux** [comment]
New failure:
```
    System.Composition.Hosting.Tests.ContainerConfigurationTests.WithAssembly_Assembly_ThrowsCompositionFailedExceptionOnCreation [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Composition.Hosting.CompositionFailedException)
      Actual:   typeof(System.InvalidCastException): Specified cast is not valid.
      ---- System.InvalidCastException : Specified cast is not valid.
      Stack Trace:
           at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
           at System.Composition.TypedParts.Util.DirectAttributeContext.GetCustomAttributes(Type reflectedType, MemberInfo member)
           at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[PartNotDiscoverableAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
           at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
           at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
           at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
           at System.Composition.Hosting.Tests.ContainerConfigurationTests.<>c__DisplayClass16_0.<WithAssembly_Assembly_ThrowsCompositionFailedExceptionOnCreation>b__0()
        ----- Inner Stack Trace -----
           at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
           at System.Composition.TypedParts.Util.DirectAttributeContext.GetCustomAttributes(Type reflectedType, MemberInfo member)
           at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[PartNotDiscoverableAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
           at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
           at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
           at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
           at System.Composition.Hosting.Tests.ContainerConfigurationTests.<>c__DisplayClass16_0.<WithAssembly_Assembly_ThrowsCompositionFailedExceptionOnCreation>b__0()
```

**Comment by CoffeeFlux** [comment]
This looks to me like a BCL issue now that the loader issue is fixed, though I can't say for sure. Same as #15171.

**Comment by CoffeeFlux** [comment]
This failure is more interesting than I thought. The runtime has an `object[]` array with two elements, of types `System.Runtime.CompilerServices.CompilerGeneratedAttribute` and `System.SerializableAttribute System.SerializableAttribute`. Both of those can be cast to `Attribute` individually, but the array as a whole cannot be downcast. Need to check the spec/potentially write some tests to see if we're doing the check correctly.
