### ISSUE TITLE
[netcore] Make System.Composition.Hosting.Tests.ContainerConfigurationTests.WithAssemblies_Assemblies_ThrowsCompositionFailedExceptionOnCreation Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15171]
Fails the same as https://github.com/mono/mono/issues/15170

This is a tracking issue.

**Comment by CoffeeFlux** [comment]
New failure:
```
    System.Composition.Hosting.Tests.ContainerConfigurationTests.WithAssemblies_Assemblies_ThrowsCompositionFailedExceptionOnCreation [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.Composition.Hosting.CompositionFailedException)
      Actual:   typeof(System.InvalidCastException): Specified cast is not valid.
      ---- System.InvalidCastException : Specified cast is not valid.
      Stack Trace:
           at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
           at System.Composition.TypedParts.Util.DirectAttributeContext.GetCustomAttributes(Type reflectedType, MemberInfo member)
           at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[PartNotDiscoverableAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
           at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
           at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
           at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
           at System.Composition.Hosting.Tests.ContainerConfigurationTests.<>c__DisplayClass18_0.<WithAssemblies_Assemblies_ThrowsCompositionFailedExceptionOnCreation>b__0()
        ----- Inner Stack Trace -----
           at System.Attribute.GetCustomAttributes(MemberInfo element, Boolean inherit)
           at System.Composition.TypedParts.Util.DirectAttributeContext.GetCustomAttributes(Type reflectedType, MemberInfo member)
           at System.Composition.Convention.AttributedModelProviderExtensions.GetDeclaredAttribute[PartNotDiscoverableAttribute](AttributedModelProvider convention, Type reflectedType, MemberInfo member)
           at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
           at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
           at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
           at System.Composition.Hosting.Tests.ContainerConfigurationTests.<>c__DisplayClass18_0.<WithAssemblies_Assemblies_ThrowsCompositionFailedExceptionOnCreation>b__0()
```
