### ISSUE TITLE
[netcore] Make System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15186]
The test currently fails with:

```
System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(stackFrame: .ctor at offset 90 in file:line:column FileName:1:2\n, expectedToString: "MoveNext at offset {offset} in file:line:column Fi"...) [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: MoveNext at offset 90 in file:line:column···
      Actual:   .ctor at offset 90 in file:line:column Fi···
                ↑ (pos 0)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(StackFrame stackFrame, String expectedToString)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(stackFrame: GenericMethod<String> at offset 98 in file:line:column <filename unknown>:0:0\n, expectedToString: "GenericMethod<T> at offset {offset} in file:line:c"...) [FAIL]
      Assert.Equal() Failure
                              ↓ (pos 14)
      Expected: GenericMethod<T> at offset 98 in file:line:column <file···
      Actual:   GenericMethod<String> at offset 98 in file:line:column ···
                              ↑ (pos 14)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(StackFrame stackFrame, String expectedToString)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(stackFrame: GenericMethod<String,Int32> at offset 90 in file:line:column <filename unknown>:0:0\n, expectedToString: "GenericMethod<T,U> at offset {offset} in file:line"...) [FAIL]
      Assert.Equal() Failure
                              ↓ (pos 14)
      Expected: GenericMethod<T,U> at offset 90 in file:line:column <fi···
      Actual:   GenericMethod<String,Int32> at offset 90 in file:line:c···
                              ↑ (pos 14)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.ToString_Invoke_ReturnsExpected(StackFrame stackFrame, String expectedToString)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Looks close, but something is off.  Determine what it'll take and make the test pass.

**Comment by EgorBo** [comment]
This issue is basically a mix of https://github.com/mono/mono/issues/15184 and https://github.com/mono/mono/issues/15315
