### ISSUE TITLE
[netcore] Make System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15184]
The test currently fails with:

```
System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0) [FAIL]
      Assert.Equal() Failure
      Expected: Void Ctor_Filename_LineNumber_ColNumber(System.String, Int32, Int32)
      Actual:   .ctorVoid (System.String, Int32, Int32)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: "", lineNumber: 0, columnNumber: -1) [FAIL]
      Assert.Equal() Failure
      Expected: Void Ctor_Filename_LineNumber_ColNumber(System.String, Int32, Int32)
      Actual:   .ctorVoid (System.String, Int32, Int32)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: "FileName", lineNumber: 1, columnNumber: 2) [FAIL]
      Assert.Equal() Failure
      Expected: Void Ctor_Filename_LineNumber_ColNumber(System.String, Int32, Int32)
      Actual:   .ctorVoid (System.String, Int32, Int32)
      Stack Trace:
           at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by EgorBo** [comment]
This one happens because this `this` https://github.com/dotnet/coreclr/blob/085398b5c6913b03180c855f56b967e2a7d6edde/src/System.Private.CoreLib/shared/System/Diagnostics/StackFrame.cs#L114 generates an unexpected frame
