### ISSUE TITLE
[netcore] Make System.Reflection.Tests.AssemblyTests.LoadFromStream_Location_IsEmpty Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15192]
The test currently fails with:

```
System.Reflection.Tests.AssemblyTests.LoadFromStream_Location_IsEmpty [FAIL]
      System.IO.FileNotFoundException : 
      Stack Trace:
           at System.Reflection.Assembly.Load(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
           at System.Reflection.Tests.AssemblyTests.LoadFromStream_Location_IsEmpty()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by CoffeeFlux** [comment]
New failure:
```
    System.Reflection.Tests.AssemblyTests.LoadFromStream_Location_IsEmpty [FAIL]
      Assert.Empty() Failure
      Collection: "data-0x102415488"
      Stack Trace:
           at System.Reflection.Tests.AssemblyTests.LoadFromStream_Location_IsEmpty()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
