### ISSUE TITLE
Running CoreFX System.Security.Cryptography.Pkcs.Tests fails with NRE occasionally

### ISSUE THREAD

**Issue by marek-safar** [mono/mono#15238]
## Steps to Reproduce

1. build Mono for netcore
2. make run-tests-corefx-System.Security.Cryptography.Pkcs.Tests
3. 

### Current Behavior

The tests fail occasionally with NRE, for me locally like 1 in 10 runs

### Expected Behavior

No unexpected NullReferenceException

One example
```
    System.Security.Cryptography.Pkcs.Tests.SignedCmsTests.CheckSignedEncrypted_IssuerSerial_FromNetFx [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.Security.Cryptography.Pkcs.Pkcs9MessageDigest.Decode(Byte[] rawData)
           at System.Security.Cryptography.Pkcs.Pkcs9MessageDigest.get_MessageDigest()
           at System.Security.Cryptography.Pkcs.SignerInfo.PrepareDigest(Boolean compatMode)
           at System.Security.Cryptography.Pkcs.SignerInfo.VerifySignature(CmsSignature signatureProcessor, X509Certificate2 certificate, Boolean compatMode)
           at System.Security.Cryptography.Pkcs.SignerInfo.Verify(X509Certificate2Collection extraStore, X509Certificate2 certificate, Boolean verifySignatureOnly)
           at System.Security.Cryptography.Pkcs.SignerInfo.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
           at System.Security.Cryptography.Pkcs.SignedCms.CheckSignatures(SignerInfoCollection signers, X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
           at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(X509Certificate2Collection extraStore, Boolean verifySignatureOnly)
           at System.Security.Cryptography.Pkcs.SignedCms.CheckSignature(Boolean verifySignatureOnly)
           at System.Security.Cryptography.Pkcs.Tests.SignedCmsTests.CheckSignedEncrypted(Byte[] docBytes, SubjectIdentifierType expectedType)
           at System.Security.Cryptography.Pkcs.Tests.SignedCmsTests.CheckSignedEncrypted_IssuerSerial_FromNetFx()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Comment by filipnavara** [comment]
On my MacBook Pro this happens roughly in 1/4th of the runs. Annoyingly enough the S.S.C.Pkcs NuGet doesn't contain PDB files to make the debugging easier.

**Comment by filipnavara** [comment]
I know it was kind of obvious that the `null` value is `PkcsPal.Instance` but I finally managed to get a debug build with full stack trace(s) that confirm it:
```
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.RSA.cs(141,0): at System.Security.Cryptography.Pkcs.CmsSignature.RSAPkcs1CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& signatureAlgorithm, Byte[]& signatureValue)
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSignature.cs(95,0): at System.Security.Cryptography.Pkcs.CmsSignature.Sign(ReadOnlySpan`1 dataHash, HashAlgorithmName hashAlgorithmName, X509Certificate2 certificate, AsymmetricAlgorithm key, Boolean silent, Oid& oid, ReadOnlyMemory`1& signatureValue)
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/CmsSigner.cs(233,0): at System.Security.Cryptography.Pkcs.CmsSigner.Sign(ReadOnlyMemory`1 data, String contentTypeOid, Boolean silent, X509Certificate2Collection& chainCerts)
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/SignerInfo.cs(252,0): at System.Security.Cryptography.Pkcs.SignerInfo.ComputeCounterSignature(CmsSigner signer)
        /_/src/System.Security.Cryptography.Pkcs/tests/SignedCms/SignerInfoTests.cs(950,0): at System.Security.Cryptography.Pkcs.Tests.SignerInfoTests.EnsureExtraCertsAdded()
        /Users/filipnavara/Documents/mono/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeMethodInfo.cs(343,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by filipnavara** [comment]
Interestingly enough it is reproducible even with single-threaded test runs:
```
  Discovering: System.Security.Cryptography.Pkcs.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.Pkcs.Tests (found 514 of 639 test cases)
  Starting:    System.Security.Cryptography.Pkcs.Tests (parallel test collections = off, max threads = 4)
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadIndefiniteEncodingNoMac [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadIndefiniteEncodingNoMac [FINISHED] Time: 0.1667372s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.VerifyMacWithNoMac [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.VerifyMacWithNoMac [FINISHED] Time: 0.0202245s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadEmptyPfx [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadEmptyPfx [FINISHED] Time: 0.0150097s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadOracleWallet [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadOracleWallet [FINISHED] Time: 0.0257428s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.BuildWithFactoryReadDirect [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.BuildWithFactoryReadDirect [FINISHED] Time: 0.7751309s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "", expectSuccess: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "", expectSuccess: False) [FINISHED] Time: 0.0011214s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0401", expectSuccess: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0401", expectSuccess: False) [FINISHED] Time: 0.000237s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0400020100", expectSuccess: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0400020100", expectSuccess: False) [FINISHED] Time: 0.000069s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "04", expectSuccess: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "04", expectSuccess: False) [FINISHED] Time: 0.0000704s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0400", expectSuccess: True) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0400", expectSuccess: True) [FINISHED] Time: 0.0000221s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0300", expectSuccess: True) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "0300", expectSuccess: True) [FINISHED] Time: 0.0000184s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "30802480048200017F00000000", expectSuccess: True) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "30802480048200017F00000000", expectSuccess: True) [FINISHED] Time: 0.0000246s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "30802480048200017F0000000000", expectSuccess: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.CtorEnsuresValidBerValue(inputHex: "30802480048200017F0000000000", expectSuccess: False) [FINISHED] Time: 0.0000669s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.SkipCopyHonored(skipCopy: False) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.SkipCopyHonored(skipCopy: False) [FINISHED] Time: 0.0020847s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.SkipCopyHonored(skipCopy: True) [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.KeyBagTests.SkipCopyHonored(skipCopy: True) [FINISHED] Time: 0.0000232s
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeBagTests.AttributesIsMutable [STARTING]
    System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeBagTests.AttributesIsMutable [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs9DocumentDescription.cs(73,0): at System.Security.Cryptography.Pkcs.Pkcs9DocumentDescription.Encode(String documentDescription)
        /Users/filipnavara/Documents/corefx/src/System.Security.Cryptography.Pkcs/src/System/Security/Cryptography/Pkcs/Pkcs9DocumentDescription.cs(26,0): at System.Security.Cryptography.Pkcs.Pkcs9DocumentDescription..ctor(String documentDescription)
        /_/src/System.Security.Cryptography.Pkcs/tests/Pkcs12/Pkcs12SafeBagTests.cs(84,0): at System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeBagTests.AttributesIsMutable()
        /Users/filipnavara/Documents/mono/netcore/System.Private.CoreLib/src/System.Reflection/RuntimeMethodInfo.cs(343,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by filipnavara** [comment]
`XUNIT_FLAGS = -notrait category=nonosxtests -parallel none -verbose -serialize` crashes every time with NRE... not sure if it's the same crash though.

**Comment by marek-safar** [comment]
yeah I noticed that as well but I am not sure -serialize is not actually separate issue (didn't try to run with that flag different test suite)

**Comment by filipnavara** [comment]
I randomly picked few other ones and they worked with `-serialize`. The diagnostic information is not very useful for it but at least it is something reproducible.

**Comment by filipnavara** [comment]
I somewhat reduced the surface area with `XUNIT_FLAGS="-method System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12InfoTests.ReadIndefiniteEncodingNoMac -method System.Security.Cryptography.Pkcs.Tests.Pkcs12.Pkcs12SafeBagTests.AttributesIsMutable"`. If `Pkcs12InfoTests` is executed first then it always crashes with NRE. The other order always succeeds.

**Comment by filipnavara** [comment]
Minimized repro:
```

using System;
using System.Security.Cryptography;
using System.Security.Cryptography.Pkcs;

class Test
{
	public static void Main()
	{
		try
		{
			var localKeyId = new Pkcs9LocalKeyId(Convert.FromBase64String("BBjmtlLdAAAABAAAAAAAAAAGAAAAAwAAAAA="));
			var vv = localKeyId.KeyId;
			new Pkcs9DocumentDescription("Description");
		}
		catch (Exception e)
		{
			Console.WriteLine(e);
		}
	}
}
```

**Comment by filipnavara** [comment]
Here's a fully reduced test case with no external dependencies:
```csharp
using System;

class Test
{
    internal abstract partial class PkcsPal
    {
        public static PkcsPal Instance => s_instance;
	    private static readonly PkcsPal s_instance = ManagedPkcsPal.Instance;
	}

    internal sealed partial class ManagedPkcsPal : PkcsPal
    {
        internal new static readonly ManagedPkcsPal Instance = new ManagedPkcsPal();
	}

	public static void Main()
	{
		Console.WriteLine(ManagedPkcsPal.Instance == null); // should be False
		Console.WriteLine(PkcsPal.Instance == null); // should be False, it is True
	}
}
```

/cc @vargaz

**Comment by vargaz** [comment]
Thanks for the testcase.
What happens is ManagerX:.ctor () calls X:.ctor () which triggers the cctor of X which reads the uninitialized X:Instance variable.

The spec says:
4. If not marked BeforeFieldInit then that type’s initializer method is executed at (i.e., is triggered by):
a. first access to any static field of that type, or
b. first invocation of any static method of that type, or
c. first invocation of any instance or virtual method of that type if it is a value type or
d. first invocation of any constructor for that type.

So this looks correct spec wise.

**Comment by marek-safar** [comment]
@jkotas @davidwrighton could you guys please weight in on the compatibility bar for .NET 5 for this scenario and why it's deterministic on CoreCLR?

**Comment by vargaz** [comment]
So apparently, netcore changed the semantics of beforefieldinit to mean "right before static field access".

**Comment by jkotas** [comment]
> why it's deterministic on CoreCLR?

We used to get quite a few customer reported issues caused by the non-deterministic behavior, e.g. when the JIT inliner heuristic improved, the static constructors run earlier, later or not at all, that resulted in compatibility breaks. It is impossible for our customers to test that their code is robust against arbitrary before-field-init constructor ordering, and we do know that a lot of code out there is not robust against it.

We choose to give up the flexibility that the spec provides and restrict ourselves to just "right before static field access". The performance loss from this is non-measurable in real world apps and it can be further reduced by optimizing the path.

The behavior in .NET Framework is  "right before static field access" in some of the compatibility quirk modes as well.

**Comment by jkotas** [comment]
Having said this, it is generally a practice to have cycles between static constructors and it would be nice to get the initialization cycle that contributes to this cycle fixed.

**Comment by lambdageek** [comment]
@SamMonoRT I think this is a good one for someone on your team - good way to jump into our codegen

**Comment by SamMonoRT** [comment]
@fanyang-mono - Very low priority given other work, moving to your queue for now. We'll need to triage later and see if it is still needed in the runtime repo
