### ISSUE TITLE
Implement GC.GetGCMemoryInfo

### ISSUE THREAD

**Issue by naricc** [mono/mono#15236]
This function exists in Dotnet 3.0, but is not yet implemented in Mono. The description in dotnet core is here:

https://docs.microsoft.com/en-us/dotnet/api/system.gcmemoryinfo?view=netcore-3.0

TODO:

- [ ] Reenable System.Tests.GCExtendedTests.GetGCMemoryInfo test in CoreFX.issues.rsp

**Comment by naricc** [comment]
Is Memory Load the same thing as the live size (total number of bytes in live objects)?

**Comment by naricc** [comment]
Pull request for this issue: https://github.com/mono/mono/pull/17607

**Comment by CoffeeFlux** [comment]
API was merged, but I'm not sure the test was enabled. Should do so and then close this.

**Comment by CoffeeFlux** [comment]
New failure for reference:

```
FAILED: HighMemoryLoadThresholdBytes

Unhandled Exception:
Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 17498344
Actual:   16777216
   at Xunit.Assert.Equal[Int64](Int64 expected, Int64 actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[Int64](Int64 expected, Int64 actual)
   at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__22_0() in /_/src/System.Runtime/tests/System/GCTests.cs:line 818
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/ryan/git/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
[ERROR] FATAL UNHANDLED EXCEPTION: Xunit.Sdk.EqualException: Assert.Equal() Failure
Expected: 17498344
Actual:   16777216
   at Xunit.Assert.Equal[Int64](Int64 expected, Int64 actual, IEqualityComparer`1 comparer)
   at Xunit.Assert.Equal[Int64](Int64 expected, Int64 actual)
   at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__22_0() in /_/src/System.Runtime/tests/System/GCTests.cs:line 818
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /Users/ryan/git/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.DotNet.RemoteExecutor.Program.Main(String[] args)
    System.Tests.GCExtendedTests.GetGCMemoryInfo [FAIL]
      Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
      Stack Trace:
        
        Child exception:
          Xunit.Sdk.EqualException: Assert.Equal() Failure
        Expected: 17498344
        Actual:   16777216
        /_/src/System.Runtime/tests/System/GCTests.cs(818,0): at System.Tests.GCExtendedTests.<>c.<GetGCMemoryInfo>b__22_0()
        /Users/ryan/git/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
        
        Child process:
          System.Runtime.Tests, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCExtendedTests+<>c Void <GetGCMemoryInfo>b__22_0()
```

**Comment by naricc** [comment]
Still some issues remaining with fragmented bytes before I can re-enable the test.

**Comment by naricc** [comment]
We are probably not going to do this in mono/mono.

**Comment by marek-safar** [comment]
If the API is not going to be implemented we should annotate it as not supported on relevant platforms.
