### ISSUE TITLE
RemoteInvoke()-based tests and System.Diagnostics.Process.Tests crash on Windows

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#15306]
All corefx tests with RemoteTestExecutor inside crash runtime on Windows. Somewhere inside Process.Start (see the following stacktrace). This blocks us on running tests on CI for Windows.

## Steps to Reproduce

1. `make run-tests-corefx-System.Runtime.Tests` or better `make run-tests-corefx-System.Diagnostics.Process.Tests`

### Current Behavior

Segmenation fault:
```
System.Diagnostics.Tests.ProcessStartInfoTests.TestWorkingDirectoryPropertyInChildProcess [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
        C:\prj\mono\mono-e\netcore\System.Private.CoreLib\shared\System\Runtime\InteropServices\SafeHandle.cs(92,0): at System.Runtime.InteropServices.SafeHandle.Dispose()
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Windows.cs(622,0): at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Win32.cs(26,0): at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1245,0): at System.Diagnostics.Process.Start()
        /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs(1288,0): at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
           at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(MethodInfo method, String[] args, RemoteInvokeOptions options, Boolean pasteArguments)
           at Microsoft.DotNet.RemoteExecutor.RemoteExecutor.Invoke(Func`2 method, String arg, RemoteInvokeOptions options)
        /_/src/System.Diagnostics.Process/tests/ProcessStartInfoTests.cs(367,0): at System.Diagnostics.Tests.ProcessStartInfoTests.TestWorkingDirectoryPropertyInChildProcess()
        C:\prj\mono\mono-e\netcore\System.Private.CoreLib\src\System.Reflection\RuntimeMethodInfo.cs(343,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
/bin/sh: line 4:  8616 Segmentation fault
```

I tried to find the place with this nullref via `--debug` and `--trace` but with no luck. I suspect it's something runtime related.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Comment by filipnavara** [comment]
Can you please run it with -O=-inline to get better stack trace?

**Comment by EgorBo** [comment]
@filipnavara yeah I tried but it didn't help :( nor improved the stacktrace

**Comment by EgorBo** [comment]
I also tried to modify code here and there around SafeHandles, etc but with no luck

**Comment by EgorBo** [comment]
It feels like SafeHandle objects are not null but any calls to them (e.g. IsInvalid) throw `NRE`

**Comment by filipnavara** [comment]
This issue can be closed now.
