### ISSUE TITLE
[netcore] Make ThreadPoolBoundHandleTests.PreAllocatedOverlapped_NonBlittableTypeAsPinData_Throws Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15313]
The test currently fails with:

```
ThreadPoolBoundHandleTests.PreAllocatedOverlapped_NonBlittableTypeAsPinData_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentException)
      Actual:   (No exception was thrown)
      Stack Trace:
           at System.AssertExtensions.Throws[ArgumentException](String paramName, Func`1 testCode)
           at ThreadPoolBoundHandleTests.PreAllocatedOverlapped_NonBlittableTypeAsPinData_Throws()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
Same for `ThreadPoolBoundHandleTests.PreAllocatedOverlapped_ObjectArrayWithNonBlittableTypeAsPinData_Throws`

**Comment by jkotas** [comment]
This is Windows specific functionality. It should be fine to make this throw `PlatformNotSupportedException(SR.PlatformNotSupported_OverlappedIO)` on non-Windows, for both CoreCLR and Mono.
