### ISSUE TITLE
[netcore] Make System.Tests.EnvironmentStackTrace.StackTraceTest Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15315]
The test currently fails with:

```
System.Tests.EnvironmentStackTrace.StackTraceTest [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Tests.EnvironmentStackTrace.StackTraceTest()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Our previous analysis was that Mono expands generic Types in stacktraces unlike the .NET Core (sounds more like a feature: https://gist.github.com/EgorBo/3abb37d2ff4fc904bc7472c62498f933).  

If this *should* be a feature, kick it upstream.  Either way the test should pass or be ignored.

**Comment by EgorBo** [comment]
I suspect the reason why we print actual name is somewhere in `ves_icall_RuntimeMethodInfo_GetGenericArguments`
