### ISSUE TITLE
[netcore] Make ThreadPoolBoundHandleTests.BindHandle_MinusOneAsHandle_ThrowsArgumentException Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15312]
The test currently fails with:

```
 ThreadPoolBoundHandleTests.BindHandle_MinusOneAsHandle_ThrowsArgumentException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.ArgumentException)
      Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object
      ---- System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
           at ThreadPoolBoundHandleTests.<>c__DisplayClass52_0.<BindHandle_MinusOneAsHandle_ThrowsArgumentException>b__0()
        ----- Inner Stack Trace -----
           at System.Threading.ThreadPoolBoundHandle.BindHandle(SafeHandle handle)
           at ThreadPoolBoundHandleTests.<>c__DisplayClass52_0.<BindHandle_MinusOneAsHandle_ThrowsArgumentException>b__0()
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
No repro on Mac OS, I'll enable it in https://github.com/dotnet/runtime/pull/2087.
