### ISSUE TITLE
[netcore] Make System.Reflection.Emit.Tests.DynamicMethodToString.ToStringTest Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15323]
The test currently fails with:

```
System.Reflection.Emit.Tests.DynamicMethodToString.ToStringTest(returnType: typeof(string), parameterTypes: [typeof(string), typeof(int), typeof(System.Reflection.Emit.Tests.TestClass)], expected: "System.String MethodName(System.String, Int32, Sys"...) [FAIL]
      Assert.Equal() Failure
                 ↓ (pos 1)
      Expected: System.String MethodName(System.String, In···
      Actual:   String MethodName(String, Int32, TestClass···
                 ↑ (pos 1)
      Stack Trace:
           at System.Reflection.Emit.Tests.DynamicMethodToString.ToStringTest(Type returnType, Type[] parameterTypes, String expected)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Emit.Tests.DynamicMethodToString.ToStringTest(returnType: typeof(string), parameterTypes: [typeof(System.Reflection.Emit.Tests.GenericClass<>)], expected: "System.String MethodName(System.Reflection.Emit.Te"...) [FAIL]
      Assert.Equal() Failure
                 ↓ (pos 1)
      Expected: System.String MethodName(System.Reflection···
      Actual:   String MethodName(GenericClass`1)
                 ↑ (pos 1)
      Stack Trace:
           at System.Reflection.Emit.Tests.DynamicMethodToString.ToStringTest(Type returnType, Type[] parameterTypes, String expected)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Looks like we need to put System on String :-).  Try to make the test pass.

**Comment by EgorBo** [comment]
Filed https://github.com/dotnet/corefx/issues/39360

**Comment by MaximLipnin** [comment]
Fixed in https://github.com/mono/mono/pull/16783
