### ISSUE TITLE
[netcore] Make System.Reflection.Tests.CustomAttributeTests.CustomAttributeNamedArguments_Field Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15339]
The test currently fails with:

```
System.Reflection.Tests.CustomAttributeTests.CustomAttributeNamedArguments_Field [FAIL]
      System.InvalidOperationException : Sequence contains no elements
      Stack Trace:
           at System.Linq.ThrowHelper.ThrowNoElementsException()
           at System.Linq.Enumerable.Single[CustomAttributeData](IEnumerable`1 source)
           at System.Reflection.Tests.CustomAttributeTests.CustomAttributeNamedArguments_Field()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
I mentioned this test with `-method System.Reflection.Tests.CustomAttributeTests.CustomAttributeNamedArguments_Field` and it passes locally on macOS.

**Comment by steveisok** [comment]
OK, let's take it out of the rsp file and see if it passes CI

**Comment by MaximLipnin** [comment]
It was checked in https://github.com/mono/mono/pull/15700.
