### ISSUE TITLE
[netcore] Make System.Reflection.Tests.CustomAttributeTests.TestDllImportPseudoCustomAttribute Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15340]
The test currently fails with:

```
System.Reflection.Tests.CustomAttributeTests.TestDllImportPseudoCustomAttribute [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.Reflection.CustomAttributeData.get_AttributeType()
           at System.Reflection.Tests.CustomAttributeInstantiator.Instantiate[DllImportAttribute](CustomAttributeData cad)
           at System.Reflection.Tests.TestUtils.UnprojectAndInstantiate[DllImportAttribute](CustomAttributeData cad)
           at System.Reflection.Tests.CustomAttributeTests.TestDllImportPseudoCustomAttribute()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by lambdageek** [comment]
This is preventing `MetadataLoadContext` from working properly with netcore Mono. Mono's `CustomAttributeData` implementation is different from CoreCLR and `MetadataLoadContext` subclasses `CustomAttributeData` and doesn't call our internal constructors.

**Comment by grendello** [comment]
If MLC worked on Mono, it could greatly improve performance on mobile devices in situations when we can't avoid using reflection (not just to retrieve custom attributes) for various reasons.

**Comment by lewing** [comment]
@mrward this is the mono issue
