### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeInvariants.TestInvariantCode Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15344]
The test currently fails with:

```
System.Reflection.Tests.TypeInvariants.TestInvariantCode [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
           at System.Reflection.Tests.CustomAttributeTests.ValidateEqualButFreshlyAllocated(IEnumerable`1 cads1, IEnumerable`1 cads2)
           at System.Reflection.Tests.CustomAttributeTests.ValidateCustomAttributesAllocatesFreshObjectsEachTime(Func`1 action)
           at System.Reflection.Tests.TypeInvariants.TestTypeCommonInvariants(Type type)
           at System.Reflection.Tests.TypeInvariants.TestTypeDefinitionCommonInvariants(Type type)
           at System.Reflection.Tests.TypeInvariants.TestTypeDefinitionInvariants(Type type)
           at System.Reflection.Tests.TypeInvariants.TestInvariantCode()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
The test fails [here](https://github.com/dotnet/runtime/blob/4f9ae42d861fcb4be2fcd5d3d55d5f227d30e723/src/libraries/System.Reflection.MetadataLoadContext/tests/src/Tests/CustomAttributes/CustomAttributeTests.cs#L148):
`Assert.True(cad1.ConstructorArguments is ReadOnlyCollection<CustomAttributeTypedArgument>);`

Netcore-mono has its own [code](https://github.com/mono/mono/blob/master/netcore/System.Private.CoreLib/src/System/Reflection/CustomAttributeData.cs#L77-L108) to resolve `CustomAttributeData.ConstructorArguments` that looks correct.

**Comment by MaximLipnin** [comment]
This seems to be related to https://github.com/mono/mono/issues/15340
