### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeTests.TypesWithStrangeCharacters Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15349]
The test currently fails with:

```
System.Reflection.Tests.TypeTests.TypesWithStrangeCharacters [FAIL]
      System.TypeLoadException : Could not find type 'Typ\\W\[t\]S\+r\*n\&e\,haracters' in assembly ''.
      Stack Trace:
           at System.Reflection.TypeLoading.Helpers.<>c__DisplayClass17_0.<LoadTypeFromAssemblyQualifiedName>b__1(Assembly assembly, String fullName, Boolean ignoreCase2)
           at System.TypeNameParser.ResolveType(Assembly assembly, List`1 names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
           at System.TypeNameParser.ConstructType(ParsedName pname, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
           at System.TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
           at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
           at System.Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase)
           at System.Reflection.TypeLoading.Helpers.LoadTypeFromAssemblyQualifiedName(String name, RoAssembly defaultAssembly, Boolean ignoreCase, Boolean throwOnError)
           at System.Reflection.TypeLoading.RoAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
           at System.Reflection.Tests.TypeTests.TypesWithStrangeCharacters()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by fanyang-mono** [comment]
Fixed by this PR
https://github.com/mono/mono/pull/16425
