### ISSUE TITLE
[netcore] Make System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.* Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15352]
The tests currently fail with:

```
 System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ExportPropertyTargetingDerivedClass_ShouldGenerateExportForPropertySelected [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.ComponentModel.Composition.Registration.Tests.InternalCalls.PartBuilder(Predicate`1 selectType)
           at System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ExportPropertyTargetingDerivedClass_ShouldGenerateExportForPropertySelected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingBaseClass_ShouldGenerateImportForPropertySelected [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.ComponentModel.Composition.Registration.Tests.InternalCalls.PartBuilder(Predicate`1 selectType)
           at System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingBaseClass_ShouldGenerateImportForPropertySelected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ExportPropertyTargetingBaseClass_ShouldGenerateExportForPropertySelected [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.ComponentModel.Composition.Registration.Tests.InternalCalls.PartBuilder(Predicate`1 selectType)
           at System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ExportPropertyTargetingBaseClass_ShouldGenerateExportForPropertySelected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingBaseClass_ShouldGenerateImportManyForPropertySelected [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.ComponentModel.Composition.Registration.Tests.InternalCalls.PartBuilder(Predicate`1 selectType)
           at System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingBaseClass_ShouldGenerateImportManyForPropertySelected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingDerivedClass_ShouldGenerateImportForPropertySelected [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object
      Stack Trace:
           at System.ComponentModel.Composition.Registration.Tests.InternalCalls.PartBuilder(Predicate`1 selectType)
           at System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.ImportPropertyTargetingDerivedClass_ShouldGenerateImportForPropertySelected()
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the tests pass.

**Comment by fanyang-mono** [comment]
System.ComponentModel.Composition.Registration.Tests.PartBuilderInheritanceTests.* seem to be passing now. I will close the issue now. However, they won't be running on the CI, cause they currently are disabled by #16417.
