### ISSUE TITLE
[netcore] Make System.Reflection.Tests.TypeTests.GetEnumUnderlyingType Pass

### ISSUE THREAD

**Issue by steveisok** [mono/mono#15350]
The test currently fails with:

```
System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(enumTypeW: SampleMetadata.GenericEnumContainer`1, expectedUnderlyingTypeW: System.Int16) [FAIL]
      System.ArgumentException : Type provided must be an enum.
      Stack Trace:
           at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoType.GetEnumUnderlyingType()
           at System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(TypeWrapper enumTypeW, TypeWrapper expectedUnderlyingTypeW)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(enumTypeW: SampleMetadata.GenericEnumContainer`1[System.Int32], expectedUnderlyingTypeW: System.Int16) [FAIL]
      System.ArgumentException : Type provided must be an enum.
      Stack Trace:
           at System.Reflection.TypeLoading.Ecma.EcmaDefinitionType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoConstructedGenericType.ComputeEnumUnderlyingType()
           at System.Reflection.TypeLoading.RoType.GetEnumUnderlyingType()
           at System.Reflection.Tests.TypeTests.GetEnumUnderlyingType(TypeWrapper enumTypeW, TypeWrapper expectedUnderlyingTypeW)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

Determine why and make the test pass.

**Comment by MaximLipnin** [comment]
It fails here: https://github.com/dotnet/corefx/blob/1b3a095c277476b746e6fb9884662cf12334c6a1/src/System.Reflection.MetadataLoadContext/tests/src/Tests/Type/TypeTests.cs#L280

The snippet from the test w/o `TypeWrapper` works (run as netcore "HelloWorld" sample):
```
using System;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            // TypeWrapper tw = typeof(GenericEnumContainer<>.GenericEnum).Project();
            // Type t= tw?.Type;
            Type t = typeof(GenericEnumContainer<>.GenericEnum);

            Console.WriteLine(t.GetEnumUnderlyingType() == typeof(short));
        }
    }

    public class GenericEnumContainer<T>
    {
        public enum GenericEnum : short { }
    }
}
```

**Comment by MaximLipnin** [comment]
Seems that something happens in [TestUtils.Project](https://github.com/dotnet/corefx/blob/cea2a3e00c9a508fbf92bcaf0aeb4df833514057/src/System.Reflection.MetadataLoadContext/tests/src/TestUtils/TestUtils.JittedRuntimes.cs#L15-L45) method.

```
    // Type type = typeof(GenericEnumContainer<>.GenericEnum).Project();
    Type type = typeof(GenericEnumContainer<>.GenericEnum);
    Console.WriteLine(type.GetEnumUnderlyingType() == typeof(short));
```

**Comment by MaximLipnin** [comment]
For me locally it returns ```HelloWorld.GenericEnumContainer`1``` rather ```HelloWorld.GenericEnumContainer`1+GenericEnum[T]```.

**Comment by MaximLipnin** [comment]
[Assembly.GetType ](https://github.com/dotnet/corefx/blob/cea2a3e00c9a508fbf92bcaf0aeb4df833514057/src/System.Reflection.MetadataLoadContext/tests/src/TestUtils/TestUtils.JittedRuntimes.cs#L39) could be the problem here.

**Comment by steveisok** [comment]
I wondered if https://github.com/mono/mono/pull/15488 might fix it.  Tried it and still failed.

**Comment by MaximLipnin** [comment]
[TypeNameParser.ParseName](https://github.com/marek-safar/mono/blob/0bb5bf2a9f61a493b50370445ac1cc5d2cd3dfbf/mcs/class/System.Private.CoreLib/System/TypeNameParser.cs#L207) seems to skip the part of the type name after "+".

**Comment by lambdageek** [comment]
I don't see any problems with TypeNameParser.

The following produces the expected output using master (8fe4109eadc3213a7cdc23ffe02fc25f17531e2a)

```csharp
using System;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
		var a = typeof(Program).Assembly;

		var full = typeof (GenericEnumContainer<>.GenericEnum).AssemblyQualifiedName;
		Console.WriteLine ("FullName: {0}", full);
		var tw = Type.GetType (full, null, null, throwOnError: true, ignoreCase: false);
		Console.WriteLine ("Type: {0}", tw.ToString());

		var full2 = typeof (GenericEnumContainer<int>.GenericEnum).AssemblyQualifiedName;

		Console.WriteLine ("FullName 2: {0}", full2);

		var tw2 = Type.GetType (full2, null, null, throwOnError: true, ignoreCase: false);

		Console.WriteLine ("Type 2: {0}", tw2.ToString ());
        }
    }

    public class GenericEnumContainer<T>
    {
        public enum GenericEnum : short { }
    }
}
```

Output:
```
FullName: HelloWorld.GenericEnumContainer`1+GenericEnum, HelloWorld, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Type: HelloWorld.GenericEnumContainer`1[T]
FullName 2: HelloWorld.GenericEnumContainer`1+GenericEnum[[System.Int32, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]], HelloWorld, Version=42.42.42.42, Culture=neutral, PublicKeyToken=31bf3856ad364e35
Type 2: HelloWorld.GenericEnumContainer`1[System.Int32]
```

(Verified by adding Debug.WriteLine to TypeNameParser)
