### ISSUE TITLE
Blazor: Unable to import .NET dll: Fatal error in IL Linker

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#15404]
_From @Z3roCoder on Friday, June 21, 2019 7:49:13 AM_

### Describe the bug
Deciding to try out what Client-Side Blazor with WASM is capable of, I tried to include one of our companies standalone DLLs and run some functions from it. However, instead I have been getting an IL Linker error at build time and could not get it to work.

```
1>Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.WasmRuntime (All).  Duplicate uses (All)
1>Fatal error in IL Linker
1>
1>Unhandled Exception: Mono.Cecil.ResolutionException: Failed to resolve System.CodeDom.Compiler.CodeDomProvider
1>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedType(TypeReference reference)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityAttribute(SecurityAttribute sa)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclaration(SecurityDeclaration sd)
1>   at Mono.Linker.Steps.MarkStep.MarkSecurityDeclarations(ISecurityDeclarationProvider provider)
1>   at Mono.Linker.Steps.MarkStep.MarkAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
1>   at Mono.Linker.Steps.MarkStep.Initialize()
1>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
1>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
1>   at Mono.Linker.Pipeline.Process(LinkContext context)
1>   at Mono.Linker.Driver.Run(ILogger customLogger)
1>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
1>   at Mono.Linker.Driver.Main(String[] args)
```

The Target-DLL was built for .NET 4.5 and only references System, System.Data, System.Xml and Microsoft.VisualBasic.

Assuming that the WASM-Example loads a full Mono-Environment (as I understand it), it should be able to work with any DLL - But here, it seems that the Problem is the Linker.

Sadly, i am not able to provide the DLL in question, but maybe anyone has an Idea as to what is going on here.

_Copied from original issue: aspnet/AspNetCore#11439_

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Friday, June 21, 2019 5:21:11 PM_

Thanks for contacting us, @Z3roCoder.
Can you try disabling the linker and see whether that works?
Simply set the `BlazorLinkOnBuild` property to `false` as shown below:
```xml
<PropertyGroup>
  <BlazorLinkOnBuild>false</BlazorLinkOnBuild>
</PropertyGroup>
```

Please note that Blazor WebAssembly apps run within the browser security sandbox so you won't be able to do operations which require elevated privileges (access files on disk, connect to database, ...).

**Comment by mkArtakMSFT** [comment]
_From @Z3roCoder on Friday, June 21, 2019 5:30:38 PM_

Hello, and thanks for you reply.
I've tried this by now and am now facing another issue.

My library uses CodeDom, which seems to not be supported by .NET Core - I think that might have been the issue in the first place as well.
(Issue being that CodeDomProvider can't be found in System, 4.0.0.0)

Is there any way to get this to work, or do I need to rewrite the library to discard CodeDom in favor of, say, Roslyn?

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Friday, June 21, 2019 5:52:10 PM_

@Z3roCoder have you tried to add a reference to the `System.CodeDom` NuGet package?

**Comment by mkArtakMSFT** [comment]
_From @Z3roCoder on Friday, June 21, 2019 6:17:18 PM_

Hello,
yes, I have added it and am still receiving the same Error as before

**Comment by mkArtakMSFT** [comment]
_From @Z3roCoder on Friday, June 21, 2019 7:44:18 PM_

In the end, I - for now - decided to drop the CodeDom and removed the parts that referenced it in my Library, and it seems to be working now. I don't know if that is a general issue, but if not, you can close the Ticket - If it is, I am happy to see it being resolved :)

**Comment by mkArtakMSFT** [comment]
_From @mkArtakMSFT on Tuesday, June 25, 2019 4:46:25 PM_

Glad you could work around this, @Z3roCoder.
Given this is not an issue we have control of, we're moving it to the Mono folks.

**Comment by kjpou1** [comment]
This might be the actual error.

```
/Users/Jimmy/websharp/projects/testwasmtemplate/Test.WebAssembly/Program.cs(9,9): Error CS1069: The type name 'CodeCompileUnit' could not be found in the namespace 'System.CodeDom'. This type has been forwarded to assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. (CS1069) (Test.WebAssembly)

/Users/Jimmy/websharp/projects/testwasmtemplate/Test.WebAssembly/Program.cs(9,9): Error CS1069: The type name 'CodeTypeDeclaration' could not be found in the namespace 'System.CodeDom'. This type has been forwarded to assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' Consider adding a reference to that assembly. (CS1069) (Test.WebAssembly)

````

**Comment by MarcosCobena** [comment]
Hey there,

We're facing a similar issue:

![imagen](https://user-images.githubusercontent.com/1142782/61291529-05453000-a7cf-11e9-95a9-457a35c23d46.png)

Here you can repro it —just build and run, you can serve the web with `xsp4`, for instance:

https://github.com/MarcosCobena/WasmApp1/tree/bug-missing-system-codedom-dll

Our guess comes from System.CodeDom having a small piece bundled with mscorlib.dll (or System.dll), thus doesn't like the incoming System.CodeDom.dll NuGet. Does it make sense? In such case, would there be any workaround or similar to get it working? We're not so much interested in compiling code actually, but it's somewhat used for generating C# on the fly.

Thanks in advance!

—@sescalada & @MarcosCobena

**Comment by kjpou1** [comment]
Was wondering if this could be related to the following issue that we had with the codedom and others?

[[wasm][sdk] WasmLinkAssemblies task wrongly uses reference assemblies](https://github.com/mono/mono/issues/15823)

@mkArtakMSFT @danroth27
