### ISSUE TITLE
System.NotImplementedException: Neutral region info at System.Globalization.RegionInfo..ctor

### ISSUE THREAD

**Issue by tarekgh** [mono/mono#15820]
_From @ststeiger on Wednesday, July 24, 2019 12:19:50 PM_

If one does
`Size = RegionInfo.CurrentRegion.IsMetric ? PageSize.A4 : PageSize.Letter;`
this fails, with a 

> System.NotImplementedException: Neutral region info at System.Globalization.RegionInfo..ctor

under certain conditions or environments (Xamarin.Forms). 

See 
https://github.com/ststeiger/PdfSharpCore/issues/46
https://github.com/ststeiger/PdfSharpCore/commit/2ba8fbe9fbde77c5f0e83d92af9b163f7a919c57

Is there something like InvariantRegion that one could return ? 
Or wouldn't it be better to return NULL in CurrentRegion, then it could be caught without exceptions. 
Could we define InvariantRegion as metric, since that's the [SI-unit](https://en.wikipedia.org/wiki/International_System_of_Units) ? 

_Copied from original issue: dotnet/corefx#39723_

**Comment by tarekgh** [comment]
_From @stephentoub on Wednesday, July 24, 2019 4:01:57 PM_

@ststeiger, can you share a more complete repro as well as the full stack trace of the exception?

And, you say "under certain conditions or environments (Xamarin.Forms)"... is your repro using .NET Core or Mono?

Thanks.

**Comment by tarekgh** [comment]
_From @tarekgh on Wednesday, July 24, 2019 4:03:08 PM_

I don't think this is coreclr issue. Maybe this is mono issue? looking at the failing stack 

https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Globalization/RegionInfo.cs#L99

We don't throw NotImplementedException but mono does:

https://github.com/mono/mono/blob/master/mcs/class/corlib/System.Globalization/RegionInfo.cs#L113

I'll move the issue to Mono.

**Comment by steveisok** [comment]
So, from what I can tell, the mono and the .net framework throw if there is a Neutral culture.  I don't want to call this 'by design' yet, so I'll get back to you.

**Comment by tarekgh** [comment]
Yes, you cannot get a region from neutral culture because such culture not having any region information. This is by design in the .NET in general.

**Comment by ststeiger** [comment]
@tarekgh: Yea, i think the better question is why does it have a neutral culture, since it's probably called from iPhone or Android. Maybe these only have neutral cultures. Also wouldn't it make more sense to return de-DE for "de", or fr-FR for fr  etc. instead of an exception ?

I don't have the information on which device or the full stacktrace, only @anuruddhar can give you that, I only have [the information in issue 46 in PdfSharpCore](https://github.com/ststeiger/PdfSharpCore/issues/46).

**Comment by steveisok** [comment]
If you guys can give me the device info / stacktrace like you're saying, then I can assess whether we can / should do something about it at the mono level.

**Comment by bondarei** [comment]
Hi guys,

I've got a similar issue. It happened during automated testing on the Google Play Console.  

Device specifications
Model name moto e5 play
Manufacturer Motorola
Android Version (SDK) Android 8.1 (SDK 27)
Locale ru
Screen size 480 x 960
Screen density (DPI) 240
RAM (total memory) 1,024 MB
OpenGL ES version 0.3
ABI ARM_V7
CPU Qualcomm MSM8917

FATAL EXCEPTION: Thread-3
Process: de.bigor.SmartTimeTracker, PID: 12757
android.runtime.JavaProxyThrowable: System.NotImplementedException: Neutral region info
  at System.Globalization.RegionInfo..ctor (System.Globalization.CultureInfo ci) [0x00083] in <9576f251dd9b41fba4db154fca1d0a62>:0 
  at System.Globalization.RegionInfo.get_CurrentRegion () [0x00012] in <9576f251dd9b41fba4db154fca1d0a62>:0 
  at PdfSharpCore.Pdf.PdfPage.Initialize () [0x00000] in <bb498c539002416aab2c6f62525b05f6>:0 
  at PdfSharpCore.Pdf.PdfPage..ctor () [0x00026] in <bb498c539002416aab2c6f62525b05f6>:0 
  at PdfSharpCore.Pdf.PdfPages.Add () [0x00000] in <bb498c539002416aab2c6f62525b05f6>:0 
  at PdfSharpCore.Pdf.PdfDocument.AddPage () [0x0001e] in <bb498c539002416aab2c6f62525b05f6>:0 
  at Bigor.SmartTimeTracker.Services.PdfExporter.AddSummaryPage (System.String title, System.TimeSpan total, System.String firstColumnHeaderName, System.Collections.Generic.IEnumerable`1[T] entries, System.Nullable`1[T] pageInfo) [0x00009] in <6ee245a0050c4d53a809d08e9082b4bc>:0 
  at Bigor.SmartTimeTracker.Services.PdfExporter.AddSummaryPage (System.String title, System.TimeSpan totalTime) [0x0000e] in <6ee245a0050c4d53a809d08e9082b4bc>:0 
  at Bigor.SmartTimeTracker.Services.PdfExporter.ExportAsync (Bigor.SmartTimeTracker.ViewModels.MonthDetailViewModel monthDetailViewModel, System.Func`2[T,TResult] errorHandler, System.Boolean isSafeRequested, System.Nullable`1[T] pageInfo) [0x0003e] in <6ee245a0050c4d53a809d08e9082b4bc>:0 
  at Bigor.SmartTimeTracker.Views.MonthDetailPage.<OnExport>b__15_0 () [0x00092] in <6ee245a0050c4d53a809d08e9082b4bc>:0 
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <9576f251dd9b41fba4db154fca1d0a62>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <8b3b769b8a3a4891bca0c3b553881f0e>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <8b3b769b8a3a4891bca0c3b553881f0e>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <8b3b769b8a3a4891bca0c3b553881f0e>:0 
  at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.18(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
	at androidx.test.espresso.action.Tap.b(Unknown Source:9)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:137)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6647)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by bondarei** [comment]
@steveisok Did you have a chance to look into the issue?

**Comment by rubiomiguel06** [comment]
I am having the same issue as @bondarei on an iPad Pro simulator

**Comment by mikernet** [comment]
Running into this in Xamarin as well. What is the correct way to do something like `RegionInfo.CurrentRegion.TwoLetterISORegionName` from Xamarin?
