### ISSUE TITLE
Fatal error in IL Linker:Failed to resolve Microsoft.Extensions.Logging.Abstractions.Internal.NullScope

### ISSUE THREAD

**Issue by mkArtakMSFT** [mono/mono#16063]
_From @ar0311 on Monday, August 5, 2019 9:47:44 PM_

### Describe the bug
Possibly related to #10651 

When compiling a Blazor Client app in a Hosted Blazor solution with references to Identity in the Shared project, compilation fails. In my case, using RavenDB.Identity in the Shared project (referenced by the Client project) pulls in the Identity references.

Manually adding a PackageReference in the Client project csproj to Microsoft.Extensions.Logging results in successful compilation

### To Reproduce
1. Using preview 7
2. Repro git repository [here](https://github.com/ar0311/blazor_IL_error) 
3. Run dotnet restore && dotnet run (server project)
4. See error output

Example: 

_Fatal error in IL Linker
  Unhandled exception. Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in assembly: 'Microsoft.Extensions.Logging.dll'
   ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Logging.Abstractions.Internal.NullScope Microsoft.Extensions.Logging.Abstractions.Internal.NullScope::get_Instance()
     at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
     at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
     at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
     at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
     at Mono.Linker.Steps.MarkStep.ProcessQueue()_

### Expected behavior
Successful compilation.

_Copied from original issue: aspnet/AspNetCore#12894_

**Comment by ar0311** [comment]
The 10651 referred to is the issue in the aspnet/AspNetCore repo, not mono's.

**Comment by ar0311** [comment]
After some more playing around, adding the following to the Blazor Client project results in a successful compilation, although obviously a much larger publish size.

`<BlazorLinkOnBuild>false</BlazorLinkOnBuild>`

Also, might it be related to [this](https://github.com/mono/mono/issues/12917)?

**Comment by ar0311** [comment]
Issue still exists in preview 8.

**Comment by ar0311** [comment]
Wasm error output in Chrome console:

`
blazor.webassembly.js:1 Uncaught (in promise) Error: Could not find method "EndInvokeJS" on type "Mono.WebAssembly.Interop.MonoWebAssemblyJSRuntime"
    at g (blazor.webassembly.js:1)
    at blazor.webassembly.js:1
    at callRuntimeCallbacks (mono.js:1)
    at postRun (mono.js:1)
    at doRun (mono.js:1)
    at run (mono.js:1)
    at runCaller (mono.js:1)
    at removeRunDependency (mono.js:1)
    at blazor.webassembly.js:1`

**Comment by Z3roCoder** [comment]
I am getting the same error. What can I do about it?

**Comment by ar0311** [comment]
Still refuses to compile the Client project under preview 9 without referencing Microsoft.Extensions.Logging in the csproj file. Wasm error seems to be gone now.

**Comment by ar0311** [comment]
Still exists on rc1... (Using updated preview9 blazor packages per rc1 release notes)

**Comment by kjpou1** [comment]
Is this still a valid issue using the current Blazor preview?

**Comment by Cheesebaron** [comment]
This is also valid when consumed in a Xamarin Android project.

Mono Framework MDK
Runtime:
	Mono 6.6.0.155 (2019-08/296a9afdb24) (64-bit)
	Package version: 606000155

**Comment by Cheesebaron** [comment]
Is anyone looking into this?

**Comment by vargaz** [comment]
This seems to be caused by mismatching assemblies, i.e. Microsoft.Extensions.Logging.dll
contains the following IL code:
    IL_000a:  call       [Microsoft.Extensions.Logging.Abstractions]Microsoft.Extensions.Logging.Abstractions.Internal.NullScope [Microsoft.Extensions.Logging.Abstractions]Microsoft.Extensions.Logging.Abstractions.Internal.NullScope::get_Instance()

but the  Microsoft.Extensions.Logging.Abstractions assembly doesn't have a type named
Microsoft.Extensions.Logging.Abstractions.Internal.NullScope, it has a type named  simply
Microsoft.Extensions.Logging.NullScope.

**Comment by Cheesebaron** [comment]
@vargaz thank you for your reply. I will investigate on my end, you are most likely right that some library is pulling in an older version or something. Although I would have never gathered that from this error.

**Comment by americanslon** [comment]
So this happened to me out of the blue...Anything I can do? Is this being looked at? Is this even a bug?

**Comment by vargaz** [comment]
It happens because mismatching assemblies are being passed to the linker.

**Comment by americanslon** [comment]
How would I troubleshoot that? It happened seemingly out of the blue.

**Comment by vargaz** [comment]
Its a problem with the build system/IDE/nuget etc. Its not a mono bug.

**Comment by Cheesebaron** [comment]
I fixed it by ensuring that every library I consumed was on the same major version of the Microsoft.Extensions.Logging.Abstractions package. Had a dependency on [Serilog.Extensions.Logging](https://www.nuget.org/packages/Serilog.Extensions.Logging) which pulled in an old version of Microsoft.Extensions.Logging in and in turn grabbed and old version of the Abstractions package.

Since we have no way of checking transitive packages easily with Xamarin projects it is a bit of a cumbersome task to do. But perhaps check your log from restoring packages and see if there are any downgrades there.

**Comment by shadow-cs** [comment]
Possibly related to mono/linker#858

**Comment by EnglishDave** [comment]
This problem also occurs when using Microsft.Bot.Connector.DirectLine 3.0.3-Preview1 (references Microsoft.Extensions.Logging 2.1.1)  with Microsoft.Extensions.Caching.Memory 3.1.7 (references Microsoft.Extensions.Logging.Abstractions 3.1.7) , specifically for Android projects built using an AzureDevOps pipeline. We see the exception, presumably because of the same mismatch, however this builds and runs successfully when built on Visual Studio (Windows or Mac), so it can be surmised that the VS build system successfully handles the mismatch (or at least handles the exception gracefully), whereas the build system used by the AzDevOps pipeline does not.

**Comment by alexanderdibenedetto** [comment]
Is this fixed or is there a workaround available? @Cheesebaron since the changes to MVVMCross 8.0 to use this library (version 5.0+), do you have any recommendations to get around the above while using Serilog (which pulls in 2.0.0)?

**Comment by amirvenus** [comment]
I am having the exact same issue using JetBrains Rider so I guess only Visual Studio knows how to [gracefully] handle this.

**Comment by gabriele-ricci-kyklos** [comment]
It is a problem related to different versions used of `Microsoft.Extensions.Logging`.
In my case, I was building a Xamarin.Forms app having a starter project in Android, and a .NET Standard project with all the logic. It worked fine in Debug, but presented the issue when building in release mode.
The error I was getting was:
```
Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Logger::BeginScope(TState)' in assembly: 'Microsoft.Extensions.Logging.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.Extensions.Logging.Abstractions.Internal.NullScope Microsoft.Extensions.Logging.Abstractions.Internal.NullScope::get_Instance()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.RunTask()
   at Microsoft.Android.Build.Tasks.AndroidTask.Execute() in /Users/builder/azdo/_work/1/s/xamarin-android/external/xamarin-android-tools/src/Microsoft.Android.Build.BaseTasks/AndroidTask.cs:line 17	WMS.Mobile.Android			
```
To troubleshoot this, you need to look at the `{project_name}.deps.json` file of the .NET Standard project, checking for different versions of `Microsoft.Extensions.Logging`.
In my case I found that the `NLog` package was using a different version than all other packages, so I removed it and manually installed the latest version of `Microsoft.Extensions.Logging` and then reinstalled `NLog`, I was then able to build in release mode.

**Comment by ToolmakerSteve** [comment]
I just had this happen on a Xamarin.Forms iOS **iPhone** Release build.  
For me, did NOT happen on **Android** Release build. Nor on **iPhoneSimulator** Release build.  Nor on **iPhone** Debug build.

Manage Nugets / Install / Microsoft.Extensions.Logging 6.0.0 did eliminate that exception. (I didn't uninstall/reinstall any other nugets).

NOTE: The build crashes when launched (ONLY on iPhone Release), so its possible adding that Logging Nuget version caused some other problem.
