### ISSUE TITLE
vb net application crash on raspberry pi 3

### ISSUE THREAD

**Issue by migu-el** [mono/mono#16255]
I am developing a vb.net  to deploy into Raspberry pi 3, the programing stage i do in my windows local machine, testing the conectivity to Informix via ODBC.

The issue occurs when deploy in raspberry pi(all odc prerrquisites has been completed,i did use isql tool to get some data from the informix database and is ok). The first call to the sub that retrieve the data and fill a grid is ok, but with the next hit the application crash.

## Steps to Reproduce

1. Test in my windows  + .net the application for get records from the database and is ok.
2. Copy the applicationgenerated.exe to raspberry pi appropiated folder
3. use 'mono applicationgenerated.exe' to open the app.
4. the application open fine
5. hit the button to get the data from informix, the data is retrieved fine.
6. but the aplication crash(see Stacktrace) with the next hit over the button(i use a button to call a sub routine).

### Using the exact sample code for get the data in the mono odbc site:
https://www.mono-project.com/docs/database-access/providers/odbc/

## On which platforms did you notice this
[x] Raspberry pi 3 with raspbian

**Dot net framework**:
4.0
Mono version 5.18.0.240

## Stacktrace

```
free(): invalid pointer
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) Interop/Odbc.SQLFreeHandle (System.Data.Odbc.ODBC32/SQL_HANDLE,intptr) <0x0003b>
  at System.Data.Odbc.OdbcHandle.ReleaseHandle () [0x00046] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Runtime.InteropServices.SafeHandle.DangerousReleaseInternal (bool) [0x000d3] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
  at System.Runtime.InteropServices.SafeHandle.InternalDispose () [0x00011] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
  at System.Runtime.InteropServices.SafeHandle.Dispose (bool) [0x00006] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
  at System.Runtime.InteropServices.SafeHandle.Dispose () [0x00000] in <d0e12f672b88444ab4b6d9b2ecf20142>:0
  at System.Data.Odbc.CMDWrapper.DisposeStatementHandle () [0x00020] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.CMDWrapper.Dispose () [0x0001d] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.OdbcCommand.CloseCommandWrapper () [0x0000d] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.OdbcCommand.CloseFromConnection () [0x0001d] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at (wrapper remoting-invoke-with-check) System.Data.Odbc.OdbcCommand.CloseFromConnection () [0x00031] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.OdbcReferenceCollection.NotifyItem (int,int,object) [0x00036] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.ProviderBase.DbReferenceCollection.Notify (int) [0x00057] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.ProviderBase.DbConnectionInternal.NotifyWeakReference (int) [0x0000d] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.OdbcConnectionOpen.Deactivate () [0x00000] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.ProviderBase.DbConnectionInternal.CloseConnection (System.Data.Common.DbConnection,System.Data.ProviderBase.DbConnectionFactory) [0x0004b] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at System.Data.Odbc.OdbcConnection.Close () [0x0000d] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at (wrapper remoting-invoke-with-check) System.Data.Odbc.OdbcConnection.Close () [0x00031] in <b59fd34ba7374187bed3adc0962b9cc7>:0
  at ChivusIOTCommon.Form1.datox () [0x000bd] in <a8f7802a366845aba9fcab3722e09ec1>:0
  at ChivusIOTCommon.Form1.Button1_Click (object,System.EventArgs) [0x00002] in <a8f7802a366845aba9fcab3722e09ec1>:0
  at System.Windows.Forms.Control.OnClick (System.EventArgs) [0x0001c] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Button.OnClick (System.EventArgs) [0x00024] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.ButtonBase.OnMouseUp (System.Windows.Forms.MouseEventArgs) [0x00081] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs) [0x00000] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message&) [0x0007e] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message&) [0x0016f] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message&) [0x0004e] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message&) [0x00000] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Control/ControlWindowTarget.OnMessage (System.Windows.Forms.Message&) [0x00000] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Control/ControlNativeWindow.WndProc (System.Windows.Forms.Message&) [0x0000b] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.NativeWindow.WndProc (intptr,System.Windows.Forms.Msg,intptr,intptr) [0x0008e] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.XplatUIX11.DispatchMessage (System.Windows.Forms.MSG&) [0x00000] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.XplatUI.DispatchMessage (System.Windows.Forms.MSG&) [0x00000] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) [0x0037b] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) [0x00014] in <0e1823914d7643eeaf1207febb083a4a>:0
  at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) [0x00006] in <0e1823914d7643eeaf1207febb083a4a>:0
  at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun () [0x00041] in <e53be19db18d43719d7c9eeb850ba902>:0
  at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Run (string[]) [0x00001] in <e53be19db18d43719d7c9eeb850ba902>:0
  at ChivusIOTCommon.My.MyApplication.Main (string[]) [0x00017] in <a8f7802a366845aba9fcab3722e09ec1>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) [0x0004e] in <a8f7802a366845aba9fcab3722e09ec1>:0
/proc/self/maps:
00010000-003d7000 r-xp 00000000 b3:02 50541      /usr/bin/mono-sgen
003e6000-003ea000 r--p 003c6000 b3:02 50541      /usr/bin/mono-sgen
003ea000-003ee000 rw-p 003ca000 b3:02 50541      /usr/bin/mono-sgen
003ee000-00474000 rw-p 00000000 00:00 0 
01bef000-023de000 rw-p 00000000 00:00 0          [heap]
718dd000-7190d000 rwxp 00000000 00:00 0 
7190d000-7192d000 r--p 00000000 b3:02 254445     /usr/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll
7192d000-71931000 r-xp 00000000 b3:02 2035       /lib/arm-linux-gnueabihf/libnss_dns-2.28.so
71931000-71940000 ---p 00004000 b3:02 2035       /lib/arm-linux-gnueabihf/libnss_dns-2.28.so
71940000-71941000 r--p 00003000 b3:02 2035       /lib/arm-linux-gnueabihf/libnss_dns-2.28.so
71941000-71942000 rw-p 00004000 b3:02 2035       /lib/arm-linux-gnueabihf/libnss_dns-2.28.so
71942000-71944000 r-xp 00000000 b3:02 2040       /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
71944000-71953000 ---p 00002000 b3:02 2040       /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
71953000-71954000 r--p 00001000 b3:02 2040       /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
71954000-71955000 rw-p 00002000 b3:02 2040       /lib/arm-linux-gnueabihf/libnss_mdns4_minimal.so.2
71959000-71969000 rwxp 00000000 00:00 0 
71969000-71970000 r-xp 00000000 b3:02 2002       /lib/arm-linux-gnueabihf/libcrypt-2.28.so
71970000-71980000 ---p 00007000 b3:02 2002       /lib/arm-linux-gnueabihf/libcrypt-2.28.so
71980000-71981000 r--p 00007000 b3:02 2002       /lib/arm-linux-gnueabihf/libcrypt-2.28.so
71981000-71982000 rw-p 00008000 b3:02 2002       /lib/arm-linux-gnueabihf/libcrypt-2.28.so
71982000-719a9000 rw-p 00000000 00:00 0 
719ac000-719b0000 rw-p 00000000 00:00 0 
719b1000-719b5000 r-xp 00000000 b3:02 257376     /opt/ibm/informix/lib/esql/igo4a304.so
719b5000-719bc000 ---p 00004000 b3:02 257376     /opt/ibm/informix/lib/esql/igo4a304.so
719bc000-719bd000 rw-p 00003000 b3:02 257376     /opt/ibm/informix/lib/esql/igo4a304.so
Memory around native instruction pointer (0x76cd3f24):
0x76cd3f14  00 20 a0 e3 08 30 a0 e3 af 70 a0 e3 00 00 00 ef  . ...0...p......
0x76cd3f24  04 21 9d e5 00 30 94 e5 0c 00 a0 e1 03 00 52 e1  .!...0........R.
0x76cd3f34  08 00 00 1a 43 df 8d e2 f0 80 bd e8 24 30 9f e5  ....C.......$0..
0x76cd3f44  00 20 60 e2 e8 ae ff eb 03 30 9f e7 00 c0 e0 e3  . `......0......

Native stacktrace:

Pkilling 0x7676b460 from 0x76f4e250
Pkilling 0x7203f460 from 0x76f4e250
Entering thread summarizer pause from 0x76f4e250
Finished thread summarizer pause from 0x76f4e250.

Waiting for dumping threads to resume


Debug info from gdb:

[New LWP 966]
[New LWP 967]
[New LWP 968]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__waitpid (options=0, stat_loc=0x7ebdb498, pid=970) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                     Frame 
* 1    Thread 0x76f4e250 (LWP 965) "mono"            __waitpid (options=0, stat_loc=0x7ebdb498, pid=970) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x75fff460 (LWP 966) "SGen worker"     futex_wait_cancelable (private=0, expected=0, futex_word=0x3f8c58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7676b460 (LWP 967) "Finalizer"       0x76e33088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x3f0ee0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
  4    Thread 0x7203f460 (LWP 968) "Timer-Scheduler" futex_reltimed_wait_cancelable (private=0, reltime=0x7203e3e8, expected=0, futex_word=0x1befd48) at ../sysdeps/unix/sysv/linux/futex-internal.h:142

Thread 4 (Thread 0x7203f460 (LWP 968)):
#0  futex_reltimed_wait_cancelable (private=0, reltime=0x7203e3e8, expected=0, futex_word=0x1befd48) at ../sysdeps/unix/sysv/linux/futex-internal.h:142
#1  __pthread_cond_wait_common (abstime=0x7203e464, mutex=0x2, cond=0x1befd20) at pthread_cond_wait.c:533
#2  __pthread_cond_timedwait (cond=0x1befd20, mutex=0x2, abstime=0x7203e464) at pthread_cond_wait.c:667
#3  0x002fda8c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0x7676b460 (LWP 967)):
#0  0x76e33088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0x3f0ee0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x3f0ee0, abstime=0x0) at sem_waitcommon.c:115
#2  0x76e331f4 in __new_sem_wait_slow (sem=0x3f0ee0, abstime=0x0) at sem_waitcommon.c:282
#3  0x00281488 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x75fff460 (LWP 966)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x3f8c58) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0x3f8c30) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x3f8c30, mutex=0x0) at pthread_cond_wait.c:655
#3  0x002ed600 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76f4e250 (LWP 965)):
#0  __waitpid (options=0, stat_loc=0x7ebdb498, pid=970) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=970, stat_loc=0x7ebdb498, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0x0010225c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 965) detached]

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

```
Any ideas or suggestions are great appreciated.

**Comment by marek-safar** [comment]
It's quite possible that Odbc wrapper is Windows specific

**Comment by migu-el** [comment]
Thanks!, I will try coding in the raspberry device with mono developer ide.

**Comment by migu-el** [comment]
The same issue is produced when generate a exe with the mono native compiler in the Raspberry device with a plain cs file....

Any suggestions?
