### ISSUE TITLE
[netcore] Could not load type _proxy_System.ComponentModel.Composition.*

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16417]
A lot of tests under `System.ComponentModel.Composition` fail time to time (flaky) with:
```
System.NotSupportedException : Interface 
'System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata' is not a valid 
MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain 
members that are not properties.\n---- System.TypeLoadException : Could not load type 
'_proxy_System.ComponentModel.Composition.ScopeExportFactoryTests+IFooMetadata_c9015c58-24c6-46dc-969a-d1740364c90d' from assembly ''.

at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IMetadataView](IDictionary`2 metadata)
   at System.ComponentModel.Composition.AttributedModelServices.GetMetadataView[IMetadataView](IDictionary`2 metadata)
   at System.ComponentModel.Composition.ExportServices.CreateStronglyTypedLazyOfTM[OptionalFooIsInt,IMetadataView](Export export)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore[OptionalFooIsInt,IMetadataView](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[OptionalFooIsInt,IMetadataView](String contractName)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports[OptionalFooIsInt,IMetadataView]()
   at System.ComponentModel.Composition.MetadataTests.TestOptionalMetadataValueTypeMismatch()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
----- Inner Stack Trace -----
   at System.RuntimeType.GetMethodsByName(String name, BindingFlags bindingAttr, MemberListType listType, RuntimeType reflectedType)
   at System.RuntimeType.GetMethodCandidates(String name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, Int32 genericParamCount, Boolean allowPrefixLookup)
   at System.RuntimeType.GetMethodImpl(String name, Int32 genericParamCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at System.ComponentModel.Composition.MetadataViewGenerator.GetMetadataViewFactory(Type viewType)
   at System.ComponentModel.Composition.MetadataViewProvider.GetMetadataView[IMetadataView](IDictionary`2 metadata)
```
Or e.g.
```
System.NotSupportedException : Interface 'System.ComponentModel.Composition.IMetadataView' is not a valid MetadataView; MetadataViews do not support non-public interfaces, and interfaces that contain members that are not properties.\n---- System.TypeLoadException : Could not load type '_proxy_System.ComponentModel.Composition.IMetadataView_a4b5585e-64c3-444d-9181-04a8d1ef7bf1' from assembly ''.
```

**Comment by lambdageek** [comment]
I built a runtime that hard asserts in `ghashtable.c`

```
* Assertion at /Users/alklig/work/dotnet-runtime/runtime/src/mono/mono/eglib/ghashtable.c:336, condition `hash != NULL' not met
```

The issue seems to be some concurrency problem in System.Reflection.Emit

```
 bt
* thread #19, name = 'tid_4803'
  * frame #0: 0x00007fff202fe7b6 libsystem_kernel.dylib`__semwait_signal + 10
    frame #1: 0x00007fff2027bc92 libsystem_c.dylib`nanosleep + 196
    frame #2: 0x0000000104b97a03 libcoreclr.dylib`monoeg_g_usleep(microseconds=1000000) at gdate-unix.c:78:9
    frame #3: 0x0000000104f56e19 libcoreclr.dylib`mono_handle_native_crash(signal="SIGABRT", mctx=0x000070000e8ccb08, info=0x000070000e8cd0e8) at mini-exceptions.c:3434:4
    frame #4: 0x00000001050588e3 libcoreclr.dylib`sigabrt_signal_handler(_dummy=6, _info=0x000070000e8cd0e8, context=0x000070000e8cd150) at mini-posix.c:234:4
    frame #5: 0x00007fff20374d7d libsystem_platform.dylib`_sigtramp + 29
    frame #6: 0x00007fff20302463 libsystem_kernel.dylib`__pthread_kill + 11
    frame #7: 0x00007fff20330610 libsystem_pthread.dylib`pthread_kill + 263
    frame #8: 0x00007fff20283720 libsystem_c.dylib`abort + 120
    frame #9: 0x0000000104b9f462 libcoreclr.dylib`monoeg_assert_abort at goutput.c:57:3
    frame #10: 0x0000000104d2ec7e libcoreclr.dylib`mono_log_write_logfile(log_domain=0x0000000000000000, level=G_LOG_LEVEL_ERROR, hdr=0, message="* Assertion at /Users/alklig/work/dotnet-runtime/runtime/src/mono/mono/eglib/ghashtable.c:336, condition `hash != NULL' not met\n") at mono-log-common.c:136:3
    frame #11: 0x0000000104d2a191 libcoreclr.dylib`structured_log_adapter(log_domain=0x0000000000000000, log_level=G_LOG_LEVEL_ERROR, message="* Assertion at /Users/alklig/work/dotnet-runtime/runtime/src/mono/mono/eglib/ghashtable.c:336, condition `hash != NULL' not met\n", user_data=0x0000000000000000) at mono-logger.c:474:2
    frame #12: 0x0000000104ba019a libcoreclr.dylib`monoeg_g_logstr(log_domain=0x0000000000000000, log_level=G_LOG_LEVEL_ERROR, msg="* Assertion at /Users/alklig/work/dotnet-runtime/runtime/src/mono/mono/eglib/ghashtable.c:336, condition `hash != NULL' not met\n") at goutput.c:151:2
    frame #13: 0x0000000104b9fb7b libcoreclr.dylib`monoeg_g_logv_nofree(log_domain=0x0000000000000000, log_level=G_LOG_LEVEL_ERROR, format="* Assertion at %s:%d, condition `%s' not met\n", args=0x000070000e8cd5b0) at goutput.c:166:2
    frame #14: 0x0000000104b9fef8 libcoreclr.dylib`monoeg_assertion_message(format="* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:207:22
    frame #15: 0x0000000104b9ff6c libcoreclr.dylib`mono_assertion_message(file="/Users/alklig/work/dotnet-runtime/runtime/src/mono/mono/eglib/ghashtable.c", line=336, condition="hash != NULL") at goutput.c:226:2
    frame #16: 0x0000000104b9a4ad libcoreclr.dylib`monoeg_g_hash_table_lookup_extended(hash=0x0000000000000000, key=0x00007f87af827860, orig_key=0x000070000e8cd670, value=0x000070000e8cd668) at ghashtable.c:336:2
    frame #17: 0x0000000104b9a5a5 libcoreclr.dylib`monoeg_g_hash_table_lookup(hash=0x0000000000000000, key=0x00007f87af827860) at ghashtable.c:322:6
    frame #18: 0x0000000104cd2886 libcoreclr.dylib`reflection_setup_internal_class_internal(ref_tb=MonoReflectionTypeBuilderHandle @ 0x000070000e8cd8c8, error=0x000070000e8cdfc8) at sre.c:2796:2
    frame #19: 0x0000000104cc764a libcoreclr.dylib`reflection_setup_internal_class(ref_tb=MonoReflectionTypeBuilderHandle @ 0x000070000e8cdbf0, error=0x000070000e8cdfc8) at sre.c:3969:13
    frame #20: 0x0000000104ccadd9 libcoreclr.dylib`ves_icall_TypeBuilder_create_runtime_class(ref_tb=MonoReflectionTypeBuilderHandle @ 0x000070000e8cde08, error=0x000070000e8cdfc8) at sre.c:3994:2
    frame #21: 0x0000000104c2bada libcoreclr.dylib`ves_icall_TypeBuilder_create_runtime_class_raw(a0=0x000070000e8ce0a0) at icall-def-netcore.h:237:1
```

We should not be getting a null `unparented_classes` hash unless two threads are calling into this SRE stuff at the same time.
