### ISSUE TITLE
[netcore] ReferenceTypes_NulledAfterDequeue fails in Release mode

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#16413]
Fails on Linux CI (after we switched to Release for runtime in https://github.com/mono/mono/pull/16329)
`System.Collections.Concurrent.Tests.ConcurrentQueueTests.ReferenceTypes_NulledAfterDequeue`
```
Assert.True() Failure\nExpected: True\nActual: False
 at System.Collections.Concurrent.Tests.ConcurrentQueueTests.ReferenceTypes_NulledAfterDequeue()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by EgorBo** [comment]
Ah, it's actually the Precise GC issue

**Comment by MaximLipnin** [comment]
Now it occurs in runtime CI. Reopening it
