### ISSUE TITLE
[wasm] Roslyn's AdhocWorkspace fails to init

### ISSUE THREAD

**Issue by scabana** [mono/mono#16462]
## Steps to Reproduce

1. Create a new console netstandard2.0 project MonoWasmSample
2. Reference ```<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.10" />```
3. Add this code to Main method: 
    ```csharp
    var workspace = new AdhocWorkspace();

    string projName = "NewProject";
    var projectId = ProjectId.CreateNewId();
    var versionStamp = VersionStamp.Create();
    var projectInfo = ProjectInfo.Create(projectId, versionStamp, projName, projName,     LanguageNames.CSharp);

    var newProject = workspace.AddProject(projectInfo);
    var sourceText = SourceText.From("public class SomeClass{    \r\n     public string Some{get;        set;}   }");
    var newDocument = workspace.AddDocument(newProject.Id, "NewFile.cs", sourceText);

    foreach (var project in workspace.CurrentSolution.Projects)
    {
     foreach (var document in project.Documents)
      {
        Formatter.FormatAsync(document).Wait();
        Console.WriteLine(document.GetTextAsync().Result);
      }
    }
    ```
1. use dotnet publish to output application
1. run ```packager.exe --copy=always --out=./publish MonoWasmSample.dll --copy=always``` on the output from previous step
1. Add app.js file to the publish folder: 
    ```javascript
    var App = {
        onClick: function () {
            this.output.value = "...";
            var res = this.int_add (1, 2);
            this.output.value = res;
        },
        init: function () {
            // initialize geolocation sample
            BINDING.call_static_method("[MonoWasmSample] MonoWasmSample.Program:Main", []);
        },
    };

    var fs = require('fs');

    // file is included here:
    eval(fs.readFileSync('mono-config.js')+'');
    eval(fs.readFileSync('runtime.js')+'');
    eval(fs.readFileSync('mono.js')+'');
    ```
1. Run ```node app.js```
1. Get exception: 
    ```
    Error: System.TypeLoadException: Could not load type of field 'Roslyn.Utilities.SemaphoreExtensions+<>c__DisplayClass1_0:semaphore' (0) due to: Could not resolve type with token 0100008a from typeref (expected class 'System.Threading.Semaphore' in assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Threading.Semaphore member:(null)
    ```

### Current Behavior

Crashes.

### Expected Behavior

For it to work! :)

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

dotnet --version: 2.2.401 (didn't try mono compile here, but a Console.WriteLine sample works with the dotnet output)
node --version: v12.7.0
webassembly sdk: https://jenkins.mono-project.com/job/test-mono-mainline-wasm/label=ubuntu-1804-amd64/lastSuccessfulBuild/Azure/

## Stacktrace

```
initializing mono runtime
>>mono_wasm_runtime_ready
Error: System.TypeLoadException: Could not load type of field 'Roslyn.Utilities.SemaphoreExtensions+<>c__DisplayClass1_0:semaphore' (0) due to: Could not resolve type with token 0100008a from typeref (expected class 'System.Threading.Semaphore' in assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Threading.Semaphore member:(null)
  at (wrapper managed-to-native) System.RuntimeType.GetPropertiesByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,System.RuntimeType/MemberListType)
  at System.RuntimeType.GetPropertiesByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.RuntimeType+MemberListType listType, System.RuntimeType reflectedType) <0x30c1c60 + 0x00078> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.RuntimeType.GetPropertyCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Type[] types, System.Boolean allowPrefixLookup) <0x30c1890 + 0x00032> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.RuntimeType.GetProperties (System.Reflection.BindingFlags bindingAttr) <0x30c14f8 + 0x00010> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperties (System.Type type) <0x30bebe0 + 0x00036> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.Composition.TypedParts.Discovery.TypeInspector+<DiscoverPropertyExports>d__7.MoveNext () <0x30be798 + 0x00056> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.Discovery.TypeInspector+<DiscoverExports>d__5.MoveNext () <0x30b7350 + 0x00162> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart (System.Reflection.TypeInfo type, System.Composition.TypedParts.Discovery.DiscoveredPart& part) <0x2e02378 + 0x000cc> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor (System.Collections.Generic.IEnumerable`1[T] types, System.Composition.Convention.AttributedModelProvider attributeContext) <0x2dcafd0 + 0x00076> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.Hosting.ContainerConfiguration.CreateContainer () <0x2dc9f48 + 0x000a6> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create (System.Collections.Generic.IEnumerable`1[T] assemblies) <0x2dab1a0 + 0x000e2> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.get_DefaultHost () <0x2d32858 + 0x0001e> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at Microsoft.CodeAnalysis.AdhocWorkspace..ctor () <0x2d32508 + 0x00004> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at MonoWasmSample.Program.Main (System.String[] args) <0x2d32120 + 0x00002> in <77f277530ec844dda428b8da585a3b23>:0
    at Object.call_method (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:164931)
    at Object.call_static_method (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:166784)
    at Object.init (D:\Playground\MonoWasmSample\publish\app.js:14:17)
    at eval (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:30:1), <anonymous>:10:8)
    at eval (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:146137)
Error: System.TypeLoadException: Could not load type of field 'Roslyn.Utilities.SemaphoreExtensions+<>c__DisplayClass1_0:semaphore' (0) due to: Could not resolve type with token 0100008a from typeref (expected class 'System.Threading.Semaphore' in assembly 'System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a') assembly:System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a type:System.Threading.Semaphore member:(null)
  at (wrapper managed-to-native) System.RuntimeType.GetPropertiesByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,System.RuntimeType/MemberListType)
  at System.RuntimeType.GetPropertiesByName (System.String name, System.Reflection.BindingFlags bindingAttr, System.RuntimeType+MemberListType listType, System.RuntimeType reflectedType) <0x30c1c60 + 0x00078> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.RuntimeType.GetPropertyCandidates (System.String name, System.Reflection.BindingFlags bindingAttr, System.Type[] types, System.Boolean allowPrefixLookup) <0x30c1890 + 0x00032> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.RuntimeType.GetProperties (System.Reflection.BindingFlags bindingAttr) <0x30c14f8 + 0x00010> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.Reflection.RuntimeReflectionExtensions.GetRuntimeProperties (System.Type type) <0x30bebe0 + 0x00036> in <79f44548ff1c405296e9c8c8fb3fc6ab>:0
  at System.Composition.TypedParts.Discovery.TypeInspector+<DiscoverPropertyExports>d__7.MoveNext () <0x30be798 + 0x00056> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.Discovery.TypeInspector+<DiscoverExports>d__5.MoveNext () <0x30b7350 + 0x00162> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart (System.Reflection.TypeInfo type, System.Composition.TypedParts.Discovery.DiscoveredPart& part) <0x2e02378 + 0x000cc> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor (System.Collections.Generic.IEnumerable`1[T] types, System.Composition.Convention.AttributedModelProvider attributeContext) <0x2dcafd0 + 0x00076> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at System.Composition.Hosting.ContainerConfiguration.CreateContainer () <0x2dc9f48 + 0x000a6> in <9aac21a4a3f24063b2b8b59143acddfc>:0
  at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create (System.Collections.Generic.IEnumerable`1[T] assemblies) <0x2dab1a0 + 0x000e2> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.get_DefaultHost () <0x2d32858 + 0x0001e> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at Microsoft.CodeAnalysis.AdhocWorkspace..ctor () <0x2d32508 + 0x00004> in <80e91370f0144e11bf42cd84c47ebd30>:0
  at MonoWasmSample.Program.Main (System.String[] args) <0x2d32120 + 0x00002> in <77f277530ec844dda428b8da585a3b23>:0
    at Object.call_method (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:164931)
    at Object.call_static_method (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:166784)
    at Object.init (D:\Playground\MonoWasmSample\publish\app.js:14:17)
    at eval (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:30:1), <anonymous>:10:8)
    at eval (eval at <anonymous> (D:\Playground\MonoWasmSample\publish\app.js:31:1), <anonymous>:1:146137)

```

## Why do this!
Trying to get the required stuff to write a vscode extension that runs .net and roslyn (primarily for formatting purposes) without having to run an out of process .net instance and write interprocess communication.

Thanks a lot!

**Comment by scabana** [comment]
Additional information, I was able to get it to work on Blazor WASM lastest preview. I had to add ```<PackageReference Include="sqlite-net-pcl" Version="1.6.258-beta" />``` for some reason. I guess I'm missing some linker information. 

Here the blazor build output: 
```
D:\Playground\BlazorWasm>dotnet build
Microsoft (R) Build Engine version 16.3.0-preview-19377-01+dd8019d9e for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 25.78 ms for D:\Playground\BlazorWasm\BlazorWasm.csproj.
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
  BlazorWasm -> D:\Playground\BlazorWasm\bin\Debug\netstandard2.0\BlazorWasm.dll
  Cannot find declaration of exported type 'System.Threading.Semaphore' from the assembly 'System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  Processing embedded resource linker descriptor: mscorlib.xml
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.ExecutionContext (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.ExecutionContext System.Threading.ExecutionContext::Capture()
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.ExecutionContext System.Threading.ExecutionContext::Capture(System.Threading.StackCrawlMark&,System.Threading.ExecutionContext/CaptureOptions)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.Interlocked (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Int32 System.Threading.Interlocked::CompareExchange(System.Int32&,System.Int32,System.Int32)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Int32 System.Threading.Interlocked::CompareExchange(System.Int32&,System.Int32,System.Int32,System.Boolean&)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Object System.Threading.Interlocked::CompareExchange(System.Object&,System.Object,System.Object)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Single System.Threading.Interlocked::CompareExchange(System.Single&,System.Single,System.Single)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Int64 System.Threading.Interlocked::CompareExchange(System.Int64&,System.Int64,System.Int64)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.IntPtr System.Threading.Interlocked::CompareExchange(System.IntPtr&,System.IntPtr,System.IntPtr)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Double System.Threading.Interlocked::CompareExchange(System.Double&,System.Double,System.Double)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of T System.Threading.Interlocked::CompareExchange(T&,T,T)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Int32 System.Threading.Interlocked::Exchange(System.Int32&,System.Int32)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Object System.Threading.Interlocked::Exchange(System.Object&,System.Object)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Single System.Threading.Interlocked::Exchange(System.Single&,System.Single)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Int64 System.Threading.Interlocked::Exchange(System.Int64&,System.Int64)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.IntPtr System.Threading.Interlocked::Exchange(System.IntPtr&,System.IntPtr)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Double System.Threading.Interlocked::Exchange(System.Double&,System.Double)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of T System.Threading.Interlocked::Exchange(T&,T)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.Monitor (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Void System.Threading.Monitor::Enter(System.Object)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Void System.Threading.Monitor::Enter(System.Object,System.Boolean&)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Void System.Threading.Monitor::Exit(System.Object)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.ManualResetEvent (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Void System.Threading.ManualResetEvent::.ctor(System.Boolean)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.SynchronizationLockException (Nothing).  Duplicate uses (Nothing)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Void System.Threading.SynchronizationLockException::.ctor(System.String)
  Duplicate preserve in resource mscorlib.xml in mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e of System.Threading.WasmRuntime (All).  Duplicate uses (All)
  Type Mono.ValueTuple has no fields to preserve
  Type System.Reflection.Assembly has no fields to preserve
  Output action:     Link assembly: BlazorWasm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
  Output action:     Save assembly: Microsoft.CodeAnalysis.Workspaces.resources, Version=3.2.0.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis.CSharp.Workspaces.resources, Version=3.2.0.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis.CSharp.resources, Version=3.2.0.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis.resources, Version=3.2.0.0, Culture=cs, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: System.Threading, Version=4.0.12.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Link assembly: mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
  Output action:     Save assembly: System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: System.Text.Encodings.Web, Version=4.0.4.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: System.Text.Encoding.CodePages, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Runtime.CompilerServices.Unsafe, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Reflection.TypeExtensions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Reflection.Emit.Lightweight, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Reflection.Emit.ILGeneration, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Reflection.Emit, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.ObjectModel, Version=4.0.13.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Numerics.Vectors, Version=4.1.4.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: System.Linq.Expressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Linq, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Composition.TypedParts, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Composition.Runtime, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Composition.Hosting, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Composition.Convention, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Composition.AttributedModel, Version=1.0.31.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.ComponentModel.Annotations, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Save assembly: System.Buffers, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: SQLitePCLRaw.core, Version=1.1.13.388, Culture=neutral, PublicKeyToken=1488e028ca7ab535
  Output action:     Save assembly: SQLitePCLRaw.batteries_v2, Version=1.1.13.388, Culture=neutral, PublicKeyToken=8226ea5df37bcae9
  Output action:     Save assembly: SQLitePCLRaw.batteries_green, Version=1.1.13.388, Culture=neutral, PublicKeyToken=a84b7dcfb1391f7f
  Output action:     Save assembly: SQLite-net, Version=1.6.258.0, Culture=neutral, PublicKeyToken=null
  Output action:     Save assembly: Mono.WebAssembly.Interop, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.JSInterop, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.Extensions.Primitives, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.Extensions.Options, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.Extensions.Logging.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.Extensions.DependencyInjection.Abstractions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.Extensions.DependencyInjection, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.CodeAnalysis.Workspaces, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis.CSharp.Workspaces, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis.CSharp, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.CodeAnalysis, Version=3.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:     Save assembly: Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Save assembly: Microsoft.AspNetCore.Metadata, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.AspNetCore.Components.Web, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.AspNetCore.Blazor.HttpClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.AspNetCore.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:     Save assembly: Microsoft.AspNetCore.Authorization, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
  Output action:   Delete assembly: netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:     Link assembly: System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
  Output action:     Link assembly: Mono.Security, Version=2.0.5.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
  Output action:     Link assembly: System.Xml, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
  Output action:     Link assembly: System.Numerics, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:     Link assembly: System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
  Output action:   Delete assembly: System.Data, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:   Delete assembly: System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
  Output action:   Delete assembly: System.IO.Compression, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:   Delete assembly: System.IO.Compression.FileSystem, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:     Link assembly: System.ComponentModel.Composition, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:     Link assembly: System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
  Output action:   Delete assembly: System.Transactions, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
  Output action:   Delete assembly: System.Web.Services, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:     Link assembly: System.Xml.Linq, Version=2.0.5.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:   Delete assembly: System.ServiceModel.Internals, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
  Output action:   Delete assembly: System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Reflection, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Collections.Concurrent, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Diagnostics.Tools, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Globalization, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Runtime.Extensions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Reflection.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.IO, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Reflection.Primitives, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Output action:   Delete assembly: System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
  Writing boot data to: D:\Playground\BlazorWasm\obj\Debug\netstandard2.0\blazor\blazor.boot.json
  Blazor Build result -> 70 files in D:\Playground\BlazorWasm\bin\Debug\netstandard2.0\dist
```

**Comment by scabana** [comment]
Oh well, easy solution, reference: ```<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="3.2.1" />``` and enjoy 😄 

Well, I think this will not be for nothing, I hope it can help the next person trying to run mono-wasm in nodejs !
