### ISSUE TITLE
[netcore] CI failure: Getting environment variables

### ISSUE THREAD

**Issue by filipnavara** [mono/mono#16607]
There was repeated failure on a test to get environment variables:

```
System.NullReferenceException : Object reference not set to an instance of an object
Stack trace
   at System.Collections.Hashtable.GetHash(Object key)
   at System.Collections.Hashtable.InitHash(Object key, Int32 hashsize, UInt32& seed, UInt32& incr)
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Collections.Hashtable.set_Item(Object key, Object value)
   at System.Environment.GetEnvironmentVariables()
   at System.Tests.GetEnvironmentVariable.CanGetAllVariablesIndividually()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

eg. https://dev.azure.com/dnceng/public/_build/results?buildId=331428&view=ms.vss-test-web.build-test-results-tab&runId=9708222&resultId=101131&paneView=debug

The [native code](https://github.com/mono/mono/blob/9db00e74950a5b9572dbcfb3c6403503ae5b236d/mono/metadata/icall.c#L7438-L7446) looks like it can produce an array that is bigger than it should be in some cases. This could affect non-netcore builds too.

**Comment by filipnavara** [comment]
Turns out, that the native code (eg. `ves_icall_System_Environment_InternalSetEnvironmentVariable`) uses the thread-unsafe native functions making the whole `Environment` class thread unsafe. Both CoreCLR and CoreRT explicitly copy the environment to prevent this issue.

**Comment by filipnavara** [comment]
Fixed by #16852

**Comment by dellis1972** [comment]
We are seeing a very similar error running under `mono` on CI (and occasionally locally).

```
System.NullReferenceException : Object reference not set to an instance of an object
at System.Collections.Hashtable.GetHash (System.Object key) [0x00015] in <08f46039e5064c628bf7795f9b970b7b>:0 
  at System.Collections.Hashtable.InitHash (System.Object key, System.Int32 hashsize, System.UInt32& seed, System.UInt32& incr) [0x00000] in <08f46039e5064c628bf7795f9b970b7b>:0 
  at System.Collections.Hashtable.Insert (System.Object key, System.Object nvalue, System.Boolean add) [0x00047] in <08f46039e5064c628bf7795f9b970b7b>:0 
  at System.Collections.Hashtable.set_Item (System.Object key, System.Object value) [0x00000] in <08f46039e5064c628bf7795f9b970b7b>:0 
  at System.Environment.GetEnvironmentVariables () [0x0002e] in <08f46039e5064c628bf7795f9b970b7b>:0 
  at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables () [0x0005e] in <ab9a187a50e54f8cb6a2692756ca03ac>:0 
  at Xamarin.ProjectTools.Builder.BuildInternal (System.String projectOrSolution, System.String target, System.String[] parameters, System.Collections.Generic.Dictionary`2[TKey,TValue] environmentVariables, System.Boolean restore) [0x0029d] in <65f22bf343d047c29354cce54f7eecac>:0 
  at Xamarin.ProjectTools.ProjectBuilder.Build (Xamarin.ProjectTools.XamarinProject project, System.Boolean doNotCleanupOnUpdate, System.String[] parameters, System.Boolean saveProject, System.Collections.Generic.Dictionary`2[TKey,TValue] environmentVariables) [0x0005c] in <65f22bf343d047c29354cce54f7eecac>:0 
  at Xamarin.Android.Build.Tests.BuildAssetsTest.CheckAssetsAreIncludedInAPK (System.Boolean useAapt2) [0x002fb] in <1be26b7a35c24a1393acaf20bc1ec93f>:0 
```

mono version info.
```
mono --version
Mono JIT compiler version 6.12.0.145 (2020-02/c633fe92383 Thu May 27 11:17:45 EDT 2021)
```

**Comment by filipnavara** [comment]
The bug was fixed only for MonoVM on .NET 6. I am not sure how much the code on classic Mono is different but it's likely to suffer from similar class of issues.
