### ISSUE TITLE
Mono 5.20 on Linux crash when import modules in IronPython 2.7.9

### ISSUE THREAD

**Issue by qihongw** [mono/mono#16781]
## Steps to Reproduce

1. mono ipy.exe
2. import System
3. from System import *

### Current Behavior

mono crashed

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**: 5.20.1.27

## Stacktrace

```
Thread 1 (Thread 0x7f26637da720 (LWP 18685)):
#0  0x000000328a20f37d in waitpid () from /lib64/libpthread.so.0
#1  0x0000000000518848 in dump_native_stacktrace.isra.4 ()
#2  0x00000000004af269 in mono_handle_native_crash () at mini-exceptions.c:3290
#3  0x0000000000511d80 in altstack_handle_and_restore ()
#4  0x0000000000647a18 in method_object_construct () at reflection.c:592
#5  0x0000000000000000 in ?? ()
```

**Comment by lambdageek** [comment]
Can reproduce this with 5.20.1.34 on OSX.

Can _not_ reproduce with 6.0.0.334 or with 6.6.0.156 (2019-08/a77128ca793).

I think this is fixed.

@qihongw  please let us know if you run into this issue with a newer version of mono.

**Comment by qihongw** [comment]
@lambdageek I had a workaround in our python code to bypass this problem. Currently I'm not ready to try the newer version of mono. I'll give you a feedback when I try mono 6.x.

**Comment by qihongw** [comment]
Sorry for the late response. I just did the same testing in mono 6.8, it crashed. In my old mono 4.8, there was no crash.
