### ISSUE TITLE
[wasm] Native-to-managed pinvoke callback causes RuntimeError

### ISSUE THREAD

**Issue by TheSpydog** [mono/mono#17389]
## Steps to Reproduce

1. Compile the following C code into a wasm archive `mylib.a`:
```c
typedef void (*csharpFunc)(void);
void CallCSharpFunc(csharpFunc fn) {
    fn();
}
```
2. Compile the following C# code into `Program.dll`:
```csharp
using System;
using System.Runtime.InteropServices;

namespace MyNamespace
{
    class MonoPInvokeCallbackAttribute : Attribute
    {
        public MonoPInvokeCallbackAttribute(Type t) { }
    }

    class MyProgram
    {
        delegate void csharpFunc();

        [DllImport("mylib", CallingConvention = CallingConvention.Cdecl)]
        static extern void CallCSharpFunc(csharpFunc f);

        static void Main(string[] args)
        {
            CallCSharpFunc(SayHi);
        }

        [MonoPInvokeCallback(typeof(csharpFunc))]
        static void SayHi()
        {
            Console.WriteLine("Hi!");
        }
    }
}
```
3. Package the dll and native library:
```
mono $WASM_SDK/packager.exe --emscripten-sdkdir=$EMSDK --mono-sdkdir=$WASM_SDK -appdir=bin --builddir=obj --aot --template=runtime.js --link-mode=SdkOnly --pinvoke-libs=mylib --native-lib=mylib.a --asset=index.html Program.dll
```
4. Build the obj/ directory with ninja.
5. Run a server in the bin/ directory.

### Current Behavior

In the browser console, a RuntimeError appears: `function signature mismatch`.

### Expected Behavior

In the browser console, the phrase "Hi!" should appear with no errors.

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[X] WebAssembly (Edge / Firefox / Chrome)

## Stacktrace

```
Uncaught (in promise) RuntimeError: function signature mismatch
    at wasm-function[11137]:0x30b78d
    at wasm-function[205]:0xf3b3
    at wasm-function[199]:0xef9b
    at wasm-function[8769]:0x284723
    at wasm-function[15498]:0x3c52c5
    at Module.dynCall_vii (http://127.0.0.1:8080/mono.js:11385:39)
    at invoke_vii (http://127.0.0.1:8080/mono.js:12264:5)
    at wasm-function[10280]:0x2da0c4
    at wasm-function[11624]:0x324b57
    at wasm-function[11606]:0x323071
```

**Comment by vargaz** [comment]
I can reproduce.

**Comment by devshgraphicsprogramming** [comment]
I'm having the exact same issue with SWIG Directors, C++ can't call any of the delegates passed as function pointers.
