### ISSUE TITLE
build fails on ppc64 and s390x, possible big endian issue introduced recently

### ISSUE THREAD

**Issue by sharkcz** [mono/mono#17521]
## Steps to Reproduce

1. ./autogen.sh
2. make

### Current Behavior
backtrace from s390x bellow, ppc64 looks pretty much the same
````
...
/bin/sh ../mkinstalldirs _tmpinst/bin
mkdir -p -- _tmpinst/bin
cp mono-wrapper _tmpinst/bin/mono
echo '#! /bin/sh' > _tmpinst/bin/ilasm ; \
r=`pwd`; m=`cd /home/jenkins/workspace/Mono/label/s390x/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/ilasm/ilasm.exe"'" "$@"' >> _tmpinst/bin/ilasm ; \
chmod +x _tmpinst/bin/ilasm
echo '#! /bin/sh' > _tmpinst/bin/csc ; \
r=`pwd`; m=`cd /home/jenkins/workspace/Mono/label/s390x/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"/home/jenkins/workspace/Mono/label/s390x/mcs/class/lib/build/mcs.exe"'" "$@"' >> _tmpinst/bin/csc ; \
chmod +x _tmpinst/bin/csc
echo '#! /bin/sh' > _tmpinst/bin/mcs ; \
r=`pwd`; m=`cd /home/jenkins/workspace/Mono/label/s390x/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/mcs.exe"'" "$@"' >> _tmpinst/bin/mcs ; \
chmod +x _tmpinst/bin/mcs
echo '#! /bin/sh' > _tmpinst/bin/al ; \
r=`pwd`; m=`cd /home/jenkins/workspace/Mono/label/s390x/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/al.exe"'" "$@"' >> _tmpinst/bin/al ; \
chmod +x _tmpinst/bin/al
if test -w /home/jenkins/workspace/Mono/label/s390x/mcs; then :; else chmod -R +w /home/jenkins/workspace/Mono/label/s390x/mcs; fi
cd /home/jenkins/workspace/Mono/label/s390x/mcs && make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14              ' CC='gcc' all-profiles
mkdir -p -- build/deps
make[6]: mcs: Command not found
make[6]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Error 127
*** Downloading bootstrap required 'monolite-linux/811DFDEB-0230-4C72-91AD-A1AC9CFDA823'
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
Makefile:20: warning: overriding recipe for target 'test-local'
../../build/library.make:208: warning: ignoring old recipe for target 'test-local'
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
/bin/sh: mono: command not found
--2019-10-23 03:44:16--  https://download.mono-project.com/monolite/monolite-linux-811DFDEB-0230-4C72-91AD-A1AC9CFDA823-latest.tar.gz
Resolving download.mono-project.com (download.mono-project.com)... 72.21.81.200, 2606:2800:11f:17a5:191a:18d5:537:22f9
Connecting to download.mono-project.com (download.mono-project.com)|72.21.81.200|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5379252 (5.1M) [application/x-gzip]
Saving to: ‘STDOUT’

     0K .......... .......... .......... .......... ..........  0% 1.01M 5s
    50K .......... .......... .......... .......... ..........  1% 1.01M 5s
...
  5200K .......... .......... .......... .......... .......... 99% 4.30M 0s
  5250K ...                                                   100% 6057G=1.2s

2019-10-23 03:44:18 (4.21 MB/s) - written to stdout [5379252/5379252]

*** The runtime 'mono' doesn't appear to be usable.
*** Trying the 'monolite-linux/811DFDEB-0230-4C72-91AD-A1AC9CFDA823' directory.
* Assertion at mini-trampolines.c:769, condition `mono_thread_is_gc_unsafe_mode ()' not met


=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
gstr.c:992: assertion 'src != NULL' failed
	0x108c4c2 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : 
gstr.c:992: assertion 'src != NULL' failed
	0x108c830 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : 
gstr.c:992: assertion 'src != NULL' failed
	0x10596b8 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : 
gstr.c:992: assertion 'src != NULL' failed
	0x108b942 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : 
	0x3ffd347c230 - Unknown
	0x3ffb96be4bc - /lib64/libc.so.6 : gsignal
	0x3ffb96a3d18 - /lib64/libc.so.6 : abort
gstr.c:992: assertion 'src != NULL' failed
	0x1362b8c - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : abort
gstr.c:992: assertion 'src != NULL' failed
	0x1341b26 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : abort
gstr.c:992: assertion 'src != NULL' failed
	0x133db4e - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : abort
gstr.c:992: assertion 'src != NULL' failed
	0x1362aee - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : abort
	0x1362f40 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : monoeg_assertion_message
gstr.c:992: assertion 'src != NULL' failed
	0x1362f86 - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : monoeg_assertion_message
gstr.c:992: assertion 'src != NULL' failed
	0x105dbac - /home/jenkins/workspace/Mono/label/s390x/mono/mini/mono : monoeg_assertion_message
	0x3ffb9c660d6 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
gstr.c:992: assertion 'src != NULL' failed
Entering thread summarizer pause from 0x3ffb9c78760
Finished thread summarizer pause from 0x3ffb9c78760.
/home/jenkins/workspace/Mono/label/s390x/runtime/etc/../bin/mono-hang-watchdog: line 3: /home/jenkins/workspace/Mono/label/s390x/tools/mono-hang-watchdog/mono-hang-watchdog: No such file or directory

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 65470]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
0x000003ffb9892ac2 in waitpid () from /lib64/libpthread.so.0
  Id   Target Id                                      Frame 
* 1    Thread 0x3ffb9c78760 (LWP 65445) "mono"        0x000003ffb9892ac2 in waitpid () from /lib64/libpthread.so.0
  2    Thread 0x3ffabfff910 (LWP 65470) "SGen worker" 0x000003ffb988e048 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0

Thread 2 (Thread 0x3ffabfff910 (LWP 65470)):
#0  0x000003ffb988e048 in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x0000000001338d02 in mono_os_cond_wait (mutex=0x14da2b0 <lock>, cond=0x14da280 <work_cond>) at ../../mono/utils/mono-os-mutex.h:177
#2  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=<optimized out>) at sgen-thread-pool.c:165
#3  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#4  0x000003ffb98880fe in start_thread () from /lib64/libpthread.so.0
#5  0x000003ffb977a19e in thread_start () from /lib64/libc.so.6

Thread 1 (Thread 0x3ffb9c78760 (LWP 65445)):
#0  0x000003ffb9892ac2 in waitpid () from /lib64/libpthread.so.0
#1  0x000000000108c70a in dump_native_stacktrace (signal=signal@entry=0x1382f1a "SIGABRT", mctx=mctx@entry=0x3ffd347bf90) at mini-posix.c:1072
#2  0x000000000108c830 in mono_dump_native_crash_info (signal=signal@entry=0x1382f1a "SIGABRT", mctx=mctx@entry=0x3ffd347bf90, info=info@entry=0x3ffd347c238) at mini-posix.c:1118
#3  0x00000000010596b8 in mono_handle_native_crash (signal=signal@entry=0x1382f1a "SIGABRT", mctx=mctx@entry=0x3ffd347bf90, info=info@entry=0x3ffd347c238) at mini-exceptions.c:3416
#4  0x000000000108b942 in sigabrt_signal_handler (_dummy=<optimized out>, _info=0x3ffd347c238, context=0x3ffd347c2b8) at mini-posix.c:232
#5  <signal handler called>
#6  0x000003ffb96be4bc in raise () from /lib64/libc.so.6
#7  0x000003ffb96a3d18 in abort () from /lib64/libc.so.6
#8  0x0000000001362b8c in monoeg_assert_abort () at goutput.c:57
#9  0x0000000001341b26 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=<optimized out>) at mono-log-common.c:136
#10 0x000000000133db4e in structured_log_adapter (log_domain=<optimized out>, log_level=<optimized out>, message=<optimized out>, user_data=<optimized out>) at mono-logger.c:468
#11 0x0000000001362aee in monoeg_g_logstr (msg=<optimized out>, log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:134
#12 monoeg_g_logv_nofree (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, format=format@entry=0x1440cf6 "* Assertion at %s:%d, condition `%s' not met\n", args=args@entry=0x3ffd347cbe0) at goutput.c:149
#13 0x0000000001362f40 in monoeg_assertion_message (format=format@entry=0x1440cf6 "* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:184
#14 0x0000000001362f86 in mono_assertion_message (file=file@entry=0x137bd80 "mini-trampolines.c", line=line@entry=769, condition=condition@entry=0x137bf3e "mono_thread_is_gc_unsafe_mode ()") at goutput.c:203
#15 0x000000000105dbac in mono_magic_trampoline (regs=0x3ffd347cea8, code=0x3ffb9c4ea4e "\343", <incomplete sequence \360\240>, arg=0x20c3618, tramp=<optimized out>) at mini-trampolines.c:780
#16 0x000003ffb9c660d6 in ?? ()
#17 0x000003ffb9c4ea4e in ?? ()
/tmp/mono-gdb-commands.65445:3: Error in sourced command file:
PC not saved
[Inferior 1 (process 65445) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x3ffb96be4bc):0x3ffb96be4ac  00 30 a7 29 00 02 a7 49 00 00 a7 59 00 08 0a af  .0.)...I...Y....
0x3ffb96be4bc  b9 14 00 21 b2 4f 00 10 eb 11 00 20 00 0d b2 4f  ...!.O..... ...O
0x3ffb96be4cc  00 11 d5 07 f1 a0 10 28 a7 74 00 1a eb df f2 10  .......(.t......
0x3ffb96be4dc  00 04 07 fe b2 4f 00 10 eb 11 00 20 00 0d b2 4f  .....O..... ...O

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.OutOfMemoryException:.ctor <0x0002c>
	  at <Module>:runtime_invoke_void__this___object <0x00178>
=================================================================
make[8]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Aborted (core dumped)
*** The contents of your 'monolite-linux/811DFDEB-0230-4C72-91AD-A1AC9CFDA823' directory may be out-of-date
*** You may want to try 'make get-monolite-latest'
make[8]: *** [build/profiles/build.make:117: do-profile-check-monolite] Error 1
make[7]: *** [build/profiles/build.make:93: do-profile-check] Error 2
make[6]: *** [build/profiles/build.make:129: do-profile-check-monolite] Error 2
make[5]: *** [build/profiles/build.make:93: do-profile-check] Error 2
make[4]: *** [Makefile:58: profile-do--build--all] Error 2
make[3]: *** [Makefile:54: profiles-do--all] Error 2
make[2]: *** [Makefile:695: all-mcs] Error 2
make[2]: Leaving directory '/home/jenkins/workspace/Mono/label/s390x/runtime'
make[1]: *** [Makefile:602: all-recursive] Error 1
make[1]: Leaving directory '/home/jenkins/workspace/Mono/label/s390x'
make: *** [Makefile:530: all] Error 2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
````

### Expected Behavior
no crash

## On which platforms did you notice this

[ ] macOS
[X] Linux
[ ] Windows

**Version Used**: master (61594078466fd80a4f80a0c3d670adb8301144b0)

We have daily rebuilds in CI, 20752df324d35dcd522688ee40ae3b0052da6a3d is the previous tested and it's OK. I can bisect to find the offending commit between them.

**Comment by lambdageek** [comment]
Possibly fixed by #17502

**Comment by sharkcz** [comment]
OK, let me fire a new build

**Comment by sharkcz** [comment]
yup, it looks good now, checked on commit 31b475e25a4ab5b6d8af731be9bb9e8158da31d9
