### ISSUE TITLE
[Wasm] "too much recursion" with AOT

### ISSUE THREAD

**Issue by MarcosCobena** [mono/mono#17584]
## Steps to Reproduce

1. Uncompress [VisualTests3.zip](https://github.com/mono/mono/files/3779468/VisualTests3.zip) and serve its content with `xsp4`
2. Browse above

### Current Behavior

With Firefox, the console shows "too much recursion" error in mono.js. With Chrome, the behavior is similar, with a different message. Below are both outputs.

### Expected Behavior

A beautiful Wave Engine/WebGL scene rendering :-)

## On which platforms did you notice this

[ ] macOS
[ ] Linux
[ ] Windows
[x] Wasm

**Version Used**:

commit 450d4746849d228c85748d9ab4ef68f90ac0c7f2 (HEAD -> master, origin/master, origin/HEAD)

## Stacktrace

Firefox:
```
MONO_WASM: Loaded: VisualTests.Wasm.dll mono.js:7149:16
MONO_WASM: Loaded: netstandard.dll mono.js:7149:16
MONO_WASM: Loaded: mscorlib.dll mono.js:7149:16
MONO_WASM: Loaded: System.dll mono.js:7149:16
MONO_WASM: Loaded: Mono.Security.dll mono.js:7149:16
MONO_WASM: Loaded: System.Xml.dll mono.js:7149:16
MONO_WASM: Loaded: System.Numerics.dll mono.js:7149:16
MONO_WASM: Loaded: System.Core.dll mono.js:7149:16
MONO_WASM: Loaded: System.Data.dll mono.js:7149:16
MONO_WASM: Loaded: System.Runtime.Serialization.dll mono.js:7149:16
MONO_WASM: Loaded: System.Drawing.Common.dll mono.js:7149:16
MONO_WASM: Loaded: System.ServiceModel.Internals.dll mono.js:7149:16
MONO_WASM: Loaded: System.Net.Http.dll mono.js:7149:16
MONO_WASM: Loaded: System.Xml.Linq.dll mono.js:7149:16
MONO_WASM: Loaded: VisualTests.LowLevel.dll mono.js:7149:16
MONO_WASM: Loaded: WaveEngine.Common.dll mono.js:7149:16
MONO_WASM: Loaded: WaveEngine.Mathematics.dll mono.js:7149:16
MONO_WASM: Loaded: System.Runtime.CompilerServices.Unsafe.dll mono.js:7149:16
MONO_WASM: Loaded: VisualTests.Runners.Common.dll mono.js:7149:16
MONO_WASM: Loaded: WaveEngine.Yaml.dll mono.js:7149:16
MONO_WASM: Loaded: SixLabors.ImageSharp.dll mono.js:7149:16
MONO_WASM: Loaded: Xamarin.Essentials.dll mono.js:7149:16
MONO_WASM: Loaded: SixLabors.Core.dll mono.js:7149:16
MONO_WASM: Loaded: WaveEngine.Platform.dll mono.js:7149:16
MONO_WASM: Loaded: WebAssembly.Bindings.dll mono.js:7149:16
MONO_WASM: Loaded: Plugin.DeviceInfo.dll mono.js:7149:16
MONO_WASM: Loaded: Newtonsoft.Json.dll mono.js:7149:16
MONO_WASM: Loaded: Microsoft.CSharp.dll mono.js:7149:16
MONO_WASM: Loaded: Plugin.Connectivity.Abstractions.dll mono.js:7149:16
MONO_WASM: Loaded: glTFLoader.dll mono.js:7149:16
MONO_WASM: Loaded: Pfim.dll mono.js:7149:16
MONO_WASM: Loaded: aot-dummy.dll mono.js:7149:16
MONO_WASM: Loaded: Plugin.Connectivity.dll mono.js:7149:16
MONO_WASM: Initializing mono runtime mono.js:7155:17
MONO-WASM: Runtime is ready. mono.js:7050:14
too much recursion
mono.js line 1668 > WebAssembly.instantiate:5763524:1
```

Chrome:
```
MONO_WASM: Loaded: VisualTests.Wasm.dll
mono.js:7149 MONO_WASM: Loaded: netstandard.dll
mono.js:7149 MONO_WASM: Loaded: System.dll
mono.js:7149 MONO_WASM: Loaded: System.Xml.dll
mono.js:7149 MONO_WASM: Loaded: Mono.Security.dll
mono.js:7149 MONO_WASM: Loaded: System.Core.dll
mono.js:7149 MONO_WASM: Loaded: mscorlib.dll
mono.js:7149 MONO_WASM: Loaded: System.Data.dll
mono.js:7149 MONO_WASM: Loaded: System.Drawing.Common.dll
mono.js:7149 MONO_WASM: Loaded: System.Runtime.Serialization.dll
mono.js:7149 MONO_WASM: Loaded: System.ServiceModel.Internals.dll
mono.js:7149 MONO_WASM: Loaded: System.Xml.Linq.dll
mono.js:7149 MONO_WASM: Loaded: VisualTests.LowLevel.dll
mono.js:7149 MONO_WASM: Loaded: SixLabors.ImageSharp.dll
mono.js:7149 MONO_WASM: Loaded: SixLabors.Core.dll
mono.js:7149 MONO_WASM: Loaded: System.Runtime.CompilerServices.Unsafe.dll
mono.js:7149 MONO_WASM: Loaded: WaveEngine.Common.dll
mono.js:7149 MONO_WASM: Loaded: WaveEngine.Mathematics.dll
mono.js:7149 MONO_WASM: Loaded: WaveEngine.Yaml.dll
mono.js:7149 MONO_WASM: Loaded: VisualTests.Runners.Common.dll
mono.js:7149 MONO_WASM: Loaded: WaveEngine.Platform.dll
mono.js:7149 MONO_WASM: Loaded: WebAssembly.Bindings.dll
mono.js:7149 MONO_WASM: Loaded: Xamarin.Essentials.dll
mono.js:7149 MONO_WASM: Loaded: Plugin.Connectivity.Abstractions.dll
mono.js:7149 MONO_WASM: Loaded: Plugin.DeviceInfo.dll
mono.js:7149 MONO_WASM: Loaded: Plugin.Connectivity.dll
mono.js:7149 MONO_WASM: Loaded: glTFLoader.dll
mono.js:7149 MONO_WASM: Loaded: Microsoft.CSharp.dll
mono.js:7149 MONO_WASM: Loaded: Newtonsoft.Json.dll
mono.js:7149 MONO_WASM: Loaded: aot-dummy.dll
mono.js:7149 MONO_WASM: Loaded: Pfim.dll
mono.js:7149 MONO_WASM: Loaded: System.Numerics.dll
mono.js:7149 MONO_WASM: Loaded: System.Net.Http.dll
mono.js:7155 MONO_WASM: Initializing mono runtime
mono.js:7050 MONO-WASM: Runtime is ready.
wasm-01e37122:21292 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at :9000/wasm-function[21291]:0x5e99b9
    at :9000/wasm-function[21283]:0x5e7785
    at :9000/wasm-function[20923]:0x5d6998
    at :9000/wasm-function[18727]:0x57f120
    at :9000/wasm-function[16831]:0x521ec2
    at :9000/wasm-function[16989]:0x528c96
    at :9000/wasm-function[16988]:0x528c6e
    at :9000/wasm-function[217]:0x14e8e
    at :9000/wasm-function[226]:0x155a8
    at :9000/wasm-function[2560]:0x88cc1
```

**Comment by MarcosCobena** [comment]
[netstandard2.0.zip](https://github.com/mono/mono/files/3779527/netstandard2.0.zip) contains the "source" used with packager.exe:
```
marcos@marcos:~/Repositorios/mono/sdks/wasm$ ﻿mono --debug packager.exe --emscripten-sdkdir="/home/marcos/Repositorios/mono/sdks/builds/toolchains/emsdk" --mono-sdkdir="/home/marcos/Repositorios/mono/sdks/out" -appdir="bin/VisualTests" --nobinding --builddir="obj/VisualTests" --aot --search-path="VisualTests" VisualTests/VisualTests.Wasm.dll
marcos@marcos:~/Repositorios/mono/sdks/wasm$ ninja -v -C obj/VisualTests/
```

**Comment by vargaz** [comment]
I can reproduce. There is something wrong with your wasm build, the mscorlib.dll its using doesn't match the current version in mono master.

**Comment by MarcosCobena** [comment]
After some chat with @vargaz through Gitter, he noticed I was using the wrong assemblies passed to packager.exe: I took the bin/Debug/netstandard2.0 directly from a Mono.WebAssembly.Sdk which, surely, modifies the managed/ DLLs in some way (although I've explicitly disabled the linker).

Changing the project to Microsoft.NET.Sdk and using this new output, Firefox reports the following:
```
MONO-WASM: Runtime is ready. mono.js:7028:14
RuntimeError: indirect call signature mismatch mono.js line 1668 > WebAssembly.instantiate:3474751:1
```

**Comment by MarcosCobena** [comment]
It seems @jeromelaban has already hit this: https://github.com/mono/mono/issues/16818#issuecomment-536091696

**Comment by MarcosCobena** [comment]
Chrome:
```
MONO-WASM: Runtime is ready.
wasm-022ae9ca:10157 Uncaught (in promise) RuntimeError: function signature mismatch
    at wasm-function[10156]:0x35053f
    at wasm-function[10191]:0x353fd1
    at wasm-function[13004]:0x48f6b4
    at wasm-function[13003]:0x48f63d
    at wasm-function[12973]:0x488c0c
    at wasm-function[23073]:0x6dfc40
    at Module.dynCall_viiiii (http://localhost:9000/mono.js:11269:42)
    at invoke_viiiii (http://localhost:9000/mono.js:12352:5)
    at wasm-function[12972]:0x487acd
    at wasm-function[204]:0x18201
```

**Comment by kjpou1** [comment]
Hola Marcos.

Right now with `packager.exe` you can use `--asset=myasset.dll` but this will not load the `.dll` during runtime initialization.  You will need to use an `HttpClient` call to load the bytes of the `.dll` and load it that way.

Hope that answers your question.

There is no available method right now to include additional `.dll`s to be loaded at runtime initialization.  

The `packager.exe` is really an internal tool with `msbuild` tooling coming later.

**Comment by MarcosCobena** [comment]
Yeah, I read that flag the other day but, as you say, you need to manually add the assembly to the array at mono.config (if you want the runtime to load it by it-self at the very beginning).

I workarounded this by adding a linker-please-include thing, but I stumbled upon a different bug, for which I'll open a new issue now.

Thanks for your help!

**Comment by MarcosCobena** [comment]
This' the new issue: https://github.com/mono/mono/issues/17686
