### ISSUE TITLE
[wasm][debugger] Selecting different stack frames can break inspection

### ISSUE THREAD

**Issue by lewing** [mono/mono#17875]
Selecting up higher stack frames sometimes breaks variable inspection in the lower frames.

**Comment by lewing** [comment]
@thaystg any idea what might be causing this?

**Comment by thaystg** [comment]
No :/

**Comment by lewing** [comment]
at jsStackTrace (http://192.168.1.135:8080/mono.js:1824:17)
    at stackTrace (http://192.168.1.135:8080/mono.js:1841:16)
    at abort (http://192.168.1.135:8080/mono.js:1596:44)
    at _abort (http://192.168.1.135:8080/mono.js:6590:7)
    at wasm_logger (wasm-function[6022]:0x11045c)
    at eglib_log_adapter (wasm-function[5367]:0xf64d2)
    at monoeg_g_logstr (wasm-function[5726]:0x1030d5)
    at monoeg_g_logv_nofree (wasm-function[5725]:0x103091)
    at monoeg_g_log (wasm-function[5727]:0x1030f5)
    at stackval_to_data_addr (wasm-function[184]:0x13f8d)
    at abort (http://192.168.1.135:8080/mono.js:1602:9)
    at _abort (http://192.168.1.135:8080/mono.js:6590:7)
    at wasm_logger (wasm-function[6022]:0x11045c)
    at eglib_log_adapter (wasm-function[5367]:0xf64d2)
    at monoeg_g_logstr (wasm-function[5726]:0x1030d5)
    at monoeg_g_logv_nofree (wasm-function[5725]:0x103091)
    at monoeg_g_log (wasm-function[5727]:0x1030f5)
    at stackval_to_data_addr (wasm-function[184]:0x13f8d)
    at interp_frame_get_arg (wasm-function[183]:0x13e9c)
    at describe_variable (wasm-function[1020]:0x4916e)
