### ISSUE TITLE
Crash in System.Threading.Tasks

### ISSUE THREAD

**Issue by mkrueger** [mono/mono#18007]
Steps to reproduce:

1. Get MonoDevelop from https://github.com/xamarin/monodevelop/tree/master-gitmsclient
2. Run Nunit Testts Addins->VersionControl->MonoDevelop.VersionControl.Git.Tests

Tests are crashing with:

Unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: baseStream
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00022] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:680 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00052] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:3165 
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2222 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x000a1] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2195 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00003] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2093 
  at System.Threading.Tasks.Task.TrySetException (System.Object exceptionObject) [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:754 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0003e] in <8786ba7ca96d408c8c0d5c5e15ea3164>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[TResult].<FromAsyncImpl>b__0 (System.IAsyncResult iar) [0x00008] in <8786ba7ca96d408c8c0d5c5e15ea3164>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:157 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00015] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1337 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:899 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1261 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentNullException: Value cannot be null.
Parameter name: baseStream
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00022] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:680 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00052] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:3165 
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2222 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x000a1] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2195 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00003] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2093 
  at System.Threading.Tasks.Task.TrySetException (System.Object exceptionObject) [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:754 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0003e] in <8786ba7ca96d408c8c0d5c5e15ea3164>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[TResult].<FromAsyncImpl>b__0 (System.IAsyncResult iar) [0x00008] in <8786ba7ca96d408c8c0d5c5e15ea3164>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:157 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00015] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1337 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:899 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2019-08/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1261 
The application exited with code: 255

---------

It's not really possible to find a solution for that with such a stack trace.

**Comment by sevoku** [comment]
same happens when running MonoDevelop from that branch (make run) and using "Version Control > Checkout > Any Git repo"

**Comment by marek-safar** [comment]
@lambdageek please assign

**Comment by mkrueger** [comment]
Edit: Upgraded mono to  6.6.0.155 - same issue - now it happens when checking out any file as well.

May've to do with the process creation/redirection ?

**Comment by lambdageek** [comment]
So what's interesting is that the only place I've foudn so far that throws a null reference exception and mentions `baseStream` is in `Mono.Profiler.Log.LogStream`:
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/Mono.Profiler.Log/Mono.Profiler.Log/LogStream.cs#L31-L40

It doesn't make too much sense to me why that would show up in some Git addin.

**Comment by steveisok** [comment]
@lambdageek Since this seems BCLish I or someone on my team will take a look.

**Comment by mkrueger** [comment]
@lambdageek: I don't think that we should focus on the git addin it's just a way of triggering the issue.

**Comment by jaykrell** [comment]
Hopefully the exception stack reporting can be fixed, and the closed-source'ness (the link doesn't work for me, for example).

**Comment by mkrueger** [comment]
Ok found the issue.

NamedPipeServerStream.BeginWaitForConnection(callback, server);

A crash in the "callback" causes that stack trace.

**Comment by steveisok** [comment]
@mkrueger Was the problem in the plugin or outside of it?

**Comment by baulig** [comment]
How do I build this?  I'm getting this error

```
"/Users/Workspace/monodevelop/main/Main.sln" (default target) (1) ->
"/Users/Workspace/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/MonoDevelop.VersionControl.Subversion.Tests.csproj" (default target) (71) ->
(CoreCompile target) -> 
  /Users/Workspace/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Git.Tests/BaseRepoUtilsTest.cs(36,34): error CS0234: The type or namespace name 'Git' does not exist in the namespace 'MonoDevelop.VersionControl' (are you missing an assembly reference?) [/Users/Workspace/monodevelop/main/src/addins/VersionControl/MonoDevelop.VersionControl.Subversion.Tests/MonoDevelop.VersionControl.Subversion.Tests.csproj]
```

**Comment by sevoku** [comment]
@steveisok the problem was that the named pipe server called the callback after being disposed, we fixed this on the client side by checking the disposed state in the callback, however the server should not call the callback after being disposed and otherwise provide a useful stack if the callback throws.

@baulig please try the latest (note: branch has been rebased), you can also load main/Main.sln in VS for Mac and just build and run the Git tests.

Fix/Workaround on our side: https://github.com/xamarin/monodevelop/commit/ad208d0aea3e2e69f15097d39d9f2d0720d73665

**Comment by baulig** [comment]
I'll see whether I can come up with a self-contained test case for this.  It would also be interesting to see what's happening in .NET Core.

However, I disagree with not calling the callback after dispose because that would be inconsistent with how other Begin/End methods behave when it comes to cancellation and disposal.   But providing a useful stack trace, definitely!  You shouldn't be going around searching where this is happening.

**Comment by sevoku** [comment]
Oh, ok, that was unexpected for me, but if that's in general expected reasonable behaviour then it's fine. Just a fix for the crash with an appropriate stacktrace would be 👍

**Comment by baulig** [comment]
Just tested this with .NET Core and the callback is invoked after disposal - as it should be.

```
using System;
using System.IO.Pipes;
using System.Threading;

namespace Bug_18007
{
	class Program
	{
		const string PipeName = "test-pipe";
		static ManualResetEvent callbackEvent;

		static void Main(string[] args)
		{
			RunServer();
		}

		static void RunServer ()
		{
			callbackEvent = new ManualResetEvent (false);
			var server = new NamedPipeServerStream (PipeName);
			var result = server.BeginWaitForConnection (ServerCallback, server);
			Thread.Sleep (500);
			server.Dispose ();
			var done = callbackEvent.WaitOne (2500);
			Console.WriteLine($"RUN SERVER DONE: {done}");
			server.EndWaitForConnection (result);
		}

		static void ServerCallback (IAsyncResult result)
		{
			callbackEvent.Set();
			Console.WriteLine($"SERVER CALLBACK: {result} {result.AsyncState}");
			throw new InvalidTimeZoneException($"I LIVE ON THE MOON!");
		}
	}
}
```

However, the exception message is slightly better.

.NET Core:

```
SERVER CALLBACK: System.Threading.Tasks.TaskToApm+TaskWrapperAsyncResult System.IO.Pipes.NamedPipeServerStream
RUN SERVER DONE: True
Unhandled exception. Unhandled exception. System.InvalidTimeZoneException: I LIVE ON THE MOON!
   at Bug_18007.Program.ServerCallback(IAsyncResult result) in /Users/martin/Projects/Bug-18007/Program.cs:line 33
   at System.Threading.Tasks.TaskToApm.<>c__DisplayClass3_0.<InvokeCallbackWhenTaskCompletes>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.<>c.<.cctor>b__17_0(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

Mono:

```
SERVER CALLBACK: System.Threading.Tasks.TaskToApm+TaskWrapperAsyncResult System.IO.Pipes.NamedPipeServerStream
RUN SERVER DONE: True

Unhandled Exception:
System.InvalidTimeZoneException: I LIVE ON THE MOON!
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00022] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:680 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00052] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:3165 
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2222 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x000a1] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2195 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00003] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2093 
  at System.Threading.Tasks.Task.TrySetException (System.Object exceptionObject) [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:754 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0003e] in <f57930ed6b284a32a727e4268233ffa6>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[TResult].<FromAsyncImpl>b__0 (System.IAsyncResult iar) [0x00008] in <f57930ed6b284a32a727e4268233ffa6>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:157 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00015] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1337 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:899 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1261 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidTimeZoneException: I LIVE ON THE MOON!
  at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction (System.Action action, System.Boolean allowInlining, System.Threading.Tasks.Task& currentTask) [0x00022] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/TaskContinuation.cs:680 
  at System.Threading.Tasks.Task.FinishContinuations () [0x00052] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:3165 
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2222 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x000a1] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2195 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x00003] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2093 
  at System.Threading.Tasks.Task.TrySetException (System.Object exceptionObject) [0x00023] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:754 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0003e] in <f57930ed6b284a32a727e4268233ffa6>:0 
  at System.Threading.Tasks.TaskFactory`1+<>c__DisplayClass35_0[TResult].<FromAsyncImpl>b__0 (System.IAsyncResult iar) [0x00008] in <f57930ed6b284a32a727e4268233ffa6>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c.<Complete>b__27_0 (System.Object state) [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:157 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00015] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1337 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:899 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono-pullrequest/pr_2/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/threadpool.cs:1261 
```

**Comment by mkrueger** [comment]
"… callback is invoked after disposal - as it should be."

Then we've a very different opinion about what a Dispose should do. IMHO a disposed object should never invoke an event of any sort. And if it does it shouldn't crash.
