### ISSUE TITLE
LLVM: try-catch doesn't catch an exception

### ISSUE THREAD

**Issue by EgorBo** [mono/mono#18067]
```csharp
using System;
using System.Reflection;

class Program
{
    public static int MyProperty
    {
        set { throw new NotSupportedException(); }
    }

    public static void Main()
    {
        try
        {
            typeof(Program).InvokeMember(name: "MyProperty", 
                invokeAttr: BindingFlags.Public | BindingFlags.Static | BindingFlags.SetProperty, 
                binder: null, 
                target: null, 
                args: new object[] { 42 }, 
                modifiers: null, 
                culture: null, 
                namedParameters: null);
        }
        catch (Exception exc)
        {
            Console.WriteLine("OK 1: " + exc.GetType());
        }
        Console.WriteLine("OK 2");
    }
}
```
Expected:
```
OK 1: System.Reflection.TargetInvocationException
OK 2
```
Actual:
```
Unwind failure. Illegal value for switch statement, assertion at unwind.c 688
.
Unwind failure. Illegal value for switch statement, assertion at unwind.c 688
.

Unhandled Exception:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Specified method is not supported.
   at Program.set_MyProperty(Int32 value)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /mnt/c/prj/mono/mono-netcore/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /mnt/c/prj/mono/mono-netcore/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 345
Unwind failure. Illegal value for switch statement, assertion at unwind.c 688
.
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Specified method is not supported.
   at Program.set_MyProperty(Int32 value)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /mnt/c/prj/mono/mono-netcore/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 339
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /mnt/c/prj/mono/mono-netcore/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 345
Makefile:84: recipe for target 'run-sample' failed
make: *** [run-sample] Error 1
```

**Comment by EgorBo** [comment]
Relevant test: https://github.com/mono/mono/blob/master/netcore/CoreFX.issues_linux.rsp#L42

**Comment by marek-safar** [comment]
@vargaz this one looks bad

**Comment by vargaz** [comment]
Can't reproduce using mono --llvm bug.exe

**Comment by EgorBo** [comment]
@vargaz forgot to mention - it's `netcore`

**Comment by vargaz** [comment]
Does this happen on linux ?

**Comment by EgorBo** [comment]
@vargaz hm.. can't reproduce it on macOS. But does happen on WSL (Linux).
