### ISSUE TITLE
[interp] [netcore] flaky NetworkInterfaceBasicTest

### ISSUE THREAD

**Issue by lewurm** [mono/mono#18695]
https://github.com/mono/corefx/blob/7c9e2158925339a5a96ff8d09d21c600a0b27e5a/src/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs#L55-L88

The output indicates some problem around `speed` parsing:
```
System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Linux [FAIL]
2020-02-04T01:27:47.3503852Z [m[37m      Assert.InRange() Failure
2020-02-04T01:27:47.3507437Z [m[37m      Range:  (-1 - 9223372036854775807)
2020-02-04T01:27:47.3510774Z [m[37m      Actual: -1539607552
2020-02-04T01:27:47.3517394Z [m[30;1m      Stack Trace:
2020-02-04T01:27:47.3531114Z [m[37m        /_/src/System.Net.NetworkInformation/tests/FunctionalTests/NetworkInterfaceBasicTest.cs(75,0): at System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_AccessInstanceProperties_NoExceptions_Linux()
2020-02-04T01:27:47.3538285Z [m[37m        /home/vsts/work/1/s/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(339,0): at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
2020-02-04T01:27:47.3542791Z [m[30;1m      Output:
2020-02-04T01:27:47.3546517Z [m[37m        - NetworkInterface -
2020-02-04T01:27:47.3549682Z [m[37m        Name: lo
2020-02-04T01:27:47.3552821Z [m[37m        Description: lo
2020-02-04T01:27:47.3555898Z [m[37m        ID: lo
2020-02-04T01:27:47.3559088Z [m[37m        Type: Loopback
2020-02-04T01:27:47.3562248Z [m[37m        Status: Up
2020-02-04T01:27:47.3565421Z [m[37m        Speed: -1
2020-02-04T01:27:47.3568599Z [m[37m        SupportsMulticast: False
2020-02-04T01:27:47.3571746Z [m[37m        GetPhysicalAddress(): 
2020-02-04T01:27:47.3574907Z [m[37m        - NetworkInterface -
2020-02-04T01:27:47.3578265Z [m[37m        Name: eth0
2020-02-04T01:27:47.3581903Z [m[37m        Description: eth0
2020-02-04T01:27:47.3585012Z [m[37m        ID: eth0
2020-02-04T01:27:47.3588131Z [m[37m        Type: Ethernet
2020-02-04T01:27:47.3591214Z [m[37m        Status: Up
2020-02-04T01:27:47.3594300Z [m[37m        Speed: -1539607552
```
which maps to
```console
$ printf "0x%016x\n" -1539607552
0xffff_ffff_a43b_7400
```
which looks suspiciously like a sign extending bug.

Alas I didn't have luck reproducing it locally, but it might be possible to repro by writing suspicious integer numbers into a file and parse them in a similar way as the network code does.

**Comment by BrzVlad** [comment]
I can't reproduce this. I'm not sure how useful it is to keep this report open given we have no clear repro steps or expected failure frequency.

**Comment by lewurm** [comment]
@akoeplinger do you still see it on CI?

**Comment by akoeplinger** [comment]
@lewurm yes, it fails on pretty much all of the netcore builds in PRs/master. If you can't repro it locally I'd suggest opening a PR to print out some more details.

**Comment by akoeplinger** [comment]
dotnet/runtime is seeing pretty much the same issue: https://github.com/dotnet/runtime/issues/18090#issuecomment-585789728

However it might still be an issue with the interpreter since we didn't see the test failure with normal JIT on the same VMs.

**Comment by lewurm** [comment]
I would say it's more likely a corefx bug ( https://github.com/dotnet/runtime/pull/32223 ) + a mini JIT bug that hides it 😄
