### ISSUE TITLE
sgen-new-threads-dont-join-stw.exe flaky

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#18817]
This is a duplicate of https://github.com/mono/mono/issues/15240 but I could not reopen the original.

## Steps to Reproduce

Submit a PR.
For example https://github.com/mono/mono/pull/18734.

### Current Behavior

Unrelated failures.

### Expected Behavior

Success.

## On which platforms did you notice this

Linux

**Version Used**:

## Stacktrace

https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/31584/testReport/junit/MonoTests/test-sgen-regular-ms-simple/sgen_new_threads_dont_join_stw_exe/

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-arm64-fullaot/19181/testReport/junit/MonoTests/test-sgen-regular-ms-simple/sgen_new_threads_dont_join_stw_exe/

**Comment by jaykrell** [comment]
https://jenkins.mono-project.com/job/test-mono-pull-request-armhf/31841/testReport/junit/MonoTests/test-sgen-regular-ms-simple/sgen_new_threads_dont_join_stw_exe/

```
Thread 4 (Thread 0xf23fd450 (LWP 30634)):
#0  0xf7b64384 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0xf7b63126 in waitpid () from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x0060ce56 in dump_native_stacktrace (mctx=mctx@entry=0xf23fbf18, signal=0x85ec1c "SIGSEGV") at mini-posix.c:1112
#3  0x0060cf72 in mono_dump_native_crash_info (signal=signal@entry=0x85ec1c "SIGSEGV", mctx=mctx@entry=0xf23fbf18, info=info@entry=0xf23fc018) at mini-posix.c:1156
#4  0x005ea388 in mono_handle_native_crash (signal=0x85ec1c "SIGSEGV", mctx=0xf23fbf18, mctx@entry=0xf23fbf20, info=0xf23fc018, info@entry=0x4) at mini-exceptions.c:3427
#5  0x005c5606 in mono_sigsegv_signal_handler_debug (_dummy=-219132296, _info=0x5e7a5a <get_generic_info_from_stack_frame+154>, context=0xb, debug_fault_addr=0xf23fc018) at mini-runtime.c:3396
#6  <signal handler called>
#7  0x005e7a5a in get_generic_info_from_stack_frame (ji=ji@entry=0xf2f0eab8, ctx=ctx@entry=0xf23fc578) at mini-exceptions.c:843
#8  0x005eb02e in handle_exception_first_pass (last_mono_wrapper_runtime_invoke=<synthetic pointer>, catch_frame=0xf23fc4f8, non_exception=0x0, out_prev_ji=<synthetic pointer>, out_ji=<synthetic pointer>, out_filter_idx=<synthetic pointer>, obj=0xf74272f0, ctx=0xf23fc578) at mini-exceptions.c:2352
#9  mono_handle_exception_internal (ctx=0xf23fc818, obj=0xf74272f0, resume=resume@entry=0, out_ji=0x0) at mini-exceptions.c:2698
#10 0x005eb974 in mono_handle_exception (ctx=ctx@entry=0xf23fc818, void_obj=<optimized out>) at mini-exceptions.c:3104
#11 0x005ebb2c in mono_raise_exception_with_ctx (exc=<optimized out>, ctx=0xf23fc818) at mini-exceptions.c:3745
#12 0x00714998 in self_interrupt_thread (_unused=<optimized out>) at threads.c:5440
#13 0xf566cb14 in string_GetHashCode (this=0xf74ddfc0) at /home/builder/jenkins/workspace/test-mono-pull-request-armhf/external/corefx/src/Common/src/CoreLib/System/String.Comparison.cs:858
#14 0xf74272a0 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
