### ISSUE TITLE
WebAssembly debugger proxy crashes if there's a service worker

### ISSUE THREAD

**Issue by SteveSandersonMS** [mono/mono#19218]
Things are looking really good in most scenarios right now, but I just noticed that an issue occurs if the site you're trying to debug has an active service worker. The `ws-proxy` code throws during connection, so the debugger IDE immediately disconnects.

As further context, we just shipped a Blazor PWA template that includes a service worker.

### Repro

In a web assembly application that you can debug using `ProxyDriver`, add a service worker registration into its `index.html` by adding:

```html
<script>navigator.serviceWorker.register('service-worker.js')</script>
```

Also add the actual service worker file called `service-worker.js` alongside `index.html`:

```js
// This is a no-op. It should not interfere with the application's behavior.
self.addEventListener('fetch', () => { });
```

Next load the page in your browser. In the browser's dev tools *Application* tab, be sure the service worker is actually activated. If it isn't yet activated, close all browser tabs then come back.

![image](https://user-images.githubusercontent.com/1101362/76612220-bbeee100-6513-11ea-91d8-4ecd832830b9.png)

Now try to debug it via `ProxyDriver`.

Expected: Debugging still works
Actual: Debugger UI immediately disconnects, and in `ProxyDriver`'s console output, you see this:

```
      DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Invalid Session: "session-1079065F2DB189F86186D137B0623747" (Parameter 'sessionId'))
       ---> System.ArgumentException: Invalid Session: "session-1079065F2DB189F86186D137B0623747" (Parameter 'sessionId')
         at WebAssembly.Net.Debugging.MonoProxy.GetContext(SessionId sessionId) in C:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\MonoProxy.cs:line 147
         at WebAssembly.Net.Debugging.MonoProxy.AcceptCommand(MessageId id, String method, JObject args, CancellationToken token) in C:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\MonoProxy.cs:line 228
         at WebAssembly.Net.Debugging.DevToolsProxy.OnCommand(MessageId id, String method, JObject args, CancellationToken token) in C:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\DevToolsProxy.cs:line 243
         --- End of inner exception stack trace ---
         at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
         at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
         at System.Threading.Tasks.Task`1.get_Result()
         at WebAssembly.Net.Debugging.DevToolsProxy.Run(Uri browserUri, WebSocket ideSocket) in C:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\DevToolsProxy.cs:line 379
```

### Thoughts about fix

Since there's no scenario (today) for having .NET code running inside the service worker, I would guess it's perfectly sufficient just to pass through commands relating to unknown sessions without taking other actions. That way you can still use the JS debugger inside service worker code, but the .NET aspects of the debugger are bypassed.

However @lewing is really the one to judge whether that would be the right solution.

**Comment by SteveSandersonMS** [comment]
FYI @danroth27 @mkArtakMSFT in case this comes up in triage

**Comment by lewing** [comment]
At first glance this just looks like we're assuming a mono runtime exists in a given worker context and we should handle that case gracefully. @radical please look into this after the all the other value type work, I'll try to resolve it before then.

**Comment by SteveSandersonMS** [comment]
Note: the same issue happens even without a service worker if the user follows a link to an external site that doesn't contain a Mono WebAssembly application, as reported here: https://github.com/aspnet/AspNetCore-ManualTests/issues/86

In this case, the exception is also:

```
DevToolsProxy::Run: Exception System.AggregateException: One or more errors occurred. (Invalid Session: "session-F09AAF18AB500935A8D08B967AE2EB9B" (Parameter 'sessionId'))
       ---> System.ArgumentException: Invalid Session: "session-F09AAF18AB500935A8D08B967AE2EB9B" (Parameter 'sessionId')
         at WebAssembly.Net.Debugging.MonoProxy.GetContext(SessionId sessionId) in c:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\MonoProxy.cs:line 147
         at WebAssembly.Net.Debugging.MonoProxy.AcceptCommand(MessageId id, String method, JObject args, CancellationToken token) in c:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\MonoProxy.cs:line 228
         at WebAssembly.Net.Debugging.DevToolsProxy.OnCommand(MessageId id, String method, JObject args, CancellationToken token) in c:\git\mono\mono\sdks\wasm\Mono.WebAssembly.DebuggerProxy\DevToolsProxy.cs:line 243
```

**Comment by mkArtakMSFT** [comment]
As you can see, we've got many reports of this overnight. I think I've linked them all here.

**Comment by lewing** [comment]
fixed in https://github.com/mono/mono/pull/19394
