### ISSUE TITLE
Mono crashes Pinta

### ISSUE THREAD

**Issue by lag-linaro** [mono/mono#19727]
## Steps to Reproduce

1. Start Pinta on Ubuntu 20.04
2. Wait few minutes
3. Use the Text tool

### Current Behaviour

```
Cairo.Surface is leaking, programmer is missing a call to Dispose
Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces
Cairo.Surface is leaking, programmer is missing a call to Dispose
Set MONO_CAIRO_DEBUG_DISPOSE to track allocation traces
free(): invalid pointer

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x55b586f99eb5 - /usr/bin/mono : (null)
	0x55b586f9a250 - /usr/bin/mono : (null)
	0x55b586f47129 - /usr/bin/mono : (null)
	0x55b586f99467 - /usr/bin/mono : (null)
	0x7fd0016603c0 - /lib/x86_64-linux-gnu/libpthread.so.0 : (null)
	0x7fd00148218b - /lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7fd001461859 - /lib/x86_64-linux-gnu/libc.so.6 : abort
	0x7fd0014cc3ee - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x7fd0014d447c - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x7fd0014d5cac - /lib/x86_64-linux-gnu/libc.so.6 : (null)
	0x40f2cb13 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x7fcfe75fd700 from 0x7fd000a6b700
Pkilling 0x7fcff5521700 from 0x7fd000a6b700
Pkilling 0x7fcfb7358700 from 0x7fd000a6b700
Pkilling 0x7fcfe7fff700 from 0x7fd000a6b700
Pkilling 0x7fcff5726700 from 0x7fd000a6b700
Pkilling 0x7fcfe77fe700 from 0x7fd000a6b700
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Pkilling 0x7fcfe73fc700 from 0x7fd000a6b700
Pkilling 0x7fd001439780 from 0x7fd000a6b700
Pkilling 0x7fcfb312b700 from 0x7fd000a6b700
Entering thread summarizer pause from 0x7fd000a6b700
Finished thread summarizer pause from 0x7fd000a6b700.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 1113221]
[New LWP 1113222]
[New LWP 1113223]
[New LWP 1113224]
[New LWP 1113225]
[New LWP 1113227]
[New LWP 1113416]
[New LWP 1113417]
[New LWP 1113419]
[New LWP 1113421]
[New LWP 1113422]
[New LWP 1113423]
[New LWP 1113424]
[New LWP 1113425]
[New LWP 1113440]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007fd00155196f in __GI___poll (fds=0x55b588335520, nfds=2, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
29	../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
  Id   Target Id                                             Frame 
* 1    Thread 0x7fd001439780 (LWP 1113220) "mono"            0x00007fd00155196f in __GI___poll (fds=0x55b588335520, nfds=2, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
  2    Thread 0x7fd0003ff700 (LWP 1113221) "SGen worker"     futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x55b58738be08) at ../sysdeps/nptl/futex-internal.h:183
  3    Thread 0x7fd000a6b700 (LWP 1113222) "Finalizer"       0x00007fd001521c6f in __GI___wait4 (pid=1113528, stat_loc=0x7fd000a69554, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
  4    Thread 0x7fcff7c21700 (LWP 1113223) "gmain"           0x00007fd00155196f in __GI___poll (fds=0x55b5881bc190, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  5    Thread 0x7fcff7420700 (LWP 1113224) "dconf worker"    0x00007fd00155196f in __GI___poll (fds=0x55b5881befa0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  6    Thread 0x7fcff6c1f700 (LWP 1113225) "gdbus"           0x00007fd00155196f in __GI___poll (fds=0x7fcfe8016760, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  7    Thread 0x7fcfe6fff700 (LWP 1113227) "threaded-ml"     0x00007fd00155196f in __GI___poll (fds=0x7fcfd8007170, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
  8    Thread 0x7fcfb7358700 (LWP 1113416) "mono"            futex_abstimed_wait_cancelable (private=<optimised out>, abstime=0x7fcfb7357ca0, clockid=<optimised out>, expected=0, futex_word=0x55b58738c488) at ../sysdeps/nptl/futex-internal.h:320
  9    Thread 0x7fcfe7fff700 (LWP 1113417) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe7ffed50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  10   Thread 0x7fcfb312b700 (LWP 1113419) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfb312ad50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  11   Thread 0x7fcff5726700 (LWP 1113421) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcff5725d50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  12   Thread 0x7fcff5521700 (LWP 1113422) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcff5520d50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  13   Thread 0x7fcfe77fe700 (LWP 1113423) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe77fdd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  14   Thread 0x7fcfe75fd700 (LWP 1113424) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe75fcd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  15   Thread 0x7fcfe73fc700 (LWP 1113425) "Thread Pool Wor" 0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe73fbd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
  16   Thread 0x7fcfa2ed7700 (LWP 1113440) "pool-Pinta"      syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38

Thread 16 (Thread 0x7fcfa2ed7700 (LWP 1113440)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007fcffcd9b5a6 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcffcd1e561 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcffcd1eb86 in g_async_queue_timeout_pop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcffcd78279 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fcffcd77931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#7  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 15 (Thread 0x7fcfe73fc700 (LWP 1113425)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe73fbd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcfe73fbd50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcfe73fbd50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 14 (Thread 0x7fcfe75fd700 (LWP 1113424)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe75fcd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcfe75fcd50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcfe75fcd50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 13 (Thread 0x7fcfe77fe700 (LWP 1113423)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe77fdd50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcfe77fdd50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcfe77fdd50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 12 (Thread 0x7fcff5521700 (LWP 1113422)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcff5520d50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcff5520d50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcff5520d50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 11 (Thread 0x7fcff5726700 (LWP 1113421)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcff5725d50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcff5725d50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcff5725d50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 10 (Thread 0x7fcfb312b700 (LWP 1113419)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfb312ad50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcfb312ad50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcfb312ad50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 9 (Thread 0x7fcfe7fff700 (LWP 1113417)):
#0  0x00007fd00165e618 in futex_abstimed_wait_cancelable (private=0, abstime=0x7fcfe7ffed50, clockid=0, expected=0, futex_word=0x55b58737d988) at ../sysdeps/nptl/futex-internal.h:320
#1  do_futex_wait (sem=sem@entry=0x55b58737d988, abstime=abstime@entry=0x7fcfe7ffed50, clockid=0) at sem_waitcommon.c:112
#2  0x00007fd00165e743 in __new_sem_wait_slow (sem=0x55b58737d988, abstime=0x7fcfe7ffed50, clockid=0) at sem_waitcommon.c:184
#3  0x000055b5871a4f81 in  ()
#4  0x000055b587141f3a in  ()
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 8 (Thread 0x7fcfb7358700 (LWP 1113416)):
#0  futex_abstimed_wait_cancelable (private=<optimised out>, abstime=0x7fcfb7357ca0, clockid=<optimised out>, expected=0, futex_word=0x55b58738c488) at ../sysdeps/nptl/futex-internal.h:320
#1  __pthread_cond_wait_common (abstime=0x7fcfb7357ca0, clockid=<optimised out>, mutex=0x55b58738c4a0, cond=0x55b58738c460) at pthread_cond_wait.c:520
#2  __pthread_cond_timedwait (cond=0x55b58738c460, mutex=0x55b58738c4a0, abstime=0x7fcfb7357ca0) at pthread_cond_wait.c:656
#3  0x000055b5871fc39e in  ()
#4  0x000055b587207609 in  ()
#5  0x000055b5871a5bc3 in  ()
#6  0x000055b587141f3a in  ()
#7  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#8  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 7 (Thread 0x7fcfe6fff700 (LWP 1113227)):
#0  0x00007fd00155196f in __GI___poll (fds=0x7fcfd8007170, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcff490b1d6 in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007fcff48fc841 in pa_mainloop_poll () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007fcff48fcec3 in pa_mainloop_iterate () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007fcff48fcf70 in pa_mainloop_run () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007fcff490b11d in  () at /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007fcff45e857c in  () at /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-13.99.so
#7  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#8  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 6 (Thread 0x7fcff6c1f700 (LWP 1113225)):
#0  0x00007fd00155196f in __GI___poll (fds=0x7fcfe8016760, nfds=3, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcffcd4e1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcffcd4e533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcffd00be9a in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007fcffcd77931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 5 (Thread 0x7fcff7420700 (LWP 1113224)):
#0  0x00007fd00155196f in __GI___poll (fds=0x55b5881befa0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcffcd4e1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcffcd4e2e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcffc04599d in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
#4  0x00007fcffcd77931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 4 (Thread 0x7fcff7c21700 (LWP 1113223)):
#0  0x00007fd00155196f in __GI___poll (fds=0x55b5881bc190, nfds=2, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcffcd4e1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcffcd4e2e3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcffcd4e331 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fcffcd77931 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#6  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7fd000a6b700 (LWP 1113222)):
#0  0x00007fd001521c6f in __GI___wait4 (pid=1113528, stat_loc=0x7fd000a69554, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x000055b586f9a0bf in  ()
#2  0x000055b586f9a250 in  ()
#3  0x000055b586f47129 in  ()
#4  0x000055b586f99467 in  ()
#5  0x00007fd0016603c0 in <signal handler called> () at /lib/x86_64-linux-gnu/libpthread.so.0
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#7  0x00007fd001461859 in __GI_abort () at abort.c:79
#8  0x00007fd0014cc3ee in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fd0015f6285 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#9  0x00007fd0014d447c in malloc_printerr (str=str@entry=0x7fd0015f44ae "free(): invalid pointer") at malloc.c:5347
#10 0x00007fd0014d5cac in _int_free (av=<optimised out>, p=<optimised out>, have_lock=0) at malloc.c:4173
#11 0x0000000040f2cb13 in  ()
#12 0x000055b58e0ce6a0 in  ()
#13 0x00007fd000a6aca0 in  ()
#14 0x000055b587ef92c0 in  ()
#15 0x0000000000000000 in  ()

Thread 2 (Thread 0x7fd0003ff700 (LWP 1113221)):
#0  futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x55b58738be08) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55b58738be20, cond=0x55b58738bde0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55b58738bde0, mutex=0x55b58738be20) at pthread_cond_wait.c:638
#3  0x000055b5871eedc6 in  ()
#4  0x00007fd001654609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#5  0x00007fd00155e103 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7fd001439780 (LWP 1113220)):
#0  0x00007fd00155196f in __GI___poll (fds=0x55b588335520, nfds=2, timeout=500) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fcffcd4e1ae in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fcffcd4e533 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fcffd576092 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#4  0x0000000040eed000 in  ()
#5  0x000055b587fae6f0 in  ()
#6  0x000055b587efd278 in  ()
#7  0x00007fd000400aa8 in  ()
#8  0x00007fd000403c30 in  ()
#9  0x00007fd000403c80 in  ()
#10 0x000055b587f15400 in  ()
#11 0x00007ffc6c1a55c0 in  ()
#12 0x00007ffc6c1a5460 in  ()
#13 0x0000000000000000 in  ()
[Inferior 1 (process 1113220) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7fd00148218b):0x7fd00148217b  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7fd00148218b  48 8b 84 24 08 01 00 00 64 48 33 04 25 28 00 00  H..$....dH3.%(..
0x7fd00148219b  00 75 26 44 89 c0 48 81 c4 18 01 00 00 c3 0f 1f  .u&D..H.........
0x7fd0014821ab  80 00 00 00 00 48 8b 15 b9 4c 1a 00 f7 d8 41 b8  .....H...L....A.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at GLib.SList:g_free <0x000a2>
	  at GLib.ListBase:Empty <0x001a4>
	  at GLib.ListBase:Dispose <0x0002b>
	  at GLib.ListBase:Finalize <0x00035>
	  at System.Object:runtime_invoke_virtual_void__this__ <0x0008c>
=================================================================
Aborted (core dumped)
```

## On which platforms did you notice this

*  Linux

**Version Used**:

```
$ mono --version
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by bernhardu** [comment]
> 	Managed Stacktrace:
> 	  at <unknown> <0xffffffff>
> 	  at GLib.SList:g_free <0x000a2>
> 	  at GLib.ListBase:Empty <0x001a4>
> 	  at GLib.ListBase:Dispose <0x0002b>
> 	  at GLib.ListBase:Finalize <0x00035>
> 	  at System.Object:runtime_invoke_virtual_void__this__ <0x0008c>

This might be caused by the gtk-sharp2 package 2.12.40 in Debian/Ubuntu.
Upstream release 2.12.41 would contain [this patch](https://github.com/mono/gtk-sharp/commit/72637de6f2e519592f946a5acdf29a334c7bff75), that probably fixes this crash.

(Similar managed backtraces appear in Debian bugs [1028206](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1028220) or [877106](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877106).)

**Comment by Tiedemate** [comment]
I can confirm this for Kubuntu 22.10 x64. It does not crash Pinta, it just freezes for a long time. Eventually Pinta will unfreeze and then the text tool works.
