### ISSUE TITLE
[Wasm][PGAOT] RuntimeError: function signature mismatch

### ISSUE THREAD

**Issue by jeromelaban** [mono/mono#19841]
I have not had much success to extract a repro, it seems specific to the set of methods that are AOTed or not.

## Steps to Reproduce

This line:
https://github.com/unoplatform/Uno.WindowsCommunityToolkit/blob/50ff76113f303a0fe9a1481523a5de71f09f8915/Microsoft.Toolkit.Uwp/Helpers/SystemInformation.cs#L175

Calling this method:
https://github.com/unoplatform/Uno.WindowsCommunityToolkit/blob/50ff76113f303a0fe9a1481523a5de71f09f8915/Microsoft.Toolkit.Uwp/Helpers/ObjectStorage/BaseObjectStorageHelper.cs#L78

### Current Behavior

```
Uno.UI.js:110 Unhandled dispatcher exception: RuntimeError: function signature mismatch (RuntimeError: function signature mismatch
    at Microsoft_Toolkit_Uwp_Microsoft_Toolkit_Uwp_Helpers_SystemInformation_TrackAppUse_Windows_ApplicationModel_Activation_LaunchActivatedEventArgs (<anonymous>:wasm-function[19349]:0xaf4d9e)
    at dynCall_vii (<anonymous>:wasm-function[34983]:0x1041d5b)
    at Module.dynCall_vii (http://localhost:49996/dotnet.js:11308:39)
    at invoke_vii (http://localhost:49996/dotnet.js:12777:5)
    at Microsoft_Toolkit_Uwp_SampleApp_Wasm_Microsoft_Toolkit_Uwp_SampleApp_App__OnLaunchedd__2_MoveNext (<anonymous>:wasm-function[273]:0x21206)
    at aot_wrapper_gsharedvt_out_sig_void_this_ (<anonymous>:wasm-function[26714]:0xee1f55)
    at jit_call_cb (<anonymous>:wasm-function[26872]:0xef5e1a)
    at dynCall_vi (<anonymous>:wasm-function[34982]:0x1041d4f)
    at Module.dynCall_vi (http://localhost:49996/dotnet.js:11301:38)
    at invoke_vi (http://localhost:49996/dotnet.js:12733:5))
```

### Expected Behavior

The method gets executed properly.

## On which platforms did you notice this

**Version Used**: cec64d9b7f4c0ca478f2913dacb766d8ff092d61

**Comment by vargaz** [comment]
Could you attach the binaries which match the offsets in the above trace ? I.e.:
    at  (<anonymous>:wasm-function[19349]:0xaf4d9e)

**Comment by vargaz** [comment]
Alternatively, run the wasm-dis tool from the emscripten sdk, and attach the disassembly of the '19349' function.

**Comment by jeromelaban** [comment]
Here's the function:
[func_19349.txt](https://github.com/mono/mono/files/4685722/func_19349.txt)

And the original file:
[dotnet_issue_19841.zip](https://github.com/mono/mono/files/4685727/dotnet_issue_19841.zip)

**Comment by vargaz** [comment]
Looks like its the _localObjectStorageHelper.Read<long>(nameof(LaunchCount)) call.

**Comment by vargaz** [comment]
Which methods were AOTed ?

**Comment by vargaz** [comment]
I can repro.

**Comment by jeromelaban** [comment]
Thanks! The code that is failing is supposed to have been AOTed completely as it is part of the startup, and the profile should have caught it.
