### ISSUE TITLE
Blazor WASM can be debugged but cannot be released

### ISSUE THREAD

**Issue by zxyao145** [mono/mono#20102]
### Question

I used blazor to create an application that runs correctly in debug state, but I can't publish it. Under release state, I get the following errors:

```
Fatal error in Mono IL Linker
C:\Users\admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime.InteropServices.PInvoke, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'System.Runtime.InteropServices.PInvoke, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
C:\Users\admin\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.0\targets\Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code -532462766.
```
I didn't use DllImport. 
I don't know what happened, and now I have to publish it in debug state, It works well on the docker. 

### Further technical details

ASP.NET Core version: 3.1
blazor WebAssembly 3.2.0
VS 16.6.0

**Comment by marek-safar** [comment]
One of your dependencies depends on System.Runtime.InteropServices.PInvoke assembly. If you don't know which one the easiest solution might be to add System.Runtime.InteropServices.PInvoke NuGet to your project

**Comment by zxyao145** [comment]
> One of your dependencies depends on System.Runtime.InteropServices.PInvoke assembly. If you don't know which one the easiest solution might be to add System.Runtime.InteropServices.PInvoke NuGet to your project


But what's interesting is why can I publish in debug mode?

**Comment by marek-safar** [comment]
> why can I publish in debug mode?

Different tools with different configuration run in debug and release mode

**Comment by zxyao145** [comment]
> Different tools with different configuration run in debug and release mode

Ok, thank you very much! And Nuget didn't have the package "System.Runtime.InteropServices.PInvoke", it exists on myget: https://dotnet.myget.org/feed/dotnet-core/package/nuget/System.Runtime.InteropServices.PInvoke.

Finally, thanks again, because I always thought it was a package that did not exist until I saw the answer and finally found it on myget.
