### ISSUE TITLE
[wasm] function signature mismatch (pinvoke callback)

### ISSUE THREAD

**Issue by SnGmng** [mono/mono#20164]
I get function signature mismatch error if i use pinvoke callback

```csharp
using System;
using System.Runtime.InteropServices;

namespace Test
{
    class MonoPInvokeCallbackAttribute : Attribute
    {
        public MonoPInvokeCallbackAttribute(Type t) { }
    }

    public enum EM_CALLBACK_THREAD_CONTEXT
    {
        MAIN_BROWSER_THREAD = 0x1,
        CALLING_THREAD = 0x2,
    }

    class Program
    {
        private const CallingConvention CallConv = CallingConvention.Winapi;
  
        [UnmanagedFunctionPointer(CallConv)]
        public delegate int em_mouse_callback_func(int eventType, int mouseEvent, int userData);

        [DllImport("emscripten", EntryPoint = "emscripten_set_click_callback_on_thread")]
        public static extern int emscripten_set_click_callback_on_thread(string target, IntPtr userData, bool useCapture, em_mouse_callback_func callback, EM_CALLBACK_THREAD_CONTEXT targetThread = EM_CALLBACK_THREAD_CONTEXT.CALLING_THREAD);

        public static void Main()
        {
            // works, result is S_OK
            var result = emscripten_set_click_callback_on_thread("#btn", IntPtr.Zero, false, MouseEventCallback);
        }

        [MonoPInvokeCallback(typeof(em_mouse_callback_func))]
        private static int MouseEventCallback(int eventType, int mouseEvent, int userData)
        {
            // never gets executed
            Console.WriteLine("clicked");
        }
    }
}
```
Each time i click the button i get this stacktrace
## Stacktrace

```
dotnet.wasm:1 Uncaught RuntimeError: function signature mismatch
    at dynCall_iiii (http://localhost:8080/dotnet.wasm:wasm-function[8889]:0x12b456)
    at Object.mouseEventHandlerFunc [as handlerFunc] (http://localhost:8080/dotnet.js:7394:13)
    at HTMLButtonElement.jsEventHandler (http://localhost:8080/dotnet.js:6424:24)
```

it says function signature mismatch but it is litteraly `iiii` and it uses dynCall_iiii so i dont understand why

pinvoke-table.h generated the following:

```cpp
typedef void  (*WasmInterpEntrySig_0) (int,int,int,int,int);
int wasm_native_to_interp_Test_Program_100663524 (int arg0,int arg1,int arg2) { 
int res;
((WasmInterpEntrySig_0)wasm_native_to_interp_ftndescs [0].func) (&res, &arg0, &arg1, &arg2, wasm_native_to_interp_ftndescs [0].arg);
return res;
}
```

**Comment by HinTak** [comment]
The calling convention? I think most things in mono land is the other one, c<something>.

**Comment by SnGmng** [comment]
@HinTak  I tried CDecl at first and it didnt work. Then I tried Winapi because othe people seem to use winapi like in this issue https://github.com/mono/mono/issues/19837. I get the same error on both cdecl and winapi

**Comment by HinTak** [comment]
Your mouseevent callback takes 3 arguments but on your c side you have 5?

**Comment by SnGmng** [comment]
Thats autogenerated code packager.exe for every callback. The typedef has 5 args but `wasm_native_to_interp_Test_Program_100663524` has 3 like expected.

**Comment by vargaz** [comment]
I get:
JS exception: TypeError: can't access property "addEventListener", eventHandler.target is undefined
registerOrRemoveHandler@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6469:11
__registerMouseEventCallback@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6554:16

_emscripten_set_click_callback_on_thread@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6556:35
emscripten_set_click_callback_on_thread@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js line 1653 > WebAssembly.instantiate:wasm-function[6]:0x0
do_icall@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js line 1653 > WebAssembly.instantiate:wasm-function[285]:0x1602a

**Comment by SnGmng** [comment]
> I get:
> 
> ```
> JS exception: TypeError: can't access property "addEventListener", eventHandler.target is undefined
> registerOrRemoveHandler@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6469:11
> __registerMouseEventCallback@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6554:16
> 
> _emscripten_set_click_callback_on_thread@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js:6556:35
> emscripten_set_click_callback_on_thread@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js line 1653 > WebAssembly.instantiate:wasm-function[6]:0x0
> do_icall@/Users/vargaz/git/wasm/sdks/wasm/bin/interp-hello/dotnet.js line 1653 > WebAssembly.instantiate:wasm-function[285]:0x1602a
> ```

@vargaz The first argument `emscripten_set_click_callback_on_thread` is a css selector, in my sample its "#btn". Looks like you forgot create button html element that has the id `btn`? It cant call the addEventListener function on a target element that doesnt exist. After you add the button it should work.

If you would then press that button the MonoPinvokeCallback should be called, but at this point i get the error `function signature mismatch`.

**Comment by vargaz** [comment]
Could you attach a complete testcase ?

**Comment by devshgraphicsprogramming** [comment]
I'm having the exact same issue with SWIG Directors, C++ can't call any of the delegates passed as function pointers.
