### ISSUE TITLE
code signing is unsuccessful when using the MKBundle fro bundling the .net app (main executable failed strict validation)

### ISSUE THREAD

**Issue by mj198615** [mono/mono#20340]
## Steps to Reproduce

1. Create an application in visual studio for mac. 
2.  Use Mkbundle and bundle the application( )
    we used the below command to execute the Mkbundle 
    mkbundle -o WSMServer --static --simple ./ourapp.exe --machine-config /Library/Frameworks/Mono.framework/Versions/Current/etc/mono/4.5/machine.config --config configfile
 As we were getting the libmono-native-compat.dylib  dll not found execption when using the Mkbundle we have manually copied these libs in our application. This worked for us
3. But it is failing during code singing.

### Current Behavior
The code signing fails.
 /Applications/Myapp: **main executable failed strict validation**

### Expected Behavior

The notarization(code signing ) should be sucessful

## On which platforms did you notice this

[ ] macOS

**Version Used**:
Mono - 6.10.0
MkBundle
Visual Studio for mac

## Stacktrace

```
Please paste the stack trace here if available.
```
Below is the Error when we notarize our application:
codesign says my main executable failed strict validation.
•	Your Mach-O executable does not conform to modern Mach-O layout rules.
•	You may be using a third party development product that hasn't been brought up to date, or post-processed your file in unsupported ways.

**Comment by HinTak** [comment]
See the now closed https://github.com/mono/mono/issues/18826 for some possible hints. (half of the fix went in for the upcoming 6.14, the other half is currently a python script)

**Comment by roslynn** [comment]
Having same issue! Trying to `mkbundle` with `--sdk` version 5.10.1 (which succeeds)
and then when trying to `codesign` it fails with the message:
> main executable failed strict validation

Is there any work around it?

**Comment by HinTak** [comment]
@roslynn see my comment above. Half of the fix went in for 6.13+, and got back-ported to late 6.12's. The other half of the fix is currently a python script you run after mkbundle. So in a nutshell: use late 6.12 or 6.13, plus run the python script after mkbundle.

**Comment by roslynn** [comment]
Hi @HinTak, thanks for quick response! I tried to play with it today and I got nowhere, unfortunately.
The only version of mono which has your fix merged is the latest [Preview - 6.12.100](https://www.mono-project.com/download/preview/).
I downloaded it, installed and in order to be just [absolutely sure I am running correct](https://forums.xamarin.com/discussion/7507/specifying-the-mono-version-to-build-against-on-the-command-line) `mkbundle` I exported mono paths at the top of my script, like:

```
#!/bin/bash
MONO_PREFIX=/Library/Frameworks/Mono.framework/Versions/6.12.0
export DYLD_FALLBACK_LIBRARY_PATH="$MONO_PREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
export LD_LIBRARY_PATH=$MONO_PREFIX/lib:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=$MONO_PREFIX/include
export ACLOCAL_PATH="$MONO_PREFIX/share/aclocal:$ACLOCAL_PATH"
export ACLOCAL_FLAGS="-I $MONO_PATH/share/aclocal $ACLOCAL_FLAGS"
export PKG_CONFIG_PATH="$MONO_PREFIX/lib/pkgconfig:$MONO_PREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
export MONO_GAC_PREFIX="$MONO_PATH:$MONO_GAC_PREFIX"
export PATH="$MONO_PREFIX/bin:$PATH"
```


I run 
```mkbundle --static --simple --sdk Library/Frameworks/Mono.framework/Versions/5.10.1 -o "My Bundle" --library (...)```

which printed correct _6.12.100_ mono version with _5.10.1_ mono version being bundled. It created **My Bundle** and then I invoked your python patch-script from #17881 (with @ylatuya update), like:

```
python <absolute-path-to-script>mono-codesign-fix.py "My Bundle"
```

and it returned:
```
Traceback (most recent call last):
  File "<absolute-path-to-script>mono-codesign-fix.py", line 32, in <module>
    if (c[0].get_cmd_name() == 'LC_SYMTAB'):
AttributeError: 'load_command' object has no attribute 'get_cmd_name'
```

What I doing wrong? The bundle is not signed yet. 😢 😢 😢 
Cheers!

**Comment by HinTak** [comment]
@roslynn my python should be run against the "main executable", which should be `"My Bundle"/Content/MacOS/something` ? It should be a file at least 4MB in size, and possibly quite a lot larger?

**Comment by roslynn** [comment]
@HinTak - I tried running your script with absolute path and with a relative; with a space in the name of the `mkbundle` output and without. 😢 and I get this error every time:

```
Generated My Bundle
Traceback (most recent call last):
  File "<absolute-path>mono-codesign-fix.py", line 20, in <module>
    file_size = stat(input_binary).st_size
OSError: [Errno 2] No such file or directory: 'My Bundle/Content/MacOS/my_app'
```
does it mean anything to you?

**my_app** properties are: 'Unix executable - 762 bytes'
I checked **My Bundle** - 'Application - 119.4 MB'
is that correct (I think it is - it is the similar size when I build it without notarization attempt)

Thank you for your help!

**Comment by HinTak** [comment]
That sounds very wrong . 762 bytes sounds like a shell script. Find the largest single file under "My Bundle"? I suspect you also need to cd inside your "My Bundle" to run my script, due to the space in the path.

**Comment by roslynn** [comment]
OK, I had two errors there - (1) the relative path was still using the name of the app which was hardcoded elsewhere; (2) the location the actual executable was placed under 'Resources/lib' for some reason. 
I realised that when I saw the absolute path of the assembly `code sign` complaints about in the error message (`failing strict validation`).

I adjusted the location, now I got a bit further with the script execution but it is still failing. I invoked it with python 2.7, is that correct?
Opened it in VScode for debugging and this is what I am getting:

```
Traceback (most recent call last):
  File "<absolute-path>mono-codesign-fix.py", line 38, in <module>
    if (c[0].get_cmd_name() == 'LC_SYMTAB'):
```

![Screen Shot 2020-10-01 at 13 04 48](https://user-images.githubusercontent.com/39137049/94808508-23ee1180-03e9-11eb-87f5-a6df1b7011ad.png)

Does it mean anything to you?

**Comment by HinTak** [comment]
Python 2.7 was end-of-life earlier this year. I am using python 3.8 (just what is shipped on fedora) . And v1.14.1 from https://github.com/ronaldoussoren/macholib

**Comment by HinTak** [comment]
@roslynn it looks like you are using an old version of macholib - there was a bug in this part which was fixed in 1.14 : 
https://github.com/ronaldoussoren/macholib/issues/32

**Comment by roslynn** [comment]
First of all - thank you for your help so far I really appreciate it!

The reason I assumed it was still `python 2` because I thought that usually to indicate that `python 3` was supposed to be used people included it in the first line, like this 

```
#!/usr/bin/env python3
```

But I presume I was wrong, or the world moved on and 3.x is standard now 😄 

I run your script with `python 3.8.5`, needed to install `macholib` via `pip`, but that's ok. And finally it did output:
```
entry(LC_SYMTAB):
	 LC_SYMTAB <symtab_command symoff=4202880 nsyms=8172 stroff=4336300 strsize=226488> b''
365214024 4562788
4th(LC_SEGMENT_64/__LINKEDIT):
	 LC_SEGMENT_64 <segment_command_64 segname=b'__LINKEDIT\x00\x00\x00\x00\x00\x00' vmaddr=4299210752 vmsize=409444 fileoff=4153344 filesize=409444 maxprot=7 initprot=1 nsects=0 flags=0> []
365214024 4562788 True
```

which after trying `codesign --verbose` it outputted:
```
signed Mach-O thin (x86_64) [My App]
``` 

I updated setup on our mac build agent and run notarization and - it got accepted! 
I was really happy, the installer after double-clicking opened with no troubles this time but after installing my app, it does not run, only sad box is displayed. 😢 

![Screen Shot 2020-10-01 at 22 30 32](https://user-images.githubusercontent.com/39137049/94865739-098e5500-0436-11eb-91e7-39869526d032.png)

**Comment by HinTak** [comment]
Python 2 was end-of-life earlier this year, so `python` means 3 these days. Glad to hear that the signing and notarization part works now - that was why I worked on the fixes/workarounds. Have you tried clicking on the "?" at the right bottom side of the sad box? It might give you some further info. I am not a mac user myself - it just happened that one of the things I do has a large mac user base.

What's the name of the file under `Resources/lib`? I don't need the actual name, just how it is in relation to the `My Bundle` part. I'll put that in as a comment notes in the code.

Please feel free to buy me a beer with the donation links at the bottom of https://hintak.github.io/ .

**Comment by roslynn** [comment]
Apologies @HinTak for the delay, I was asked to change priorities and move to different task briefly. As to beer, I am happy that I met friends willing to help, I think having a virtual beer sounds great :) 🍺 🍻 (btw, did not know you could do that - is that popular?)

I am back on this now, started to investigate the issue of the app not running after header size adjustments (your script - which on the positive note does fix the notarization issue).

So, the app (`mkbundle`-ed) is invoked from the shell script located in "`Contents\MacOS\myapp`" which pre-sets some environment variables/paths (like `DYLD_LIBRARY_PATH` etc)
People suggested [permissions issues](https://stackoverflow.com/questions/58325615/mono-run-time-exception-on-catalina-macos) but adjusting them did not solve the problem.

If I do not modify the bundle with your script - the application is invoked correctly (runs as intended).
When I do modify the bundle - I encounter the same issue mentioned in [#15815](https://github.com/mono/mono/issues/15815), I get:
```
$ cd '/Applications/My\ App.app/Contents/Resources/lib/
$ ./My\ App
Usage is: mono [options] program [program-options]

Development:
    --aot[=<options>]      Compiles the assembly to native code
    --debug[=<options>]    Enable debugging support, use --help-debug for details
    --debugger-agent=options Enable the debugger agent
    --profile[=profiler]   Runs in profiling mode with the specified profiler module
    --trace[=EXPR]         Enable tracing, use --help-trace for details
    --jitmap               Output a jit method map to /tmp/perf-PID.map
    --help-devel           Shows more options available to developers

Runtime:
    --config FILE          Loads FILE as the Mono config
    --verbose, -v          Increases the verbosity level
    --help, -h             Show usage information
    --version, -V          Show version information
    --runtime=VERSION      Use the VERSION runtime, instead of autodetecting
    --optimize=OPT         Turns on or off a specific optimization
                           Use --list-opt to get a list of optimizations
    --security[=mode]      Turns on the unsupported security manager (off by default)
                           mode is one of cas, core-clr, verifiable or validil
    --attach=OPTIONS       Pass OPTIONS to the attach agent in the runtime.
                           Currently the only supported option is 'disable'.
    --llvm, --nollvm       Controls whenever the runtime uses LLVM to compile code.
    --gc=[sgen,boehm]      Select SGen or Boehm GC (runs mono or mono-sgen)
    --arch=[32,64]         Select architecture (runs mono32 or mono64)
    --handlers             Install custom handlers, use --help-handlers for details.
    --aot-path=PATH        List of additional directories to search for AOT images.
```

I had an idea that it might be just another bug in mkbundle of the preview version, so I built the app again with _mono 6.12.100_ without header amendments (notarization failed) but after installing it the app run as usual :( 

So I draw the conclusions that the header size adjustments must be breaking the bundle.
Do you have any idea what/why the bundle might be broken? Or how to fix it?

**Comment by HinTak** [comment]
@roslynn - I got a "Cheers!" from a Patrycja earlier today - if that's you, thanks a lot! 

I have seen this problem before:

```
$ ./My\ App
Usage is: mono [options] program [program-options]
```

And I know the cause / answer: for the mkbundle result to work as intended, the mono binary needs to be able to find itself, by looking at `argv[0]` and finding itself in as a file. So you should not put any redirection anywhere: e.g. If `My App` is a symbolic link to where the big mkbundle result is, it won't work, because `argv[0]` contains the location of the symlink instead of the file. Does it make sense? I think I filed a documentation bug / fix on this a while ago. I'll go and look up the issue / bug id now.

**Comment by HinTak** [comment]
@roslynn the issue I filed was https://github.com/mono/mono/issues/10470 , which explains how mkbundle works a bit. Have a look and see if it give you any clues on solving yours?

**Comment by HinTak** [comment]
@roslynn my guess is that your shell script needs to do something like:

```
...
`pwd`/../Resources/lib/My\ App
```

Instead of what you may have been doing, something similar to this?

```
...
cd ../Resources/lib
./My\ App
```

Basically, you need to make sure that `argv[0]` as see from inside `My\ App`, is where `My\ App` is actually located. Use "`pwd`" to prepend full paths.

**Comment by HinTak** [comment]
@roslynn Argh, you did not read 
https://github.com/mono/mono/issues/18826 carefully - if you are mixing versions (not a good idea...) , you need to use older mkbundle but bundling most current mono runtime. Not the other way round. The half of the fix that has gotten into mono is in the runtime's launcher. The python script's functionality is be included and merged into mkbundle itself eventually, but not yet.

I have back-ported the runtime patch to 5.20 - you can copy `mono-sgen` from

https://github.com/HinTak/mono-modification/tree/macosx-10.13/mono-5.20.1.34/mono/mini overwriting your `.../bin/mono`. You can try back-porting to 5.10 but that's really old... The current FontVal (2.1.6) is made with 5.20 - overwriting one file of the official mono 5.20 partially with mine, run mkbundle, then run the script.

Btw, according to Google, Patrycja is likely 20 miles / 30 minutes drive west of me. Small world - an actual 🍺 🍻 across a real table is possible! If it wasn't for the social distancing etc, I would probably say come bring your laptop and offer to buy me dinner. That's the well-known but small university town a little east.

**Comment by HinTak** [comment]
#10478 #10479 #10490 were all about using mkbundle with mixed versions. Hence not good idea... 

Mkbundle's fetch-target result ends up in `~/.mono`, and that's where the `../bin/mono` which needs to be overwritten with mine.
