### ISSUE TITLE
Fatal error in Mono IL Linker - Failed to resolve assembly - Error while processing references of 'Microsoft.Azure.SignalR'

### ISSUE THREAD

**Issue by dme-development** [mono/mono#20401]
## Steps to Reproduce

1. Create a Blazor WASM project
2. Add Microsoft.Azure.SignalR, Version=1.5.1.0 nuget package
3. Build project in release mode

### Current Behavior

Build in release mode fails due to Mono IL Linker a problem.

### Expected Behavior

Build without issues.

## On which platforms did you notice this

[ X] Windows

**Version Used**:

Microsoft Visual Studio Professional 2019
Version 16.7.3
VisualStudio.16.Release/16.7.3+30503.244
Microsoft .NET Framework
Version 4.8.04084

Mono Debugging for Visual Studio   16.7.5 (112c7bc)
Support for debugging Mono processes with Visual Studio.

## Stacktrace

```
Fatal error in Mono IL Linker
C:\Users\xxxxxxx\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets(326,5): error : Unhandled exception. Mono.Linker.LoadException: Error while processing references of 'Microsoft.Azure.SignalR, Version=1.5.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Identity.Client, Version=4.9.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Microsoft.Identity.Client, Version=4.9.0.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae'
   at Mono.Cecil.BaseAssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.AssemblyResolver.Resolve(AssemblyNameReference name, ReaderParameters parameters)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope)
   at Mono.Linker.LinkContext.ResolveReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.LoadReferencesStep.ProcessReferences(AssemblyDefinition assembly)
   at Mono.Linker.Steps.LoadReferencesStep.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Mono.Linker.Driver.Run(ILogger customLogger)
   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
   at Mono.Linker.Driver.Main(String[] args)
C:\Users\xxxxxxx\.nuget\packages\microsoft.aspnetcore.components.webassembly.build\3.2.1\targets\Blazor.MonoRuntime.targets(326,5): error : ILLink failed with exit code -532462766.
```

**Comment by dme-development** [comment]
Only way to fix release build right now, is to disable Blazor WebAssembly Linking: <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>, but that's not really what we want to do.

**Comment by CoffeeFlux** [comment]
cc: @lewing
