### ISSUE TITLE
mono-symbolicate fails to symbolicate iOS stack trace

### ISSUE THREAD

**Issue by bruno-garcia** [mono/mono#20433]
I'm building a Xamarin iOS app and trying to symbolicate the stack trace to get line numbers.

Similar to this #11625 but no outcome there.

## Steps to Reproduce

1. Pull this [repo](https://github.com/bruno-garcia/sentry-dotnet/tree/bfea20efbd0fb42ffa6ad95f4d0b06413cadc385/samples/Sentry.Samples.Mobile.iOS)
2. Build the repo (the build script uses `dotnet` so doesn't build the Xamarin samples)
3. Run the iOS app in release mode (Mono AOT, I used a real iPhone)

Get the mangled stack trace:
```
System.Net.CookieException: One of the identified items was in an invalid format.
  at Sentry.Samples.Mobile.MainPage+InnerCode.GiveMeCookieAsync (System.Threading.CancellationToken token) <0x103b08160 + 0x000d0> in <ad0e3f7af6e6494f8e208646eca2ae37#31b1f99c40c122d91bc8a9e4de2b2ee1>:0 
  at Sentry.Samples.Mobile.MainPage.SomethingAsync (System.Threading.CancellationToken token) <0x103b089c0 + 0x00173> in <ad0e3f7af6e6494f8e208646eca2ae37#31b1f99c40c122d91bc8a9e4de2b2ee1>:0 
  at Sentry.Samples.Mobile.MainPage.TryCatchAsync (System.Object sender, System.EventArgs e) <0x103b08580 + 0x00227> in <ad0e3f7af6e6494f8e208646eca2ae37#31b1f99c40c122d91bc8a9e4de2b2ee1>:0 
```

Try to symbolicate with `mono-symbolicate` passing the right debug files.

Please note I didn't use `mono-symbolicate store-symbols` since building the iOS project already gave me the `mSYM` directory with the IL module id as folder, which is what `store-symbols` does.

### Current Behavior

The stack trace can't be demangled. Errors with:

```
System.Net.CookieException: One of the identified items was in an invalid format.
Unhandled exception. System.Exception: Could not find data for method token 6000026
   at Mono.SeqPointInfo.GetILOffset(Int32 methodToken, UInt32 methodIndex, Int32 nativeOffset) in SeqPointInfo.cs:line 143
   at Mono.AssemblyLocationProvider.TryResolveLocation(StackFrameData sfData, SeqPointInfo seqPointInfo, Location& location) in AssemblyLocationProvider.cs:line 89
   at Mono.SymbolManager.TryResolveLocation(StackFrameData sfData, Location& location) in SymbolManager.cs:line 54

```

### Expected Behavior

Line numbers.

## On which platforms did you notice this

[x] macOS 
[ ] Linux
[ ] Windows

**Version Used**:

`Mono JIT compiler version 6.10.0.95 (2019-12/f2379f2d665 Fri Mar 13 12:13:52 EDT 2020)`

Note that I used Mono.Cecil from NuGet, version `0.11.1`. I didn't build `mono-symbolicate` by building the while `mono/mono` repo.

I ran the program with `dotnet`, pinned the SDK to the latest stable: `3.1.301`

```
22:00 $ dotnet --version
3.1.301
```

**Comment by bruno-garcia** [comment]
I'm happy to attempt to provide another repro if that helps. I'd like to build on top of `mono-symbolicate` but before I move on I'd like to make sure this works.

**Comment by MaximMikhisor** [comment]
We have similar error "Could not find data for method token XXXXXX" for iOS case.

Downloaded **mono-symbolicate** source code and used debugger to find out what problem is.
In our case problem was that all lines inside exception message had same **<mvid#aotid>** values. 
Our project consist of many our libraries.  **<mvid#aotid>** suppose to correspond to each library, and as result **<mvid#aotid>** values inside exception need to be different.

Could assume two options: or Mono generate wrong exception data during crash, or data inside folder mSYM is created in wrong way.

Our solution was to merge all our libs into one final exe.

Another possible options was to change source code  of **mono-symbolicate** to search proper data inside mSYM folder, but we decided do not do it.
