### ISSUE TITLE
Linux File Read Errors

### ISSUE THREAD

**Issue by n432sean** [mono/mono#20625]
Steps to reproduce
1. Create a multi-threaded program on linux that reads many large files simultaneously
2. Spawn child processes that it communicates with via stdin/stdout
3. Occasionally dispose of child processes

With mono 6.12.0.90 on Linux, we are getting strange exceptions due to the data from the large file reads being incorrect. This only occurs when the unrelated child processes are performing stdin/stdout or are being disposed.

Previously, with 6.4.0.198, in the same scenarios, we would get this exception.
```
System.ObjectDisposedException Safe handle has been closed  at System.Runtime.InteropServices.SafeHandle.DangerousAddRef (System.Boolean& success) [0x0001c] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.MonoIO.Read (System.Runtime.InteropServices.SafeHandle safeHandle, System.Byte[] dest, System.Int32 dest_offset, System.Int32 count, System.IO.MonoIOError& error) [0x00002] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.FileStream.ReadData (System.Runtime.InteropServices.SafeHandle safeHandle, System.Byte[] buf, System.Int32 offset, System.Int32 count) [0x00002] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.FileStream.ReadInternal (System.Byte[] dest, System.Int32 offset, System.Int32 count) [0x00026] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.FileStream.Read (System.Byte[] array, System.Int32 offset, System.Int32 count) [0x000a1] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.Stream+<>c.<BeginReadInternal>b__40_0 (System.Object <p0>) [0x0000b] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task`1[TResult].InnerInvoke () [0x0002b] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.Execute () [0x00000] in <3af0b575ced1452ebd604493c1bf5da9>:0 
--- End of stack trace from previous location where exception was thrown ---
 
  at System.IO.Stream.EndRead (System.IAsyncResult asyncResult) [0x0004d] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.FileStream.EndRead (System.IAsyncResult asyncResult) [0x00016] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Diagnostics.AsyncStreamReader.ReadBuffer (System.IAsyncResult ar) [0x0000e] in <c694b0fd1ad8468e96f9b7ad952c434e>:0 
  at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback (System.Object completedTask) [0x00007] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke (System.Threading.Tasks.Task completingTask) [0x00041] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.FinishContinuations () [0x0007a] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.FinishStageThree () [0x0003c] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.FinishStageTwo () [0x000a1] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.Finish (System.Boolean bUserDelegateExecuted) [0x0002e] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.ExecuteWithThreadLocal (System.Threading.Tasks.Task& currentTaskSlot) [0x0004b] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.ExecuteEntry (System.Boolean bPreventDoubleExecution) [0x0004a] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <3af0b575ced1452ebd604493c1bf5da9>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <3af0b575ced1452ebd604493c1bf5da9>:0 
Additional information: Safe handle has been closed 
```

I think the errors we are now seeing relate to this comment, "Ieaving Unix not working well is fine too imho. I not sure Unix stands a chance in general of working well anyway. Async I/o is an area of active Linux kernel development, still, decades in."

_Originally posted by @jaykrell in https://github.com/mono/mono/issues/16793#issuecomment-530751274_

## On which platforms did you notice this

[ ] macOS
[x ] Linux
[ ] Windows

**Version Used**:  6.12.0.90

**Comment by n432sean** [comment]
Here is a small application that demonstrates the issue.
```
using System;
using System.Diagnostics;

namespace FileReadError
{
    class MainClass
    {
        public static void Main(string[] args)
        {
            // Create some data files to read below
            for (int j = 0; j < 10; j++)
            {
                if (!System.IO.File.Exists($"data{j}.bin"))
                {
                    using (var writer = System.IO.File.Create($"data{j}.bin"))
                    {
                        for (int i = 0; i < 10000000; i++)
                        {
                            writer.Write(BitConverter.GetBytes(i), 0, sizeof(int));
                        }
                        writer.Flush();
                        writer.Close();
                    }
                }
            }

            while(true)
            {
                var tasks = new System.Collections.Generic.List<System.Threading.Tasks.Task>();
                for (int j = 0; j < 10; j++)
                {
                    int n = j; // don't let j increment inside Action below
                    // Spin up a child process to make unused copies of files
                    tasks.Add(System.Threading.Tasks.Task.Run(() =>
                    {
                        using (var proc = new Process())
                        {
                            proc.StartInfo.FileName = "cp";
                            proc.StartInfo.Arguments = $"data{n}.bin data{n}.copy";
                            proc.StartInfo.RedirectStandardOutput = true;
                            proc.StartInfo.RedirectStandardError = true;
                            proc.OutputDataReceived += (s, o) => Console.Write(".");
                            proc.ErrorDataReceived += (s, o) => Console.Write(".");
                            proc.StartInfo.CreateNoWindow = true;
                            proc.StartInfo.UseShellExecute = false;
                            bool success = proc.Start();
                            Console.WriteLine("Proc started");
                            proc.BeginErrorReadLine();
                            proc.BeginOutputReadLine();
                            bool cleanExit = proc.WaitForExit(1000);
                            Console.WriteLine(cleanExit? "Proc done" : "Closing proc");
                        }
                    }));
                    // In parallel, read our 10 files, and check the values being read
                    tasks.Add(System.Threading.Tasks.Task.Run(() =>
                    {
                        Console.WriteLine("Starting read.");
                        var buff = new byte[sizeof(int)];
                        using (var reader = new System.IO.FileStream($"data{n}.bin", System.IO.FileMode.Open))
                        {
                            for (int i = 0; i < 10000000; i++)
                            {
                                reader.Read(buff, 0, buff.Length);
                                int read = BitConverter.ToInt32(buff, 0);
                                if (read != i)
                                {
                                    throw new ApplicationException($"Read Error: expected {i}, but was {read}");
                                }
                            }
                            Console.WriteLine("Read OK");
                        }
                    }));
                }
                tasks.ForEach(task => task.Wait());
            }
        }
    }
}
```
The application will run for a few iterations without issue, but in less than a minute on Red Hat Enterprise Linux with mono 6.12.0.90, it with throw a read error like the following.
```
Unhandled Exception:
System.AggregateException: One or more errors occurred. (Read Error: expected 8233984, but was 8234240) ---> System.ApplicationException: Read Error: expected 8233984, but was 8234240
  at FileReadError.MainClass+<>c__DisplayClass0_0.<Main>b__2 () [0x00057] in /Projects/FileReadError/FileReadError/Program.cs:84 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2759 
  at System.Threading.Tasks.Task.Wait () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2625 
  at FileReadError.MainClass+<>c.<Main>b__0_0 (System.Threading.Tasks.Task task) [0x00000] in /Projects/FileReadError/FileReadError/Program.cs:91 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <6de68d9ed0b943838b4ddc538c95c31e>:0 
  at FileReadError.MainClass.Main (System.String[] args) [0x000fb] in /Projects/FileReadError/FileReadError/Program.cs:91 
---> (Inner Exception #0) System.ApplicationException: Read Error: expected 8233984, but was 8234240
  at FileReadError.MainClass+<>c__DisplayClass0_0.<Main>b__2 () [0x00057] in /Projects/FileReadError/FileReadError/Program.cs:84 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 <---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. (Read Error: expected 8233984, but was 8234240) ---> System.ApplicationException: Read Error: expected 8233984, but was 8234240
  at FileReadError.MainClass+<>c__DisplayClass0_0.<Main>b__2 () [0x00057] in /Projects/FileReadError/FileReadError/Program.cs:84 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00013] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2029 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2759 
  at System.Threading.Tasks.Task.Wait () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2625 
  at FileReadError.MainClass+<>c.<Main>b__0_0 (System.Threading.Tasks.Task task) [0x00000] in /Projects/FileReadError/FileReadError/Program.cs:91 
  at System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) [0x0001e] in <6de68d9ed0b943838b4ddc538c95c31e>:0 
  at FileReadError.MainClass.Main (System.String[] args) [0x000fb] in /Projects/FileReadError/FileReadError/Program.cs:91 
---> (Inner Exception #0) System.ApplicationException: Read Error: expected 8233984, but was 8234240
  at FileReadError.MainClass+<>c__DisplayClass0_0.<Main>b__2 () [0x00057] in /Projects/FileReadError/FileReadError/Program.cs:84 
  at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2476 
  at System.Threading.Tasks.Task.Execute () [0x00000] in /builddir/build/BUILD/mono-6.12.0.90/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2319 <---
```

**Comment by n432sean** [comment]
@lateralusX

**Comment by n432sean** [comment]
@lateralusX 
I installed the following version of dotnet
```
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     rhel
 OS Version:  7
 OS Platform: Linux
 RID:         rhel.7-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  5.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

```
When I `dotnet run` the program above, I don't get the error (at least running a couple of minutes). When I `dotnet run --clr=mono` (not sure if that is the right command), I don't see the error either (at least not within a minute). Is that what you were asking?

**Comment by n432sean** [comment]
After running about an hour with dotnet, I got the following error (which is more acceptable than an incorrect read).
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Resource temporarily unavailable)
 ---> System.ComponentModel.Win32Exception (11): Resource temporarily unavailable
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at FileReadError.MainClass.<>c__DisplayClass0_0.<Main>b__1() in Projects/dotnet_read_test/Program.cs:line 46
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at FileReadError.MainClass.<>c.<Main>b__0_0(Task task) in Projects/dotnet_read_test/Program.cs:line 74
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at FileReadError.MainClass.Main(String[] args) in Projects/dotnet_read_test/Program.cs:line 74
```

**Comment by n432sean** [comment]
Note that we aren't able to use dotnet instead of mono, because we need winforms. We need the file read issue fixed in mono.

**Comment by n432sean** [comment]
With the example program above, I am able to workaround the error if I don't use OutputDataReceived , ErrorDataReceived, BeginErrorReadLine, BeginOutputReadLine, and instead use StandardOutput and StandardError streams, and Close() them. When using those async methods, it appears that the read operation can still write to memory after they are done being used. This is similar to the issue lateralusX fixed for Windows by canceling the async read. On linux, the read isn't canceled. The read can still write to the memory after the memory has been garbage collected and reassigned elsewhere (such as an unrelated FileStream).
