### ISSUE TITLE
SIGSEGV on Raspberry Pi

### ISSUE THREAD

**Issue by oligu** [mono/mono#20698]
## Steps to Reproduce

1. Install mono on a Raspberry Pi with Raspbian Buster
2. Try to import clr
3. 

### Current Behavior

```console
pi@raspi:~ $ python3 -c "import clr"

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
         (No frames) 


=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x3017528416x from 0x3069958864x
Could not exec mono-hang-watchdog, expected on path '/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x3069958864x
Finished thread summarizer pause from 0x3069958864x.
Failed to create breadcrumb file (null)/crash_hash_0x0

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 8088]
[New LWP 8089]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__waitpid (options=0, stat_loc=0xbec8777c, pid=8095) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
  Id   Target Id                                  Frame 
* 1    Thread 0xb6fbdad0 (LWP 8087) "python3"     __waitpid (options=0, stat_loc=0xbec8777c, pid=8095) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0xb5bff460 (LWP 8088) "SGen worker" futex_wait_cancelable (private=0, expected=0, futex_word=0xb665b290) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0xb3dbd460 (LWP 8089) "Finalizer"   0xb6f0c088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0xb6653900) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0xb3dbd460 (LWP 8089)):
#0  0xb6f0c088 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=1, futex_word=0xb6653900) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0xb6653900, abstime=0x0) at sem_waitcommon.c:115
#2  0xb6f0c1f4 in __new_sem_wait_slow (sem=0xb6653900, abstime=0x0) at sem_waitcommon.c:282
#3  0xb64ec274 in ?? () from /usr/lib/libmonosgen-2.0.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xb5bff460 (LWP 8088)):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0xb665b290) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x0, cond=0xb665b268) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0xb665b268, mutex=0x0) at pthread_cond_wait.c:655
#3  0xb6540c44 in ?? () from /usr/lib/libmonosgen-2.0.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xb6fbdad0 (LWP 8087)):
#0  __waitpid (options=0, stat_loc=0xbec8777c, pid=8095) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  __waitpid (pid=8095, stat_loc=0xbec8777c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:25
#2  0xb636a31c in ?? () from /usr/lib/libmonosgen-2.0.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 8087) detached]

=================================================================
        Basic Fault Address Reporting
=================================================================
instruction pointer is NULL, skip dumping
=================================================================
        Managed Stacktrace:
=================================================================
=================================================================
Aborted
```

### Expected Behavior

No crash.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:
```console
Mono JIT compiler version 6.12.0.107 (tarball Thu Dec 10 05:44:54 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
Please paste the stack trace here if available.
```

**Comment by oligu** [comment]
This seems not to be a mono issue, but one of https://github.com/pythonnet/pythonnet/issues/1351.
