### ISSUE TITLE
Mono crashing on ubuntu-server 22.04 fresh install on RaspberryPi4

### ISSUE THREAD

**Issue by mvfpoa** [mono/mono#21469]
## Steps to Reproduce

1. Install Ubuntu Server 32 bits on a SD card and start ubuntu on a rpi4
2. install xserver-xorg, install libgtk2.0-0
3. follow the instructions on https://www.mono-project.com/download/stable/#download-lin-ubuntu
4. test the installation with console and Winforms sources from https://www.mono-project.com/docs/getting-started/mono-basics/
### Current Behavior
5. apps runs
### Expected Behavior
6. running winforms sample crashes

## On which platforms did you notice this

[ ] macOS
[X] Ubuntu Linux ARM on Raspberry pi 4
[ ] Windows

**Version Used**: 
Mono JIT compiler version 6.12.0.122 (tarball Mon Feb 22 17:54:19 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       normal
        Notifications: epoll
        Architecture:  armel,vfp+hard
        Disabled:      none
        Misc:          softdebug
        Interpreter:   yes
        LLVM:          yes(610)
        Suspend:       preemptive
        GC:            sgen (concurrent by default)

## Stacktrace

```
=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
         (No frames)


=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x3059364704x from 0x3069136224x
Entering thread summarizer pause from 0x3069136224x
Finished thread summarizer pause from 0x3069136224x.
Failed to create breadcrumb file (null)/crash_hash_0x416b03301

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 15253]
[New LWP 15254]
Mono support loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
46      ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
  Id   Target Id                                   Frame
* 1    Thread 0xb6ef4d60 (LWP 15252) "mono"        __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  2    Thread 0xb5fff360 (LWP 15253) "SGen worker" __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
  3    Thread 0xb65a3360 (LWP 15254) "Finalizer"   __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46

Thread 3 (Thread 0xb65a3360 (LWP 15254) "Finalizer"):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6b49106 in __futex_abstimed_wait_common32 (private=<optimized out>, cancel=<optimized out>, abstime=<optimized out>, op=<optimized out>, expected=<optimized out>, futex_word=<optimized out>) at futex-internal.c:40
#2  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x72e528, expected=expected@entry=1, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:99
#3  0xb6b491d4 in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x72e528, expected=expected@entry=1, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#4  0xb6b52572 in do_futex_wait (sem=sem@entry=0x72e528, abstime=0x0, clockid=0) at sem_waitcommon.c:116
#5  0xb6b52630 in __new_sem_wait_slow64 (sem=0x72e528, abstime=0x0, clockid=0) at sem_waitcommon.c:284
#6  0x005e97ea in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0xb5fff360 (LWP 15253) "SGen worker"):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6b49106 in __futex_abstimed_wait_common32 (private=<optimized out>, cancel=<optimized out>, abstime=<optimized out>, op=<optimized out>, expected=<optimized out>, futex_word=<optimized out>) at futex-internal.c:40
#2  __futex_abstimed_wait_common (futex_word=futex_word@entry=0x736290, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0, cancel=cancel@entry=true) at futex-internal.c:99
#3  0xb6b491d4 in __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x736290, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at futex-internal.c:139
#4  0xb6b4b394 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x73622c, cond=0x736268) at pthread_cond_wait.c:503
#5  ___pthread_cond_wait (cond=0x736268, mutex=0x73622c) at pthread_cond_wait.c:627
#6  0x0062dd1c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xb6ef4d60 (LWP 15252) "mono"):
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:46
#1  0xb6b778e8 in __GI___wait4_time64 (pid=15259, stat_loc=0xbea9482c, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:35
#2  0x0048ec6e in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 15252) detached]

=================================================================
        Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0xb6b4a5b0):0xb6b4a5a0  8c 00 00 00 8a 3a 0c 00 2d e9 f0 4f 87 b0 00 bf  .....:..-..O....
0xb6b4a5b0  47 6a fb 08 00 f0 7a 81 04 46 ff 01 05 46 ff b2  Gj....z..F...F..
0xb6b4a5c0  54 f8 20 3f 0e e0 43 f0 01 01 54 e8 00 2f 9a 42  T. ?..C...T../.B
0xb6b4a5d0  05 d1 44 e8 00 10 00 28 f7 d1 bf f3 5b 8f 93 42  ..D....(....[..B

=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at System.Windows.Forms.Theme:get_MenuAccessKeysUnderlined <0x0000f>
          at System.Windows.Forms.SystemInformation:get_MenuAccessKeysUnderlined <0x00023>
          at System.Windows.Forms.Control:.ctor <0x0026b>
          at System.Windows.Forms.Control:.ctor <0x00037>
          at System.Windows.Forms.WindowsFormsSynchronizationContext:.cctor <0x0002b>
          at System.Object:runtime_invoke_void <0x0007b>
          at <unknown> <0xffffffff>
          at System.Windows.Forms.Control:.ctor <0x0002b>
          at System.Windows.Forms.ScrollableControl:.ctor <0x00013>
          at System.Windows.Forms.ContainerControl:.ctor <0x00033>
          at System.Windows.Forms.Form:.ctor <0x000e7>
          at HelloWorld:.ctor <0x00013>
          at HelloWorld:.ctor <0x00037>
          at HelloWorld:Main <0x0002b>
          at System.Object:runtime_invoke_void <0x000e3>
=================================================================
Aborted (core dumped)```

NOTE:
* installing mono version from apt repository also crashes

**Comment by homeseerwu** [comment]
Seeing the same on Raspberry Pi 3 with Debian Bullseye (with Desktop).

```
mono -V
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3.2 Mon Jul 12 07:04:24 UTC 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
```

Simple Winforms app with no PInvoke. Only linked assembly is Newtonsoft's JSON parser. App starts from a desktop terminal window then:
```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	 (No frames) 


=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x74723440 from 0x76fba240
Entering thread summarizer pause from 0x76fba240
Finished thread summarizer pause from 0x76fba240.

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 1858]
[New LWP 1859]
Mono support loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
0x76dbf034 in __GI___wait4 (pid=1861, stat_loc=0x7e93d7b0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
27	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
  Id   Target Id                                  Frame 
* 1    Thread 0x76fba240 (LWP 1857) "mono"        0x76dbf034 in __GI___wait4 (pid=1861, stat_loc=0x7e93d7b0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
  2    Thread 0x763ff440 (LWP 1858) "SGen worker" futex_wait_cancelable (private=0, expected=0, futex_word=0x447698) at ../sysdeps/nptl/futex-internal.h:186
  3    Thread 0x74723440 (LWP 1859) "Finalizer"   futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323

Thread 3 (Thread 0x74723440 (LWP 1859) "Finalizer"):
#0  futex_abstimed_wait_cancelable (private=0, abstime=0x0, clockid=0, expected=1, futex_word=0x43f73c) at ../sysdeps/nptl/futex-internal.h:323
#1  do_futex_wait (sem=sem@entry=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:117
#2  0x76eaec90 in __new_sem_wait_slow (sem=0x43f73c, abstime=0x0, clockid=0) at sem_waitcommon.c:285
#3  0x002c2120 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 (Thread 0x763ff440 (LWP 1858) "SGen worker"):
#0  futex_wait_cancelable (private=0, expected=0, futex_word=0x447698) at ../sysdeps/nptl/futex-internal.h:186
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x0, cond=0x447670) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x447670, mutex=0x0) at pthread_cond_wait.c:638
#3  0x00327c84 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0x76fba240 (LWP 1857) "mono"):
#0  0x76dbf034 in __GI___wait4 (pid=1861, stat_loc=0x7e93d7b0, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
#1  0x0009f73c in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
[Inferior 1 (process 1857) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x76eac5c0):0x76eac5b0  bc ff ff ea 98 70 00 00 f0 4f 2d e9 14 d0 4d e2  .....p...O-...M.
0x76eac5c0  24 50 90 e5 a5 31 b0 e1 28 01 00 0a 00 c0 a0 e1  $P...1..(.......
0x76eac5d0  01 50 15 e2 20 30 bc e5 00 e0 a0 e1 80 50 a0 13  .P.. 0.......P..
0x76eac5e0  0a 00 00 ea 01 10 83 e3 9f 2f 9c e1 03 00 52 e1  ........./....R.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at System.Windows.Forms.Theme:get_MenuAccessKeysUnderlined <0x0000f>
	  at System.Windows.Forms.SystemInformation:get_MenuAccessKeysUnderlined <0x00023>
	  at System.Windows.Forms.Control:.ctor <0x00287>
	  at System.Windows.Forms.Control:.ctor <0x00037>
	  at System.Windows.Forms.WindowsFormsSynchronizationContext:.cctor <0x0002b>
	  at System.Object:runtime_invoke_void <0x0007b>
	  at <unknown> <0xffffffff>
	  at System.Windows.Forms.Control:.ctor <0x0004b>
	  at System.Windows.Forms.ScrollableControl:.ctor <0x00013>
	  at System.Windows.Forms.ContainerControl:.ctor <0x00033>
	  at System.Windows.Forms.Form:.ctor <0x000d7>
	  at AirQuality.Form1:.ctor <0x00023>
	  at AirQuality.Form1:.ctor <0x00037>
	  at AirQuality.Program:Main <0x00033>
	  at System.Object:runtime_invoke_void <0x000e3>
=================================================================
Aborted

```
