### ISSUE TITLE
Unable to build mono in flatpaks

### ISSUE THREAD

**Issue by bbhtt** [mono/mono#21492]
## Steps to Reproduce

I haven't tried building in my host machine to see if I get the same issue but the issue persistently occurs with a Flatpak manifest which uses the GNOME runtime 42 and possible also 41. 

1. Install `flatpak-builder` https://github.com/flatpak/flatpak-builder, it's packaged by most Linux distributions.
2. Create a minimal app manifest to build mono with the GNOME 42 runtime:

```
$ cat com.app.app.yml

app-id: com.app.app
sdk: org.gnome.Sdk
runtime: org.gnome.Platform
runtime-version: '42'

modules:
    - name: mono
      sources:
          - type: archive
            url: https://download.mono-project.com/sources/mono/mono-6.12.0.122.tar.xz
            sha256: 29c277660fc5e7513107aee1cbf8c5057c9370a4cdfeda2fc781be6986d89d23
      config-opts:
          - --enable-minimal=aot,profiler,attach,full_messages
          - --with-mcs-docs=no
          - --with-profile2=no
```

4. Start the build: `flatpak-builder build-dir  com.app.app.yml` This uses autogen.

### Current Behavior

Build fails and crashes (trace attached below):

```
</configuration>
/bin/sh ../mkinstalldirs _tmpinst/bin
mkdir -p -- _tmpinst/bin
cp mono-wrapper _tmpinst/bin/mono
echo '#! /bin/sh' > _tmpinst/bin/ilasm ; \
r=`pwd`; m=`cd /run/build/mono/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/ilasm/ilasm.exe"'" "$@"' >> _tmpinst/bin/ilasm ; \
chmod +x _tmpinst/bin/ilasm
echo '#! /bin/sh' > _tmpinst/bin/csc ; \
r=`pwd`; m=`cd /run/build/mono/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"/run/build/mono/external/roslyn-binaries/Microsoft.Net.Compilers/3.6.0/csc.exe"'" "$@"' >> _tmpinst/bin/csc ; \
chmod +x _tmpinst/bin/csc
echo '#! /bin/sh' > _tmpinst/bin/mcs ; \
r=`pwd`; m=`cd /run/build/mono/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/mcs.exe"'" "$@"' >> _tmpinst/bin/mcs ; \
chmod +x _tmpinst/bin/mcs
echo '#! /bin/sh' > _tmpinst/bin/al ; \
r=`pwd`; m=`cd /run/build/mono/mcs && pwd`; \
echo 'exec "'"$r/_tmpinst/bin/mono"'" "'"$m/class/lib/net_4_x/al.exe"'" "$@"' >> _tmpinst/bin/al ; \
chmod +x _tmpinst/bin/al
if test -w /run/build/mono/mcs; then :; else chmod -R +w /run/build/mono/mcs; fi
cd /run/build/mono/mcs && make --no-print-directory -s NO_DIR_CHECK=1 PROFILES='binary_reference_assemblies net_4_x xbuild_12 xbuild_14              ' CC='gcc' all-profiles
mkdir -p -- build/deps
make[6]: mono: No such file or directory
make[6]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Error 127
*** The runtime 'mono' doesn't appear to be usable.
*** Trying the 'monolite-linux/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory.
* Assertion: should not be reached at aot-compiler.c:14269

```

Entire build.log: [build.log](https://github.com/mono/mono/files/8764745/build.log)

This is with GCC `11.3.0`, I think.
### Expected Behavior

Build to complete successfully.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

6.12.0.122

## Stacktrace

It SIGABRTs

```
=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x5627da9eab48 - /run/build/mono/mono/mini/mono : 
	0x5627da9eaf15 - /run/build/mono/mono/mini/mono : 
	0x5627da99c69e - /run/build/mono/mono/mini/mono : 
	0x5627da9ea040 - /run/build/mono/mono/mini/mono : 
	0x7f990718de60 - /usr/lib/x86_64-linux-gnu/libpthread.so.0 : 
	0x7f9906fb44bb - /usr/lib/x86_64-linux-gnu/libc.so.6 : gsignal
	0x7f9906f9d877 - /usr/lib/x86_64-linux-gnu/libc.so.6 : abort
	0x5627da981388 - /run/build/mono/mono/mini/mono : 
	0x5627dac577bd - /run/build/mono/mono/mini/mono : 
	0x5627dac772e7 - /run/build/mono/mono/mini/mono : monoeg_assertion_message
	0x5627dac7737b - /run/build/mono/mono/mini/mono : 
	0x5627da996909 - /run/build/mono/mono/mini/mono : 
	0x5627daa2bf5a - /run/build/mono/mono/mini/mono : 
	0x5627daa2c59c - /run/build/mono/mono/mini/mono : 
	0x5627daa27ba7 - /run/build/mono/mono/mini/mono : 
	0x5627daa2c59c - /run/build/mono/mono/mini/mono : 
	0x5627daa27ba7 - /run/build/mono/mono/mini/mono : 
	0x5627daa2c59c - /run/build/mono/mono/mini/mono : 
	0x5627daa27ba7 - /run/build/mono/mono/mini/mono : 
	0x5627da9f04af - /run/build/mono/mono/mini/mono : 
	0x5627da9f275c - /run/build/mono/mono/mini/mono : 
	0x5627da986eb2 - /run/build/mono/mono/mini/mono : 
	0x5627da9a02f6 - /run/build/mono/mono/mini/mono : 
	0x5627da9a0e1e - /run/build/mono/mono/mini/mono : 
	0x40e4f393 - Unknown

=================================================================
	Telemetry Dumper:
=================================================================
Pkilling 0x140295219377728x from 0x140295227508544x
Entering thread summarizer pause from 0x140295227508544x
Finished thread summarizer pause from 0x140295227508544x.
Failed to create breadcrumb file (null)/crash_hash_0xc048738

Waiting for dumping threads to resume

=================================================================
	External Debugger Dump:
=================================================================
[New LWP 9889]
[New LWP 9890]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f99070488db in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
  Id   Target Id                                      Frame 
* 1    Thread 0x7f9907330740 (LWP 9864) "mono"        0x00007f99070488db in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
  2    Thread 0x7f99063ff640 (LWP 9889) "SGen worker" 0x00007f990718fe1d in __futex_abstimed_wait_common64 () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
  3    Thread 0x7f9906b6f640 (LWP 9890) "Finalizer"   0x00007f990718fe1d in __futex_abstimed_wait_common64 () from /usr/lib/x86_64-linux-gnu/libpthread.so.0

Thread 3 (Thread 0x7f9906b6f640 (LWP 9890) "Finalizer"):
#0  0x00007f990718fe1d in __futex_abstimed_wait_common64 () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f990718c0d0 in __new_sem_wait_slow64.constprop.0 () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00005627dabed916 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x5627dadbf2e0 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:203
#3  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x5627dadbf2e0 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:41
#4  finalizer_thread (unused=unused@entry=0x0) at gc.c:965
#5  0x00005627daba3eec in start_wrapper_internal (stack_ptr=0x7f9906b70000, start_info=0x0) at threads.c:1233
#6  start_wrapper (data=0x5627db125dc0) at threads.c:1308
#7  0x00007f99071833ba in start_thread () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f990707e393 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f99063ff640 (LWP 9889) "SGen worker"):
#0  0x00007f990718fe1d in __futex_abstimed_wait_common64 () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f99071895b4 in pthread_cond_wait () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00005627dac4efbb in mono_os_cond_wait (mutex=0x5627dadce500 <lock>, cond=0x5627dadce4c0 <work_cond>) at ../../mono/utils/mono-os-mutex.h:219
#3  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#4  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#5  0x00007f99071833ba in start_thread () from /usr/lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f990707e393 in clone () from /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f9907330740 (LWP 9864) "mono"):
#0  0x00007f99070488db in wait4 () from /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00005627da9eade3 in dump_native_stacktrace (signal=signal@entry=0x5627dac91405 "SIGABRT", mctx=mctx@entry=0x7fffb892e240) at mini-posix.c:1112
#2  0x00005627da9eaf15 in mono_dump_native_crash_info (signal=signal@entry=0x5627dac91405 "SIGABRT", mctx=mctx@entry=0x7fffb892e240, info=info@entry=0x7fffb892e530) at mini-posix.c:1156
#3  0x00005627da99c69e in mono_handle_native_crash (signal=0x5627dac91405 "SIGABRT", mctx=mctx@entry=0x7fffb892e240, info=info@entry=0x7fffb892e530) at mini-exceptions.c:3423
#4  0x00005627da9ea040 in sigabrt_signal_handler (_dummy=<optimized out>, _info=0x7fffb892e530, context=0x7fffb892e400) at mini-posix.c:234
#5  <signal handler called>
#6  0x00007f9906fb44bb in raise () from /usr/lib/x86_64-linux-gnu/libc.so.6
#7  0x00007f9906f9d877 in abort () from /usr/lib/x86_64-linux-gnu/libc.so.6
#8  0x00005627da981388 in monoeg_assert_abort () at goutput.c:57
#9  0x00005627dac577bd in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=0x5627db161430 "* Assertion: should not be reached at aot-compiler.c:14269\n") at mono-log-common.c:136
#10 0x00005627dac772e7 in monoeg_g_logstr (msg=<optimized out>, log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:151
#11 monoeg_g_logv_nofree (args=0x7fffb892ed20, format=0x5627dad45d88 "* Assertion: should not be reached at %s:%d\n", log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:166
#12 monoeg_g_logv_nofree (args=0x7fffb892ed20, format=0x5627dad45d88 "* Assertion: should not be reached at %s:%d\n", log_level=G_LOG_LEVEL_ERROR, log_domain=0x0) at goutput.c:155
#13 monoeg_assertion_message (format=format@entry=0x5627dad45d88 "* Assertion: should not be reached at %s:%d\n") at goutput.c:201
#14 0x00005627dac7737b in mono_assertion_message_unreachable (file=file@entry=0x5627dac87aa9 "aot-compiler.c", line=line@entry=14269) at goutput.c:228
#15 0x00005627da996909 in mono_aot_direct_icalls_enabled_for_method (cfg=cfg@entry=0x5627db160a90, method=method@entry=0x5627db1ad788) at aot-compiler.c:14269
#16 0x00005627daa2bf5a in direct_icalls_enabled (method=0x5627db1ad788, cfg=<optimized out>) at method-to-ir.c:2178
#17 mono_method_to_ir (cfg=<optimized out>, method=<optimized out>, start_bblock=<optimized out>, end_bblock=<optimized out>, return_var=<optimized out>, inline_args=<optimized out>, inline_offset=<optimized out>, is_virtual_call=<optimized out>) at method-to-ir.c:7167
#18 0x00005627daa2c59c in inline_method (cfg=cfg@entry=0x5627db160a90, cmethod=cmethod@entry=0x5627db1ad550, fsig=<optimized out>, fsig@entry=0x5627db166a98, sp=sp@entry=0x5627db1aef28, ip=<optimized out>, real_offset=<optimized out>, inline_always=<optimized out>) at method-to-ir.c:4570
#19 0x00005627daa27ba7 in mono_method_to_ir (cfg=<optimized out>, method=<optimized out>, start_bblock=<optimized out>, end_bblock=<optimized out>, return_var=<optimized out>, inline_args=<optimized out>, inline_offset=<optimized out>, is_virtual_call=<optimized out>) at method-to-ir.c:7552
#20 0x00005627daa2c59c in inline_method (cfg=cfg@entry=0x5627db160a90, cmethod=cmethod@entry=0x5627db1ad528, fsig=<optimized out>, fsig@entry=0x5627db166a98, sp=sp@entry=0x5627db1aa798, ip=<optimized out>, real_offset=<optimized out>, inline_always=<optimized out>) at method-to-ir.c:4570
#21 0x00005627daa27ba7 in mono_method_to_ir (cfg=<optimized out>, method=<optimized out>, start_bblock=<optimized out>, end_bblock=<optimized out>, return_var=<optimized out>, inline_args=<optimized out>, inline_offset=<optimized out>, is_virtual_call=<optimized out>) at method-to-ir.c:7552
#22 0x00005627daa2c59c in inline_method (cfg=cfg@entry=0x5627db160a90, cmethod=cmethod@entry=0x5627db1ad500, fsig=<optimized out>, fsig@entry=0x5627db130868, sp=sp@entry=0x5627db1a5440, ip=<optimized out>, real_offset=<optimized out>, inline_always=<optimized out>) at method-to-ir.c:4570
#23 0x00005627daa27ba7 in mono_method_to_ir (cfg=cfg@entry=0x5627db160a90, method=method@entry=0x5627db1a3068, start_bblock=<optimized out>, start_bblock@entry=0x0, end_bblock=<optimized out>, end_bblock@entry=0x0, return_var=return_var@entry=0x0, inline_args=inline_args@entry=0x0, inline_offset=<optimized out>, is_virtual_call=<optimized out>) at method-to-ir.c:7552
#24 0x00005627da9f04af in mini_method_compile (method=<optimized out>, opts=<optimized out>, domain=<optimized out>, flags=<optimized out>, parts=<optimized out>, aot_method_index=<optimized out>) at mini.c:3467
#25 0x00005627da9f275c in mono_jit_compile_method_inner (method=method@entry=0x5627db1a3068, target_domain=target_domain@entry=0x5627db0bc6f0, opt=opt@entry=374434303, error=error@entry=0x7fffb8930290) at mini.c:4060
#26 0x00005627da986eb2 in mono_jit_compile_method_with_opt (method=0x5627db1a3068, opt=<optimized out>, jit_only=<optimized out>, error=0x7fffb8930290) at mini-runtime.c:2449
#27 0x00005627da987ef1 in mono_jit_compile_method (method=<optimized out>, error=<optimized out>) at mini-runtime.c:2499
#28 0x00005627da9a02f6 in common_call_trampoline (regs=regs@entry=0x7fffb8930358, code=code@entry=0x41b06580 "H\203\304\b\303\350v\214\064\377\bh0\032\333'V", m=m@entry=0x5627db1a3068, vt=vt@entry=0x0, vtable_slot=<optimized out>, vtable_slot@entry=0x0, error=error@entry=0x7fffb8930290) at mini-trampolines.c:635
#29 0x00005627da9a0e1e in mono_magic_trampoline (regs=0x7fffb8930358, code=0x41b06580 "H\203\304\b\303\350v\214\064\377\bh0\032\333'V", arg=0x5627db1a3068, tramp=<optimized out>) at mini-trampolines.c:773
#30 0x0000000040e4f393 in ?? ()
#31 0x00005627db1050d5 in ?? ()
#32 0x0000000040e4f3c1 in ?? ()
#33 0x00007fffb8930520 in ?? ()
#34 0x00007fffb8930358 in ?? ()
#35 0x00005627db110bd0 in ?? ()
#36 0x0000000000000000 in ?? ()
[Inferior 1 (process 9864) detached]

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x7f9906fb44bb):0x7f9906fb44ab  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f9906fb44bb  48 8b 45 f8 64 48 2b 04 25 28 00 00 00 75 1a c9  H.E.dH+.%(...u..
0x7f9906fb44cb  44 89 c0 c3 90 48 8b 15 81 b9 19 00 f7 d8 41 b8  D....H........A.
0x7f9906fb44db  ff ff ff ff 64 89 02 eb c0 e8 c7 9a 0d 00 0f 1f  ....d...........

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program:MainCore <0x0007f>
	  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program:Main <0x00033>
	  at <Module>:runtime_invoke_int_object <0x00091>
=================================================================
make[8]: *** [build/profiles/build.make:134: build/deps/basic-profile-check.exe] Aborted (core dumped)
*** The contents of your 'monolite-linux/1A5E0066-58DC-428A-B21C-0AD6CDAE2789' directory may be out-of-date

```

**Comment by bbhtt** [comment]
> make[6]: mono: No such file or directory

Ok, xvitaly in the Flatpak chat room kindly pointed out that I need to bootstrap Mono first to compile from source. I didn't know this and this was not mentioned in the docs I was following https://www.mono-project.com/docs/compiling-mono/linux/. After finding out, I searched for it and the only place it is mentioned is in the readme in a single line. It'd be nice to have that in the main documentation along with some steps on how to do it. Thanks. 

Closing.
