### ISSUE TITLE
Assertion at local-propagation.c:555, condition `ins->opcode > MONO_CEE_LAST' not met

### ISSUE THREAD

**Issue by okayabc** [mono/mono#21683]
## Steps to Reproduce

1. run ./autogen.sh --prefix=/usr/local
2. make
3. occur error during making

## On which platforms did you notice this

[ ] macOS
[ yes] Linux  ubuntu18.04.6LTS
[ ] Windows

**Version Used**:

## Stacktrace
System.IO.MemoryMappedFiles/MemoryMappedFile.cs(114,26): warning CS0414: The private field `System.IO.MemoryMappedFiles.MemoryMappedFile.fileAccess' is assigned but its value is never used
System.IO.MemoryMappedFiles/MemoryMappedFile.cs(115,10): warning CS0414: The private field `System.IO.MemoryMappedFiles.MemoryMappedFile.name' is assigned but its value is never used
System.IO.MemoryMappedFiles/MemoryMappedFile.cs(116,8): warning CS0414: The private field `System.IO.MemoryMappedFiles.MemoryMappedFile.fileCapacity' is assigned but its value is never used
Compilation succeeded - 17 warning(s)
mkdir -p -- ../../class/lib/build/
MCS     [build] mscorlib.dll
* Assertion at local-propagation.c:555, condition `ins->opcode > MONO_CEE_LAST' not met

Stacktrace:

  at <unknown> <0xffffffff>
  at System.Text.StringBuilder..ctor (string,int) [0x0000f] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.Text.StringBuilder..ctor (int) [0x00000] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.Text.StringBuilderCache.Acquire (int) [0x00032] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at string.FormatHelper (System.IFormatProvider,string,System.ParamsArray) [0x0001e] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at string.Format (string,object,object,object) [0x0000a] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.TermInfoDriver.TryTermInfoDir (string,string) [0x0000d] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.TermInfoDriver.SearchTerminfo (string) [0x00067] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.TermInfoDriver..ctor (string) [0x0004b] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.ConsoleDriver.CreateTermInfoDriver (string) [0x00000] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.ConsoleDriver..cctor () [0x00062] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0001e] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at <unknown> <0xffffffff>
  at System.Console.SetupStreams (System.Text.Encoding,System.Text.Encoding) [0x0000a] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at System.Console..cctor () [0x000a8] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at (wrapper runtime-invoke) object.runtime_invoke_void (object,intptr,intptr,intptr) [0x0001e] in <3e88c30319ca4d6da939d5cf5acc2161>:0
  at <unknown> <0xffffffff>
  at Mono.CSharp.Driver.Main (string[]) [0x00019] in <960e5391c6244638913695c8c826df09>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x00054] in <960e5391c6244638913695c8c826df09>:0
/proc/self/maps:
404d2000-404e2000 rwxp 00000000 00:00 0 
40f46000-40f56000 rwxp 00000000 00:00 0 
5646c655b000-5646c6aa5000 r-xp 00000000 08:01 551995                     /home/mono-mono-4.8.1.0/mono/mini/mono-sgen
5646c6ca4000-5646c6cbb000 r--p 00549000 08:01 551995                     /home/mono-mono-4.8.1.0/mono/mini/mono-sgen
5646c6cbb000-5646c6cc7000 rw-p 00560000 08:01 551995                     /home/mono-mono-4.8.1.0/mono/mini/mono-sgen
5646c6cc7000-5646c6cfb000 rw-p 00000000 00:00 0 
5646c879c000-5646c88c7000 rw-p 00000000 00:00 0                          [heap]
7f1730000000-7f1730021000 rw-p 00000000 00:00 0 
7f1730021000-7f1734000000 ---p 00000000 00:00 0 
7f173661e000-7f17368a5000 r--p 00000000 08:01 1225266                    /home/mono-mono-4.8.1.0/mcs/class/lib/basic/System.dll
7f17368a5000-7f17368a6000 ---p 00000000 00:00 0 
7f17368a6000-7f1736aa6000 rw-p 00000000 00:00 0 
7f1736aa6000-7f1736e3b000 r--p 00000000 08:01 1225249                    /home/mono-mono-4.8.1.0/mcs/class/lib/basic/mscorlib.dll
7f1736e3b000-7f1736fff000 r--p 00000000 08:01 1225245                    /home/mono-mono-4.8.1.0/mcs/class/lib/basic/basic.exe
7f1736fff000-7f1737fff000 rw-p 00000000 00:00 0 
7f1737fff000-7f1738000000 ---p 00000000 00:00 0 
7f1738000000-7f1738c00000 rw-p 00000000 00:00 0 
7f1738c84000-7f1738d68000 r--p 00000000 08:01 1225270                    /home/mono-mono-4.8.1.0/mcs/class/lib/basic/System.Core.dll
7f1738d68000-7f17391fc000 r--p 00000000 08:01 524869                     /usr/lib/locale/locale-archive
7f17391fc000-7f17393e3000 r-xp 00000000 08:01 2762532                    /lib/x86_64-linux-gnu/libc-2.27.so
7f17393e3000-7f17395e3000 ---p 001e7000 08:01 2762532                    /lib/x86_64-linux-gnu/libc-2.27.so
7f17395e3000-7f17395e7000 r--p 001e7000 08:01 2762532                    /lib/x86_64-linux-gnu/libc-2.27.so
7f17395e7000-7f17395e9000 rw-p 001eb000 08:01 2762532                    /lib/x86_64-linux-gnu/libc-2.27.so
7f17395e9000-7f17395ed000 rw-p 00000000 00:00 0 
7f17395ed000-7f1739604000 r-xp 00000000 08:01 2758022                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1739604000-7f1739803000 ---p 00017000 08:01 2758022                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1739803000-7f1739804000 r--p 00016000 08:01 2758022                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1739804000-7f1739805000 rw-p 00017000 08:01 2758022                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f1739805000-7f173981f000 r-xp 00000000 08:01 2762547                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7f173981f000-7f1739a1e000 ---p 0001a000 08:01 2762547                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7f1739a1e000-7f1739a1f000 r--p 00019000 08:01 2762547                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7f1739a1f000-7f1739a20000 rw-p 0001a000 08:01 2762547                    /lib/x86_64-linux-gnu/libpthread-2.27.so
7f1739a20000-7f1739a24000 rw-p 00000000 00:00 0 
7f1739a24000-7f1739a27000 r-xp 00000000 08:01 2762535                    /lib/x86_64-linux-gnu/libdl-2.27.so
7f1739a27000-7f1739c26000 ---p 00003000 08:01 2762535                    /lib/x86_64-linux-gnu/libdl-2.27.so
7f1739c26000-7f1739c27000 r--p 00002000 08:01 2762535                    /lib/x86_64-linux-gnu/libdl-2.27.so
7f1739c27000-7f1739c28000 rw-p 00003000 08:01 2762535                    /lib/x86_64-linux-gnu/libdl-2.27.so
7f1739c28000-7f1739c2f000 r-xp 00000000 08:01 2762549                    /lib/x86_64-linux-gnu/librt-2.27.so
7f1739c2f000-7f1739e2e000 ---p 00007000 08:01 2762549                    /lib/x86_64-linux-gnu/librt-2.27.so
7f1739e2e000-7f1739e2f000 r--p 00006000 08:01 2762549                    /lib/x86_64-linux-gnu/librt-2.27.so
7f1739e2f000-7f1739e30000 rw-p 00007000 08:01 2762549                    /lib/x86_64-linux-gnu/librt-2.27.so
7f1739e30000-7f1739fcd000 r-xp 00000000 08:01 2762536                    /lib/x86_64-linux-gnu/libm-2.27.so
7f1739fcd000-7f173a1cc000 ---p 0019d000 08:01 2762536                    /lib/x86_64-linux-gnu/libm-2.27.so
7f173a1cc000-7f173a1cd000 r--p 0019c000 08:01 2762536                    /lib/x86_64-linux-gnu/libm-2.27.so
7f173a1cd000-7f173a1ce000 rw-p 0019d000 08:01 2762536                    /lib/x86_64-linux-gnu/libm-2.27.so
7f173a1ce000-7f173a1f7000 r-xp 00000000 08:01 2762527                    /lib/x86_64-linux-gnu/ld-2.27.so
7f173a2d4000-7f173a354000 rw-p 00000000 00:00 0 
7f173a358000-7f173a379000 r--p 00000000 08:01 1053439                    /usr/share/locale-langpack/zh_CN/LC_MESSAGES/libc.mo
7f173a379000-7f173a37a000 rw-p 00000000 00:00 0 
7f173a37a000-7f173a3d9000 ---p 00000000 00:00 0 
7f173a3d9000-7f173a3e0000 rw-p 00000000 00:00 0 
7f173a3e4000-7f173a3e5000 rw-p 00000000 00:00 0 
7f173a3e5000-7f173a3ec000 r--s 00000000 08:01 796488                     /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f173a3ec000-7f173a3f6000 rw-p 00000000 00:00 0 
7f173a3f6000-7f173a3f7000 rw-s 00000000 00:19 3                          /dev/shm/mono.27855
7f173a3f7000-7f173a3f8000 r--p 00029000 08:01 2762527                    /lib/x86_64-linux-gnu/ld-2.27.so
7f173a3f8000-7f173a3f9000 rw-p 0002a000 08:01 2762527                    /lib/x86_64-linux-gnu/ld-2.27.so
7f173a3f9000-7f173a3fa000 rw-p 00000000 00:00 0 
7ffed2ae0000-7ffed2b02000 rw-p 00000000 00:00 0                          [stack]
7ffed2bf4000-7ffed2bf7000 r--p 00000000 00:00 0                          [vvar]
7ffed2bf7000-7ffed2bf8000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 --xp 00000000 00:00 0                  [vsyscall]

Native stacktrace:

	/home/mono-mono-4.8.1.0/mono/mini/mono(+0xecf0d) [0x5646c6647f0d]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f1739817980]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f173923ae87]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f173923c7f1]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x3a7ba0) [0x5646c6902ba0]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x3c07c7) [0x5646c691b7c7]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x3c097b) [0x5646c691b97b]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0xb98c1) [0x5646c66148c1]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x152b17) [0x5646c66adb17]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x153649) [0x5646c66ae649]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0x5924a) [0x5646c65b424a]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0xee9bf) [0x5646c66499bf]
	/home/mono-mono-4.8.1.0/mono/mini/mono(+0xef0bc) [0x5646c664a0bc]
	[0x404d2298]

Debug info from gdb:

[New LWP 27879]
[New LWP 27880]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f173981732a in __waitpid (pid=pid@entry=27881, stat_loc=stat_loc@entry=0x7ffed2afba2c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: 没有那个文件或目录.
  Id   Target Id         Frame 
* 1    Thread 0x7f173a3d9780 (LWP 27855) "mono" 0x00007f173981732a in __waitpid (pid=pid@entry=27881, stat_loc=stat_loc@entry=0x7ffed2afba2c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f17387ff700 (LWP 27879) "SGen worker" 0x00007f1739812ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5646c6cd8f48 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7f1736aa5700 (LWP 27880) "Finalizer" 0x00007f17398157c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5646c6cc9300 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205

Thread 3 (Thread 0x7f1736aa5700 (LWP 27880)):
#0  0x00007f17398157c6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x5646c6cc9300 <finalizer_sem>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x5646c6cc9300 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f17398158b8 in __new_sem_wait_slow (sem=sem@entry=0x5646c6cc9300 <finalizer_sem>, abstime=0x0) at sem_waitcommon.c:181
#3  0x00007f1739815929 in __new_sem_wait (sem=sem@entry=0x5646c6cc9300 <finalizer_sem>) at sem_wait.c:42
#4  0x00005646c676dd07 in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x5646c6cc9300 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:209
#5  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x5646c6cc9300 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:40
#6  finalizer_thread (unused=unused@entry=0x0) at gc.c:905
#7  0x00005646c67493c8 in start_wrapper_internal (stack_ptr=0x7f1736aa4dc0, start_info=0x0) at threads.c:760
#8  start_wrapper (data=0x5646c8820aa0) at threads.c:824
#9  0x00005646c690e653 in inner_start_thread (data=0x5646c8820b00) at mono-threads.c:1181
#10 0x00007f173980c6db in start_thread (arg=0x7f1736aa5700) at pthread_create.c:463
#11 0x00007f173931d61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f17387ff700 (LWP 27879)):
#0  0x00007f1739812ad3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x5646c6cd8f48 <work_cond+40>) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x5646c6cd8f60 <lock>, cond=0x5646c6cd8f20 <work_cond>) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=cond@entry=0x5646c6cd8f20 <work_cond>, mutex=mutex@entry=0x5646c6cd8f60 <lock>) at pthread_cond_wait.c:655
#3  0x00005646c68e5123 in mono_os_cond_wait (mutex=0x5646c6cd8f60 <lock>, cond=0x5646c6cd8f20 <work_cond>) at ../../mono/utils/mono-os-mutex.h:150
#4  thread_func (thread_data=0x0) at sgen-thread-pool.c:110
#5  0x00007f173980c6db in start_thread (arg=0x7f17387ff700) at pthread_create.c:463
#6  0x00007f173931d61f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f173a3d9780 (LWP 27855)):
#0  0x00007f173981732a in __waitpid (pid=pid@entry=27881, stat_loc=stat_loc@entry=0x7ffed2afba2c, options=options@entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00005646c6647fb5 in mono_handle_native_sigsegv (signal=<optimized out>, ctx=<optimized out>, info=<optimized out>) at mini-exceptions.c:2469
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x00007f173923c7f1 in __GI_abort () at abort.c:79
#5  0x00005646c6902ba0 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=<optimized out>) at mono-log-common.c:136
#6  0x00005646c691b7c7 in monoeg_g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x5646c69281f0 "* Assertion at %s:%d, condition `%s' not met\n", args=0x7ffed2afccc0) at goutput.c:111
#7  0x00005646c691b97b in monoeg_assertion_message (format=0x5646c69281f0 "* Assertion at %s:%d, condition `%s' not met\n") at goutput.c:131
#8  0x00005646c66148c1 in mono_local_cprop (cfg=cfg@entry=0x5646c88b7590) at local-propagation.c:555
#9  0x00005646c66adb17 in mini_method_compile (method=method@entry=0x5646c88b1c88, opts=opts@entry=370239999, domain=domain@entry=0x5646c87aa580, flags=flags@entry=JIT_FLAG_RUN_CCTORS, parts=parts@entry=0, aot_method_index=aot_method_index@entry=-1) at mini.c:3644
#10 0x00005646c66ae649 in mono_jit_compile_method_inner (method=method@entry=0x5646c88b1c88, target_domain=target_domain@entry=0x5646c87aa580, opt=opt@entry=370239999, error=error@entry=0x7ffed2afd160) at mini.c:4258
#11 0x00005646c65b424a in mono_jit_compile_method_with_opt (method=method@entry=0x5646c88b1c88, opt=370239999, error=error@entry=0x7ffed2afd160) at mini-runtime.c:1934
#12 0x00005646c65b4c3a in mono_jit_compile_method (method=method@entry=0x5646c88b1c88, error=error@entry=0x7ffed2afd160) at mini-runtime.c:1978
#13 0x00005646c66499bf in common_call_trampoline (regs=regs@entry=0x7ffed2afd248, code=code@entry=0x40f4b334 "H\213,$L\213l$\bL\213t$\020H\203\304\070\303\350\264mX\377\b\210\034\213\310FV", m=m@entry=0x5646c88b1c88, vt=vt@entry=0x0, vtable_slot=<optimized out>, vtable_slot@entry=0x0, error=error@entry=0x7ffed2afd160) at mini-trampolines.c:699
#14 0x00005646c664a0bc in mono_magic_trampoline (regs=0x7ffed2afd248, code=0x40f4b334 "H\213,$L\213l$\bL\213t$\020H\203\304\070\303\350\264mX\377\b\210\034\213\310FV", arg=0x5646c88b1c88, tramp=<optimized out>) at mini-trampolines.c:829
#15 0x00000000404d2298 in ?? ()
#16 0x0000000000000000 in ?? ()

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
../../build/library.make:302: recipe for target '../../class/lib/build/mscorlib.dll' failed
make[8]: *** [../../class/lib/build/mscorlib.dll] Error 134

```
Please paste the stack trace here if available.
```

**Comment by baltermia** [comment]
Hi did you manage to fix this? I'm trying to build 4.6.2.16 from source.
