### ISSUE TITLE
[Libgdi+][System.Drawings]Upgrade to Net 8 cause a BUG using PrivateFontCollection

### ISSUE THREAD

**Issue by dcaponetti** [mono/mono#21739]
I upgraded my solution to Net 8, upgrading from System.Drawings 6.0 to 8.0.

The libgdiplus i use on a Kubernetees cluster is:
libgdiplus/now 6.1+dfsg-1+b1 amd64 [installed,local]
   interface library for System.Drawing of Mono

Downloaded from org.debian.org

When using PrivateFontCollection i get this Exception:

```
> ===> 25-01-2024 09:10:29 [Error] [] [f8e90bfa-258b-48be-9d47-c8e9247723e6] Unhandled Exception: The type initializer for 'Gdip' threw an exception.
> ===> 25-01-2024 09:10:29 [Warning] [] [f8e90bfa-258b-48be-9d47-c8e9247723e6] Stacktrace:    at System.Drawing.SafeNativeMethods.Gdip.GdipNewPrivateFontCollection(IntPtr& fontCollection)
>    at System.Drawing.Text.PrivateFontCollection..ctor()
```

I revert the System.Drawings to 6.0 and it worked again.

Will you upgrade libgdi+ to framework 8?
And if so, when will it be available for Debian?

Thank,
Daniel.

**Comment by lextm** [comment]
You should post to https://github.com/mono/libgdiplus/issues and also refer to https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only#reason-for-change

In short, there isn't likely to be some changes as you wished. You should check out the alternatives.
