### ISSUE TITLE
System.Reflection.Metadata.dll is linked with different version of System.Collections.Immutable.dll than Microsoft.CodeAnalysis*.dll

### ISSUE THREAD

**Issue by pod063** [mono/mono#6347]
## Steps to Reproduce

1. compile and run code with Microsoft.CodeAnalysis features:
Script<object> result = CSharpScript.Create(string code);
result.Compile(); //this will throw exception:

## Current Behavior

System.Reflection.Metadata.dll is linked with System.Collections.Immutable.dll 1.2.0 but other dlls like Microsoft.CodeAnalysis*.dll are linked with  System.Collections.Immutable.dll 1.2.1.
This prevent to run code using Microsoft.CodeAnalysis features. For example:

Script<object> result = CSharpScript.Create(Code);
result.Compile(); //this will throw exception:

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)

## Expected Behavior

System.Reflection.Metadata.dll will be linked with the same version like Microsoft.CodeAnalysis*.dll

### On which platforms did you notice this

[ ] macOS
[ ] Linux
[x] Windows

**Version Used**:

Mono JIT compiler version 5.4.1 (Visual Studio built mono)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           normal
        SIGSEGV:       normal
        Notification:  Thread + polling
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

### Stacktrace

Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Microsoft.CodeAnalysis.ModuleMetadata.CreateFromStream(Stream peStream, PEStreamOptions options)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromAssemblyInternal(Assembly assembly, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.CodeAnalysis.Scripting.Script.GetReferencesForCompilation(CommonMessageProvider messageProvider, DiagnosticBag diagnostics, MetadataReference languageRuntimeReferenceOpt)
   at Microsoft.CodeAnalysis.CSharp.Scripting.CSharpScriptCompiler.CreateSubmission(Script script)
   at Microsoft.CodeAnalysis.Scripting.Script.GetCompilation()
   at Microsoft.CodeAnalysis.Scripting.Script`1.GetExecutor(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script`1.CommonCompile(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Scripting.Script.Compile(CancellationToken cancellationToken)
   at HelloWorld.Main()

**Comment by pod063** [comment]
I'm very sorry. The System.Reflection.Metadata is really linked with different version of System.Collection.Immutable than Microsoft.CodeAnalysis but I was made mistake and didn't run application via mono.exe. If application is run via mono.exe everything works perfectly. I'm really very sorry.
