### ISSUE TITLE
WCF service - MethodAsync error

### ISSUE THREAD

**Issue by esseivan** [mono/mono#6938]
## Steps to Reproduce
I used an Async method ("Task<T> MethodAsync();") in a WCF service. When hosting it on windows (from a console project), there's no problem but when hosting it on my raspberry pi (which is my goal), it throws an exception.

The following files were sent through FTP to the raspberry pi :
HostService.exe, HostService.exe.config, EsseivaServices.dll
And the command to host :
`sudo mono HostService.exe`

Here's a zip file containing the projects used
[WCF.zip](https://github.com/mono/mono/files/1713297/WCF.zip)

Or there's the code
### IEsseivaService.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;

namespace EsseivaServices
{
    // NOTE: You can use the "Rename" command on the "Refactor" menu to change the interface name "IService1" in both code and config file together.
    [ServiceContract]
    public interface IGameService
    {
        [OperationContract]
        string GetData(string msg);

        [OperationContract]
        Task<string> DelayAsync();
    }
}
```
### EsseivaService.cs
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.ServiceModel;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace EsseivaServices
{
    [ServiceBehavior(InstanceContextMode = InstanceContextMode.Single, ConcurrencyMode = ConcurrencyMode.Single)]
    public class GameService : IGameService
    {
        public string GetData(string msg)
        {
            return string.Format("You entered: {0}", msg);
        }

        public async Task<string> DelayAsync()
        {
            await Task.Delay(2500);
            return "Complete";
        }  
    }
}
```
### Program.cs (Host from console project)
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;

namespace HostService
{
    class Program
    {
        static void Main(string[] args)
        {
            using (ServiceHost Host = new ServiceHost(typeof(EsseivaServices.GameService)))
            {
                Host.Open();

                Console.WriteLine("WCF host started");
                Console.WriteLine(Host.State);
                Console.ReadLine();
            }
        }
    }
}
```
### App.config (from host project)
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.serviceModel>
    <services>
      <service name="EsseivaServices.GameService" behaviorConfiguration="mexBehaviour">
        <endpoint address="GameService" binding="basicHttpBinding" contract="EsseivaServices.IGameService"></endpoint>
        <endpoint address="GameService" binding="netTcpBinding" contract="EsseivaServices.IGameService"></endpoint>
        <endpoint address="mex" binding="mexHttpBinding" contract="IMetadataExchange"></endpoint>
        <host>
          <baseAddresses>
            <add baseAddress="http://localhost:17855/"/>
            <add baseAddress="net.tcp://localhost:17856/"/>
          </baseAddresses>
        </host>
      </service>
    </services>
    <behaviors>
      <serviceBehaviors>
        <behavior name="mexBehaviour">
          <serviceMetadata httpGetEnabled="true"/>
        </behavior>
      </serviceBehaviors>
    </behaviors>
  </system.serviceModel>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5"/>
  </startup>
</configuration>
```
### Form.cs (Client app)
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace clientServiceApp
{
    public partial class Form1 : Form
    {
        EsseivaService.GameServiceClient client;
        ChannelFactory<EsseivaService.IGameServiceChannel> factory;
        EsseivaService.IGameServiceChannel channel;

        public Form1()
        {
            InitializeComponent();
            client = new EsseivaService.GameServiceClient("BasicHttpBinding_IGameService");
            factory = new ChannelFactory<EsseivaService.IGameServiceChannel>("BasicHttpBinding_IGameService");
            channel = factory.CreateChannel();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            label1.Text = client.GetData(textBox1.Text);

            var task = Method2();
            if (!task.IsCompleted)
                label1.Text = "Waiting method2";
        }

        private async Task<bool> Method2()
        {
            try
            {
                label1.Text = await client.DelayAsync();
            }
            catch (Exception ex)
            {
                label1.Text = "Error";
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
                return false;
            }
            return true;
        }

        private void button2_Click(object sender, EventArgs e)
        {
            label1.Text = channel.GetData(textBox1.Text);

            var task = Method3();
            if (!task.IsCompleted)
                label1.Text = "Waiting method3";
        }

        private async Task<bool> Method3()
        {
            try
            {
                label1.Text = await channel.DelayAsync();
            }
            catch (Exception ex)
            {
                label1.Text = "Error";
                Console.WriteLine(ex.Message);
                Console.WriteLine(ex.StackTrace);
                return false;
            }
            return true;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            client.Open();
            channel.Open();
        }

        private void Form1_FormClosing(object sender, FormClosingEventArgs e)
        {
            client.Close();
            channel.Open();
        } 
    }
}
```
### App.config (from client app)
Endpoint's addresses changed according the raspberry pi ip address
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup> 
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.7.1" />
    </startup>
    <system.serviceModel>
        <bindings>
            <basicHttpBinding>
                <binding name="BasicHttpBinding_IGameService" />
            </basicHttpBinding>
            <netTcpBinding>
                <binding name="NetTcpBinding_IGameService" />
            </netTcpBinding>
        </bindings>
        <client>
            <endpoint address="http://192.168.1.30:17855/GameService" binding="basicHttpBinding"
                bindingConfiguration="BasicHttpBinding_IGameService" contract="EsseivaService.IGameService"
                name="BasicHttpBinding_IGameService" />
            <endpoint address="net.tcp://192.168.1.30:17856/GameService" binding="netTcpBinding"
                bindingConfiguration="NetTcpBinding_IGameService" contract="EsseivaService.IGameService"
                name="NetTcpBinding_IGameService">
                <identity>
                    <userPrincipalName value="PC-ESSEIVAN\Esseiva" />
                </identity>
            </endpoint>
        </client>
    </system.serviceModel>
</configuration>
```

## Current Behavior
```
System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
Inner Exception
ActionNotSupportedException: Action 'http://tempuri.org/IGameService/Delay' did not match any operations in the target contract
```

## Expected Behavior

Waiting 2.5 seconds without freezing client UI
Set label text to "Complete"

### On which platforms did you notice this
[x] Raspberry PI 3
#### OS version
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian

**MONO Version Used**:

Mono JIT compiler version 5.8.0.108 (tarball Fri Jan 19 18:55:10 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  armel,vfp+hard
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

### Stacktrace

When Try Catch is inside Method2/3
```
   at System.ServiceModel.Channels.ServiceChannel.ThrowIfFaultUnderstood(Message reply, MessageFault fault, String action, MessageVersion version, FaultConverter faultConverter)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.EndCall(String action, Object[] outs, IAsyncResult result)
   at System.ServiceModel.Channels.ServiceChannelProxy.TaskCreator.<>c__DisplayClass7_0`1.<CreateGenericTask>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at clientServiceApp.Form1.<Method2>d__5.MoveNext() in C:\WorkSpace\VisualStudio\WCF\clientServiceApp\clientServiceApp\Form1.cs:line 41
```
Without Try Catch
```
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at clientServiceApp.Program.Main() in C:\WorkSpace\VisualStudio\WCF\clientServiceApp\clientServiceApp\Program.cs:line 19
```

**Comment by rspulini** [comment]
solution?

**Comment by esseivan** [comment]
my temporary solution was to not use await delay as an infinite loop...

**Comment by Shazib** [comment]
Has there been any progress on this?
