### ISSUE TITLE
startup/shutdown flaky under WSL/gdb??

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7026]
Debugging with gdb on current WSL often sees stuff like these.
I don't know if this WSL or gdb or mono.
It is flaky.
Maybe some bugs in initialization or tear down??

```
/mnt/d/dev2/mono2$ MONO_PATH="./mcs/class/lib/basic:$MONO_PATH" gdb --args /dev2/mono2/mono/mini/mono-sgen \
 ./mcs/class/lib/basic/ilasm.exe ./mcs/class/corlib/System.Runtime.CompilerServices/Unsafe.il /dll \
/noautoinherit /out:../../class/lib/build-linux/corlib.unsafe.dll.tmp

mono_thread_internal_set_priority: pthread_getschedparam failed, error: "No such process" (3)

Thread 3 "mono-sgen" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffffc430700 (LWP 7217)]
0x00007ffffe4f5428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffffe4f5428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ffffe4f702a in __GI_abort () at abort.c:89
#2  0x000000000088b181 in mono_log_write_logfile (log_domain=0x0, level=G_LOG_LEVEL_ERROR, hdr=0,
    message=0x7ffff8001d70 "mono_thread_internal_set_priority: pthread_getschedparam failed, error: \"No such process\" (3)") at mono-log-common.c:135
#3  0x0000000000881fcd in structured_log_adapter (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR,
    message=0x7ffff8001d70 "mono_thread_internal_set_priority: pthread_getschedparam failed, error: \"No such process\" (3)", user_data=0x0) at mono-logger.c:458
#4  0x00000000008a830e in monoeg_g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x9088d8 "%s: pthread_getschedparam failed, error: \"%s\" (%d)",
    args=0x7ffffc42fc90) at goutput.c:115
#5  0x00000000008a83ed in monoeg_g_log (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x9088d8 "%s: pthread_getschedparam failed, error: \"%s\" (%d)")
    at goutput.c:125
#6  0x000000000074fbe3 in mono_thread_internal_set_priority (internal=0x7ffffe4a0278, priority=MONO_THREAD_PRIORITY_NORMAL) at threads.c:612
#7  0x000000000075091f in start_wrapper_internal (start_info=0xca5810, stack_ptr=0x7ffffc431000) at threads.c:1011
#8  0x0000000000750cdd in start_wrapper (data=0xca5810) at threads.c:1123
#9  0x00007ffffeab76ba in start_thread (arg=0x7ffffc430700) at pthread_create.c:333
#10 0x00007ffffe5c73dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109


A separate run, same command or fixed "../../class" to "./mcs/class" which surely isn't the proble:


#1  0x00007ffffe4f702a in __GI_abort () at abort.c:89
#2  0x000000000088b181 in mono_log_write_logfile (log_domain=0x0, level=G_LOG_LEVEL_ERROR, hdr=0,
    message=0xd3a8b0 "mono_os_mutex_destroy: pthread_mutex_destroy failed with \"Device or resource busy\" (16)") at mono-log-common.c:135
#3  0x0000000000881fcd in structured_log_adapter (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR,
    message=0xd3a8b0 "mono_os_mutex_destroy: pthread_mutex_destroy failed with \"Device or resource busy\" (16)", user_data=0x0) at mono-logger.c:458
#4  0x00000000008a830e in monoeg_g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x8e3818 "%s: pthread_mutex_destroy failed with \"%s\" (%d)",
    args=0x7ffffffeda80) at goutput.c:115
#5  0x00000000008a83ed in monoeg_g_log (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=0x8e3818 "%s: pthread_mutex_destroy failed with \"%s\" (%d)")
    at goutput.c:125
#6  0x00000000006737b3 in mono_os_mutex_destroy (mutex=0xc39880) at ../../mono/utils/mono-os-mutex.h:91
#7  0x0000000000673947 in mono_coop_mutex_destroy (mutex=0xc39880) at ../../mono/utils/mono-coop-mutex.h:44
#8  0x000000000067635f in mono_domain_free (domain=0xc39880, force=1) at domain.c:1221
#9  0x0000000000424d60 in mini_cleanup (domain=0xc39880) at mini-runtime.c:4450
#10 0x00000000004d53b3 in mono_main (argc=6, argv=0x7ffffffedf08) at driver.c:2384
#11 0x0000000000418ee2 in mono_main_with_options (argc=6, argv=0x7ffffffedf08) at main.c:50
#12 0x0000000000419c3b in main (argc=6, argv=0x7ffffffedf08) at main.c:398

**Comment by marek-safar** [comment]
Closing as a development issue. If you have proper repro please reopen and include full steps to reproduce it
