### ISSUE TITLE
coreclr acceptance test times out external/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/test_il.exe

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7809]
Linux x64 Acceptance Tests

https://jenkins.mono-project.com/job/test-mono-pull-request-acceptance-tests/2819/

https://jenkins.mono-project.com/job/test-mono-pull-request-acceptance-tests/2819/testReport/junit/MonoTests/coreclr/external_coreclr_tests_src_JIT_Regression_VS_ia64_JIT_V1_2_M02_b28158_test_il_exe_timedout/

MonoTests.coreclr.external/coreclr/tests/src/JIT/Regression/VS-ia64-JIT/V1.2-M02/b28158/test_il.exe_timedout

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
mono_arch_output_basic_block (cfg=cfg@entry=0x560372bbd280, bb=bb@entry=0x560373107480) at mini-amd64.c:3762
3762				current_offset += current_bb->max_length;
  Id   Target Id         Frame 
* 1    Thread 0x7f95954db740 (LWP 26089) "mono" mono_arch_output_basic_block (cfg=cfg@entry=0x560372bbd280, bb=bb@entry=0x560373107480) at mini-amd64.c:3762
  2    Thread 0x7f9593bff700 (LWP 26142) "SGen worker" 0x00007f95949a615f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
  3    Thread 0x7f95919d4700 (LWP 26149) "Finalizer" 0x00007f95949a8536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0

Thread 3 (Thread 0x7f95919d4700 (LWP 26149)):

"Finalizer" tid=0x7f95919d4700 this=0x7f9591a78278 , thread handle : 0x7f958c000f40, state : not waiting

$1 = void

Thread 2 (Thread 0x7f9593bff700 (LWP 26142)):
$2 = void

Thread 1 (Thread 0x7f95954db740 (LWP 26089)):

"<unnamed thread>" tid=0x7f95954db740 this=0x7f9591a78130 , thread handle : 0x560372b57f60, state : not waiting

$3 = void

Thread 3 (Thread 0x7f95919d4700 (LWP 26149)):
#0  0x00007f95949a8536 in do_futex_wait.constprop () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f95949a85e4 in __new_sem_wait_slow.constprop.0 () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00005603720a4d5a in mono_os_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x560372467820 <finalizer_sem>) at ../../mono/utils/mono-os-semaphore.h:209
#3  mono_coop_sem_wait (flags=MONO_SEM_FLAGS_ALERTABLE, sem=0x560372467820 <finalizer_sem>) at ../../mono/utils/mono-coop-semaphore.h:43
#4  finalizer_thread (unused=unused@entry=0x0) at gc.c:903
#5  0x000056037205ee42 in start_wrapper_internal (stack_ptr=<optimized out>, start_info=0x0) at threads.c:1099
#6  start_wrapper (data=0x560372ba7fd0) at threads.c:1159
#7  0x00007f95949a0494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f95944cbacf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f9593bff700 (LWP 26142)):
#0  0x00007f95949a615f in pthread_cond_wait@@GLIBC_2.3.2 () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x000056037210994b in mono_os_cond_wait (mutex=0x560372476680 <lock>, cond=0x560372476640 <work_cond>) at ../../mono/utils/mono-os-mutex.h:173
#2  get_work (job=<synthetic pointer>, do_idle=<synthetic pointer>, work_context=<synthetic pointer>, worker_index=0) at sgen-thread-pool.c:165
#3  thread_func (data=<optimized out>) at sgen-thread-pool.c:196
#4  0x00007f95949a0494 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#5  0x00007f95944cbacf in clone () from /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f95954db740 (LWP 26089)):
#0  mono_arch_output_basic_block (cfg=cfg@entry=0x560372bbd280, bb=bb@entry=0x560373107480) at mini-amd64.c:3760
#1  0x0000560371f81869 in mono_codegen (cfg=cfg@entry=0x560372bbd280) at mini.c:2233
#2  0x0000560371f82a4b in mini_method_compile (method=method@entry=0x560372b60218, opts=opts@entry=370239999, domain=domain@entry=0x560372b5c070, flags=flags@entry=JIT_FLAG_RUN_CCTORS, parts=parts@entry=0, aot_method_index=aot_method_index@entry=-1) at mini.c:3837
#3  0x0000560371f8495f in mono_jit_compile_method_inner (method=method@entry=0x560372b60218, target_domain=target_domain@entry=0x560372b5c070, opt=opt@entry=370239999, error=error@entry=0x7fffc3d66240) at mini.c:4173
#4  0x0000560371e7bf36 in mono_jit_compile_method_with_opt (method=method@entry=0x560372b60218, opt=370239999, jit_only=<optimized out>, jit_only@entry=0, error=error@entry=0x7fffc3d66240) at mini-runtime.c:2237
#5  0x0000560371e7d01c in mono_jit_compile_method (method=method@entry=0x560372b60218, error=error@entry=0x7fffc3d66240) at mini-runtime.c:2283
#6  0x0000560371e7d421 in mono_jit_runtime_invoke (method=0x560372b60218, obj=<optimized out>, params=0x7fffc3d661f8, exc=0x0, error=0x7fffc3d66240) at mini-runtime.c:2796
#7  0x000056037203a8f0 in do_runtime_invoke (method=0x560372b60218, obj=<optimized out>, params=<optimized out>, exc=<optimized out>, error=0x7fffc3d66240) at object.c:2942
#8  0x000056037203cc1d in do_exec_main_checked (method=0x560372b60218, args=<optimized out>, error=0x7fffc3d66240) at object.c:4848
#9  0x0000560371ed31a1 in mono_jit_exec (domain=domain@entry=0x560372b5c070, assembly=assembly@entry=0x560372bb6fc0, argc=argc@entry=1, argv=argv@entry=0x7fffc3d66690) at driver.c:1202
#10 0x0000560371ed52de in main_thread_handler (user_data=<synthetic pointer>) at driver.c:1279
#11 mono_main (argc=4, argv=<optimized out>) at driver.c:2380
#12 0x0000560371e7726d in mono_main_with_options (argv=<optimized out>, argc=<optimized out>) at main.c:50
#13 main (argc=<optimized out>, argv=<optimized out>) at main.c:398

                                                +++++++++++++++++++
                                                STACK TRACE:
                                                /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/mnt/jenkins/workspace/test-mono-pull-request-acceptance-tests/libtool: line 4471: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
```

**Comment by kumpera** [comment]
This is not a runtime bug per-se. The test case causes the JIT to take a minute to compile a humongous method with tens of thousands of EH clauses. It's hardly representative of any realistic workload.

I did some profiling and fixed a couple of the worst offenders: https://github.com/mono/mono/pull/9100

**Comment by marek-safar** [comment]
We could disable the test but if it's just a minute we should just bump https://github.com/mono/mono/blob/master/scripts/ci/run-test-acceptance-tests.sh#L21

**Comment by akoeplinger** [comment]
We'd actually have to change the timeout passed to test-runner.exe (it uses the default of 2mins).

I haven't seen this test fail a lot recently and most recent runs took about 60 seconds on nightly builds so #9100 will probably make this go away.

**Comment by kumpera** [comment]
I found a couple more non linearities in the JIT worth fixing. Compilation times on good-keyboard MBP is down to 5s.

**Comment by akoeplinger** [comment]
#9100 dropped the b28158/test_il.exe run time from 58sec to 3.3sec so we'll probably not see this again, closing :) Nice work @kumpera !
