### ISSUE TITLE
mono hangs reading zero bytes of random on possibly misconfigured system

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#7865]
I created a Debian 9 stretch armhf chroot on the builder (which is arm64 native).
Maybe I did not do this correctly.
Maybe the runtime could be better.
It hangs reading /dev/urandom because it keeps getting zero bytes and it just keeps retrying.
I have no changes, just using mono/master.

root@xam-jetsontx1-5:/s/mono/mcs# MONO_PATH="./class/lib/monolite-linux/1051300003:./class/lib/monolite-linux/1051300003/Facades:$MONO_PATH" /s/mono/mono/mini/mono --trace /s/mono/external/roslyn-binaries/Microsoft.Net.Compilers/Microsoft.Net.Compilers.2.7.0/tools/csc.exe /warn:0 /noconfig /r:System.dll /r:mscorlib.dll /out:build/deps/basic-profile-check.exe build/common/basic-profile-check.cs

Same thing if I replace it with "echo > 1.cs"

#0  0xf770f460 in read () at ../sysdeps/unix/syscall-template.S:84
#1  0xaadced9c in mono_rand_try_get_bytes (handle=0xaaebc8bc <worker+316>, buffer=0xfffee10c "", buffer_size=4,
    error=0xfffee110) at mono-rand.c:286
#2  0xaadcee7e in mono_rand_try_get_uint32 (handle=0xaaebc8bc <worker+316>, val=0xfffee10c, min=10, max=200,
    error=0xfffee110) at mono-rand.c:380
#3  0xaad3225a in rand_next (handle=0xaaebc8bc <worker+316>, min=10, max=200) at threadpool-worker-default.c:209
#4  0xaad324b4 in mono_threadpool_worker_init (callback=0xaaccf205 <worker_callback>)
    at threadpool-worker-default.c:275
#5  0xaaccede8 in initialize () at threadpool.c:145
#6  0xaaccea9a in mono_lazy_initialize (lazy_init=0xaaeb9cfc <status>, initialize=0xaacced59 <initialize>)
    at ../../mono/utils/mono-lazy-init.h:77
#7  0xaaccffde in ves_icall_System_Threading_ThreadPool_InitializeVMTp (enable_worker_tracking=0xaafec572 "",
    error=0xfffee1b4) at threadpool.c:721
#8  0xf4cc4264 in ?? ()

96                     } while (count < buffer_size);
(gdb)
286                             err = read (file, buffer + count, buffer_size - count);
(gdb)
287                             if (err < 0) {
(gdb)
295                             count += err;
(gdb)
296                     } while (count < buffer_size);

it keeps reading zero bytes so loops forever.

It should probably break when it gets zero and then fail out.

**Comment by jaykrell** [comment]
mount --bind /dev armhf/dev to fix.
