### ISSUE TITLE
Fix "clang-analyze-build" step on the CI static analysis job

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#8610]
The "clang-analyze-build" step on the [static analysis jenkins job](https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/) shows green ✅ but when you click on [Clang Analysis Report](https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/Clang_Analysis_Report) it's actually broken.

This is correleated with the static analysis job upgrading to Ubuntu 18.04 a couple of weeks ago.

Log from a sample job:
```
*** start: clang-analyze-build
analyze-build: INFO: Report directory created: /mnt/jenkins/workspace/test-mono-mainline-staticanalysis/clang-scan-build-report/scan-build-2018-05-07-03-23-25-244581-eDl9ne
analyze-build: WARNING: analysis failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/analyze.py", line 405, in run_analyzer
    cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/clang.py", line 46, in get_arguments
    output = run_command(cmd, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/libscanbuild/__init__.py", line 78, in run_command
    raise ex
CalledProcessError: Command '['clang', '-###', '--analyze', '-Xclang', '-analyzer-output=html', '-x', 'c', u'-DHAVE_CONFIG_H', u'-I.', u'-I../..', u'-I../..', u'-I../../mono', u'-I../../libgc/include', u'-I../../mono/eglib', u'-I../../mono/eglib', u'-fvisibility=hidden', u'-DGC_LINUX_THREADS', u'-D_GNU_SOURCE', u'-D_REENTRANT', u'-DUSE_MMAP', u'-DUSE_MUNMAP', u'-Wno-cast-qual', u'-Wno-switch', u'-Wno-switch-enum', u'-Wno-unused-value', u'-Wno-attributes', u'-Wno-format-zero-length', u'-DUSE_COMPILER_TLS', u'-DHAVE_BOEHM_GC', u'-ggdb3', u'-O2', u'-std=gnu99', u'-fno-strict-aliasing', u'-fwrapv', u'-DMONO_DLL_EXPORT', u'-Wno-unused-but-set-variable', u'-Wno-cast-qual', u'-Wno-switch', u'-Wno-switch-enum', u'-Wno-unused-value', u'-Wno-attributes', u'-Wno-format-zero-length', u'-mno-tls-direct-seg-refs', u'/mnt/jenkins/workspace/test-mono-mainline-staticanalysis/mono/metadata/method-builder.c', '-o', '/mnt/jenkins/workspace/test-mono-mainline-staticanalysis/clang-scan-build-report/scan-build-2018-05-07-03-23-25-244581-eDl9ne']' returned non-zero exit status 1
```

Not clear if this is due to a new version of clang, or some change in the `scan-build` python package that we use for `intercept-build/intercept-cc`.

I haven't tried to reproduce this in a local Ubuntu 18.04 VM yet, so that would be the first step.

**Comment by akoeplinger** [comment]
I looked at this today and it's due to `clang: error: unknown argument: '-mno-tls-direct-seg-refs'`. 

This is a GCC specific flag that we're only setting when configure.ac thinks it doesn't build with clang so somewhere along the lines setting clang as the compiler in the job got broken.

It's probably not related to the Ubuntu 18.04 upgrade though since e.g. https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/538/consoleFull already shows `checking whether we are using the GNU C compiler... yes` and that was still running on Ubuntu 17.10.

**Comment by akoeplinger** [comment]
@lambdageek it was most likely this change: https://jenkins.mono-project.com/job/test-mono-mainline-staticanalysis/jobConfigHistory/showDiffFiles?timestamp1=2017-10-05_12-20-16&timestamp2=2017-10-20_18-51-51

It caused autogen.sh to no longer be replaced with `scan-build autogen.sh` so during autogen we don't switch to clang.

**Comment by Kensuke-Hinata** [comment]
I also encountered the problem "clang: error: unknown argument: '-mno-tls-direct-seg-refs'" when  running make, and my environment is "OSX Darwin Kernel Version 15.6.0".

**Comment by Kensuke-Hinata** [comment]
I found the reason is that the gcc/g++ in PATH is a soft link to the clang toolchain.
