### ISSUE TITLE
ParallelEnumerableTests.TestGroupBy flaky test

### ISSUE THREAD

**Issue by jaykrell** [mono/mono#9046]
## Steps to Reproduce

1.  Submit a PR.

### Current Behavior

e.g.

https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-fullaot+llvm/1438/#showFailuresLink

ParallelEnumerableTests.TestGroupBy

```
Regression
ParallelEnumerableTests.TestGroupBy

Failing for the past 1 build (Since Unstable#1438 )
Took 5 sec.
Stacktrace
                                                MESSAGE:
                                                System.AggregateException : One or more errors occurred.
  ----> System.NullReferenceException : Object reference not set to an instance of an object
                                                +++++++++++++++++++
                                                STACK TRACE:
                                                  at System.Linq.Parallel.QueryTaskGroupState.QueryEnd (System.Boolean userInitiatedDispose) [0x00081] in <d07252c7308d4678b2bfc6a9a28e5c4c>:0 
  at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1[T].MoveNextSlowPath () <0x7f74638a1ff0 + 0x0049a> in <d07252c7308d4678b2bfc6a9a28e5c4c#17884142f13783db20e8a3d8a2ed0edc>:0 
  at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1[T].MoveNext () <0x7f74638a1f40 + 0x00044> in <d07252c7308d4678b2bfc6a9a28e5c4c#17884142f13783db20e8a3d8a2ed0edc>:0 
  at System.Linq.Parallel.QueryOpeningEnumerator`1[TOutput].MoveNext () <0x7f74638ae7c0 + 0x00039> in <d07252c7308d4678b2bfc6a9a28e5c4c#17884142f13783db20e8a3d8a2ed0edc>:0 
  at MonoTests.System.Linq.ParallelEnumerableTests+<>c__DisplayClass44_0.<TestGroupBy>b__1 () [0x000e8] in /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/System.Core/Test/System.Linq/ParallelEnumerableTests.cs:606 
  at MonoTests.System.Linq.ParallelEnumerableTests.TestGroupBy () <0x7f746875dfc0 + 0x0014b> in <0dc1ddc4fbf9442a824faf89ee7def8b#17884142f13783db20e8a3d8a2ed0edc>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags i
```

### Expected Behavior

Success.

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Comment by marek-safar** [comment]
This one is interesting, could be the same issue we are hitting with Roslyn.

/cc @lewurm

**Comment by alexischr** [comment]
This one seems to also show up as a native crash with interesting stacktrace ([Log](https://jenkins.mono-project.com/job/test-mono-pull-request-amd64-fullaot+llvm/2270/parsed_console/log.html))

```
Thread 13 (Thread 0x7efbf79fc700 (LWP 1435)):
#0  0x00007efc186e2b3a in waitpid () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x0000557690bab0f9 in dump_native_stacktrace (ctx=0x7efc0e637ac0, signal=0x5576912309e9 "SIGSEGV") at mini-posix.c:719
#2  0x0000557690bab23d in mono_dump_native_crash_info (signal=signal@entry=0x5576912309e9 "SIGSEGV", ctx=ctx@entry=0x7efc0e637ac0, info=info@entry=0x7efc0e637bf0) at mini-posix.c:742
#3  0x0000557690b2e8d5 in mono_handle_native_crash (signal=signal@entry=0x5576912309e9 "SIGSEGV", ctx=ctx@entry=0x7efc0e637ac0, info=info@entry=0x7efc0e637bf0) at mini-exceptions.c:2938
#4  0x0000557690ab08bf in mono_sigsegv_signal_handler (_dummy=11, _info=0x7efc0e637bf0, context=0x7efc0e637ac0) at mini-runtime.c:3414
#5  <signal handler called>
#6  0x00007efc154770f0 in string_memcpy_aligned_4_byte.byte.int () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#7  0x00007efc0ef44824 in System_Linq_Parallel_WrapperEqualityComparer_1_T_GSHAREDVT_Equals_System_Linq_Parallel_Wrapper_1_T_GSHAREDVT_System_Linq_Parallel_Wrapper_1_T_GSHAREDVT (this=139621195409016, x=357003504, y=357003504) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#8  0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#9  0x00007efc0ef3fb9b in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_AreKeysEqual_TKey_GSHAREDVT_TKey_GSHAREDVT (this=..., key1=357003504, key2=357003504) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#10 0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#11 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#12 0x00007efc0ef4008c in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_Find_TKey_GSHAREDVT_bool_bool_TValue_GSHAREDVT_ (this=..., key=357003504, add=false, set=false, value=139620656329536) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#13 0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#14 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#15 0x00007efc0ef3f7c7 in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_TryGetValue_TKey_GSHAREDVT_TValue_GSHAREDVT_ (this=..., key=357003504, value=139620656329536) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#16 0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#17 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#18 0x00007efc0ef33c08 in System_Linq_Parallel_GroupByElementSelectorQueryOperatorEnumerator_4_TSource_GSHAREDVT_TGroupKey_GSHAREDVT_TElement_GSHAREDVT_TOrderKey_GSHAREDVT_BuildHashLookup (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#19 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#20 0x00007efc0ef3315d in System_Linq_Parallel_GroupByQueryOperatorEnumerator_4_TSource_GSHAREDVT_TGroupKey_GSHAREDVT_TElement_GSHAREDVT_TOrderKey_GSHAREDVT_MoveNext_System_Linq_IGrouping_2_TGroupKey_GSHAREDVT_TElement_GSHAREDVT__TOrderKey_GSHAREDVT_ (this=..., currentElement=139620656330016, currentKey=<optimized out>) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#21 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#22 0x00007efc0ef3d826 in System_Linq_Parallel_PipelineSpoolingTask_2_TInputOutput_GSHAREDVT_TIgnoreKey_GSHAREDVT_SpoolingWork (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#23 0x00007efc0eedca92 in System_Linq_Parallel_SpoolingTaskBase_Work (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#24 0x00007efc0ed221a6 in System_Linq_Parallel_QueryTask_BaseWork_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#25 0x00007efc17c1a2c8 in ?? ()
#26 0x00007efc0e0c9580 in ?? ()
#27 0x00007efc0ed99dad in System_Linq_Parallel_QueryTask__c___cctorb__10_0_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#28 0x00007efc0e272c30 in ?? ()
#29 0x00007efc155b4f39 in System_Threading_Tasks_Task_InnerInvoke () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#30 0x00007efc17c1a2c8 in ?? ()
#31 0x00007efc155b4d55 in System_Threading_Tasks_Task_Execute () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#32 0x00007efc17c1a448 in ?? ()
#33 0x00007efc155b4ec9 in System_Threading_Tasks_Task_ExecutionContextCallback_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#34 0x00007efc0e2736b0 in ?? ()
#35 0x00007efc15598902 in System_Threading_ExecutionContext_RunInternal_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#36 0x0000000000000000 in ?? ()
```

with another thread being also in `string_memcpy_aligned_4_byte.byte.int`

```
Thread 10 (Thread 0x7efbf7fff700 (LWP 1432)):
#0  0x00007efc154770f0 in string_memcpy_aligned_4_byte.byte.int () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#1  0x00007efc0ef44824 in System_Linq_Parallel_WrapperEqualityComparer_1_T_GSHAREDVT_Equals_System_Linq_Parallel_Wrapper_1_T_GSHAREDVT_System_Linq_Parallel_Wrapper_1_T_GSHAREDVT (this=139621195660840, x=357003504, y=357003504) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#2  0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#3  0x00007efc0ef3fb9b in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_AreKeysEqual_TKey_GSHAREDVT_TKey_GSHAREDVT (this=..., key1=357003504, key2=357003504) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#4  0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#5  0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#6  0x00007efc0ef4008c in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_Find_TKey_GSHAREDVT_bool_bool_TValue_GSHAREDVT_ (this=..., key=357003504, add=false, set=false, value=139620662633280) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#7  0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#8  0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#9  0x00007efc0ef3f7c7 in System_Linq_Parallel_HashLookup_2_TKey_GSHAREDVT_TValue_GSHAREDVT_TryGetValue_TKey_GSHAREDVT_TValue_GSHAREDVT_ (this=..., key=357003504, value=139620662633280) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#10 0x00007efc15aaf3f0 in gsharedvt_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#11 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#12 0x00007efc0ef33c08 in System_Linq_Parallel_GroupByElementSelectorQueryOperatorEnumerator_4_TSource_GSHAREDVT_TGroupKey_GSHAREDVT_TElement_GSHAREDVT_TOrderKey_GSHAREDVT_BuildHashLookup (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#13 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#14 0x00007efc0ef3315d in System_Linq_Parallel_GroupByQueryOperatorEnumerator_4_TSource_GSHAREDVT_TGroupKey_GSHAREDVT_TElement_GSHAREDVT_TOrderKey_GSHAREDVT_MoveNext_System_Linq_IGrouping_2_TGroupKey_GSHAREDVT_TElement_GSHAREDVT__TOrderKey_GSHAREDVT_ (this=..., currentElement=139620662633760, currentKey=<optimized out>) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#15 0x00007efc15aaf630 in gsharedvt_out_trampoline () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#16 0x00007efc0ef3d826 in System_Linq_Parallel_PipelineSpoolingTask_2_TInputOutput_GSHAREDVT_TIgnoreKey_GSHAREDVT_SpoolingWork (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#17 0x00007efc0eedca92 in System_Linq_Parallel_SpoolingTaskBase_Work (this=...) from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#18 0x00007efc0ed221a6 in System_Linq_Parallel_QueryTask_BaseWork_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#19 0x00007efc17c1a748 in ?? ()
#20 0x00007efc0e0c9490 in ?? ()
#21 0x00007efc0ed99dad in System_Linq_Parallel_QueryTask__c___cctorb__10_0_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/System.Core.dll.so
#22 0x00007efc0e272c30 in ?? ()
#23 0x00007efc155b4f39 in System_Threading_Tasks_Task_InnerInvoke () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#24 0x00007efc17c1a748 in ?? ()
#25 0x00007efc155b4d55 in System_Threading_Tasks_Task_Execute () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#26 0x00007efc17c1a8c8 in ?? ()
#27 0x00007efc155b4ec9 in System_Threading_Tasks_Task_ExecutionContextCallback_object () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#28 0x00007efc0e2736b0 in ?? ()
#29 0x00007efc15598902 in System_Threading_ExecutionContext_RunInternal_System_Threading_ExecutionContext_System_Threading_ContextCallback_object_bool () from /mnt/jenkins/workspace/test-mono-pull-request-amd64-fullaot+llvm/mcs/class/lib/testing_aot_full/mscorlib.dll.so
#30 0x0000000000000000 in ?? ()
```
