### ISSUE TITLE
SIGILL when running roslyn on arm64

### ISSUE THREAD

**Issue by lewurm** [mono/mono#9096]
## Steps to Reproduce

1. run roslyn on arm64

### Current Behavior

it crashes rarely

### Expected Behavior

never crash

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

master

## Stacktrace

```
  at <unknown> <0xffffffff>
  at Microsoft.Cci.ReferenceIndexerBase.VisitTypeDefinitionNoMembers (Microsoft.Cci.ITypeDefinition) [0x00056] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.ReferenceIndexerBase.Visit (Microsoft.Cci.ITypeDefinition) [0x00000] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.MetadataVisitor.Visit (System.Collections.Generic.IEnumerable`1<Microsoft.Cci.INamedTypeDefinition>) [0x00010] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.ReferenceIndexer.Visit (Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder) [0x00051] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.MetadataWriter.CreateIndices () [0x00032] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.MetadataWriter.BuildMetadataAndIL (Microsoft.Cci.PdbWriter,System.Reflection.Metadata.BlobBuilder,System.Reflection.Metadata.BlobBuilder,System.Reflection.Metadata.BlobBuilder,System.Reflection.Metadata.Blob&,System.Reflection.Metadata.Blob&) [0x00000] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.Cci.PeWriter.WritePeToStream (Microsoft.CodeAnalysis.Emit.EmitContext,Microsoft.CodeAnalysis.CommonMessageProvider,System.Func`1<System.IO.Stream>,System.Func`1<System.IO.Stream>,Microsoft.Cci.PdbWriter,string,bool,bool,bool,System.Nullable`1<System.Security.Cryptography.RSAParameters>,System.Threading.CancellationToken) [0x00066] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.Compilation.SerializePeToStream (Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder,Microsoft.CodeAnalysis.DiagnosticBag,Microsoft.CodeAnalysis.CommonMessageProvider,System.Func`1<System.IO.Stream>,System.Func`1<System.IO.Stream>,System.Func`1<System.IO.Stream>,Microsoft.Cci.PdbWriter,string,bool,bool,bool,bool,System.Nullable`1<System.Security.Cryptography.RSAParameters>,System.Threading.CancellationToken) [0x0002b] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream (Microsoft.CodeAnalysis.Emit.CommonPEModuleBuilder,Microsoft.CodeAnalysis.Compilation/EmitStreamProvider,Microsoft.CodeAnalysis.Compilation/EmitStreamProvider,Microsoft.CodeAnalysis.Compilation/EmitStreamProvider,System.Func`2<Microsoft.DiaSymReader.ISymWriterMetadataProvider, Microsoft.DiaSymReader.SymUnmanagedWriter>,Microsoft.CodeAnalysis.DiagnosticBag,bool,bool,bool,string,System.Nullable`1<System.Security.Cryptography.RSAParameters>,System.Threading.CancellationToken) [0x00133] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommonCompiler.CompileAndEmit (Microsoft.CodeAnalysis.TouchedFileLogger,Microsoft.CodeAnalysis.Compilation&,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.Diagnostics.DiagnosticAnalyzer>,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.AdditionalTextFile>,System.Collections.Immutable.ImmutableArray`1<Microsoft.CodeAnalysis.EmbeddedText>,Microsoft.CodeAnalysis.DiagnosticBag,System.Threading.CancellationToken,System.Threading.CancellationTokenSource&,bool&,Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver&) [0x003fb] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommonCompiler.RunCore (System.IO.TextWriter,Microsoft.CodeAnalysis.ErrorLogger,System.Threading.CancellationToken) [0x000ef] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommonCompiler.Run (System.IO.TextWriter,System.Threading.CancellationToken) [0x00035] in <b28b918e025b48209f28967b441780d7#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc/<>c__DisplayClass1_0.<Run>b__0 (System.IO.TextWriter) [0x00000] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommandLine.ConsoleUtil.RunWithUtf8Output<int> (bool,System.IO.TextWriter,System.Func`2<System.IO.TextWriter, int>) [0x00034] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Csc.Run (string[],Microsoft.CodeAnalysis.BuildPaths,System.IO.TextWriter,Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader) [0x00048] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at (wrapper delegate-invoke) <Module>.invoke_int_string[]_BuildPaths_TextWriter_IAnalyzerAssemblyLoader (string[],Microsoft.CodeAnalysis.BuildPaths,System.IO.TextWriter,Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader) [0x0004e] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.RunLocalCompilation (string[],Microsoft.CodeAnalysis.BuildPaths,System.IO.TextWriter) [0x00000] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommandLine.BuildClient.RunCompilation (System.Collections.Generic.IEnumerable`1<string>,Microsoft.CodeAnalysis.BuildPaths,System.IO.TextWriter) [0x00098] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run (System.Collections.Generic.IEnumerable`1<string>,Microsoft.CodeAnalysis.CommandLine.RequestLanguage,Microsoft.CodeAnalysis.CommandLine.CompileFunc,Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader) [0x00043] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.MainCore (string[]) [0x00006] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main (string[]) [0x00000] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x0001e] in <3853db4dce5d45189bea37fcfe62530b#9BC1974C-D3B2-5F5D-C752-615B823E76F1>:0
/proc/self/maps:
[...]

Memory around native instruction pointer (0x7fa5275ff8):
0x7fa5275fe8  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
0x7fa5275ff8  fd 7b be a9 fd 03 00 91 a0 0b 00 f9 00 8b 95 d2  .{..............
0x7fa5276008  00 c9 ab f2 a0 0a c0 f2 11 00 40 f9 51 00 00 b4  ..........@.Q...
0x7fa5276018  8a 29 b7 95 a0 0b 40 f9 0c 00 00 94 bf 03 00 91  .)....@.........

[...]

Thread 1 (Thread 0x7fafefd8c0 (LWP 18162)):
#0  0x0000007fafdeea38 in waitpid () from /lib/aarch64-linux-gnu/libpthread.so.0
#1  0x000000555e195ad8 in mono_handle_native_crash (signal=0x555f3f9fa0 "\360\320\027\224\177", signal@entry=0x555e39bba0 "SIGILL", ctx=ctx@entry=0x7ff3075be0, info=info@entry=0x7ff3075b60) at mini-exceptions.c:3156
#2  0x000000555e12b640 in mono_sigill_signal_handler (_dummy=4, _info=0x7ff3075b60, context=0x7ff3075be0) at mini-runtime.c:3311
#3  <signal handler called>
#4  0x0000007fa5275ff8 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

=================================================================
Got a SIGILL while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
```

instruction stream that causes the SIGILL:
<img width="560" alt="screen shot 2018-06-10 at 15 48 01" src="https://user-images.githubusercontent.com/75403/41209935-d8187bf4-6d2e-11e8-81ae-2315946becc2.png">

Two ideas what could cause that:
* we are missing an icache flush
* it looks like a method entry point. It is 8 byte aligned, maybe 16 byte is required?

(from: https://github.com/mono/mono/pull/8912#issuecomment-396050633 )

**Comment by marek-safar** [comment]
@vargaz @kumpera any thoughts on this?

**Comment by kumpera** [comment]
@marek-safar nop, it can be anything.
