### ISSUE TITLE
[sgen] SIGABRT: Array fill produced wrong size

### ISSUE THREAD

**Issue by sjaenick** [mono/mono#9185]
## Steps to Reproduce

Unfortunately, I can't provide a reasonable test case; the problem occured within a workflow
engine that makes heavy use of multithreading and generates lots of possibly short-lived objects.

```
MONO_GC_PARAMS=nursery-size=8g,evacuation-threshold=50
```

### Current Behavior

SIGABRT / core dump

## On which platforms did you notice this

[ ] macOS
[x] Linux
[ ] Windows

**Version Used**:

5.12.0.226 built from source, configured as

```
--with-xen_opt=no --with-large-heap=yes \
   --disable-boehm --disable-nls --with-mcs-docs=no \
   --with-sgen-default-concurrent=no --without-x
```

```
Mono JIT compiler version 5.12.0.226 (tarball Mon Jun 11 09:52:18 CEST 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        Interpreter:   yes
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

## Stacktrace

```
[New LWP 55931]
[New LWP 56949]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/vol/mgx-sw/lib/mono-5.12/bin/mono --debug /vol/mgx-sw/lib/Conveyor/GraphRun.ex'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00001489bfe0f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
54      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[Current thread is 1 (Thread 0x1489c0ef9740 (LWP 55931))]
Mono support loaded.
(gdb) thread apply all bt

Thread 2 (Thread 0x1489b645e700 (LWP 56949)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x0000148140f46114 in cl_thread_wait_for_thread_condition () from /usr/lib/gridengine-drmaa/lib/libdrmaa.so
#2  0x0000148140f464ee in cl_thread_wait_for_event () from /usr/lib/gridengine-drmaa/lib/libdrmaa.so
#3  0x0000148140f2a147 in ?? () from /usr/lib/gridengine-drmaa/lib/libdrmaa.so
#4  0x00001489c03c16ba in start_thread (arg=0x1489b645e700) at pthread_create.c:333
#5  0x00001489bfee141d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x1489c0ef9740 (LWP 55931)):
#0  0x00001489bfe0f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00001489bfe1102a in __GI_abort () at abort.c:89
#2  0x00000000006d7749 in mono_log_write_logfile (log_domain=<optimized out>, level=<optimized out>, hdr=<optimized out>, message=0xf4f970 "Array fill produced wrong size")
    at mono-log-common.c:135
#3  0x00000000006ecf1d in monoeg_g_logv (log_domain=0x0, log_level=G_LOG_LEVEL_ERROR, format=<optimized out>, args=args@entry=0x7ffc02dcd250) at goutput.c:115
#4  0x00000000006ecfef in monoeg_g_log (log_domain=log_domain@entry=0x0, log_level=log_level@entry=G_LOG_LEVEL_ERROR, 
    format=format@entry=0x7a9500 "Array fill produced wrong size") at goutput.c:125
#5  0x00000000006c3ae1 in sgen_clear_range (start=0x148600001000 "", end=0x148800000000 <error: Cannot access memory at address 0x148800000000>) at sgen-nursery-allocator.c:634
#6  0x00000000006c3d9d in sgen_clear_allocator_fragments (allocator=allocator@entry=0xa36020 <mutator_allocator>) at sgen-nursery-allocator.c:598
#7  0x00000000006c3ddc in sgen_clear_nursery_fragments () at sgen-nursery-allocator.c:610
#8  0x0000000000673b3b in mono_gc_clear_domain (domain=domain@entry=0xf1a080) at sgen-mono.c:824
#9  0x0000000000587d20 in mono_domain_free (domain=domain@entry=0xf1a080, force=force@entry=1) at domain.c:1111
#10 0x000000000042c6ef in mini_cleanup (domain=0xf1a080) at mini-runtime.c:4483
#11 0x0000000000487744 in mono_main (argc=7, argv=<optimized out>) at driver.c:2384
#12 0x00000000004299f6 in mono_main_with_options (argv=0x7ffc02dcd7b8, argc=7) at main.c:50
#13 main (argc=7, argv=0x7ffc02dcd7b8) at main.c:398
(gdb) 
```

**Comment by marek-safar** [comment]
@BrzVlad is there better way to track this down?

**Comment by BrzVlad** [comment]
@sjaenick We don't support arrays larger than 4GB, and there is a dependency on that for nursery sizes larger than 4GB. Sounds like an abnormally high value for a first generation.

**Comment by jaykrell** [comment]
Programs that use large bounded amount of memory that fits in physical memory and don't want to incur GC cost?
8GB is not much physical memory these days.

**Comment by BrzVlad** [comment]
This seems to have been fixed
