### ISSUE TITLE
Build break/test failures on FullAOT+LLVM configuration on ARM

### ISSUE THREAD

**Issue by akoeplinger** [mono/mono#9229]
## Steps to Reproduce

1. Run FullAOT+LLVM config
2. Issue 1: Observe build failures on armel
3. Issue 2: Observe test failures on arm64/armhf

## Current Behavior

Issue 1: Build on armel is broken (https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/label=debian-9-armel/588/):

```
MONO_PATH=".//class/lib/testing_aot_full" /home/builder/jenkins/workspace/test-mono-mainline-linux-fullaot+llvm/label/debian-9-armel/runtime/mono-wrapper  --runtime=mobile -O=gsharedvt --llvm --aot=full,nimt-trampolines=2000,ntrampolines=10000,nrgctx-fetch-trampolines=256,ngsharedvt-trampolines=4000,temp-path=class/lib/testing_aot_full/I18N.Rare.dll_bitcode_tmp --verbose class/lib/testing_aot_full/I18N.Rare.dll > class/lib/testing_aot_full/I18N.Rare.dll.so.aot-log
llc: Unknown command line argument '-soft-float'.  Try: 'llc -help'
llc: Did you mean '-load'?
build/rules.make:194: recipe for target 'class/lib/testing_aot_full/I18N.MidEast.dll.so' failed
AOT of image class/lib/testing_aot_full/I18N.MidEast.dll failed.
make[6]: *** [class/lib/testing_aot_full/I18N.MidEast.dll.so] Error 1
make[6]: *** Waiting for unfinished jobs....
llc: Unknown command line argument '-soft-float'.  Try: 'llc -help'
llc: Did you mean '-load'?
AOT of image class/lib/testing_aot_full/I18N.Other.dll failed.
build/rules.make:194: recipe for target 'class/lib/testing_aot_full/I18N.Other.dll.so' failed
make[6]: *** [class/lib/testing_aot_full/I18N.Other.dll.so] Error 1
llc: Unknown command line argument '-soft-float'.  Try: 'llc -help'
llc: Did you mean '-load'?
AOT of image class/lib/testing_aot_full/I18N.CJK.dll failed.
make[6]: *** [class/lib/testing_aot_full/I18N.CJK.dll.so] Error 1
build/rules.make:194: recipe for target 'class/lib/testing_aot_full/I18N.CJK.dll.so' failed
llc: Unknown command line argument '-soft-float'.  Try: 'llc -help'
llc: Did you mean '-load'?
AOT of image class/lib/testing_aot_full/I18N.Rare.dll failed.
make[6]: *** [class/lib/testing_aot_full/I18N.Rare.dll.so] Error 1
make[5]: *** [do-all-aot] Error 2
make[4]: *** [profile-do--testing_aot_full--all] Error 2
make[3]: *** [profiles-do--all] Error 2
make[2]: *** [all-local] Error 2
build/rules.make:194: recipe for target 'class/lib/testing_aot_full/I18N.Rare.dll.so' failed
make[6]: Leaving directory '/home/builder/jenkins/workspace/test-mono-mainline-linux-fullaot+llvm/label/debian-9-armel/mcs'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Issue 2:

Test failures on arm64 (https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/label=debian-9-arm64/588/) and armhf (https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/label=debian-9-armhf/588/):

```
amd64:
MonoTests.runtime.generic-stack-traces2.2.exe
MonoTests.runtime.finally_block_ending_in_dead_bb.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe
MonoTests.gshared.generic-stack-traces2.2.exe

arm64:
MonoTests.test-sgen-regular-ms-conc-simple.bug-17590.exe
MonoTests.test-sgen-regular-ms-simple.bug-17590.exe
```

## Expected Behavior

No build/test failures

### On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

**Version Used**: master

Continuation from https://github.com/mono/mono/issues/8321

**Comment by vargaz** [comment]
6.0 is MONO_API_VERSION>=600

**Comment by vargaz** [comment]
Its already done:
#ifdef LLVM_API_VERSION > 100
		g_string_append (acfg->llc_args, " -mattr=+soft-float");
#else
		g_string_append (acfg->llc_args, " -soft-float");
#endif

**Comment by alexanderkyte** [comment]
After checking with @akoeplinger , it looks like the x86 failures are fixed. I'm going to investigate reproducing the ARM failures locally before I close this.

**Comment by alexanderkyte** [comment]
Issue encountered/fixed: https://github.com/mono/mono/pull/11074

**Comment by alexanderkyte** [comment]
I'm not seeing the failures linked but I'm definitely seeing some failures: 

```Executing opt: "opt" -f -O2 -disable-tail-calls -o "mono_aot_BTOu5V/temp.opt.bc" "mono_aot_BTOu5V/temp.bc"
Executing llc: "llc"  -mattr=+vfp2,-neon,+d16 -float-abi=hard -asm-verbose=false -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_I18N_CJK_eh_frame -disable-tail-calls -relocation-model=pic -filetype=obj -o "mono_aot_BTOu5V/temp-llvm.o" "mono_aot_BTOu5V/temp.opt.bc"
Stack dump:
0.      Program arguments: llc -mattr=+vfp2,-neon,+d16 -float-abi=hard -asm-verbose=false -disable-gnu-eh-frame -enable-mono-eh-frame -mono-eh-frame-symbol=mono_aot_I18N_CJK_eh_frame -disable-tail-calls -relocation-model=pic -filetype=obj -o mono_aot_BTOu5V/temp-llvm.o mono_aot_BTOu5V/temp.opt.bc 
1.      Running pass 'Function Pass Manager' on module 'mono_aot_BTOu5V/temp.opt.bc'.
2.      Running pass 'ARM Instruction Selection' on function '@I18N_CJK_CP51932__ctor'
Segmentation fault (core dumped)
AOT of image ../../class/lib/testing_aot_full/I18N.CJK.dll failed.
```

**Comment by alexanderkyte** [comment]
https://github.com/mono/mono/pull/11172 fixes ^

**Comment by alexanderkyte** [comment]
Currently seeing: ```Thread 1 (Thread 0xf7bdcc80 (LWP 10962)):
#0  0xf79fd344 in __libc_do_syscall () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0xf79fc0e6 in waitpid () from /lib/arm-linux-gnueabihf/libpthread.so.0
#2  0x002953fc in dump_native_stacktrace (signal=0x8a09ac "SIGSEGV", ctx=0xff9ea3e8) at mini-posix.c:1084
#3  0x00294fa8 in mono_dump_native_crash_info (signal=0x8a09ac "SIGSEGV", ctx=0xff9ea3e8, info=0xff9ea368) at mini-posix.c:1107
#4  0x001f10cc in mono_handle_native_crash (signal=0x8a09ac "SIGSEGV", ctx=0xff9ea3e8, info=0xff9ea368) at mini-exceptions.c:3038
#5  0x000f1800 in mono_sigsegv_signal_handler_debug (_dummy=11, _info=0xff9ea368, context=0xff9ea3e8, debug_fault_addr=0x0) at mini-runtime.c:3504
#6  0x000f1600 in mono_sigsegv_signal_handler (_dummy=11, _info=0xff9ea368, context=0xff9ea3e8) at mini-runtime.c:3533
#7  <signal handler called>
#8  0x00000000 in ?? ()
#9  0xf539bbb8 in System_Collections_Generic_ArraySortHelper_1_T_REF_SwapIfGreater_T_REF___System_Comparison_1_T_REF_int_int () from /home/builder/mono/mcs/class/lib/testing_aot_full/mscorlib.dll.so``` now

**Comment by timmi-on-rails** [comment]
Can you please check if there is a relation with the LLVM bug in issue #11095?
There seems to go something wrong with passing parameters as @lewurm pointed out...

**Comment by lewurm** [comment]
@akoeplinger do you still see those issues on CI?

**Comment by akoeplinger** [comment]
@lewurm yes, armel/armhf are still broken:

- https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/label=debian-9-armhf/
- https://jenkins.mono-project.com/job/test-mono-mainline-linux-fullaot+llvm/label=debian-9-armel/
