### ISSUE TITLE
mono gdb python scripts should format using positional parameters to support gdb linked to python 2.4-2.6 and 3.0

### ISSUE THREAD

**Issue by rjvdboon** [mono/mono#9292]
## Steps to Reproduce

1. Run a program using mono --debug ...
2. Attach gdb
3. Print backtrace

### Current Behavior

The backtrace mostly works, but the printing of stack information shows python errors
```
#28 0x00000000005eaa32 in do_exec_main_checked (method=Traceback (most recent call last):
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 154, in to_string
    class_name = stringify_class_name (klass ["name_space"].string (), klass ["name"].string ())
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 51, in stringify_class_name
    return "{}.{}".format (ns, name)
ValueError: zero length field name in format
, args=<value optimized out>, error=0x7fffc4d16fa0) at object.c:4784
```
This is due to the use of `"{}.{}".format(...)` instead of `"{0}.{1}".format(...)` in `data/gdb/mono-gdb.py`. Omitting positional parameters was introduced in python 2.7 and 3.1, but gdb uses its private linked interpreter which will be python2.6 on rhel6/centos6.

### Expected Behavior

No python errors, proper backtrace.

## On which platforms did you notice this

[ ] macOS
[ X ] Linux
[ ] Windows

RHEL 6.9 (on premise), Centos 6.8 (Azure VM, OpenLogic provided base image)
GDB linked to system default python (2.6)

**Version Used**:
```
$ mono --version
Mono JIT compiler version 5.10.0.160 (tarball Fri Apr 13 16:38:30 CEST 2018)
$ uname
Linux 2.6.32-696.3.2.el6.x86_64 #1 SMP Wed Jun 7 11:51:39 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
$ gdb --version
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-90.el6)
$ ldd `which gdb`|grep python
        libpython2.6.so.1.0 => /usr/lib64/libpython2.6.so.1.0 (0x0000003290a00000)
```

## Stacktrace

```
Thread 1 (Thread 0x2b113ed64ea0 (LWP 26473)):
#0  0x00000000005eef41 in mono_runtime_try_invoke_array (method=<value optimized out>, obj=<value optimized out>, params=<value optimized out>, exc=0x0, error=0x7fffc4d15cb0) at object.c:5183
#1  0x00000000005999eb in ves_icall_InternalInvoke (method=<value optimized out>, this_arg=<value optimized out>, params=0x0, exc=0x7fffc4d15e10) at icall.c:3385
#2  0x000000004080774f in (wrapper_managed-to-native)_System.Reflection.MonoCMethod:InternalInvoke (param0=..., param1=null, param2=null, param3=140736495443472)
#3  0x00002aaaac7332a8 in System.Reflection.MonoCMethod:InternalInvoke (this=..., obj=null, parameters=null) at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/class/corlib/System.Reflection/MonoMethod.cs:661
#4  0x00002aaaac6b728f in System.RuntimeType:CreateInstanceMono (this=..., nonPublic=false) at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/class/corlib/ReferenceSources/RuntimeType.cs:179
#5  0x00002aaaac6b717c in System.RuntimeType:CreateInstanceSlow (this=..., publicOnly=true, skipCheckThis=true, fillCache=<value optimized out>, stackMark=<value optimized out>) at /build/Mono/5.10.0.160/dummy--rhel6/mono
#6  0x00002aaaac6b6c7d in System.RuntimeType:CreateInstanceDefaultCtor (this=..., publicOnly=true, skipCheckThis=true, fillCache=true, stackMark=140736495443688) at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/
#7  0x00002aaaac6656cb in System.Activator:CreateInstance<T_REF> () at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/class/referencesource/mscorlib/system/activator.cs:231
#8  0x000000004090d3db in ...redacted...
#9  0x0000000040949590 in ?? ()
#10 0x00000000409491f0 in ?? ()
#11 0x00000000409490cc in ?? ()
#12 0x000000004094908c in ?? ()
#13 0x0000000040942020 in ...redacted...
#14 0x000000004088e0b0 in ?? ()
#15 0x00000000408360bd in (wrapper_runtime-invoke)_object:runtime_invoke_void__this__ (this=<type 'exceptions.ValueError'>
zero length field name in format
46912497798152, params=<value optimized out>, exc=0, method=1082711488)
#16 0x0000000000420954 in mono_jit_runtime_invoke (method=<value optimized out>, obj=0x2aaaaac44c08, params=<value optimized out>, exc=0x0, error=0x7fffc4d16920) at mini-runtime.c:2807
#17 0x00000000005e9db6 in do_runtime_invoke (method=Traceback (most recent call last):
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 154, in to_string
    class_name = stringify_class_name (klass ["name_space"].string (), klass ["name"].string ())
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 51, in stringify_class_name
    return "{}.{}".format (ns, name)
ValueError: zero length field name in format
, obj=<value optimized out>, params=<value optimized out>, exc=<value optimized out>, error=0x7fffc4d16920) at object.c:2887
#18 0x00000000005eedd5 in mono_runtime_try_invoke_array (method=<value optimized out>, obj=0x2aaaaac44c08, params=0x0, exc=0x0, error=0x7fffc4d16920) at object.c:5225
#19 0x00000000005999eb in ves_icall_InternalInvoke (method=<value optimized out>, this_arg=<value optimized out>, params=0x0, exc=0x7fffc4d16aa0) at icall.c:3385
#20 0x000000004083932f in (wrapper_managed-to-native)_System.Reflection.MonoMethod:InternalInvoke (param0=..., param1=<type 'exceptions.ValueError'>
zero length field name in format
46912497798152, param2=null, param3=140736495446688)
#21 0x00002aaaac7323cc in System.Reflection.MonoMethod:Invoke (this=..., obj=<type 'exceptions.ValueError'>
zero length field name in format
46912497798152, invokeAttr=Default, binder=..., parameters=null, culture=...) at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/class/corlib/System.Reflection/MonoMethod.cs:305
#22 0x00002aaaac723d5b in System.Reflection.MethodBase:Invoke (this=..., obj=<type 'exceptions.ValueError'>
zero length field name in format
46912497798152, parameters=null) at /build/Mono/5.10.0.160/dummy--rhel6/mono-5.10.0.160/mcs/class/referencesource/mscorlib/system/reflection/methodbase.cs:229
#23 0x00000000408389d3 in RunTest.Program:CallFunction (method=..., obj=<type 'exceptions.ValueError'>
zero length field name in format
46912497798152, timeExecution=true)
#24 0x000000004080352c in RunTest.Program:Main (args=<type 'exceptions.ValueError'>
zero length field name in format
46912497517544)
#25 0x000000004080382c in (wrapper_runtime-invoke)_<Module>:runtime_invoke_int_object (this=<value optimized out>, params=140736495447904, exc=0, method=1082142464)
#26 0x0000000000420954 in mono_jit_runtime_invoke (method=<value optimized out>, obj=0x0, params=<value optimized out>, exc=0x0, error=0x7fffc4d16fa0) at mini-runtime.c:2807
#27 0x00000000005e9db6 in do_runtime_invoke (method=Traceback (most recent call last):
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 154, in to_string
    class_name = stringify_class_name (klass ["name_space"].string (), klass ["name"].string ())
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 51, in stringify_class_name
    return "{}.{}".format (ns, name)
ValueError: zero length field name in format
, obj=<value optimized out>, params=<value optimized out>, exc=<value optimized out>, error=0x7fffc4d16fa0) at object.c:2887
#28 0x00000000005eaa32 in do_exec_main_checked (method=Traceback (most recent call last):
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 154, in to_string
    class_name = stringify_class_name (klass ["name_space"].string (), klass ["name"].string ())
  File "/rhel/6/Mono/5.10.0.160-rhel6/bin/mono-sgen-gdb.py", line 51, in stringify_class_name
    return "{}.{}".format (ns, name)
ValueError: zero length field name in format
, args=<value optimized out>, error=0x7fffc4d16fa0) at object.c:4784
#29 0x00000000004742f8 in mono_jit_exec (domain=<value optimized out>, assembly=<value optimized out>, argc=7, argv=0x7fffc4d17380) at driver.c:1202
#30 0x0000000000476347 in main_thread_handler (argc=<value optimized out>, argv=<value optimized out>) at driver.c:1279
#31 mono_main (argc=<value optimized out>, argv=<value optimized out>) at driver.c:2370
#32 0x0000000000418cac in mono_main_with_options (argc=8, argv=0x7fffc4d17378) at main.c:47
#33 main (argc=8, argv=0x7fffc4d17378) at main.c:340
```

**Comment by lewurm** [comment]
> This is due to the use of "{}.{}".format(...) instead of "{0}.{1}".format(...) in data/gdb/mono-gdb.py. Omitting positional parameters was introduced in python 2.7 and 3.1, but gdb uses its private linked interpreter which will be python2.6 on rhel6/centos6.

could you change that, test it (since you have such system at hand) and submit a PR? 🙂

**Comment by rjvdboon** [comment]
I'm testing right now.
