### ISSUE TITLE
[mini] invalid cfg->bblocks causes SIGSEGV

### ISSUE THREAD

**Issue by lewurm** [mono/mono#9298]
## Steps to Reproduce

1. download https://www.mono-project.com/download/stable/#download-lin-ubuntu on Ubuntu 18.04
2. installation will fail with NRE or native crashes, when running `gacutil.exe -u someassembly`
3. narrow it down by running with `MONO_VERBOSE_METHOD=GetPathRoot` to get a "reliable" crash in native code

It looks like it happens only with this CPU:
```
model name    : AMD Ryzen Threadripper 1920X 12-Core Processor
```

### Current Behavior

it crashes here but only with a specific input (`System.IO.Path:GetPathRoot (string)`):
https://github.com/mono/mono/blob/639ca72904d12bbe149c93645ff31374524e5c10/mono/mini/dominators.c#L57

### Expected Behavior
no crash

## On which platforms did you notice this

[ ] macOS
[x] Linux, Ubuntu 18.04
[ ] Windows

**Version Used**:
```
Mono JIT compiler version 5.14.0.141 (tarball Sun Jun 24 11:22:03 UTC 2018)
```
from https://www.mono-project.com/download/stable/#download-lin-ubuntu

## Stacktrace

```
Thread 1 (Thread 0x7ffff7fb8780 (LWP 15898)):
#0  0x00005555556a60ea in printf (__fmt=0x55555587cad4 "BB%d IN: ") at /usr/include/x86_64-linux-gnu/bits/stdio2.h:104
#1  compute_dominators (cfg=0x555555cb2660) at dominators.c:57
#2  mono_compile_dominator_info (cfg=cfg@entry=0x555555cb2660, dom_flags=dom_flags@entry=3) at dominators.c:296
#3  0x00005555556a0cf5 in mini_method_compile (method=method@entry=0x555555d0fd60, opts=opts@entry=374434303, domain=domain@entry=0x555555bb0fe0, flags=flags@entry=JIT_FLAG_RUN_CCTORS, parts=parts@entry=0, aot_method_index=aot_method_index@entry=-1) at mini.c:3591
#4  0x00005555556a207f in mono_jit_compile_method_inner (method=method@entry=0x555555d0fd60, target_domain=target_domain@entry=0x555555bb0fe0, opt=opt@entry=374434303, error=error@entry=0x7fffffffd360) at mini.c:4177
#5  0x0000555555594c59 in mono_jit_compile_method_with_opt (method=method@entry=0x555555d0fd60, opt=374434303, jit_only=<optimized out>, jit_only@entry=0, error=error@entry=0x7fffffffd360) at mini-runtime.c:2237
#6  0x0000555555595d2c in mono_jit_compile_method (method=method@entry=0x555555d0fd60, error=error@entry=0x7fffffffd360) at mini-runtime.c:2283
#7  0x00005555556250f6 in common_call_trampoline (regs=regs@entry=0x7fffffffd428, code=code@entry=0x40020080 "H\211D$0\276\002", m=m@entry=0x555555d0fd60, vt=vt@entry=0x0, vtable_slot=<optimized out>, vtable_slot@entry=0x0, error=error@entry=0x7fffffffd360) at mini-trampolines.c:755
#8  0x0000555555625c1b in mono_magic_trampoline (regs=0x7fffffffd428, code=0x40020080 "H\211D$0\276\002", arg=0x555555d0fd60, tramp=<optimized out>) at mini-trampolines.c:888
#9  0x0000000040000393 in ?? ()
#10 0x0000555555c08145 in ?? ()
#11 0x730a6fe96fa15f00 in ?? ()
#12 0x00007fffffffd5f0 in ?? ()
#13 0x00007fffffffd428 in ?? ()
#14 0x0000555555c0cba0 in ?? ()
#15 0x000000000000001c in ?? ()
#16 0x0000000000000004 in ?? ()
#17 0x0000000000000002 in ?? ()
#18 0x000000000000002f in ?? ()
#19 0x00007fffffffd5f0 in ?? ()
#20 0x0000000000000065 in ?? ()
#21 0x0000000000000000 in ?? ()
```

```
(gdb) i r
rax            0x0    0
rbx            0xffffffff0000000e    -4294967282
rcx            0x7ffff6f13187    140737336390023
rdx            0x555555d146a0    93825000359584
rsi            0x55555587cad4    93824995543764
rdi            0x1    1
rbp            0x555555ce5038    0x555555ce5038
rsp            0x7fffffffcfc0    0x7fffffffcfc0
r8             0x0    0
r9             0x7ffff7fb8780    140737353844608
r10            0x0    0
r11            0x0    0
r12            0x555555cb2660    93824999958112
r13            0x1    1
r14            0x8    8
r15            0x3c    60
rip            0x5555556a60ea    0x5555556a60ea <mono_compile_dominator_info+506>
eflags         0x10246    [ PF ZF IF RF ]
cs             0x33    51
ss             0x2b    43
ds             0x0    0
es             0x0    0
fs             0x0    0
gs             0x0    0
(gdb) x/20i $pc
=> 0x5555556a60ea <mono_compile_dominator_info+506>:    mov    0x18(%rbx),%edx
   0x5555556a60ed <mono_compile_dominator_info+509>:    callq  0x55555557e360 <__printf_chk@plt>
   0x5555556a60f2 <mono_compile_dominator_info+514>:    cmpw   $0x0,0x22(%rbx)
   0x5555556a60f7 <mono_compile_dominator_info+519>:    jle    0x5555556a612f <mono_compile_dominator_info+575>
   0x5555556a60f9 <mono_compile_dominator_info+521>:    xor    %r14d,%r14d
   0x5555556a60fc <mono_compile_dominator_info+524>:    xor    %r13d,%r13d
   0x5555556a60ff <mono_compile_dominator_info+527>:    nop
   0x5555556a6100 <mono_compile_dominator_info+528>:    mov    0x28(%rbx),%rax
   0x5555556a6104 <mono_compile_dominator_info+532>:    lea    0x1d9f89(%rip),%rsi        # 0x555555880094
   0x5555556a610b <mono_compile_dominator_info+539>:    mov    $0x1,%edi
   0x5555556a6110 <mono_compile_dominator_info+544>:    add    $0x1,%r13d
   0x5555556a6114 <mono_compile_dominator_info+548>:    mov    (%rax,%r14,1),%rax
   0x5555556a6118 <mono_compile_dominator_info+552>:    add    $0x8,%r14
   0x5555556a611c <mono_compile_dominator_info+556>:    mov    0x18(%rax),%edx
   0x5555556a611f <mono_compile_dominator_info+559>:    xor    %eax,%eax
   0x5555556a6121 <mono_compile_dominator_info+561>:    callq  0x55555557e360 <__printf_chk@plt>
   0x5555556a6126 <mono_compile_dominator_info+566>:    movswl 0x22(%rbx),%eax
   0x5555556a612a <mono_compile_dominator_info+570>:    cmp    %eax,%r13d
   0x5555556a612d <mono_compile_dominator_info+573>:    jl     0x5555556a6100 <mono_compile_dominator_info+528>
   0x5555556a612f <mono_compile_dominator_info+575>:    mov    $0xa,%edi
(gdb) p bb->in_bb
Cannot access memory at address 0xffffffff00000036
(gdb) print bb
$1 = (MonoBasicBlock *) 0xffffffff000000
(gdb) p cfg->bblocks
$2 = (MonoBasicBlock **) 0x555555d146a0
(gdb) p cfg->bblocks[i]
$4 = (MonoBasicBlock *) 0xffffffff0000000e
(gdb) p i
$5 = 60
(gdb) print cfg
$6 = (MonoCompile *) 0x555555cb2660
(gdb) print cfg->bblocks
$7 = (MonoBasicBlock **) 0x555555d146a0
(gdb) print cfg->bblocks[60]
$8 = (MonoBasicBlock *) 0xffffffff0000000e
(gdb) print cfg->num_bblocks
$14 = 32768 / 0x8000
(gdb) p cfg->max_block_num
$16 = 99
```

```
$ cat /proc/$whateverPIDitis/maps | grep -i stack
7ffffffde000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
```

reported by @grendello

**Comment by lewurm** [comment]
verbose output of the JIT: https://gist.github.com/grendello/d241614c9110d09b6b6dba32088d486b#file-gistfile1-txt

**Comment by lewurm** [comment]
when I compare the compilation output, it diverges here:

crashy:
```
block merge triggered 3 -> 2
cbranch to throw block triggered 4.
block merge triggered 11 -> 46
br removal triggered 48 -> 45
block merge triggered 15 -> 53
br removal triggered 55 -> 52
block merge triggered 17 -> 60
br removal triggered 62 -> 59
block merge triggered 20 -> 67
br removal triggered 69 -> 66
cbranch2 to branch triggered 66 -> (21) 22 (0x1d7)
remove_block_if_useless, removed BB21
block merge triggered 25 -> 74
br removal triggered 76 -> 73
block merge triggered 30 -> 81
br removal triggered 83 -> 80
block merge triggered 19 -> 88
br removal triggered 90 -> 87
block merge triggered 36 -> 95
br removal triggered 97 -> 94
br removal triggered 35 -> 1
```

working:
```
block merge triggered 3 -> 2
cbranch to throw block triggered 4.
block merge triggered 11 -> 46
br removal triggered 48 -> 45
nullify block triggered 10
nullify block triggered 15
br removal triggered 55 -> 52
block merge triggered 17 -> 60
br removal triggered 62 -> 59
block merge triggered 20 -> 67
br removal triggered 69 -> 66
cbranch2 to branch triggered 66 -> (21) 22 (0x1db)
remove_block_if_useless, removed BB21
br removal triggered 8 -> 11
block merge triggered 8 -> 11
nullify block triggered 53
nullify block triggered 56
block merge triggered 55 -> 52
block merge triggered 25 -> 74
br removal triggered 76 -> 73
block merge triggered 30 -> 81
br removal triggered 83 -> 80
block merge triggered 19 -> 88
br removal triggered 90 -> 87
block merge triggered 36 -> 95
br removal triggered 97 -> 94
br removal triggered 35 -> 1
nullify block triggered 55
nullify block triggered 16
nullify block triggered 14
nullify block triggered 18
nullify block triggered 17
nullify block triggered 63
block merge triggered 62 -> 59
nullify block triggered 62
nullify block triggered 20
nullify block triggered 69
br removal triggered 70 -> 66
block merge triggered 70 -> 66
nullify block triggered 70
block merge triggered 23 -> 22
nullify block triggered 19
nullify block triggered 91
block merge triggered 90 -> 87
nullify block triggered 90
nullify block triggered 32
nullify block triggered 31
nullify block triggered 34
nullify block triggered 33
br removal triggered 37 -> 35
nullify block triggered 36
nullify block triggered 98
block merge triggered 97 -> 94
nullify block triggered 97
nullify block triggered 37
nullify block triggered 35
br removal triggered 26 -> 1
```

**Comment by jaykrell** [comment]
Also, given the printf is correct, how about read the value, check, and if fails, read again (cast pointer to volatile -- but only on x86/amd64, where volatile is cheap), and print both?
Also, can the CPU bug strike 32bit mode? ifdef x86 | amd64?

**Comment by lewurm** [comment]
Back then AMD confirmed in private conversations that we were indeed hitting a CPU bug. This is the relevant entry in their [updated revision guide](https://developer.amd.com/wp-content/resources/55449_1.16.pdf):
<img width="903" alt="Screenshot 2019-10-10 at 23 04 30" src="https://user-images.githubusercontent.com/75403/66606518-820b5e80-ebb2-11e9-85d5-ab5064a149a6.png">

Closing it with this :-)
