### ISSUE TITLE
System.Reflection.Assembly.LoadFile should throw ArgumentException for relative path name

### ISSUE THREAD

**Issue by lambdageek** [mono/mono#9943]
Calling `System.Reflection.Assembly.LoadFile` with a relative path name should throw an `ArgumentException ("Absolute path information is required.")`

## Steps to Reproduce

1. Compile and run this program:

```csharp
using System;
using System.Reflection;

public class Program {
	public static void Main ()
	{
		var a = Assembly.LoadFile ("SomeAsm.dll");
		Console.WriteLine (a);
	}
}
```

### Current Behavior

```
Unhandled Exception:
System.IO.FileNotFoundException: Invalid Image
File name: 'SomeAsm.dll'
  at (wrapper managed-to-native) System.Reflection.Assembly.LoadFile_internal(string)
  at System.Reflection.Assembly.LoadFile (System.String path, System.Security.Policy.Evidence securityEvidence) [0x0002b] in <5049491233774e40ababbf3cf415ec8f>:0 
  at System.Reflection.Assembly.LoadFile (System.String path) [0x00000] in <5049491233774e40ababbf3cf415ec8f>:0 
  at Program.Main () [0x00000] in <abfe6b809f8541679003f0b1afd5905e>:0 
```

### Expected Behavior

```
System.ArgumentException
  HResult=0x80070057
  Message=Absolute path information is required.
  Source=mscorlib
  StackTrace:
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.Assembly.LoadFile(String path)
   at lfrel.Program.Main(String[] args) in c:\users\aleksey\documents\visual studio 2017\Projects\lfrel\lfrel\Program.cs:line 10
```

## On which platforms did you notice this

[x] macOS
[ ] Linux
[ ] Windows

**Version Used**:
Mono JIT compiler version 5.17.0.535 (pull-request-9858/1f4a79cef4e Thu Aug  2 14:01:37 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)

**Comment by lambdageek** [comment]
Note that the behavior of `LoadFile` is different from `LoadFrom` which on .NET Framework appears to work with relative paths (relative to the current working directory).
